typedef enum _AM_GRAPH_CONFIG_RECONNECT_FLAGS {
  AM_GRAPH_CONFIG_RECONNECT_DIRECTCONNECT = 0x1,
  AM_GRAPH_CONFIG_RECONNECT_CACHE_REMOVED_FILTERS = 0x2,
  AM_GRAPH_CONFIG_RECONNECT_USE_ONLY_CACHED_FILTERS = 0x4
} AM_GRAPH_CONFIG_RECONNECT_FLAGS;