typedef enum _AM_AUDIO_RENDERER_STAT_PARAM {
  AM_AUDREND_STAT_PARAM_BREAK_COUNT = 1,
  AM_AUDREND_STAT_PARAM_SLAVE_MODE,
  AM_AUDREND_STAT_PARAM_SILENCE_DUR,
  AM_AUDREND_STAT_PARAM_LAST_BUFFER_DUR,
  AM_AUDREND_STAT_PARAM_DISCONTINUITIES,
  AM_AUDREND_STAT_PARAM_SLAVE_RATE,
  AM_AUDREND_STAT_PARAM_SLAVE_DROPWRITE_DUR,
  AM_AUDREND_STAT_PARAM_SLAVE_HIGHLOWERROR,
  AM_AUDREND_STAT_PARAM_SLAVE_LASTHIGHLOWERROR,
  AM_AUDREND_STAT_PARAM_SLAVE_ACCUMERROR,
  AM_AUDREND_STAT_PARAM_BUFFERFULLNESS,
  AM_AUDREND_STAT_PARAM_JITTER
} ;