typedef enum APO_FLAG {
  APO_FLAG_NONE,
  APO_FLAG_INPLACE,
  APO_FLAG_SAMPLESPERFRAME_MUST_MATCH,
  APO_FLAG_FRAMESPERSECOND_MUST_MATCH,
  APO_FLAG_BITSPERSAMPLE_MUST_MATCH,
  APO_FLAG_MIXER,
  APO_FLAG_DEFAULT
} ;