typedef enum tagWCN_VALUE_TYPE_CONFIG_METHODS {
  WCN_VALUE_CM_USBA = 0x1,
  WCN_VALUE_CM_ETHERNET = 0x2,
  WCN_VALUE_CM_LABEL = 0x4,
  WCN_VALUE_CM_DISPLAY = 0x8,
  WCN_VALUE_CM_EXTERNAL_NFC = 0x10,
  WCN_VALUE_CM_INTEGRATED_NFC = 0x20,
  WCN_VALUE_CM_NFC_INTERFACE = 0x40,
  WCN_VALUE_CM_PUSHBUTTON = 0x80,
  WCN_VALUE_CM_KEYPAD = 0x100,
  WCN_VALUE_CM_VIRT_PUSHBUTTON = 0x280,
  WCN_VALUE_CM_PHYS_PUSHBUTTON = 0x480,
  WCN_VALUE_CM_VIRT_DISPLAY = 0x2008,
  WCN_VALUE_CM_PHYS_DISPLAY = 0x4008
} WCN_VALUE_TYPE_CONFIG_METHODS;