typedef enum tagWCN_VALUE_TYPE_DEVICE_PASSWORD_ID {
  WCN_VALUE_DP_DEFAULT = 0,
  WCN_VALUE_DP_USER_SPECIFIED = 0x1,
  WCN_VALUE_DP_MACHINE_SPECIFIED = 0x2,
  WCN_VALUE_DP_REKEY = 0x3,
  WCN_VALUE_DP_PUSHBUTTON = 0x4,
  WCN_VALUE_DP_REGISTRAR_SPECIFIED = 0x5,
  WCN_VALUE_DP_NFC_CONNECTION_HANDOVER = 0x7,
  WCN_VALUE_DP_WFD_SERVICES = 0x8,
  WCN_VALUE_DP_OUTOFBAND_MIN = 0x10,
  WCN_VALUE_DP_OUTOFBAND_MAX = 0xffff
} WCN_VALUE_TYPE_DEVICE_PASSWORD_ID;