typedef enum tagWCN_VALUE_TYPE_ENCRYPTION_TYPE {
  WCN_VALUE_ET_NONE = 0x1,
  WCN_VALUE_ET_WEP = 0x2,
  WCN_VALUE_ET_TKIP = 0x4,
  WCN_VALUE_ET_AES = 0x8,
  WCN_VALUE_ET_TKIP_AES_MIXED = 0xc
} WCN_VALUE_TYPE_ENCRYPTION_TYPE;