typedef enum tagWCN_VALUE_TYPE_WI_FI_PROTECTED_SETUP_STATE {
  WCN_VALUE_SS_RESERVED00 = 0,
  WCN_VALUE_SS_NOT_CONFIGURED = 0x1,
  WCN_VALUE_SS_CONFIGURED = 0x2
} WCN_VALUE_TYPE_WI_FI_PROTECTED_SETUP_STATE;