typedef enum tagWCN_VALUE_TYPE_ASSOCIATION_STATE {
  WCN_VALUE_AS_NOT_ASSOCIATED = 0,
  WCN_VALUE_AS_CONNECTION_SUCCESS = 1,
  WCN_VALUE_AS_CONFIGURATION_FAILURE = 2,
  WCN_VALUE_AS_ASSOCIATION_FAILURE = 3,
  WCN_VALUE_AS_IP_FAILURE = 4
} WCN_VALUE_TYPE_ASSOCIATION_STATE;