typedef enum tagWCN_VALUE_TYPE_AUTHENTICATION_TYPE {
  WCN_VALUE_AT_OPEN = 0x1,
  WCN_VALUE_AT_WPAPSK = 0x2,
  WCN_VALUE_AT_SHARED = 0x4,
  WCN_VALUE_AT_WPA = 0x8,
  WCN_VALUE_AT_WPA2 = 0x10,
  WCN_VALUE_AT_WPA2PSK = 0x20,
  WCN_VALUE_AT_WPAWPA2PSK_MIXED = 0x22
} WCN_VALUE_TYPE_AUTHENTICATION_TYPE;