typedef struct tagWCN_VALUE_TYPE_PRIMARY_DEVICE_TYPE {
  WCN_VALUE_TYPE_DEVICE_TYPE_CATEGORY        Category;
  WCN_VALUE_TYPE_DEVICE_TYPE_SUBCATEGORY_OUI SubCategoryOUI;
  WCN_VALUE_TYPE_DEVICE_TYPE_SUBCATEGORY     SubCategory;
} WCN_VALUE_TYPE_PRIMARY_DEVICE_TYPE;