typedef struct phonestatus_tag {
  DWORD dwTotalSize;
  DWORD dwNeededSize;
  DWORD dwUsedSize;
  DWORD dwStatusFlags;
  DWORD dwNumOwners;
  DWORD dwNumMonitors;
  DWORD dwRingMode;
  DWORD dwRingVolume;
  DWORD dwHandsetHookSwitchMode;
  DWORD dwHandsetVolume;
  DWORD dwHandsetGain;
  DWORD dwSpeakerHookSwitchMode;
  DWORD dwSpeakerVolume;
  DWORD dwSpeakerGain;
  DWORD dwHeadsetHookSwitchMode;
  DWORD dwHeadsetVolume;
  DWORD dwHeadsetGain;
  DWORD dwDisplaySize;
  DWORD dwDisplayOffset;
  DWORD dwLampModesSize;
  DWORD dwLampModesOffset;
  DWORD dwOwnerNameSize;
  DWORD dwOwnerNameOffset;
  DWORD dwDevSpecificSize;
  DWORD dwDevSpecificOffset;
  DWORD dwPhoneFeatures;
} PHONESTATUS, *LPPHONESTATUS;