typedef struct lineproxyrequest_tag {
  DWORD dwSize;
  DWORD dwClientMachineNameSize;
  DWORD dwClientMachineNameOffset;
  DWORD dwClientUserNameSize;
  DWORD dwClientUserNameOffset;
  DWORD dwClientAppAPIVersion;
  DWORD dwRequestType;
  union {
    struct {
      DWORD              dwAddressID;
      LINEAGENTGROUPLIST GroupList;
    } SetAgentGroup;
    struct {
      DWORD dwAddressID;
      DWORD dwAgentState;
      DWORD dwNextAgentState;
    } SetAgentState;
    struct {
      DWORD dwAddressID;
      DWORD dwActivityID;
    } SetAgentActivity;
    struct {
      DWORD         dwAddressID;
      LINEAGENTCAPS AgentCaps;
    } GetAgentCaps;
    struct {
      DWORD           dwAddressID;
      LINEAGENTSTATUS AgentStatus;
    } GetAgentStatus;
    struct {
      DWORD dwAddressID;
      DWORD dwAgentExtensionIDIndex;
      DWORD dwSize;
      BYTE  Params[1];
    } AgentSpecific;
    struct {
      DWORD                 dwAddressID;
      LINEAGENTACTIVITYLIST ActivityList;
    } GetAgentActivityList;
    struct {
      DWORD              dwAddressID;
      LINEAGENTGROUPLIST GroupList;
    } GetAgentGroupList;
    struct {
      HAGENT hAgent;
      DWORD  dwAgentIDSize;
      DWORD  dwAgentIDOffset;
      DWORD  dwAgentPINSize;
      DWORD  dwAgentPINOffset;
    } CreateAgent;
    struct {
      HAGENT hAgent;
      DWORD  dwAgentState;
      DWORD  dwNextAgentState;
    } SetAgentStateEx;
    struct {
      HAGENT hAgent;
      DWORD  dwMeasurementPeriod;
    } SetAgentMeasurementPeriod;
    struct {
      HAGENT        hAgent;
      LINEAGENTINFO AgentInfo;
    } GetAgentInfo;
    struct {
      HAGENTSESSION hAgentSession;
      DWORD         dwAgentPINSize;
      DWORD         dwAgentPINOffset;
      HAGENT        hAgent;
      GUID          GroupID;
      DWORD         dwWorkingAddressID;
    } CreateAgentSession;
    struct {
      HAGENT               hAgent;
      LINEAGENTSESSIONLIST SessionList;
    } GetAgentSessionList;
    struct {
      HAGENTSESSION        hAgentSession;
      LINEAGENTSESSIONINFO SessionInfo;
    } GetAgentSessionInfo;
    struct {
      HAGENTSESSION hAgentSession;
      DWORD         dwAgentSessionState;
      DWORD         dwNextAgentSessionState;
    } SetAgentSessionState;
    struct {
      GUID          GroupID;
      LINEQUEUELIST QueueList;
    } GetQueueList;
    struct {
      DWORD dwQueueID;
      DWORD dwMeasurementPeriod;
    } SetQueueMeasurementPeriod;
    struct {
      DWORD         dwQueueID;
      LINEQUEUEINFO QueueInfo;
    } GetQueueInfo;
    struct {
      LINEAGENTGROUPLIST GroupList;
    } GetGroupList;
  };
} LINEPROXYREQUEST, *LPLINEPROXYREQUEST;