typedef struct _NET_VALIDATE_AUTHENTICATION_INPUT_ARG {
  NET_VALIDATE_PERSISTED_FIELDS InputPersistedFields;
  BOOLEAN                       PasswordMatched;
} NET_VALIDATE_AUTHENTICATION_INPUT_ARG, *PNET_VALIDATE_AUTHENTICATION_INPUT_ARG;