typedef enum _D3DTEXTURETRANSFORMFLAGS {
  D3DTTFF_DISABLE,
  D3DTTFF_COUNT1,
  D3DTTFF_COUNT2,
  D3DTTFF_COUNT3,
  D3DTTFF_COUNT4,
  D3DTTFF_PROJECTED,
  D3DTTFF_FORCE_DWORD
} D3DTEXTURETRANSFORMFLAGS;