typedef struct _UCMTCPCI_PORT_CONTROLLER_SET_TRANSMIT_BUFFER_IN_PARAMS {
  UCMTCPCIPORTCONTROLLER                   PortControllerObject;
  UCMTCPCI_PORT_CONTROLLER_TRANSMIT_BUFFER TransmitBuffer;
} UCMTCPCI_PORT_CONTROLLER_SET_TRANSMIT_BUFFER_IN_PARAMS, *PUCMTCPCI_PORT_CONTROLLER_SET_TRANSMIT_BUFFER_IN_PARAMS;