typedef struct _SECURE_ELEMENT_ENDPOINT_LIST {
  DWORD                        NumberOfEndpoints;
  SECURE_ELEMENT_ENDPOINT_INFO EndpointList[ANYSIZE_ARRAY];
} SECURE_ELEMENT_ENDPOINT_LIST, *PSECURE_ELEMENT_ENDPOINT_LIST;