typedef struct _SECURE_ELEMENT_SET_CARD_EMULATION_MODE_INFO {
  GUID                               guidSecureElementId;
  SECURE_ELEMENT_CARD_EMULATION_MODE eMode;
} SECURE_ELEMENT_SET_CARD_EMULATION_MODE_INFO, *PSECURE_ELEMENT_SET_CARD_EMULATION_MODE_INFO;