typedef struct _SECURE_ELEMENT_HCE_ACTIVATION_PAYLOAD {
  USHORT bConnectionId;
  BYTE   eRfTechType;
  BYTE   eRfProtocolType;
} SECURE_ELEMENT_HCE_ACTIVATION_PAYLOAD, *PSECURE_ELEMENT_HCE_ACTIVATION_PAYLOAD;