typedef struct _SECURE_ELEMENT_EVENT_SUBSCRIPTION_INFO {
  GUID                      guidSecureElementId;
  SECURE_ELEMENT_EVENT_TYPE eEventType;
} SECURE_ELEMENT_EVENT_SUBSCRIPTION_INFO, *PSECURE_ELEMENT_EVENT_SUBSCRIPTION_INFO;