typedef struct _SECURE_ELEMENT_ROUTING_TABLE_ENTRY {
  SECURE_ELEMENT_ROUTING_TYPE eRoutingType;
  union {
    SECURE_ELEMENT_TECH_ROUTING_INFO  TechRoutingInfo;
    SECURE_ELEMENT_PROTO_ROUTING_INFO ProtoRoutingInfo;
    SECURE_ELEMENT_AID_ROUTING_INFO   AidRoutingInfo;
  };
} SECURE_ELEMENT_ROUTING_TABLE_ENTRY, *PSECURE_ELEMENT_ROUTING_TABLE_ENTRY;