typedef struct _SECURE_ELEMENT_ROUTING_TABLE {
  DWORD                              NumberOfEntries;
  SECURE_ELEMENT_ROUTING_TABLE_ENTRY TableEntries[ANYSIZE_ARRAY];
} SECURE_ELEMENT_ROUTING_TABLE, *PSECURE_ELEMENT_ROUTING_TABLE;