typedef struct _SECURE_ELEMENT_AID_ROUTING_INFO {
  GUID  guidSecureElementId;
  DWORD cbAid;
  BYTE  pbAid[ISO_7816_MAXIMUM_AID_LENGTH];
} SECURE_ELEMENT_AID_ROUTING_INFO, *PSECURE_ELEMENT_AID_ROUTING_INFO;