typedef enum D3D11_TILE_COPY_FLAG {
  D3D11_TILE_COPY_NO_OVERWRITE = 0x1,
  D3D11_TILE_COPY_LINEAR_BUFFER_TO_SWIZZLED_TILED_RESOURCE = 0x2,
  D3D11_TILE_COPY_SWIZZLED_TILED_RESOURCE_TO_LINEAR_BUFFER = 0x4
} ;