typedef enum WLDP_HOST_ID {
  WLDP_HOST_ID_UNKNOWN,
  WLDP_HOST_ID_GLOBAL,
  WLDP_HOST_ID_VBA,
  WLDP_HOST_ID_WSH,
  WLDP_HOST_ID_POWERSHELL,
  WLDP_HOST_ID_IE,
  WLDP_HOST_ID_MSI,
  WLDP_HOST_ID_ALL,
  WLDP_HOST_ID_MAX
} ;