typedef enum WLDP_WINDOWS_LOCKDOWN_MODE {
  WLDP_WINDOWS_LOCKDOWN_MODE_UNLOCKED,
  WLDP_WINDOWS_LOCKDOWN_MODE_TRIAL,
  WLDP_WINDOWS_LOCKDOWN_MODE_LOCKED,
  WLDP_WINDOWS_LOCKDOWN_MODE_MAX
}  *PWLDP_WINDOWS_LOCKDOWN_MODE;