typedef struct _WNV_REDIRECT_PARAM {
  ADDRESS_FAMILY CAFamily;
  ADDRESS_FAMILY PAFamily;
  ADDRESS_FAMILY NewPAFamily;
  ULONG          VirtualSubnetId;
  WNV_IP_ADDRESS CA;
  WNV_IP_ADDRESS PA;
  WNV_IP_ADDRESS NewPA;
} WNV_REDIRECT_PARAM, *PWNV_REDIRECT_PARAM;