typedef struct _WNV_PROVIDER_ADDRESS_CHANGE_PARAM {
  ADDRESS_FAMILY PAFamily;
  WNV_IP_ADDRESS PA;
  NL_DAD_STATE   AddressState;
} WNV_PROVIDER_ADDRESS_CHANGE_PARAM, *PWNV_PROVIDER_ADDRESS_CHANGE_PARAM;