typedef struct _WNV_POLICY_MISMATCH_PARAM {
  ADDRESS_FAMILY CAFamily;
  ADDRESS_FAMILY PAFamily;
  ULONG          VirtualSubnetId;
  WNV_IP_ADDRESS CA;
  WNV_IP_ADDRESS PA;
} WNV_POLICY_MISMATCH_PARAM, *PWNV_POLICY_MISMATCH_PARAM;