typedef enum tagQUERY_PARSER_MANAGER_OPTION {
  QPMO_SCHEMA_BINARY_NAME = 0,
  QPMO_PRELOCALIZED_SCHEMA_BINARY_PATH,
  QPMO_UNLOCALIZED_SCHEMA_BINARY_PATH,
  QPMO_LOCALIZED_SCHEMA_BINARY_PATH,
  QPMO_APPEND_LCID_TO_LOCALIZED_PATH,
  QPMO_LOCALIZER_SUPPORT
} QUERY_PARSER_MANAGER_OPTION;