typedef enum tagSTRUCTURED_QUERY_SINGLE_OPTION {
  SQSO_SCHEMA = 0,
  SQSO_LOCALE_WORD_BREAKING,
  SQSO_WORD_BREAKER,
  SQSO_NATURAL_SYNTAX,
  SQSO_AUTOMATIC_WILDCARD,
  SQSO_TRACE_LEVEL,
  SQSO_LANGUAGE_KEYWORDS,
  SQSO_SYNTAX,
  SQSO_TIME_ZONE,
  SQSO_IMPLICIT_CONNECTOR,
  SQSO_CONNECTOR_CASE
} STRUCTURED_QUERY_SINGLE_OPTION;