typedef enum tagSTRUCTURED_QUERY_PARSE_ERROR {
  SQPE_NONE = 0,
  SQPE_EXTRA_OPENING_PARENTHESIS,
  SQPE_EXTRA_CLOSING_PARENTHESIS,
  SQPE_IGNORED_MODIFIER,
  SQPE_IGNORED_CONNECTOR,
  SQPE_IGNORED_KEYWORD,
  SQPE_UNHANDLED
} STRUCTURED_QUERY_PARSE_ERROR;