typedef enum CONDITION_CREATION_OPTIONS {
  CONDITION_CREATION_DEFAULT = 0,
  CONDITION_CREATION_NONE = 0,
  CONDITION_CREATION_SIMPLIFY = 0x1,
  CONDITION_CREATION_VECTOR_AND = 0x2,
  CONDITION_CREATION_VECTOR_OR = 0x4,
  CONDITION_CREATION_VECTOR_LEAF = 0x8,
  CONDITION_CREATION_USE_CONTENT_LOCALE = 0x10
} ;