typedef enum __MIDL_IAssemblyName_0004 {
  ASM_CMPF_NAME = 0x1,
  ASM_CMPF_MAJOR_VERSION = 0x2,
  ASM_CMPF_MINOR_VERSION = 0x4,
  ASM_CMPF_BUILD_NUMBER = 0x8,
  ASM_CMPF_REVISION_NUMBER = 0x10,
  ASM_CMPF_PUBLIC_KEY_TOKEN = 0x20,
  ASM_CMPF_CULTURE = 0x40,
  ASM_CMPF_CUSTOM = 0x80,
  ASM_CMPF_ALL,
  ASM_CMPF_DEFAULT = 0x100
} ASM_CMP_FLAGS;