typedef enum __MIDL_IAssemblyName_0003 {
  ASM_DISPLAYF_VERSION = 0x1,
  ASM_DISPLAYF_CULTURE = 0x2,
  ASM_DISPLAYF_PUBLIC_KEY_TOKEN = 0x4,
  ASM_DISPLAYF_PUBLIC_KEY = 0x8,
  ASM_DISPLAYF_CUSTOM = 0x10,
  ASM_DISPLAYF_PROCESSORARCHITECTURE = 0x20,
  ASM_DISPLAYF_LANGUAGEID = 0x40
} ASM_DISPLAY_FLAGS;