typedef enum MFVP_MESSAGE_TYPE {
  MFVP_MESSAGE_FLUSH = 0,
  MFVP_MESSAGE_INVALIDATEMEDIATYPE = 0x1,
  MFVP_MESSAGE_PROCESSINPUTNOTIFY = 0x2,
  MFVP_MESSAGE_BEGINSTREAMING = 0x3,
  MFVP_MESSAGE_ENDSTREAMING = 0x4,
  MFVP_MESSAGE_ENDOFSTREAM = 0x5,
  MFVP_MESSAGE_STEP = 0x6,
  MFVP_MESSAGE_CANCELSTEP = 0x7
} ;