typedef enum _RAS_AUTH_ATTRIBUTE_TYPE_ {
  raatMinimum = 0,
  raatUserName,
  raatUserPassword,
  raatMD5CHAPPassword,
  raatNASIPAddress,
  raatNASPort,
  raatServiceType,
  raatFramedProtocol,
  raatFramedIPAddress,
  raatFramedIPNetmask,
  raatFramedRouting = 10,
  raatFilterId,
  raatFramedMTU,
  raatFramedCompression,
  raatLoginIPHost,
  raatLoginService,
  raatLoginTCPPort,
  raatUnassigned17,
  raatReplyMessage,
  raatCallbackNumber,
  raatCallbackId = 20,
  raatUnassigned21,
  raatFramedRoute,
  raatFramedIPXNetwork,
  raatState,
  raatClass,
  raatVendorSpecific,
  raatSessionTimeout,
  raatIdleTimeout,
  raatTerminationAction,
  raatCalledStationId = 30,
  raatCallingStationId,
  raatNASIdentifier,
  raatProxyState,
  raatLoginLATService,
  raatLoginLATNode,
  raatLoginLATGroup,
  raatFramedAppleTalkLink,
  raatFramedAppleTalkNetwork,
  raatFramedAppleTalkZone,
  raatAcctStatusType = 40,
  raatAcctDelayTime,
  raatAcctInputOctets,
  raatAcctOutputOctets,
  raatAcctSessionId,
  raatAcctAuthentic,
  raatAcctSessionTime,
  raatAcctInputPackets,
  raatAcctOutputPackets,
  raatAcctTerminateCause,
  raatAcctMultiSessionId = 50,
  raatAcctLinkCount,
  raatAcctEventTimeStamp = 55,
  raatMD5CHAPChallenge = 60,
  raatNASPortType,
  raatPortLimit,
  raatLoginLATPort,
  raatTunnelType,
  raatTunnelMediumType,
  raatTunnelClientEndpoint,
  raatTunnelServerEndpoint,
  raatARAPPassword = 70,
  raatARAPFeatures,
  raatARAPZoneAccess,
  raatARAPSecurity,
  raatARAPSecurityData,
  raatPasswordRetry,
  raatPrompt,
  raatConnectInfo,
  raatConfigurationToken,
  raatEAPMessage,
  raatSignature = 80,
  raatARAPChallengeResponse = 84,
  raatAcctInterimInterval = 85,
  raatNASIPv6Address = 95,
  raatFramedInterfaceId,
  raatFramedIPv6Prefix,
  raatLoginIPv6Host,
  raatFramedIPv6Route,
  raatFramedIPv6Pool,
  raatARAPGuestLogon = 8096,
  raatCertificateOID,
  raatEAPConfiguration,
  raatPEAPEmbeddedEAPTypeId = 8099,
  raatInnerEAPTypeId = 8099,
  raatPEAPFastRoamedSession = 8100,
  raatFastRoamedSession = 8100,
  raatEAPTLV = 8102,
  raatCredentialsChanged,
  raatCertificateThumbprint = 8250,
  raatPeerId = 9000,
  raatServerId,
  raatMethodId,
  raatEMSK,
  raatSessionId,
  raatReserved
} RAS_AUTH_ATTRIBUTE_TYPE;