typedef struct _NET_ADAPTER_RECEIVE_SCALING_INDIRECTION_ENTRIES {
  NET_ADAPTER_RECEIVE_SCALING_INDIRECTION_ENTRY *Entries;
  SIZE_T                                        Length;
} NET_ADAPTER_RECEIVE_SCALING_INDIRECTION_ENTRIES;