typedef enum {
  KSMETHOD_BDA_GDDS_DATATYPE,
  KSMETHOD_BDA_GDDS_DATA,
  KSMETHOD_BDA_GDDS_TUNEXMLFROMIDX,
  KSMETHOD_BDA_GDDS_GETSERVICES,
  KSMETHOD_BDA_GDDS_SERVICEFROMTUNEXML,
  KSMETHOD_BDA_GDDS_DATAUPDATE
} KSMETHOD_BDA_GDDS_SERVICE;