typedef enum {
  KSEVENT_BDA_PROGRAM_FLOW_STATUS_CHANGED,
  KSEVENT_BDA_CA_MODULE_STATUS_CHANGED,
  KSEVENT_BDA_CA_SMART_CARD_STATUS_CHANGED,
  KSEVENT_BDA_CA_MODULE_UI_REQUESTED
} KSPROPERTY_BDA_CA_EVENT;