typedef enum {
  KSMETHOD_BDA_WMDRM_STATUS,
  KSMETHOD_BDA_WMDRM_REVINFO,
  KSMETHOD_BDA_WMDRM_CRL,
  KSMETHOD_BDA_WMDRM_MESSAGE,
  KSMETHOD_BDA_WMDRM_REISSUELICENSE,
  KSMETHOD_BDA_WMDRM_RENEWLICENSE,
  KSMETHOD_BDA_WMDRM_LICENSE,
  KSMETHOD_BDA_WMDRM_KEYINFO
} KSMETHOD_BDA_WMDRM;