typedef enum {
  KSPROPERTY_BDA_ECM_MAP_STATUS,
  KSPROPERTY_BDA_CA_MODULE_STATUS,
  KSPROPERTY_BDA_CA_SMART_CARD_STATUS,
  KSPROPERTY_BDA_CA_MODULE_UI,
  KSPROPERTY_BDA_CA_SET_PROGRAM_PIDS,
  KSPROPERTY_BDA_CA_REMOVE_PROGRAM
} KSPROPERTY_BDA_CA;