typedef enum {
  KSPROPERTY_BDA_DISEQC_ENABLE,
  KSPROPERTY_BDA_DISEQC_LNB_SOURCE,
  KSPROPERTY_BDA_DISEQC_USETONEBURST,
  KSPROPERTY_BDA_DISEQC_REPEATS,
  KSPROPERTY_BDA_DISEQC_SEND,
  KSPROPERTY_BDA_DISEQC_RESPONSE
} KSPROPERTY_BDA_DISEQC_COMMAND;