typedef enum {
  KSMETHOD_BDA_SCAN_CAPABILTIES,
  KSMETHOD_BDA_SCANNING_STATE,
  KSMETHOD_BDA_SCAN_FILTER,
  KSMETHOD_BDA_SCAN_START,
  KSMETHOD_BDA_SCAN_RESUME,
  KSMETHOD_BDA_SCAN_STOP
} KSMETHOD_BDA_SCAN_SERVICE;