typedef enum _WINHTTP_REQUEST_TIME_ENTRY {
  WinHttpProxyDetectionStart = 0,
  WinHttpProxyDetectionEnd,
  WinHttpConnectionAcquireStart,
  WinHttpConnectionAcquireWaitEnd,
  WinHttpConnectionAcquireEnd,
  WinHttpNameResolutionStart,
  WinHttpNameResolutionEnd,
  WinHttpConnectionEstablishmentStart,
  WinHttpConnectionEstablishmentEnd,
  WinHttpTlsHandshakeClientLeg1Start,
  WinHttpTlsHandshakeClientLeg1End,
  WinHttpTlsHandshakeClientLeg2Start,
  WinHttpTlsHandshakeClientLeg2End,
  WinHttpTlsHandshakeClientLeg3Start,
  WinHttpTlsHandshakeClientLeg3End,
  WinHttpStreamWaitStart,
  WinHttpStreamWaitEnd,
  WinHttpSendRequestStart,
  WinHttpSendRequestHeadersCompressionStart,
  WinHttpSendRequestHeadersCompressionEnd,
  WinHttpSendRequestHeadersEnd,
  WinHttpSendRequestEnd,
  WinHttpReceiveResponseStart,
  WinHttpReceiveResponseHeadersDecompressionStart,
  WinHttpReceiveResponseHeadersDecompressionEnd,
  WinHttpReceiveResponseHeadersEnd,
  WinHttpReceiveResponseBodyDecompressionDelta,
  WinHttpReceiveResponseEnd,
  WinHttpProxyTunnelStart,
  WinHttpProxyTunnelEnd,
  WinHttpProxyTlsHandshakeClientLeg1Start,
  WinHttpProxyTlsHandshakeClientLeg1End,
  WinHttpProxyTlsHandshakeClientLeg2Start,
  WinHttpProxyTlsHandshakeClientLeg2End,
  WinHttpProxyTlsHandshakeClientLeg3Start,
  WinHttpProxyTlsHandshakeClientLeg3End,
  WinHttpRequestTimeLast,
  WinHttpRequestTimeMax = 64
} WINHTTP_REQUEST_TIME_ENTRY;