typedef struct FWPS_ALE_ENDPOINT_ENUM_TEMPLATE0_ {
  FWP_CONDITION_VALUE0 localSubNet;
  FWP_CONDITION_VALUE0 remoteSubNet;
  FWP_CONDITION_VALUE0 ipProtocol;
  FWP_CONDITION_VALUE0 localPort;
  FWP_CONDITION_VALUE0 remotePort;
} FWPS_ALE_ENDPOINT_ENUM_TEMPLATE0;