typedef enum HWREQCHK_TARGET_RELEASE {
  HWREQCHK_TARGET_RELEASE_INVALID,
  HWREQCHK_TARGET_RELEASE_WIN11_VNEXT,
  HWREQCHK_TARGET_RELEASE_WIN11_21H2,
  HWREQCHK_TARGET_RELEASE_WIN11_22H2,
  HWREQCHK_TARGET_RELEASE_SRV2022_21H2
} ;