typedef enum HWREQCHK_PRODUCT_TYPE {
  HWREQCHK_PRODUCT_INVALID,
  HWREQCHK_PRODUCT_DEFAULT,
  HWREQCHK_PRODUCT_DESKTOP,
  HWREQCHK_PRODUCT_SERVER,
  HWREQCHK_PRODUCT_IOTENTERPRISE,
  HWREQCHK_PRODUCT_IOT,
  HWREQCHK_PRODUCT_IOTENTERPRISE_LTSC
} ;