typedef enum tagACTIVATIONTYPE {
  ACTIVATIONTYPE_UNCATEGORIZED = 0,
  ACTIVATIONTYPE_FROM_MONIKER = 0x1,
  ACTIVATIONTYPE_FROM_DATA = 0x2,
  ACTIVATIONTYPE_FROM_STORAGE = 0x4,
  ACTIVATIONTYPE_FROM_STREAM = 0x8,
  ACTIVATIONTYPE_FROM_FILE = 0x10
} ACTIVATIONTYPE;