typedef struct _UDECX_USB_ENDPOINT_CALLBACKS {
  ULONG                        Size;
  PFN_UDECX_USB_ENDPOINT_RESET EvtUsbEndpointReset;
  PFN_UDECX_USB_ENDPOINT_START EvtUsbEndpointStart;
  PFN_UDECX_USB_ENDPOINT_PURGE EvtUsbEndpointPurge;
} UDECX_USB_ENDPOINT_CALLBACKS, *PUDECX_USB_ENDPOINT_CALLBACKS;