typedef struct _DEVICE_NOTIFY_SUBSCRIBE_PARAMETERS {
  PDEVICE_NOTIFY_CALLBACK_ROUTINE Callback;
  PVOID                           Context;
} DEVICE_NOTIFY_SUBSCRIBE_PARAMETERS, *PDEVICE_NOTIFY_SUBSCRIBE_PARAMETERS;