typedef struct _GLOBAL_USER_POWER_POLICY {
  ULONG               Revision;
  POWER_ACTION_POLICY PowerButtonAc;
  POWER_ACTION_POLICY PowerButtonDc;
  POWER_ACTION_POLICY SleepButtonAc;
  POWER_ACTION_POLICY SleepButtonDc;
  POWER_ACTION_POLICY LidCloseAc;
  POWER_ACTION_POLICY LidCloseDc;
  SYSTEM_POWER_LEVEL  DischargePolicy[NUM_DISCHARGE_POLICIES];
  ULONG               GlobalFlags;
} GLOBAL_USER_POWER_POLICY, *PGLOBAL_USER_POWER_POLICY;