typedef struct _MACHINE_PROCESSOR_POWER_POLICY {
  ULONG                  Revision;
  PROCESSOR_POWER_POLICY ProcessorPolicyAc;
  PROCESSOR_POWER_POLICY ProcessorPolicyDc;
} MACHINE_PROCESSOR_POWER_POLICY, *PMACHINE_PROCESSOR_POWER_POLICY;