typedef enum FLICKDIRECTION {
  FLICKDIRECTION_MIN = 0,
  FLICKDIRECTION_RIGHT = 0,
  FLICKDIRECTION_UPRIGHT = 1,
  FLICKDIRECTION_UP = 2,
  FLICKDIRECTION_UPLEFT = 3,
  FLICKDIRECTION_LEFT = 4,
  FLICKDIRECTION_DOWNLEFT = 5,
  FLICKDIRECTION_DOWN = 6,
  FLICKDIRECTION_DOWNRIGHT = 7,
  FLICKDIRECTION_INVALID = 8
} ;