typedef enum FLICKACTION_COMMANDCODE {
  FLICKACTION_COMMANDCODE_NULL = 0,
  FLICKACTION_COMMANDCODE_SCROLL = 1,
  FLICKACTION_COMMANDCODE_APPCOMMAND = 2,
  FLICKACTION_COMMANDCODE_CUSTOMKEY = 3,
  FLICKACTION_COMMANDCODE_KEYMODIFIER = 4
} ;