typedef enum GAMING_DEVICE_DEVICE_ID {
  GAMING_DEVICE_DEVICE_ID_NONE = 0,
  GAMING_DEVICE_DEVICE_ID_XBOX_ONE = 0x768BAE26,
  GAMING_DEVICE_DEVICE_ID_XBOX_ONE_S = 0x2A7361D9,
  GAMING_DEVICE_DEVICE_ID_XBOX_ONE_X = 0x5AD617C7,
  GAMING_DEVICE_DEVICE_ID_XBOX_ONE_X_DEVKIT = 0x10F7CDE3,
  GAMING_DEVICE_DEVICE_ID_XBOX_SERIES_S,
  GAMING_DEVICE_DEVICE_ID_XBOX_SERIES_X,
  GAMING_DEVICE_DEVICE_ID_XBOX_SERIES_X_DEVKIT
} ;