typedef struct _GPIO_CLIENT_CONTROLLER_SPECIFIC_FUNCTION_PARAMETERS {
  PVOID  InputBuffer;
  SIZE_T InputBufferLength;
  PVOID  OutputBuffer;
  SIZE_T OutputBufferLength;
  ULONG  BytesWritten;
} GPIO_CLIENT_CONTROLLER_SPECIFIC_FUNCTION_PARAMETERS, *PGPIO_CLIENT_CONTROLLER_SPECIFIC_FUNCTION_PARAMETERS;