typedef struct _GPIO_QUERY_ACTIVE_INTERRUPTS_PARAMETERS {
  BANK_ID BankId;
  ULONG64 EnabledMask;
  ULONG64 ActiveMask;
} GPIO_QUERY_ACTIVE_INTERRUPTS_PARAMETERS, *PGPIO_QUERY_ACTIVE_INTERRUPTS_PARAMETERS;