typedef struct _CLIENT_QUERY_BANK_POWER_INFORMATION_OUTPUT {
  struct {
    USHORT F1StateSupported : 1;
    USHORT Reserved : 15;
  };
  PO_FX_COMPONENT_IDLE_STATE F1IdleStateParameters;
} CLIENT_QUERY_BANK_POWER_INFORMATION_OUTPUT, *PCLIENT_QUERY_BANK_POWER_INFORMATION_OUTPUT;