typedef struct _GPIO_DISABLE_INTERRUPT_PARAMETERS {
  BANK_ID                      BankId;
  PIN_NUMBER                   PinNumber;
  GPIO_DISABLE_INTERRUPT_FLAGS Flags;
} GPIO_DISABLE_INTERRUPT_PARAMETERS, *PGPIO_DISABLE_INTERRUPT_PARAMETERS;