typedef struct _GPIO_CLEAR_ACTIVE_INTERRUPTS_PARAMETERS {
  BANK_ID BankId;
  ULONG64 ClearActiveMask;
  ULONG64 FailedClearMask;
} GPIO_CLEAR_ACTIVE_INTERRUPTS_PARAMETERS, *PGPIO_CLEAR_ACTIVE_INTERRUPTS_PARAMETERS;