typedef struct _GPIO_SAVE_RESTORE_BANK_HARDWARE_CONTEXT_PARAMETERS {
  BANK_ID                                       BankId;
  ULONG                                         State;
  GPIO_SAVE_RESTORE_BANK_HARDWARE_CONTEXT_FLAGS Flags;
} GPIO_SAVE_RESTORE_BANK_HARDWARE_CONTEXT_PARAMETERS, *PGPIO_SAVE_RESTORE_BANK_HARDWARE_CONTEXT_PARAMETERS;