typedef enum _TRANSPORTPROVIDER_CALLBACK_ID {
  WDS_TRANSPORTPROVIDER_CREATE_INSTANCE = 0,
  WDS_TRANSPORTPROVIDER_COMPARE_CONTENT,
  WDS_TRANSPORTPROVIDER_OPEN_CONTENT,
  WDS_TRANSPORTPROVIDER_USER_ACCESS_CHECK,
  WDS_TRANSPORTPROVIDER_GET_CONTENT_SIZE,
  WDS_TRANSPORTPROVIDER_READ_CONTENT,
  WDS_TRANSPORTPROVIDER_CLOSE_CONTENT,
  WDS_TRANSPORTPROVIDER_CLOSE_INSTANCE,
  WDS_TRANSPORTPROVIDER_SHUTDOWN,
  WDS_TRANSPORTPROVIDER_DUMP_STATE,
  WDS_TRANSPORTPROVIDER_REFRESH_SETTINGS,
  WDS_TRANSPORTPROVIDER_GET_CONTENT_METADATA,
  WDS_TRANSPORTPROVIDER_MAX_CALLBACKS
} TRANSPORTPROVIDER_CALLBACK_ID, *PTRANSPORTPROVIDER_CALLBACK_ID;