typedef struct _WDS_TRANSPORTPROVIDER_INIT_PARAMS {
  ULONG  ulLength;
  ULONG  ulMcServerVersion;
  HKEY   hRegistryKey;
  HANDLE hProvider;
} WDS_TRANSPORTPROVIDER_INIT_PARAMS, *PWDS_TRANSPORTPROVIDER_INIT_PARAMS;