typedef enum _FS_BPIO_OUTFLAGS {
  FSBPIO_OUTFL_None,
  FSBPIO_OUTFL_VOLUME_STACK_BYPASS_PAUSED,
  FSBPIO_OUTFL_STREAM_BYPASS_PAUSED,
  FSBPIO_OUTFL_FILTER_ATTACH_BLOCKED,
  FSBPIO_OUTFL_COMPATIBLE_STORAGE_DRIVER
} FS_BPIO_OUTFLAGS;