typedef struct _VIRTUAL_STORAGE_SET_BEHAVIOR_INPUT {
  ULONG                         Size;
  VIRTUAL_STORAGE_BEHAVIOR_CODE BehaviorCode;
} VIRTUAL_STORAGE_SET_BEHAVIOR_INPUT, *PVIRTUAL_STORAGE_SET_BEHAVIOR_INPUT;