typedef struct _LCN_WEAK_REFERENCE_CREATE_OUTPUT_BUFFER {
  ULONG                          MappingCount;
  LCN_WEAK_REFERENCE_VCN_MAPPING VcnLcnMappings[ANYSIZE_ARRAY];
} LCN_WEAK_REFERENCE_CREATE_OUTPUT_BUFFER, *PLCN_WEAK_REFERENCE_CREATE_OUTPUT_BUFFER;