typedef struct _LCN_WEAK_REFERENCE_CLEAR_INPUT_BUFFER {
  ULONG                    RangeCount;
  LCN_WEAK_REFERENCE_RANGE Ranges[ANYSIZE_ARRAY];
} LCN_WEAK_REFERENCE_CLEAR_INPUT_BUFFER, *PLCN_WEAK_REFERENCE_CLEAR_INPUT_BUFFER;