typedef struct _FILE_DESIRED_STORAGE_CLASS_INFORMATION {
  FILE_STORAGE_TIER_CLASS Class;
  ULONG                   Flags;
} FILE_DESIRED_STORAGE_CLASS_INFORMATION, *PFILE_DESIRED_STORAGE_CLASS_INFORMATION;