typedef struct _CSV_SET_HANDLE_PROPERTIES_ECP_CONTEXT {
  SIZE_T Size;
  ULONG  PauseTimeoutInSeconds;
  ULONG  Flags;
} CSV_SET_HANDLE_PROPERTIES_ECP_CONTEXT, *PCSV_SET_HANDLE_PROPERTIES_ECP_CONTEXT;