typedef struct _WIM_PROVIDER_UPDATE_OVERLAY_INPUT {
  LARGE_INTEGER DataSourceId;
  ULONG         WimFileNameOffset;
  ULONG         WimFileNameLength;
} WIM_PROVIDER_UPDATE_OVERLAY_INPUT, *PWIM_PROVIDER_UPDATE_OVERLAY_INPUT;