typedef struct {
  ULONG         ByteCount;
  ULONG         MajorVersion;
  ULONG         MinorVersion;
  ULONG         BytesPerPhysicalSector;
  LARGE_INTEGER VolumeSerialNumber;
  LARGE_INTEGER NumberSectors;
  LARGE_INTEGER TotalClusters;
  LARGE_INTEGER FreeClusters;
  LARGE_INTEGER TotalReserved;
  ULONG         BytesPerSector;
  ULONG         BytesPerCluster;
  LARGE_INTEGER MaximumSizeOfResidentFile;
  USHORT        FastTierDataFillRatio;
  USHORT        SlowTierDataFillRatio;
  ULONG         DestagesFastTierToSlowTierRate;
  USHORT        MetadataChecksumType;
  UCHAR         Reserved0[6];
  ULONG         DriverMajorVersion;
  ULONG         DriverMinorVersion;
  LARGE_INTEGER Reserved[7];
} REFS_VOLUME_DATA_BUFFER, *PREFS_VOLUME_DATA_BUFFER;