typedef enum __MIDL___MIDL_itf_msp_0000_0000_0003 {
  CALL_CAUSE_UNKNOWN = 0,
  CALL_CAUSE_BAD_DEVICE,
  CALL_CAUSE_CONNECT_FAIL,
  CALL_CAUSE_LOCAL_REQUEST,
  CALL_CAUSE_REMOTE_REQUEST,
  CALL_CAUSE_MEDIA_TIMEOUT,
  CALL_CAUSE_MEDIA_RECOVERED,
  CALL_CAUSE_QUALITY_OF_SERVICE
} MSP_CALL_EVENT_CAUSE;