typedef enum __MIDL___MIDL_itf_winsync_0000_0000_0005 {
  SRA_DEFER = 0,
  SRA_ACCEPT_DESTINATION_PROVIDER,
  SRA_ACCEPT_SOURCE_PROVIDER,
  SRA_MERGE,
  SRA_TRANSFER_AND_DEFER,
  SRA_LAST
} SYNC_RESOLVE_ACTION;