typedef struct _HTTP_SERVICE_CONFIG_URLACL_SET {
  HTTP_SERVICE_CONFIG_URLACL_KEY   KeyDesc;
  HTTP_SERVICE_CONFIG_URLACL_PARAM ParamDesc;
} HTTP_SERVICE_CONFIG_URLACL_SET, *PHTTP_SERVICE_CONFIG_URLACL_SET;