typedef struct _HTTP_SERVICE_CONFIG_TIMEOUT_SET {
  HTTP_SERVICE_CONFIG_TIMEOUT_KEY   KeyDesc;
  HTTP_SERVICE_CONFIG_TIMEOUT_PARAM ParamDesc;
} HTTP_SERVICE_CONFIG_TIMEOUT_SET, *PHTTP_SERVICE_CONFIG_TIMEOUT_SET;