typedef struct _HTTP_SERVER_AUTHENTICATION_DIGEST_PARAMS {
  USHORT DomainNameLength;
  PWSTR  DomainName;
  USHORT RealmLength;
  PWSTR  Realm;
} HTTP_SERVER_AUTHENTICATION_DIGEST_PARAMS, *PHTTP_SERVER_AUTHENTICATION_DIGEST_PARAMS;