typedef struct _HTTP_SERVICE_CONFIG_URLACL_QUERY {
  HTTP_SERVICE_CONFIG_QUERY_TYPE QueryDesc;
  HTTP_SERVICE_CONFIG_URLACL_KEY KeyDesc;
  DWORD                          dwToken;
} HTTP_SERVICE_CONFIG_URLACL_QUERY, *PHTTP_SERVICE_CONFIG_URLACL_QUERY;