typedef struct _HTTP_SERVICE_CONFIG_SSL_SNI_SET {
  HTTP_SERVICE_CONFIG_SSL_SNI_KEY KeyDesc;
  HTTP_SERVICE_CONFIG_SSL_PARAM   ParamDesc;
} HTTP_SERVICE_CONFIG_SSL_SNI_SET, *PHTTP_SERVICE_CONFIG_SSL_SNI_SET;