typedef struct _HTTP_SERVICE_CONFIG_IP_LISTEN_QUERY {
  ULONG            AddrCount;
  SOCKADDR_STORAGE AddrList[ANYSIZE_ARRAY];
} HTTP_SERVICE_CONFIG_IP_LISTEN_QUERY, *PHTTP_SERVICE_CONFIG_IP_LISTEN_QUERY;