typedef enum NLM_NETWORK_PROPERTY_CHANGE {
  NLM_NETWORK_PROPERTY_CHANGE_CONNECTION = 0x1,
  NLM_NETWORK_PROPERTY_CHANGE_DESCRIPTION = 0x2,
  NLM_NETWORK_PROPERTY_CHANGE_NAME = 0x4,
  NLM_NETWORK_PROPERTY_CHANGE_ICON = 0x8,
  NLM_NETWORK_PROPERTY_CHANGE_CATEGORY_VALUE = 0x10
} ;