typedef enum NLM_CONNECTIVITY {
  NLM_CONNECTIVITY_DISCONNECTED = 0,
  NLM_CONNECTIVITY_IPV4_NOTRAFFIC = 0x1,
  NLM_CONNECTIVITY_IPV6_NOTRAFFIC = 0x2,
  NLM_CONNECTIVITY_IPV4_SUBNET = 0x10,
  NLM_CONNECTIVITY_IPV4_LOCALNETWORK = 0x20,
  NLM_CONNECTIVITY_IPV4_INTERNET = 0x40,
  NLM_CONNECTIVITY_IPV6_SUBNET = 0x100,
  NLM_CONNECTIVITY_IPV6_LOCALNETWORK = 0x200,
  NLM_CONNECTIVITY_IPV6_INTERNET = 0x400
} ;