typedef enum NLM_CONNECTION_COST {
  NLM_CONNECTION_COST_UNKNOWN = 0,
  NLM_CONNECTION_COST_UNRESTRICTED = 0x1,
  NLM_CONNECTION_COST_FIXED = 0x2,
  NLM_CONNECTION_COST_VARIABLE = 0x4,
  NLM_CONNECTION_COST_OVERDATALIMIT = 0x10000,
  NLM_CONNECTION_COST_CONGESTED = 0x20000,
  NLM_CONNECTION_COST_ROAMING = 0x40000,
  NLM_CONNECTION_COST_APPROACHINGDATALIMIT = 0x80000
} ;