typedef enum tagNETCON_STATUS {
  NCS_DISCONNECTED = 0,
  NCS_CONNECTING,
  NCS_CONNECTED,
  NCS_DISCONNECTING,
  NCS_HARDWARE_NOT_PRESENT,
  NCS_HARDWARE_DISABLED,
  NCS_HARDWARE_MALFUNCTION,
  NCS_MEDIA_DISCONNECTED,
  NCS_AUTHENTICATING,
  NCS_AUTHENTICATION_SUCCEEDED,
  NCS_AUTHENTICATION_FAILED,
  NCS_INVALID_ADDRESS,
  NCS_CREDENTIALS_REQUIRED,
  NCS_ACTION_REQUIRED,
  NCS_ACTION_REQUIRED_RETRY,
  NCS_CONNECT_FAILED
} NETCON_STATUS;