typedef enum tagNETCON_MEDIATYPE {
  NCM_NONE = 0,
  NCM_DIRECT,
  NCM_ISDN = 2,
  NCM_LAN,
  NCM_PHONE,
  NCM_TUNNEL,
  NCM_PPPOE,
  NCM_BRIDGE,
  NCM_SHAREDACCESSHOST_LAN,
  NCM_SHAREDACCESSHOST_RAS
} NETCON_MEDIATYPE;