typedef struct _ACX_FACTORY_CIRCUIT_OPERATION_CALLBACKS {
  ULONG                                        Size;
  PFN_ACX_FACTORY_CIRCUIT_CREATE_CIRCUITDEVICE EvtAcxFactoryCircuitCreateCircuitDevice;
  PFN_ACX_FACTORY_CIRCUIT_DELETE_CIRCUITDEVICE EvtAcxFactoryCircuitDeleteCircuitDevice;
  PFN_ACX_FACTORY_CIRCUIT_CREATE_CIRCUIT       EvtAcxFactoryCircuitCreateCircuit;
} ACX_FACTORY_CIRCUIT_OPERATION_CALLBACKS, *PACX_FACTORY_CIRCUIT_OPERATION_CALLBACKS;