typedef struct _ACX_FACTORY_CIRCUIT_PNPPOWER_CALLBACKS {
  ULONG                                    Size;
  PFN_ACX_FACTORY_CIRCUIT_PREPARE_HARDWARE EvtAcxFactoryCircuitPrepareHardware;
  PFN_ACX_FACTORY_CIRCUIT_RELEASE_HARDWARE EvtAcxFactoryCircuitReleaseHardware;
  PFN_ACX_FACTORY_CIRCUIT_POWER_UP         EvtAcxFactoryCircuitPowerUp;
  PFN_ACX_FACTORY_CIRCUIT_POWER_DOWN       EvtAcxFactoryCircuitPowerDown;
} ACX_FACTORY_CIRCUIT_PNPPOWER_CALLBACKS, *PACX_FACTORY_CIRCUIT_PNPPOWER_CALLBACKS;