typedef enum _TASK_SESSION_STATE_CHANGE_TYPE {
  TASK_CONSOLE_CONNECT = 1,
  TASK_CONSOLE_DISCONNECT = 2,
  TASK_REMOTE_CONNECT = 3,
  TASK_REMOTE_DISCONNECT = 4,
  TASK_SESSION_LOCK = 7,
  TASK_SESSION_UNLOCK = 8
} TASK_SESSION_STATE_CHANGE_TYPE;