typedef enum {
  eMINIPORT_IHV_DEFINED,
  eMINIPORT_BUFFER_COMPLETE,
  eMINIPORT_PIN_STATE,
  eMINIPORT_GET_STREAM_POSITION,
  eMINIPORT_SET_WAVERT_BUFFER_WRITE_POSITION,
  eMINIPORT_GET_PRESENTATION_POSITION,
  eMINIPORT_PROGRAM_DMA,
  eMINIPORT_GLITCH_REPORT,
  eMINIPORT_LAST_BUFFER_RENDERED,
  eMINIPORT_PROCESSING_MODE,
  eMINIPORT_FX_CLSID,
  eMINIPORT_MaxValue
} EPcMiniportEngineEvent;