typedef enum {
  WS_SERVICE_ENDPOINT_PROPERTY_ACCEPT_CHANNEL_CALLBACK = 0,
  WS_SERVICE_ENDPOINT_PROPERTY_CLOSE_CHANNEL_CALLBACK = 1,
  WS_SERVICE_ENDPOINT_PROPERTY_MAX_ACCEPTING_CHANNELS = 2,
  WS_SERVICE_ENDPOINT_PROPERTY_MAX_CONCURRENCY = 3,
  WS_SERVICE_ENDPOINT_PROPERTY_BODY_HEAP_MAX_SIZE = 4,
  WS_SERVICE_ENDPOINT_PROPERTY_BODY_HEAP_TRIM_SIZE = 5,
  WS_SERVICE_ENDPOINT_PROPERTY_MESSAGE_PROPERTIES = 6,
  WS_SERVICE_ENDPOINT_PROPERTY_MAX_CALL_POOL_SIZE = 7,
  WS_SERVICE_ENDPOINT_PROPERTY_MAX_CHANNEL_POOL_SIZE = 8,
  WS_SERVICE_ENDPOINT_PROPERTY_LISTENER_PROPERTIES = 9,
  WS_SERVICE_ENDPOINT_PROPERTY_CHECK_MUST_UNDERSTAND = 10,
  WS_SERVICE_ENDPOINT_PROPERTY_METADATA_EXCHANGE_TYPE = 11,
  WS_SERVICE_ENDPOINT_PROPERTY_METADATA = 12,
  WS_SERVICE_ENDPOINT_PROPERTY_METADATA_EXCHANGE_URL_SUFFIX = 13,
  WS_SERVICE_ENDPOINT_PROPERTY_MAX_CHANNELS = 14,
  WS_SERVICE_ENDPOINT_PROPERTY_MAX_CHANNELS_PER_IP
} WS_SERVICE_ENDPOINT_PROPERTY_ID;