typedef enum {
  WS_SECURITY_CONTEXT_PROPERTY_IDENTIFIER = 1,
  WS_SECURITY_CONTEXT_PROPERTY_USERNAME = 2,
  WS_SECURITY_CONTEXT_PROPERTY_MESSAGE_SECURITY_WINDOWS_TOKEN = 3,
  WS_SECURITY_CONTEXT_PROPERTY_SAML_ASSERTION = 4
} WS_SECURITY_CONTEXT_PROPERTY_ID;