typedef enum {
  WS_SECURITY_PROPERTY_TRANSPORT_PROTECTION_LEVEL = 1,
  WS_SECURITY_PROPERTY_ALGORITHM_SUITE = 2,
  WS_SECURITY_PROPERTY_ALGORITHM_SUITE_NAME = 3,
  WS_SECURITY_PROPERTY_MAX_ALLOWED_LATENCY = 4,
  WS_SECURITY_PROPERTY_TIMESTAMP_VALIDITY_DURATION = 5,
  WS_SECURITY_PROPERTY_MAX_ALLOWED_CLOCK_SKEW = 6,
  WS_SECURITY_PROPERTY_TIMESTAMP_USAGE = 7,
  WS_SECURITY_PROPERTY_SECURITY_HEADER_LAYOUT = 8,
  WS_SECURITY_PROPERTY_SECURITY_HEADER_VERSION = 9,
  WS_SECURITY_PROPERTY_EXTENDED_PROTECTION_POLICY = 10,
  WS_SECURITY_PROPERTY_EXTENDED_PROTECTION_SCENARIO = 11,
  WS_SECURITY_PROPERTY_SERVICE_IDENTITIES = 12
} WS_SECURITY_PROPERTY_ID;