typedef enum {
  WS_DNS_ENDPOINT_IDENTITY_TYPE = 1,
  WS_UPN_ENDPOINT_IDENTITY_TYPE = 2,
  WS_SPN_ENDPOINT_IDENTITY_TYPE = 3,
  WS_RSA_ENDPOINT_IDENTITY_TYPE = 4,
  WS_CERT_ENDPOINT_IDENTITY_TYPE = 5,
  WS_UNKNOWN_ENDPOINT_IDENTITY_TYPE = 6
} WS_ENDPOINT_IDENTITY_TYPE;