typedef enum {
  WS_EXCLUSIVE_XML_CANONICALIZATION_ALGORITHM = 0,
  WS_EXCLUSIVE_WITH_COMMENTS_XML_CANONICALIZATION_ALGORITHM = 1,
  WS_INCLUSIVE_XML_CANONICALIZATION_ALGORITHM = 2,
  WS_INCLUSIVE_WITH_COMMENTS_XML_CANONICALIZATION_ALGORITHM = 3
} WS_XML_CANONICALIZATION_ALGORITHM;