typedef enum {
  WS_SECURITY_TOKEN_REFERENCE_MODE_LOCAL_ID = 1,
  WS_SECURITY_TOKEN_REFERENCE_MODE_XML_BUFFER = 2,
  WS_SECURITY_TOKEN_REFERENCE_MODE_CERT_THUMBPRINT = 3,
  WS_SECURITY_TOKEN_REFERENCE_MODE_SECURITY_CONTEXT_ID = 4,
  WS_SECURITY_TOKEN_REFERENCE_MODE_SAML_ASSERTION_ID = 5
} WS_SECURITY_TOKEN_REFERENCE_MODE;