typedef enum {
  WS_CHANNEL_TYPE_INPUT = 0x1,
  WS_CHANNEL_TYPE_OUTPUT = 0x2,
  WS_CHANNEL_TYPE_SESSION = 0x4,
  WS_CHANNEL_TYPE_INPUT_SESSION,
  WS_CHANNEL_TYPE_OUTPUT_SESSION,
  WS_CHANNEL_TYPE_DUPLEX,
  WS_CHANNEL_TYPE_DUPLEX_SESSION,
  WS_CHANNEL_TYPE_REQUEST = 0x8,
  WS_CHANNEL_TYPE_REPLY = 0x10
} WS_CHANNEL_TYPE;