typedef enum {
  WS_OPERATION_CONTEXT_PROPERTY_CHANNEL = 0,
  WS_OPERATION_CONTEXT_PROPERTY_CONTRACT_DESCRIPTION = 1,
  WS_OPERATION_CONTEXT_PROPERTY_HOST_USER_STATE = 2,
  WS_OPERATION_CONTEXT_PROPERTY_CHANNEL_USER_STATE = 3,
  WS_OPERATION_CONTEXT_PROPERTY_INPUT_MESSAGE = 4,
  WS_OPERATION_CONTEXT_PROPERTY_OUTPUT_MESSAGE = 5,
  WS_OPERATION_CONTEXT_PROPERTY_HEAP = 6,
  WS_OPERATION_CONTEXT_PROPERTY_LISTENER = 7,
  WS_OPERATION_CONTEXT_PROPERTY_ENDPOINT_ADDRESS = 8
} WS_OPERATION_CONTEXT_PROPERTY_ID;