typedef enum {
  WS_XML_CANONICALIZATION_PROPERTY_ALGORITHM = 0,
  WS_XML_CANONICALIZATION_PROPERTY_INCLUSIVE_PREFIXES = 1,
  WS_XML_CANONICALIZATION_PROPERTY_OMITTED_ELEMENT = 2,
  WS_XML_CANONICALIZATION_PROPERTY_OUTPUT_BUFFER_SIZE = 3
} WS_XML_CANONICALIZATION_PROPERTY_ID;