typedef enum {
  WS_METADATA_PROPERTY_STATE = 1,
  WS_METADATA_PROPERTY_HEAP_PROPERTIES = 2,
  WS_METADATA_PROPERTY_POLICY_PROPERTIES = 3,
  WS_METADATA_PROPERTY_HEAP_REQUESTED_SIZE = 4,
  WS_METADATA_PROPERTY_MAX_DOCUMENTS = 5,
  WS_METADATA_PROPERTY_HOST_NAMES = 6,
  WS_METADATA_PROPERTY_VERIFY_HOST_NAMES = 7
} WS_METADATA_PROPERTY_ID;