typedef enum {
  WS_CALL_PROPERTY_CHECK_MUST_UNDERSTAND = 0,
  WS_CALL_PROPERTY_SEND_MESSAGE_CONTEXT = 1,
  WS_CALL_PROPERTY_RECEIVE_MESSAGE_CONTEXT = 2,
  WS_CALL_PROPERTY_CALL_ID = 3
} WS_CALL_PROPERTY_ID;