typedef enum {
  WS_SECURITY_HEADER_LAYOUT_STRICT = 1,
  WS_SECURITY_HEADER_LAYOUT_LAX = 2,
  WS_SECURITY_HEADER_LAYOUT_LAX_WITH_TIMESTAMP_FIRST = 3,
  WS_SECURITY_HEADER_LAYOUT_LAX_WITH_TIMESTAMP_LAST = 4
} WS_SECURITY_HEADER_LAYOUT;