typedef enum {
  WS_SERVICE_PROPERTY_HOST_USER_STATE = 0,
  WS_SERVICE_PROPERTY_FAULT_DISCLOSURE = 1,
  WS_SERVICE_PROPERTY_FAULT_LANGID = 2,
  WS_SERVICE_PROPERTY_HOST_STATE = 3,
  WS_SERVICE_PROPERTY_METADATA = 4,
  WS_SERVICE_PROPERTY_CLOSE_TIMEOUT = 5
} WS_SERVICE_PROPERTY_ID;