typedef enum {
  WS_XML_READER_ENCODING_TYPE_TEXT = 1,
  WS_XML_READER_ENCODING_TYPE_BINARY = 2,
  WS_XML_READER_ENCODING_TYPE_MTOM = 3,
  WS_XML_READER_ENCODING_TYPE_RAW = 4
} WS_XML_READER_ENCODING_TYPE;