typedef enum {
  WS_SECURITY_TOKEN_PROPERTY_KEY_TYPE = 1,
  WS_SECURITY_TOKEN_PROPERTY_VALID_FROM_TIME = 2,
  WS_SECURITY_TOKEN_PROPERTY_VALID_TILL_TIME = 3,
  WS_SECURITY_TOKEN_PROPERTY_SERIALIZED_XML = 4,
  WS_SECURITY_TOKEN_PROPERTY_ATTACHED_REFERENCE_XML = 5,
  WS_SECURITY_TOKEN_PROPERTY_UNATTACHED_REFERENCE_XML = 6,
  WS_SECURITY_TOKEN_PROPERTY_SYMMETRIC_KEY = 7
} WS_SECURITY_TOKEN_PROPERTY_ID;