typedef enum {
  WS_LISTENER_STATE_CREATED = 0,
  WS_LISTENER_STATE_OPENING = 1,
  WS_LISTENER_STATE_OPEN = 2,
  WS_LISTENER_STATE_FAULTED = 3,
  WS_LISTENER_STATE_CLOSING = 4,
  WS_LISTENER_STATE_CLOSED = 5
} WS_LISTENER_STATE;