typedef enum {
  WS_SERVICE_HOST_STATE_CREATED = 0,
  WS_SERVICE_HOST_STATE_OPENING = 1,
  WS_SERVICE_HOST_STATE_OPEN = 2,
  WS_SERVICE_HOST_STATE_CLOSING = 3,
  WS_SERVICE_HOST_STATE_CLOSED = 4,
  WS_SERVICE_HOST_STATE_FAULTED = 5
} WS_SERVICE_HOST_STATE;