typedef enum {
  WS_XML_SECURITY_TOKEN_PROPERTY_ATTACHED_REFERENCE = 1,
  WS_XML_SECURITY_TOKEN_PROPERTY_UNATTACHED_REFERENCE = 2,
  WS_XML_SECURITY_TOKEN_PROPERTY_VALID_FROM_TIME = 3,
  WS_XML_SECURITY_TOKEN_PROPERTY_VALID_TILL_TIME = 4
} WS_XML_SECURITY_TOKEN_PROPERTY_ID;