typedef enum {
  WS_ACTION_HEADER = 1,
  WS_TO_HEADER = 2,
  WS_MESSAGE_ID_HEADER = 3,
  WS_RELATES_TO_HEADER = 4,
  WS_FROM_HEADER = 5,
  WS_REPLY_TO_HEADER = 6,
  WS_FAULT_TO_HEADER = 7
} WS_HEADER_TYPE;