typedef enum {
  WS_REQUEST_SECURITY_TOKEN_ACTION_ISSUE = 1,
  WS_REQUEST_SECURITY_TOKEN_ACTION_NEW_CONTEXT = 2,
  WS_REQUEST_SECURITY_TOKEN_ACTION_RENEW_CONTEXT = 3
} WS_REQUEST_SECURITY_TOKEN_ACTION;