typedef enum {
  WS_ENCODING_XML_BINARY_1 = 0,
  WS_ENCODING_XML_BINARY_SESSION_1 = 1,
  WS_ENCODING_XML_MTOM_UTF8 = 2,
  WS_ENCODING_XML_MTOM_UTF16BE = 3,
  WS_ENCODING_XML_MTOM_UTF16LE = 4,
  WS_ENCODING_XML_UTF8 = 5,
  WS_ENCODING_XML_UTF16BE = 6,
  WS_ENCODING_XML_UTF16LE = 7,
  WS_ENCODING_RAW = 8
} WS_ENCODING;