typedef enum {
  WS_XML_NODE_TYPE_ELEMENT = 1,
  WS_XML_NODE_TYPE_TEXT = 2,
  WS_XML_NODE_TYPE_END_ELEMENT = 3,
  WS_XML_NODE_TYPE_COMMENT = 4,
  WS_XML_NODE_TYPE_CDATA = 6,
  WS_XML_NODE_TYPE_END_CDATA = 7,
  WS_XML_NODE_TYPE_EOF = 8,
  WS_XML_NODE_TYPE_BOF = 9
} WS_XML_NODE_TYPE;