typedef enum {
  WS_XML_READER_PROPERTY_MAX_DEPTH = 0,
  WS_XML_READER_PROPERTY_ALLOW_FRAGMENT = 1,
  WS_XML_READER_PROPERTY_MAX_ATTRIBUTES = 2,
  WS_XML_READER_PROPERTY_READ_DECLARATION = 3,
  WS_XML_READER_PROPERTY_CHARSET = 4,
  WS_XML_READER_PROPERTY_ROW = 5,
  WS_XML_READER_PROPERTY_COLUMN = 6,
  WS_XML_READER_PROPERTY_UTF8_TRIM_SIZE = 7,
  WS_XML_READER_PROPERTY_STREAM_BUFFER_SIZE = 8,
  WS_XML_READER_PROPERTY_IN_ATTRIBUTE = 9,
  WS_XML_READER_PROPERTY_STREAM_MAX_ROOT_MIME_PART_SIZE = 10,
  WS_XML_READER_PROPERTY_STREAM_MAX_MIME_HEADERS_SIZE = 11,
  WS_XML_READER_PROPERTY_MAX_MIME_PARTS = 12,
  WS_XML_READER_PROPERTY_ALLOW_INVALID_CHARACTER_REFERENCES = 13,
  WS_XML_READER_PROPERTY_MAX_NAMESPACES = 14
} WS_XML_READER_PROPERTY_ID;