typedef enum {
  WS_CHANNEL_STATE_CREATED = 0,
  WS_CHANNEL_STATE_OPENING = 1,
  WS_CHANNEL_STATE_ACCEPTING = 2,
  WS_CHANNEL_STATE_OPEN = 3,
  WS_CHANNEL_STATE_FAULTED = 4,
  WS_CHANNEL_STATE_CLOSING = 5,
  WS_CHANNEL_STATE_CLOSED = 6
} WS_CHANNEL_STATE;