typedef enum {
  WS_REQUEST_SECURITY_TOKEN_PROPERTY_APPLIES_TO = 1,
  WS_REQUEST_SECURITY_TOKEN_PROPERTY_TRUST_VERSION = 2,
  WS_REQUEST_SECURITY_TOKEN_PROPERTY_SECURE_CONVERSATION_VERSION = 3,
  WS_REQUEST_SECURITY_TOKEN_PROPERTY_ISSUED_TOKEN_TYPE = 4,
  WS_REQUEST_SECURITY_TOKEN_PROPERTY_REQUEST_ACTION = 5,
  WS_REQUEST_SECURITY_TOKEN_PROPERTY_EXISTING_TOKEN = 6,
  WS_REQUEST_SECURITY_TOKEN_PROPERTY_ISSUED_TOKEN_KEY_TYPE = 7,
  WS_REQUEST_SECURITY_TOKEN_PROPERTY_ISSUED_TOKEN_KEY_SIZE = 8,
  WS_REQUEST_SECURITY_TOKEN_PROPERTY_ISSUED_TOKEN_KEY_ENTROPY = 9,
  WS_REQUEST_SECURITY_TOKEN_PROPERTY_LOCAL_REQUEST_PARAMETERS = 10,
  WS_REQUEST_SECURITY_TOKEN_PROPERTY_SERVICE_REQUEST_PARAMETERS = 11,
  WS_REQUEST_SECURITY_TOKEN_PROPERTY_MESSAGE_PROPERTIES = 12,
  WS_REQUEST_SECURITY_TOKEN_PROPERTY_BEARER_KEY_TYPE_VERSION = 13
} WS_REQUEST_SECURITY_TOKEN_PROPERTY_ID;