typedef enum {
  WS_MOVE_TO_ROOT_ELEMENT = 0,
  WS_MOVE_TO_NEXT_ELEMENT = 1,
  WS_MOVE_TO_PREVIOUS_ELEMENT = 2,
  WS_MOVE_TO_CHILD_ELEMENT = 3,
  WS_MOVE_TO_END_ELEMENT = 4,
  WS_MOVE_TO_PARENT_ELEMENT = 5,
  WS_MOVE_TO_NEXT_NODE = 6,
  WS_MOVE_TO_PREVIOUS_NODE = 7,
  WS_MOVE_TO_FIRST_NODE = 8,
  WS_MOVE_TO_BOF = 9,
  WS_MOVE_TO_EOF = 10,
  WS_MOVE_TO_CHILD_NODE = 11
} WS_MOVE_TO;