typedef struct _WS_NAMEDPIPE_SSPI_TRANSPORT_SECURITY_BINDING {
  WS_SECURITY_BINDING                   binding;
  WS_WINDOWS_INTEGRATED_AUTH_CREDENTIAL *clientCredential;
} WS_NAMEDPIPE_SSPI_TRANSPORT_SECURITY_BINDING;