typedef struct _WS_SECURITY_CONTEXT_MESSAGE_SECURITY_BINDING_CONSTRAINT {
  WS_SECURITY_BINDING_CONSTRAINT bindingConstraint;
  WS_MESSAGE_SECURITY_USAGE      bindingUsage;
  WS_SECURITY_CONSTRAINTS        *bootstrapSecurityConstraint;
} WS_SECURITY_CONTEXT_MESSAGE_SECURITY_BINDING_CONSTRAINT;