typedef struct _WS_SAML_MESSAGE_SECURITY_BINDING {
  WS_SECURITY_BINDING       binding;
  WS_MESSAGE_SECURITY_USAGE bindingUsage;
  WS_SAML_AUTHENTICATOR     *authenticator;
} WS_SAML_MESSAGE_SECURITY_BINDING;