typedef struct _WS_CERT_MESSAGE_SECURITY_BINDING_CONSTRAINT {
  WS_SECURITY_BINDING_CONSTRAINT bindingConstraint;
  WS_MESSAGE_SECURITY_USAGE      bindingUsage;
} WS_CERT_MESSAGE_SECURITY_BINDING_CONSTRAINT;