typedef struct _WS_SECURITY_CONTEXT_SECURITY_BINDING_TEMPLATE {
  WS_SECURITY_CONTEXT_MESSAGE_SECURITY_BINDING_TEMPLATE securityContextMessageSecurityBinding;
  WS_SECURITY_PROPERTIES                                securityProperties;
} WS_SECURITY_CONTEXT_SECURITY_BINDING_TEMPLATE;