typedef struct _WS_TCP_SSPI_TRANSPORT_SECURITY_BINDING_TEMPLATE {
  WS_SECURITY_BINDING_PROPERTIES        securityBindingProperties;
  WS_WINDOWS_INTEGRATED_AUTH_CREDENTIAL *clientCredential;
} WS_TCP_SSPI_TRANSPORT_SECURITY_BINDING_TEMPLATE;