typedef struct _WS_SECURITY_CONTEXT_SECURITY_BINDING_POLICY_DESCRIPTION {
  WS_SECURITY_CONTEXT_MESSAGE_SECURITY_BINDING_POLICY_DESCRIPTION securityContextMessageSecurityBinding;
  WS_SECURITY_PROPERTIES                                          securityProperties;
} WS_SECURITY_CONTEXT_SECURITY_BINDING_POLICY_DESCRIPTION;