typedef struct _WS_SSL_TRANSPORT_SECURITY_BINDING_TEMPLATE {
  WS_SECURITY_BINDING_PROPERTIES securityBindingProperties;
  WS_CERT_CREDENTIAL             *localCertCredential;
} WS_SSL_TRANSPORT_SECURITY_BINDING_TEMPLATE;