typedef struct _WS_KERBEROS_APREQ_MESSAGE_SECURITY_BINDING_TEMPLATE {
  WS_SECURITY_BINDING_PROPERTIES        securityBindingProperties;
  WS_WINDOWS_INTEGRATED_AUTH_CREDENTIAL *clientCredential;
} WS_KERBEROS_APREQ_MESSAGE_SECURITY_BINDING_TEMPLATE;