typedef struct _WS_HTTP_HEADER_AUTH_SECURITY_BINDING {
  WS_SECURITY_BINDING                   binding;
  WS_WINDOWS_INTEGRATED_AUTH_CREDENTIAL *clientCredential;
} WS_HTTP_HEADER_AUTH_SECURITY_BINDING;