typedef struct _WS_HTTP_HEADER_AUTH_SECURITY_BINDING_TEMPLATE {
  WS_SECURITY_BINDING_PROPERTIES        securityBindingProperties;
  WS_WINDOWS_INTEGRATED_AUTH_CREDENTIAL *clientCredential;
} WS_HTTP_HEADER_AUTH_SECURITY_BINDING_TEMPLATE;