typedef struct _WS_SECURITY_CONTEXT_MESSAGE_SECURITY_BINDING {
  WS_SECURITY_BINDING       binding;
  WS_MESSAGE_SECURITY_USAGE bindingUsage;
  WS_SECURITY_DESCRIPTION   *bootstrapSecurityDescription;
} WS_SECURITY_CONTEXT_MESSAGE_SECURITY_BINDING;