typedef struct _WS_KERBEROS_APREQ_MESSAGE_SECURITY_BINDING {
  WS_SECURITY_BINDING                   binding;
  WS_MESSAGE_SECURITY_USAGE             bindingUsage;
  WS_WINDOWS_INTEGRATED_AUTH_CREDENTIAL *clientCredential;
} WS_KERBEROS_APREQ_MESSAGE_SECURITY_BINDING;