typedef enum {
  DS_UNKNOWN_NAME = 0,
  DS_FQDN_1779_NAME = 1,
  DS_NT4_ACCOUNT_NAME = 2,
  DS_DISPLAY_NAME = 3,
  DS_UNIQUE_ID_NAME = 6,
  DS_CANONICAL_NAME = 7,
  DS_USER_PRINCIPAL_NAME = 8,
  DS_CANONICAL_NAME_EX = 9,
  DS_SERVICE_PRINCIPAL_NAME = 10,
  DS_SID_OR_SID_HISTORY_NAME = 11,
  DS_DNS_DOMAIN_NAME = 12
} DS_NAME_FORMAT;