typedef enum _DS_REPL_INFO_TYPE {
  DS_REPL_INFO_NEIGHBORS = 0,
  DS_REPL_INFO_CURSORS_FOR_NC = 1,
  DS_REPL_INFO_METADATA_FOR_OBJ = 2,
  DS_REPL_INFO_KCC_DSA_CONNECT_FAILURES = 3,
  DS_REPL_INFO_KCC_DSA_LINK_FAILURES = 4,
  DS_REPL_INFO_PENDING_OPS = 5,
  DS_REPL_INFO_METADATA_FOR_ATTR_VALUE = 6,
  DS_REPL_INFO_CURSORS_2_FOR_NC = 7,
  DS_REPL_INFO_CURSORS_3_FOR_NC = 8,
  DS_REPL_INFO_METADATA_2_FOR_OBJ = 9,
  DS_REPL_INFO_METADATA_2_FOR_ATTR_VALUE = 10,
  DS_REPL_INFO_METADATA_EXT_FOR_ATTR_VALUE = 11,
  DS_REPL_INFO_TYPE_MAX
} DS_REPL_INFO_TYPE;