typedef enum {
  DS_NAME_NO_ERROR = 0,
  DS_NAME_ERROR_RESOLVING = 1,
  DS_NAME_ERROR_NOT_FOUND = 2,
  DS_NAME_ERROR_NOT_UNIQUE = 3,
  DS_NAME_ERROR_NO_MAPPING = 4,
  DS_NAME_ERROR_DOMAIN_ONLY = 5,
  DS_NAME_ERROR_NO_SYNTACTICAL_MAPPING = 6,
  DS_NAME_ERROR_TRUST_REFERRAL = 7
} DS_NAME_ERROR;