typedef enum AUDCLNT_STREAMOPTIONS {
  AUDCLNT_STREAMOPTIONS_NONE,
  AUDCLNT_STREAMOPTIONS_RAW,
  AUDCLNT_STREAMOPTIONS_MATCH_FORMAT,
  AUDCLNT_STREAMOPTIONS_AMBISONICS,
  AUDCLNT_STREAMOPTIONS_POST_VOLUME_LOOPBACK
} ;