typedef struct _CDROM_PERFORMANCE_REQUEST {
  CDROM_PERFORMANCE_REQUEST_TYPE   RequestType;
  CDROM_PERFORMANCE_TYPE           PerformanceType;
  CDROM_PERFORMANCE_EXCEPTION_TYPE Exceptions;
  CDROM_PERFORMANCE_TOLERANCE_TYPE Tolerance;
  ULONG                            StaringLba;
} CDROM_PERFORMANCE_REQUEST, *PCDROM_PERFORMANCE_REQUEST;