typedef struct _CDROM_NOMINAL_PERFORMANCE_DESCRIPTOR {
  UCHAR StartLba[4];
  UCHAR StartPerformance[4];
  UCHAR EndLba[4];
  UCHAR EndPerformance[4];
} CDROM_NOMINAL_PERFORMANCE_DESCRIPTOR, *PCDROM_NOMINAL_PERFORMANCE_DESCRIPTOR;