typedef enum _INET_FIREWALL_AC_CREATION_TYPE {
  INET_FIREWALL_AC_NONE = 0x00,
  INET_FIREWALL_AC_PACKAGE_ID_ONLY = 0x01,
  INET_FIREWALL_AC_BINARY = 0x02,
  INET_FIREWALL_AC_MAX = 0x04
} INET_FIREWALL_AC_CREATION_TYPE;