typedef enum _INET_FIREWALL_AC_CHANGE_TYPE {
  INET_FIREWALL_AC_CHANGE_INVALID = 0,
  INET_FIREWALL_AC_CHANGE_CREATE = 1,
  INET_FIREWALL_AC_CHANGE_DELETE = 2,
  INET_FIREWALL_AC_CHANGE_MAX = 3
} INET_FIREWALL_AC_CHANGE_TYPE;