enum DSTORAGE_COMPRESSION_SUPPORT : UINT32 {
  DSTORAGE_COMPRESSION_SUPPORT_NONE = 0,
  DSTORAGE_COMPRESSION_SUPPORT_GPU_OPTIMIZED = 1,
  DSTORAGE_COMPRESSION_SUPPORT_GPU_FALLBACK = 2,
  DSTORAGE_COMPRESSION_SUPPORT_CPU_FALLBACK = 4,
  DSTORAGE_COMPRESSION_SUPPORT_USES_COMPUTE_QUEUE = 8,
  DSTORAGE_COMPRESSION_SUPPORT_USES_COPY_QUEUE = 0x010
} ;