enum DSTORAGE_COMMAND_TYPE {
  DSTORAGE_COMMAND_TYPE_NONE = -1,
  DSTORAGE_COMMAND_TYPE_REQUEST = 0,
  DSTORAGE_COMMAND_TYPE_STATUS = 1,
  DSTORAGE_COMMAND_TYPE_SIGNAL = 2,
  DSTORAGE_COMMAND_TYPE_EVENT = 3,
} ;