enum DSTORAGE_REQUEST_DESTINATION_TYPE {
  DSTORAGE_REQUEST_DESTINATION_MEMORY = 0,
  DSTORAGE_REQUEST_DESTINATION_BUFFER = 1,
  DSTORAGE_REQUEST_DESTINATION_TEXTURE_REGION = 2,
  DSTORAGE_REQUEST_DESTINATION_MULTIPLE_SUBRESOURCES = 3,
  DSTORAGE_REQUEST_DESTINATION_TILES = 4,
  DSTORAGE_REQUEST_DESTINATION_MULTIPLE_SUBRESOURCES_RANGE = 5
};