enum DSTORAGE_ENQUEUE_REQUEST_FLAGS : UINT32 {
  DSTORAGE_ENQUEUE_REQUEST_FLAG_NONE = 0,
  DSTORAGE_ENQUEUE_REQUEST_FLAG_FENCE_WAIT_BEFORE_GPU_WORK = 1,
  DSTORAGE_ENQUEUE_REQUEST_FLAG_FENCE_WAIT_BEFORE_SOURCE_ACCESS = 2
} ;