enum DSTORAGE_GET_REQUEST_FLAGS {
  DSTORAGE_GET_REQUEST_FLAG_SELECT_CUSTOM = 0x01,
  DSTORAGE_GET_REQUEST_FLAG_SELECT_BUILTIN = 0x02,
  DSTORAGE_GET_REQUEST_FLAG_SELECT_ALL = (DSTORAGE_GET_REQUEST_FLAG_SELECT_CUSTOM | DSTORAGE_GET_REQUEST_FLAG_SELECT_BUILTIN)
} ;