enum DSTORAGE_PRIORITY {
  DSTORAGE_PRIORITY_LOW,
  DSTORAGE_PRIORITY_NORMAL,
  DSTORAGE_PRIORITY_HIGH,
  DSTORAGE_PRIORITY_REALTIME,
  DSTORAGE_PRIORITY_FIRST,
  DSTORAGE_PRIORITY_LAST,
  DSTORAGE_PRIORITY_COUNT
} ;