struct DSTORAGE_ERROR_FIRST_FAILURE {
  HRESULT               HResult;
  DSTORAGE_COMMAND_TYPE CommandType;
  union {
    DSTORAGE_ERROR_PARAMETERS_REQUEST Request;
    DSTORAGE_ERROR_PARAMETERS_STATUS  Status;
    DSTORAGE_ERROR_PARAMETERS_SIGNAL  Signal;
  };
};