typedef enum __MIDL___MIDL_itf_windowssensorclassextension_0000_0000_0001 {
  SENSOR_STATE_MIN,
  SENSOR_STATE_READY,
  SENSOR_STATE_NOT_AVAILABLE,
  SENSOR_STATE_NO_DATA,
  SENSOR_STATE_INITIALIZING,
  SENSOR_STATE_ACCESS_DENIED,
  SENSOR_STATE_ERROR,
  SENSOR_STATE_MAX
} SensorState;