typedef enum tagWCN_PASSWORD_TYPE {
  WCN_PASSWORD_TYPE_PUSH_BUTTON = 0,
  WCN_PASSWORD_TYPE_PIN,
  WCN_PASSWORD_TYPE_PIN_REGISTRAR_SPECIFIED,
  WCN_PASSWORD_TYPE_OOB_SPECIFIED,
  WCN_PASSWORD_TYPE_WFDS
} WCN_PASSWORD_TYPE;