typedef enum _eAVEncVideoQPMapElementDataType {
  CODEC_API_QP_MAP_INT8,
  CODEC_API_QP_MAP_INT16,
  CODEC_API_QP_MAP_INT32,
  CODEC_API_QP_MAP_UINT8,
  CODEC_API_QP_MAP_UINT16,
  CODEC_API_QP_MAP_UINT32
} eAVEncVideoQPMapElementDataType;