typedef enum _MFSampleEncryptionProtectionScheme {
  MF_SAMPLE_ENCRYPTION_PROTECTION_SCHEME_NONE = 0,
  MF_SAMPLE_ENCRYPTION_PROTECTION_SCHEME_AES_CTR = 1,
  MF_SAMPLE_ENCRYPTION_PROTECTION_SCHEME_AES_CBC = 2
} MFSampleEncryptionProtectionScheme;