typedef enum PHONE_EVENT {
  PE_DISPLAY = 0,
  PE_LAMPMODE,
  PE_RINGMODE,
  PE_RINGVOLUME,
  PE_HOOKSWITCH,
  PE_CAPSCHANGE,
  PE_BUTTON,
  PE_CLOSE,
  PE_NUMBERGATHERED,
  PE_DIALING,
  PE_ANSWER,
  PE_DISCONNECT,
  PE_LASTITEM
} ;