typedef enum CALLINFO_BUFFER {
  CIB_USERUSERINFO = 0,
  CIB_DEVSPECIFICBUFFER,
  CIB_CALLDATABUFFER,
  CIB_CHARGINGINFOBUFFER,
  CIB_HIGHLEVELCOMPATIBILITYBUFFER,
  CIB_LOWLEVELCOMPATIBILITYBUFFER
} ;