typedef enum PHONECAPS_LONG {
  PCL_HOOKSWITCHES = 0,
  PCL_HANDSETHOOKSWITCHMODES,
  PCL_HEADSETHOOKSWITCHMODES,
  PCL_SPEAKERPHONEHOOKSWITCHMODES,
  PCL_DISPLAYNUMROWS,
  PCL_DISPLAYNUMCOLUMNS,
  PCL_NUMRINGMODES,
  PCL_NUMBUTTONLAMPS,
  PCL_GENERICPHONE
} ;