typedef enum CALL_STATE_EVENT_CAUSE {
  CEC_NONE = 0,
  CEC_DISCONNECT_NORMAL,
  CEC_DISCONNECT_BUSY,
  CEC_DISCONNECT_BADADDRESS,
  CEC_DISCONNECT_NOANSWER,
  CEC_DISCONNECT_CANCELLED,
  CEC_DISCONNECT_REJECTED,
  CEC_DISCONNECT_FAILED,
  CEC_DISCONNECT_BLOCKED
} ;