typedef enum CALLINFO_STRING {
  CIS_CALLERIDNAME = 0,
  CIS_CALLERIDNUMBER,
  CIS_CALLEDIDNAME,
  CIS_CALLEDIDNUMBER,
  CIS_CONNECTEDIDNAME,
  CIS_CONNECTEDIDNUMBER,
  CIS_REDIRECTIONIDNAME,
  CIS_REDIRECTIONIDNUMBER,
  CIS_REDIRECTINGIDNAME,
  CIS_REDIRECTINGIDNUMBER,
  CIS_CALLEDPARTYFRIENDLYNAME,
  CIS_COMMENT,
  CIS_DISPLAYABLEADDRESS,
  CIS_CALLINGPARTYID
} ;