typedef enum CALL_MEDIA_EVENT_CAUSE {
  CMC_UNKNOWN = 0,
  CMC_BAD_DEVICE,
  CMC_CONNECT_FAIL,
  CMC_LOCAL_REQUEST,
  CMC_REMOTE_REQUEST,
  CMC_MEDIA_TIMEOUT,
  CMC_MEDIA_RECOVERED,
  CMC_QUALITY_OF_SERVICE
} ;