typedef enum CreatePackageDependencyOptions {
  CreatePackageDependencyOptions_None,
  CreatePackageDependencyOptions_DoNotVerifyDependencyResolution,
  CreatePackageDependencyOptions_ScopeIsSystem
} ;