typedef enum WSManProxyAccessType {
  WSMAN_OPTION_PROXY_IE_PROXY_CONFIG = 1,
  WSMAN_OPTION_PROXY_WINHTTP_PROXY_CONFIG = 2,
  WSMAN_OPTION_PROXY_AUTO_DETECT = 4,
  WSMAN_OPTION_PROXY_NO_PROXY_SERVER = 8
} ;