typedef enum WSManAuthenticationFlags {
  WSMAN_FLAG_DEFAULT_AUTHENTICATION = 0x0,
  WSMAN_FLAG_NO_AUTHENTICATION = 0x1,
  WSMAN_FLAG_AUTH_DIGEST = 0x2,
  WSMAN_FLAG_AUTH_NEGOTIATE = 0x4,
  WSMAN_FLAG_AUTH_BASIC = 0x8,
  WSMAN_FLAG_AUTH_KERBEROS = 0x10,
  WSMAN_FLAG_AUTH_CREDSSP = 0x80,
  WSMAN_FLAG_AUTH_CLIENT_CERTIFICATE = 0x20
} ;