typedef enum _CREATE_VIRTUAL_DISK_FLAG {
  CREATE_VIRTUAL_DISK_FLAG_NONE = 0x0,
  CREATE_VIRTUAL_DISK_FLAG_FULL_PHYSICAL_ALLOCATION = 0x1,
  CREATE_VIRTUAL_DISK_FLAG_PREVENT_WRITES_TO_SOURCE_DISK = 0x2,
  CREATE_VIRTUAL_DISK_FLAG_DO_NOT_COPY_METADATA_FROM_PARENT = 0x4,
  CREATE_VIRTUAL_DISK_FLAG_CREATE_BACKING_STORAGE = 0x8,
  CREATE_VIRTUAL_DISK_FLAG_USE_CHANGE_TRACKING_SOURCE_LIMIT = 0x10,
  CREATE_VIRTUAL_DISK_FLAG_PRESERVE_PARENT_CHANGE_TRACKING_STATE = 0x20,
  CREATE_VIRTUAL_DISK_FLAG_VHD_SET_USE_ORIGINAL_BACKING_STORAGE = 0x40,
  CREATE_VIRTUAL_DISK_FLAG_SPARSE_FILE = 0x80,
  CREATE_VIRTUAL_DISK_FLAG_PMEM_COMPATIBLE = 0x100,
  CREATE_VIRTUAL_DISK_FLAG_SUPPORT_COMPRESSED_VOLUMES,
  CREATE_VIRTUAL_DISK_FLAG_SUPPORT_SPARSE_FILES_ANY_FS
} CREATE_VIRTUAL_DISK_FLAG;