typedef enum _MODIFY_VHDSET_VERSION {
  MODIFY_VHDSET_UNSPECIFIED = 0,
  MODIFY_VHDSET_SNAPSHOT_PATH = 1,
  MODIFY_VHDSET_REMOVE_SNAPSHOT = 2,
  MODIFY_VHDSET_DEFAULT_SNAPSHOT_PATH = 3
} MODIFY_VHDSET_VERSION, *PMODIFY_VHDSET_VERSION;