typedef enum _OPEN_VIRTUAL_DISK_VERSION {
  OPEN_VIRTUAL_DISK_VERSION_UNSPECIFIED = 0,
  OPEN_VIRTUAL_DISK_VERSION_1 = 1,
  OPEN_VIRTUAL_DISK_VERSION_2 = 2,
  OPEN_VIRTUAL_DISK_VERSION_3 = 3
} OPEN_VIRTUAL_DISK_VERSION;