typedef enum _SET_VIRTUAL_DISK_INFO_VERSION {
  SET_VIRTUAL_DISK_INFO_UNSPECIFIED = 0,
  SET_VIRTUAL_DISK_INFO_PARENT_PATH = 1,
  SET_VIRTUAL_DISK_INFO_IDENTIFIER = 2,
  SET_VIRTUAL_DISK_INFO_PARENT_PATH_WITH_DEPTH = 3,
  SET_VIRTUAL_DISK_INFO_PHYSICAL_SECTOR_SIZE = 4,
  SET_VIRTUAL_DISK_INFO_VIRTUAL_DISK_ID = 5,
  SET_VIRTUAL_DISK_INFO_CHANGE_TRACKING_STATE = 6,
  SET_VIRTUAL_DISK_INFO_PARENT_LOCATOR = 7
} SET_VIRTUAL_DISK_INFO_VERSION;