typedef enum _MIRROR_VIRTUAL_DISK_FLAG {
  MIRROR_VIRTUAL_DISK_FLAG_NONE = 0x00000000,
  MIRROR_VIRTUAL_DISK_FLAG_EXISTING_FILE = 0x00000001,
  MIRROR_VIRTUAL_DISK_FLAG_SKIP_MIRROR_ACTIVATION = 0x00000002,
  MIRROR_VIRTUAL_DISK_FLAG_ENABLE_SMB_COMPRESSION,
  MIRROR_VIRTUAL_DISK_FLAG_IS_LIVE_MIGRATION
} MIRROR_VIRTUAL_DISK_FLAG;