typedef enum _ATTACH_VIRTUAL_DISK_FLAG {
  ATTACH_VIRTUAL_DISK_FLAG_NONE = 0x00000000,
  ATTACH_VIRTUAL_DISK_FLAG_READ_ONLY = 0x00000001,
  ATTACH_VIRTUAL_DISK_FLAG_NO_DRIVE_LETTER = 0x00000002,
  ATTACH_VIRTUAL_DISK_FLAG_PERMANENT_LIFETIME = 0x00000004,
  ATTACH_VIRTUAL_DISK_FLAG_NO_LOCAL_HOST = 0x00000008,
  ATTACH_VIRTUAL_DISK_FLAG_NO_SECURITY_DESCRIPTOR = 0x00000010,
  ATTACH_VIRTUAL_DISK_FLAG_BYPASS_DEFAULT_ENCRYPTION_POLICY = 0x00000020,
  ATTACH_VIRTUAL_DISK_FLAG_NON_PNP,
  ATTACH_VIRTUAL_DISK_FLAG_RESTRICTED_RANGE,
  ATTACH_VIRTUAL_DISK_FLAG_SINGLE_PARTITION,
  ATTACH_VIRTUAL_DISK_FLAG_REGISTER_VOLUME,
  ATTACH_VIRTUAL_DISK_FLAG_AT_BOOT
} ATTACH_VIRTUAL_DISK_FLAG;