typedef enum _CREATE_VIRTUAL_DISK_VERSION {
  CREATE_VIRTUAL_DISK_VERSION_UNSPECIFIED = 0,
  CREATE_VIRTUAL_DISK_VERSION_1 = 1,
  CREATE_VIRTUAL_DISK_VERSION_2 = 2,
  CREATE_VIRTUAL_DISK_VERSION_3 = 3,
  CREATE_VIRTUAL_DISK_VERSION_4 = 4
} CREATE_VIRTUAL_DISK_VERSION;