typedef enum INTERACTION_CONTEXT_PROPERTY {
  INTERACTION_CONTEXT_PROPERTY_MEASUREMENT_UNITS = 0x00000001,
  INTERACTION_CONTEXT_PROPERTY_INTERACTION_UI_FEEDBACK = 0x00000002,
  INTERACTION_CONTEXT_PROPERTY_FILTER_POINTERS = 0x00000003,
  INTERACTION_CONTEXT_PROPERTY_MAX = 0xffffffff
} ;