typedef enum HOLD_PARAMETER {
  HOLD_PARAMETER_MIN_CONTACT_COUNT,
  HOLD_PARAMETER_MAX_CONTACT_COUNT,
  HOLD_PARAMETER_THRESHOLD_RADIUS,
  HOLD_PARAMETER_THRESHOLD_START_DELAY,
  HOLD_PARAMETER_MAX
} ;