typedef struct INTERACTION_ARGUMENTS_MANIPULATION {
  MANIPULATION_TRANSFORM   delta;
  MANIPULATION_TRANSFORM   cumulative;
  MANIPULATION_VELOCITY    velocity;
  MANIPULATION_RAILS_STATE railsState;
} INTERACTION_ARGUMENTS_MANIPULATION;