typedef struct _PKTMON_NETEVT_CLIENT_REPORT_PACKET_DROP_OUT {
  PKTMON_EVT_STREAM_PACKET_HEADER *BufferStart;
  UCHAR                           *BufferEnd;
} PKTMON_NETEVT_CLIENT_REPORT_PACKET_DROP_OUT;