typedef struct _INTERFACE_SOFTWARE_TIMESTAMP_CAPABILITIES {
  BOOLEAN AllReceive;
  BOOLEAN AllTransmit;
  BOOLEAN TaggedTransmit;
} INTERFACE_SOFTWARE_TIMESTAMP_CAPABILITIES, *PINTERFACE_SOFTWARE_TIMESTAMP_CAPABILITIES;