typedef struct _INTERFACE_HARDWARE_CROSSTIMESTAMP {
  ULONG64 SystemTimestamp1;
  ULONG64 HardwareClockTimestamp;
  ULONG64 SystemTimestamp2;
} INTERFACE_HARDWARE_CROSSTIMESTAMP, *PINTERFACE_HARDWARE_CROSSTIMESTAMP;