typedef enum PROPDESC_SEARCHINFO_FLAGS {
  PDSIF_DEFAULT = 0,
  PDSIF_ININVERTEDINDEX = 0x1,
  PDSIF_ISCOLUMN = 0x2,
  PDSIF_ISCOLUMNSPARSE = 0x4,
  PDSIF_ALWAYSINCLUDE = 0x8,
  PDSIF_USEFORTYPEAHEAD = 0x10
} ;