typedef enum _MFP_CREDENTIAL_FLAGS {
  MFP_CREDENTIAL_PROMPT = 0x1,
  MFP_CREDENTIAL_SAVE = 0x2,
  MFP_CREDENTIAL_DO_NOT_CACHE = 0x4,
  MFP_CREDENTIAL_CLEAR_TEXT = 0x8,
  MFP_CREDENTIAL_PROXY = 0x10,
  MFP_CREDENTIAL_LOGGED_ON_USER = 0x20
} ;