typedef enum MFP_MEDIAPLAYER_STATE {
  MFP_MEDIAPLAYER_STATE_EMPTY = 0,
  MFP_MEDIAPLAYER_STATE_STOPPED = 0x1,
  MFP_MEDIAPLAYER_STATE_PLAYING = 0x2,
  MFP_MEDIAPLAYER_STATE_PAUSED = 0x3,
  MFP_MEDIAPLAYER_STATE_SHUTDOWN = 0x4
} ;