typedef enum tagPROGRESS_DIALOG_IMAGE_TYPE {
  PROGRESS_DIALOG_ICON_SMALL = 0,
  PROGRESS_DIALOG_ICON_LARGE = 0x1,
  PROGRESS_DIALOG_ICON_THUMBNAIL = 0x2,
  PROGRESS_DIALOG_BITMAP_THUMBNAIL = 0x3
} PROGRESS_DIALOG_IMAGE_TYPE;