typedef enum tagERROR_ADVISE_MESSAGE_TYPE {
  PHOTOACQUIRE_ERROR_SKIPRETRYCANCEL = 0,
  PHOTOACQUIRE_ERROR_RETRYCANCEL = 1,
  PHOTOACQUIRE_ERROR_YESNO = 2,
  PHOTOACQUIRE_ERROR_OK = 3
} ERROR_ADVISE_MESSAGE_TYPE;