typedef enum tagDEVICE_SELECTION_DEVICE_TYPE {
  DST_UNKNOWN_DEVICE = 0,
  DST_WPD_DEVICE = 0x1,
  DST_WIA_DEVICE = 0x2,
  DST_STI_DEVICE = 0x3,
  DSF_TWAIN_DEVICE = 0x4,
  DST_FS_DEVICE = 0x5,
  DST_DV_DEVICE = 0x6
} DEVICE_SELECTION_DEVICE_TYPE;