typedef struct _PDTT_PCC_SUBCHANNEL_INDENTIFIER {
  UCHAR SubChannelId;
  UCHAR Runtime : 1;
  UCHAR WaitCompletion : 1;
  UCHAR Reserved : 6;
} PDTT_PCC_SUBCHANNEL_INDENTIFIER, *PPDTT_PCC_SUBCHANNEL_INDENTIFIER;