typedef union _ASPT_ENTRY {
  ASPT_ENTRY_HEADER                    Header;
  ASPT_ENTRY_ASP_GLOBAL_REGISTERS_V1   AspGlobalRegistersV1;
  ASPT_ENTRY_SEV_MAILBOX_REGISTERS_V1  SevMailboxRegistersV1;
  ASPT_ENTRY_ACPI_MAILBOX_REGISTERS_V1 AcpiMailboxRegistersV1;
  ASPT_ENTRY_ASP_GLOBAL_REGISTERS_V2   AspGlobalRegistersV2;
  ASPT_ENTRY_SEV_MAILBOX_REGISTERS_V2  SevMailboxRegistersV2;
  ASPT_ENTRY_ACPI_MAILBOX_REGISTERS_V2 AcpiMailboxRegistersV2;
} ASPT_ENTRY, *PASPT_ENTRY;