typedef enum {
  RX_CONTEXT_CREATE_FLAG_UNC_NAME = 0x1,
  RX_CONTEXT_CREATE_FLAG_STRIPPED_TRAILING_BACKSLASH = 0x2,
  RX_CONTEXT_CREATE_FLAG_ADDEDBACKSLASH = 0x4,
  RX_CONTEXT_CREATE_FLAG_REPARSE = 0x8,
  RX_CONTEXT_CREATE_FLAG_SPECIAL_PATH = 0x10
} RX_CONTEXT_CREATE_FLAGS;