typedef enum {
  RXCONTEXT_FLAG4LOWIO_PIPE_OPERATION = 0x1,
  RXCONTEXT_FLAG4LOWIO_PIPE_SYNC_OPERATION = 0x2,
  RXCONTEXT_FLAG4LOWIO_READAHEAD = 0x4,
  RXCONTEXT_FLAG4LOWIO_THIS_READ_ENLARGED = 0x8,
  RXCONTEXT_FLAG4LOWIO_THIS_IO_BUFFERED = 0x10,
  RXCONTEXT_FLAG4LOWIO_LOCK_FCB_RESOURCE_HELD = 0x20,
  RXCONTEXT_FLAG4LOWIO_LOCK_WAS_QUEUED_IN_LOCKMANAGER = 0x40,
  RXCONTEXT_FLAG4LOWIO_THIS_IO_FAST = 0x80,
  RXCONTEXT_FLAG4LOWIO_LOCK_OPERATION_COMPLETED = 0x100,
  RXCONTEXT_FLAG4LOWIO_LOCK_BUFFERED_ON_ENTRY = 0x200
} RX_CONTEXT_LOWIO_FLAGS;