typedef enum _WEB_SOCKET_ACTION {
  WEB_SOCKET_NO_ACTION = 0,
  WEB_SOCKET_SEND_TO_NETWORK_ACTION = 1,
  WEB_SOCKET_INDICATE_SEND_COMPLETE_ACTION = 2,
  WEB_SOCKET_RECEIVE_FROM_NETWORK_ACTION = 3,
  WEB_SOCKET_INDICATE_RECEIVE_COMPLETE_ACTION = 4
} WEB_SOCKET_ACTION, *PWEB_SOCKET_ACTION;