typedef enum _WEB_SOCKET_CLOSE_STATUS {
  WEB_SOCKET_SUCCESS_CLOSE_STATUS = 1000,
  WEB_SOCKET_ENDPOINT_UNAVAILABLE_CLOSE_STATUS = 1001,
  WEB_SOCKET_PROTOCOL_ERROR_CLOSE_STATUS = 1002,
  WEB_SOCKET_INVALID_DATA_TYPE_CLOSE_STATUS = 1003,
  WEB_SOCKET_EMPTY_CLOSE_STATUS = 1005,
  WEB_SOCKET_ABORTED_CLOSE_STATUS = 1006,
  WEB_SOCKET_INVALID_PAYLOAD_CLOSE_STATUS = 1007,
  WEB_SOCKET_POLICY_VIOLATION_CLOSE_STATUS = 1008,
  WEB_SOCKET_MESSAGE_TOO_BIG_CLOSE_STATUS = 1009,
  WEB_SOCKET_UNSUPPORTED_EXTENSIONS_CLOSE_STATUS = 1010,
  WEB_SOCKET_SERVER_ERROR_CLOSE_STATUS = 1011,
  WEB_SOCKET_SECURE_HANDSHAKE_ERROR_CLOSE_STATUS = 1015
} WEB_SOCKET_CLOSE_STATUS;