typedef enum _WEB_SOCKET_PROPERTY_TYPE {
  WEB_SOCKET_RECEIVE_BUFFER_SIZE_PROPERTY_TYPE = 0,
  WEB_SOCKET_SEND_BUFFER_SIZE_PROPERTY_TYPE = 1,
  WEB_SOCKET_DISABLE_MASKING_PROPERTY_TYPE = 2,
  WEB_SOCKET_ALLOCATED_BUFFER_PROPERTY_TYPE = 3,
  WEB_SOCKET_DISABLE_UTF8_VERIFICATION_PROPERTY_TYPE = 4,
  WEB_SOCKET_KEEPALIVE_INTERVAL_PROPERTY_TYPE = 5,
  WEB_SOCKET_SUPPORTED_VERSIONS_PROPERTY_TYPE = 6
} WEB_SOCKET_PROPERTY_TYPE;