typedef struct _CERT_KEY_USAGE_RESTRICTION_INFO {
  DWORD           cCertPolicyId;
  PCERT_POLICY_ID rgCertPolicyId;
  CRYPT_BIT_BLOB  RestrictedKeyUsage;
} CERT_KEY_USAGE_RESTRICTION_INFO, *PCERT_KEY_USAGE_RESTRICTION_INFO;