typedef struct _CERT_AUTHORITY_KEY_ID_INFO {
  CRYPT_DATA_BLOB    KeyId;
  CERT_NAME_BLOB     CertIssuer;
  CRYPT_INTEGER_BLOB CertSerialNumber;
} CERT_AUTHORITY_KEY_ID_INFO, *PCERT_AUTHORITY_KEY_ID_INFO;