typedef struct _CRYPT_ENCRYPTED_PRIVATE_KEY_INFO {
  CRYPT_ALGORITHM_IDENTIFIER EncryptionAlgorithm;
  CRYPT_DATA_BLOB            EncryptedPrivateKey;
} CRYPT_ENCRYPTED_PRIVATE_KEY_INFO, *PCRYPT_ENCRYPTED_PRIVATE_KEY_INFO;