typedef struct _AUTHENTICODE_EXTRA_CERT_CHAIN_POLICY_PARA {
  DWORD             cbSize;
  DWORD             dwRegPolicySettings;
  PCMSG_SIGNER_INFO pSignerInfo;
} AUTHENTICODE_EXTRA_CERT_CHAIN_POLICY_PARA, *PAUTHENTICODE_EXTRA_CERT_CHAIN_POLICY_PARA;