typedef struct _CMSG_CTRL_DEL_SIGNER_UNAUTH_ATTR_PARA {
  DWORD cbSize;
  DWORD dwSignerIndex;
  DWORD dwUnauthAttrIndex;
} CMSG_CTRL_DEL_SIGNER_UNAUTH_ATTR_PARA, *PCMSG_CTRL_DEL_SIGNER_UNAUTH_ATTR_PARA;