typedef struct _CRYPT_OBJECT_LOCATOR_PROVIDER_TABLE {
  DWORD                                             cbSize;
  PFN_CRYPT_OBJECT_LOCATOR_PROVIDER_GET             pfnGet;
  PFN_CRYPT_OBJECT_LOCATOR_PROVIDER_RELEASE         pfnRelease;
  PFN_CRYPT_OBJECT_LOCATOR_PROVIDER_FREE_PASSWORD   pfnFreePassword;
  PFN_CRYPT_OBJECT_LOCATOR_PROVIDER_FREE            pfnFree;
  PFN_CRYPT_OBJECT_LOCATOR_PROVIDER_FREE_IDENTIFIER pfnFreeIdentifier;
} CRYPT_OBJECT_LOCATOR_PROVIDER_TABLE, *PCRYPT_OBJECT_LOCATOR_PROVIDER_TABLE;