typedef struct _SSL_F12_EXTRA_CERT_CHAIN_POLICY_STATUS {
  DWORD cbSize;
  DWORD dwErrorLevel;
  DWORD dwErrorCategory;
  DWORD dwReserved;
  WCHAR wszErrorText[SSL_F12_ERROR_TEXT_LENGTH];
} SSL_F12_EXTRA_CERT_CHAIN_POLICY_STATUS, *PSSL_F12_EXTRA_CERT_CHAIN_POLICY_STATUS;