typedef struct _CRYPT_CONTENT_INFO_SEQUENCE_OF_ANY {
  LPSTR           pszObjId;
  DWORD           cValue;
  PCRYPT_DER_BLOB rgValue;
} CRYPT_CONTENT_INFO_SEQUENCE_OF_ANY, *PCRYPT_CONTENT_INFO_SEQUENCE_OF_ANY;