typedef struct _CERT_AUTHORITY_KEY_ID2_INFO {
  CRYPT_DATA_BLOB    KeyId;
  CERT_ALT_NAME_INFO AuthorityCertIssuer;
  CRYPT_INTEGER_BLOB AuthorityCertSerialNumber;
} CERT_AUTHORITY_KEY_ID2_INFO, *PCERT_AUTHORITY_KEY_ID2_INFO;