typedef struct _CMSG_CTRL_ADD_SIGNER_UNAUTH_ATTR_PARA {
  DWORD           cbSize;
  DWORD           dwSignerIndex;
  CRYPT_DATA_BLOB blob;
} CMSG_CTRL_ADD_SIGNER_UNAUTH_ATTR_PARA, *PCMSG_CTRL_ADD_SIGNER_UNAUTH_ATTR_PARA;