typedef enum D2D1_CHANGE_TYPE {
  D2D1_CHANGE_TYPE_NONE = 0,
  D2D1_CHANGE_TYPE_PROPERTIES = 1,
  D2D1_CHANGE_TYPE_CONTEXT = 2,
  D2D1_CHANGE_TYPE_GRAPH = 3,
  D2D1_CHANGE_TYPE_FORCE_DWORD = 0xffffffff
} ;