typedef enum SYNC_ENGINE_STATE_FLAGS {
  SESF_NONE = 0,
  SESF_SERVICE_QUOTA_NEARING_LIMIT = 0x1,
  SESF_SERVICE_QUOTA_EXCEEDED_LIMIT = 0x2,
  SESF_AUTHENTICATION_ERROR = 0x4,
  SESF_PAUSED_DUE_TO_METERED_NETWORK = 0x8,
  SESF_PAUSED_DUE_TO_DISK_SPACE_FULL = 0x10,
  SESF_PAUSED_DUE_TO_CLIENT_POLICY = 0x20,
  SESF_PAUSED_DUE_TO_SERVICE_POLICY = 0x40,
  SESF_SERVICE_UNAVAILABLE = 0x80,
  SESF_PAUSED_DUE_TO_USER_REQUEST = 0x100,
  SESF_ALL_FLAGS
} ;