typedef enum NSTCSTYLE2 {
  NSTCS2_DEFAULT = 0,
  NSTCS2_INTERRUPTNOTIFICATIONS = 0x1,
  NSTCS2_SHOWNULLSPACEMENU = 0x2,
  NSTCS2_DISPLAYPADDING = 0x4,
  NSTCS2_DISPLAYPINNEDONLY = 0x8,
  NTSCS2_NOSINGLETONAUTOEXPAND = 0x10,
  NTSCS2_NEVERINSERTNONENUMERATED = 0x20
} ;