typedef struct _CLS_ARCHIVE_DESCRIPTOR {
  ULONGLONG                 coffLow;
  ULONGLONG                 coffHigh;
  CLS_CONTAINER_INFORMATION infoContainer;
} CLS_ARCHIVE_DESCRIPTOR, *PCLS_ARCHIVE_DESCRIPTOR, PPCLS_ARCHIVE_DESCRIPTOR;