typedef enum _WDI_SAE_INDICATION_TYPE {
  WDI_SAE_INDICATION_TYPE_COMMIT_REQUEST_PARAMS_NEEDED = 0,
  WDI_SAE_INDICATION_TYPE_COMMIT_FRAME = 1,
  WDI_SAE_INDICATION_TYPE_CONFIRM_FRAME = 2,
  WDI_SAE_INDICATION_TYPE_ERROR = 3,
  WDI_SAE_INDICATION_TYPE_CONFIRM_REQUEST_RESEND_REQUEST = 4
} WDI_SAE_INDICATION_TYPE;