typedef enum _WDI_CIPHER_KEY_TYPE {
  WDI_CIPHER_KEY_TYPE_NONE = 0,
  WDI_CIPHER_KEY_TYPE_PAIRWISE_KEY = 1,
  WDI_CIPHER_KEY_TYPE_GROUP_KEY = 2,
  WDI_CIPHER_KEY_TYPE_IGTK = 3,
  WDI_CIPHER_KEY_TYPE_BIGTK = 3
} WDI_CIPHER_KEY_TYPE;