typedef enum _WDI_SCAN_TRIGGER {
  WDI_SCAN_TRIGGER_MANUAL = 1,
  WDI_SCAN_TRIGGER_BACKGROUND = 2,
  WDI_SCAN_TRIGGER_ROAM = 3,
  WDI_SCAN_TRIGGER_CONNECT = 4,
  WDI_SCAN_TRIGGER_ANQP_QUERY = 5,
  WDI_SCAN_TRIGGER_FAST_ROAM = 6,
  WDI_SCAN_TRIGGER_FTM = 7,
  WDI_SCAN_TRIGGER_BEACON_REQUEST = 8
} WDI_SCAN_TRIGGER;