typedef enum _WDI_CONNECTION_QUALITY_HINT {
  WDI_CONNECTION_QUALITY_AUTO_POWER_SAVE = 1,
  WDI_CONNECTION_QUALITY_LOW_LATENCY = 2,
  WDI_CONNECTION_QUALITY_HIGH_THROUGHPUT = 3,
  WDI_CONNECTION_QUALITY_NO_POWER_SAVE = 4
} WDI_CONNECTION_QUALITY_HINT;