typedef enum _WDI_ACTION_FRAME_CATEGORY {
  WDI_ACTION_FRAME_CATEGORY_SPECTRUM_MANAGEMENT = 0,
  WDI_ACTION_FRAME_CATEGORY_QOS = 1,
  WDI_ACTION_FRAME_CATEGORY_RESERVED = 2,
  WDI_ACTION_FRAME_CATEGORY_BLOCK_ACK = 3,
  WDI_ACTION_FRAME_CATEGORY_PUBLIC = 4,
  WDI_ACTION_FRAME_CATEGORY_RADIO_MEASUREMENT = 5,
  WDI_ACTION_FRAME_CATEGORY_FAST_BSS_TRANSITION = 6,
  WDI_ACTION_FRAME_CATEGORY_HT = 7,
  WDI_ACTION_FRAME_CATEGORY_SA_QUERY = 8,
  WDI_ACTION_FRAME_CATEGORY_PROTECTED_DUAL_OF_PUBLIC_ACTION = 9,
  WDI_ACTION_FRAME_CATEGORY_WNM = 10,
  WDI_ACTION_FRAME_CATEGORY_UNPROTECTED_WNM = 11,
  WDI_ACTION_FRAME_CATEGORY_ROBUST_AV_STREAMING = 19
} WDI_ACTION_FRAME_CATEGORY;