typedef enum _WDI_FTM_BANDWIDTH {
  WDI_FTM_BANDWIDTH_5 = 1,
  WDI_FTM_BANDWIDTH_10 = 2,
  WDI_FTM_BANDWIDTH_20 = 3,
  WDI_FTM_BANDWIDTH_40 = 4,
  WDI_FTM_BANDWIDTH_80 = 5,
  WDI_FTM_BANDWIDTH_80_80 = 6,
  WDI_FTM_BANDWIDTH_160 = 7,
  WDI_FTM_BANDWIDTH_2160 = 8
} WDI_FTM_BANDWIDTH;