typedef enum _WDI_STOP_AP_REASON {
  WDI_STOP_AP_REASON_FREQUENCY_NOT_AVAILABLE = 0x0001,
  WDI_STOP_AP_REASON_CHANNEL_NOT_AVAILABLE = 0x0002,
  WDI_STOP_AP_REASON_AP_ACTIVE = 0x0003,
  WDI_STOP_AP_REASON_IHV_START = 0xFF000000,
  WDI_STOP_AP_REASON_IHV_END = 0xFFFFFFFF
} WDI_STOP_AP_REASON;