typedef enum _WDI_P2P_SERVICE_DISCOVERY_TYPE {
  WDI_P2P_SERVICE_DISCOVERY_TYPE_NO_SERVICE_DISCOVERY = 1,
  WDI_P2P_SERVICE_DISCOVERY_TYPE_SERVICE_NAME_ONLY = 2,
  WDI_P2P_SERVICE_DISCOVERY_TYPE_SERVICE_INFORMATION = 3,
  WDI_P2P_SERVICE_DISCOVERY_TYPE_MAX_VALUE = 0xFFFFFFFF
} WDI_P2P_SERVICE_DISCOVERY_TYPE;