typedef enum _WDI_WNM_ACTION {
  WDI_WNM_ACTION_EVENT_REQUEST = 0,
  WDI_WNM_ACTION_EVENT_RESPONSE = 1,
  WDI_WNM_ACTION_DIAGNOSTIC_REQUEST = 2,
  WDI_WNM_ACTION_DIAGNOSTIC_RESPONSE = 3,
  WDI_WNM_ACTION_LOCATION_CONFIGURATION_REQUEST = 4,
  WDI_WNM_ACTION_LOCATION_CONFIGURATION_RESPONSE = 5,
  WDI_WNM_ACTION_BSS_TRANSITION_MANAGEMENT_QUERY = 6,
  WDI_WNM_ACTION_BSS_TRANSITION_MANAGEMENT_REQUEST = 7,
  WDI_WNM_ACTION_BSS_TRANSITION_MANAGEMENT_RESPONSE = 8
} WDI_WNM_ACTION;