typedef enum _WDI_P2P_ACTION_FRAME_TYPE {
  WDI_P2P_ACTION_FRAME_GO_NEGOTIATION_REQUEST = 1,
  WDI_P2P_ACTION_FRAME_GO_NEGOTIATION_RESPONSE = 2,
  WDI_P2P_ACTION_FRAME_GO_NEGOTIATION_CONFIRM = 3,
  WDI_P2P_ACTION_FRAME_INVITATION_REQUEST = 4,
  WDI_P2P_ACTION_FRAME_INVITATION_RESPONSE = 5,
  WDI_P2P_ACTION_FRAME_PROVISION_DISCOVERY_REQUEST = 6,
  WDI_P2P_ACTION_FRAME_PROVISION_DISCOVERY_RESPONSE = 7,
  WDI_P2P_ACTION_FRAME_MAX_VALUE = 0xFFFFFFFF
} WDI_P2P_ACTION_FRAME_TYPE;