typedef enum _WDI_P2P_GO_INTERNAL_RESET_POLICY {
  WDI_P2P_GO_INTERNAL_RESET_POLICY_USE_LAST_CHANNEL = 1,
  WDI_P2P_GO_INTERNAL_RESET_POLICY_ALLOW_CHANNEL_OPTIMIZATION = 2,
  WDI_P2P_GO_INTERNAL_RESET_POLICY_MAX = 0xFFFFFFFF
} WDI_P2P_GO_INTERNAL_RESET_POLICY;