typedef enum _WDI_P2P_LISTEN_STATE {
  WDI_P2P_LISTEN_STATE_OFF = 0,
  WDI_P2P_LISTEN_STATE_PASSIVE_AVAILABILITY = 8,
  WDI_P2P_LISTEN_STATE_AUTOMATIC_AVAILABILITY = 16,
  WDI_P2P_LISTEN_STATE_HIGH_AVAILABILITY = 24,
  WDI_P2P_LISTEN_STATE_DUMMY_MAX_VALUE = 0xFFFFFFFF
} WDI_P2P_LISTEN_STATE;