typedef enum _WDI_FTM_RESPONSE_STATUS {
  WDI_FTM_RESPONSE_STATUS_SUCCESS = 0,
  WDI_FTM_RESPONSE_STATUS_UNREACHABLE = 1,
  WDI_FTM_RESPONSE_STATUS_REJECTED = 2,
  WDI_FTM_RESPONSE_STATUS_INCAPABLE = 3,
  WDI_FTM_RESPONSE_STATUS_TIMEOUT = 4,
  WDI_FTM_RESPONSE_STATUS_NOT_ATTEMPTED = 5,
  WDI_FTM_RESPONSE_STATUS_ABORTED = 6,
  WDI_FTM_RESPONSE_STATUS_FAILED = 7
} WDI_FTM_RESPONSE_STATUS;