typedef enum _WDI_SAE_REQUEST_TYPE {
  WDI_SAE_REQUEST_TYPE_COMMIT_PARAMS = 0,
  WDI_SAE_REQUEST_TYPE_CONFIRM_PARAMS = 1,
  WDI_SAE_REQUEST_TYPE_FAILURE = 2,
  WDI_SAE_REQUEST_TYPE_SUCCESS = 3,
  WDI_SAE_REQUEST_TYPE_COMMIT_H2E_PARAMS = 4
} WDI_SAE_REQUEST_TYPE;