typedef enum _WDI_RADIO_MEASUREMENT_ACTION {
  WDI_RADIO_MEASUREMENT_ACTION_RADIO_MEASUREMENT_REQUEST = 0,
  WDI_RADIO_MEASUREMENT_ACTION_RADIO_MEASUREMENT_REPORT = 1,
  WDI_RADIO_MEASUREMENT_ACTION_LINK_MEASUREMENT_REQUEST = 2,
  WDI_RADIO_MEASUREMENT_ACTION_LINK_MEASUREMENT_RESPONSE = 3,
  WDI_RADIO_MEASUREMENT_ACTION_NEIGHBOR_REPORT_REQUEST = 4,
  WDI_RADIO_MEASUREMENT_ACTION_NEIGHBOR_REPORT_RESPONSE = 5
} WDI_RADIO_MEASUREMENT_ACTION;