typedef enum _WDI_AUTH_ALGORITHM {
  WDI_AUTH_ALGO_UNKNOWN = 0,
  WDI_AUTH_ALGO_80211_OPEN = 1,
  WDI_AUTH_ALGO_80211_SHARED_KEY = 2,
  WDI_AUTH_ALGO_WPA = 3,
  WDI_AUTH_ALGO_WPA_PSK = 4,
  WDI_AUTH_ALGO_WPA_NONE = 5,
  WDI_AUTH_ALGO_RSNA = 6,
  WDI_AUTH_ALGO_RSNA_PSK = 7,
  WDI_AUTH_ALGO_WPA3_ENT_192 = 8,
  WDI_AUTH_ALGO_WPA3_SAE = 9,
  WDI_AUTH_ALGO_OWE = 10,
  WDI_AUTH_ALGO_WPA3_ENT = 11,
  WDI_AUTH_ALGO_IHV_START = 0x80000000,
  WDI_AUTH_ALGO_IHV_END = 0xffffffff
} WDI_AUTH_ALGORITHM;