typedef enum _WDI_WPS_CONFIGURATION_METHOD {
  WDI_WPS_CONFIGURATION_METHOD_NULL = 0,
  WDI_WPS_CONFIGURATION_METHOD_DISPLAY = 0x0008,
  WDI_WPS_CONFIGURATION_METHOD_NFC_TAG = 0x0020,
  WDI_WPS_CONFIGURATION_METHOD_NFC_INTERFACE = 0x0040,
  WDI_WPS_CONFIGURATION_METHOD_PUSHBUTTON = 0x0080,
  WDI_WPS_CONFIGURATION_METHOD_KEYPAD = 0x0100,
  WDI_WPS_CONFIGURATION_METHOD_WFDS_DEFAULT = 0x1000,
  WDI_WPS_CONFIGURATION_METHOD_DUMMY_MAX_VALUE = 0xFFFF
} WDI_WPS_CONFIGURATION_METHOD;