typedef enum _WDI_BLUETOOTH_COEXISTENCE_SUPPORT {
  WDI_BLUETOOTH_COEXISTENCE_UNKNOWN = 0,
  WDI_BLUETOOTH_COEXISTENCE_PERFORMANCE_MAINTAINED = 1,
  WDI_BLUETOOTH_COEXISTENCE_WIFI_DEGRADED_TO_1x1 = 2,
  WDI_BLUETOOTH_COEXISTENCE_WIFI_THROUGHPUT_DEGRADED = 3,
  WDI_BLUETOOTH_COEXISTENCE_MUTUALLY_EXCLUSIVE = 4,
  WDI_BLUETOOTH_COEXISTENCE_MAX = 5
} WDI_BLUETOOTH_COEXISTENCE_SUPPORT;