typedef enum _WDI_LCI_REPORT_STATUS {
  WDI_LCI_REPORT_STATUS_SUCCESS = 0,
  WDI_LCI_REPORT_STATUS_FAILURE = 1,
  WDI_LCI_REPORT_STATUS_INCAPABLE = 2,
  WDI_LCI_REPORT_STATUS_REFUSED = 3
} WDI_LCI_REPORT_STATUS;