typedef enum _WDI_POWER_SAVE_LEVEL {
  WDI_POWER_SAVE_LEVEL_NO_POWER_SAVE = 0,
  WDI_POWER_SAVE_LEVEL_FAST_PSP = 8,
  WDI_POWER_SAVE_LEVEL_MAX_PSP = 16,
  WDI_POWER_SAVE_LEVEL_MAXIMUM_LEVEL = 24
} WDI_POWER_SAVE_LEVEL;