typedef enum D2D1_CHROMAKEY_PROP {
  D2D1_CHROMAKEY_PROP_COLOR = 0,
  D2D1_CHROMAKEY_PROP_TOLERANCE = 1,
  D2D1_CHROMAKEY_PROP_INVERT_ALPHA = 2,
  D2D1_CHROMAKEY_PROP_FEATHER = 3,
  D2D1_CHROMAKEY_PROP_FORCE_DWORD = 0xffffffff
} ;