typedef enum D2D1_HIGHLIGHTSANDSHADOWS_PROP {
  D2D1_HIGHLIGHTSANDSHADOWS_PROP_HIGHLIGHTS = 0,
  D2D1_HIGHLIGHTSANDSHADOWS_PROP_SHADOWS = 1,
  D2D1_HIGHLIGHTSANDSHADOWS_PROP_CLARITY = 2,
  D2D1_HIGHLIGHTSANDSHADOWS_PROP_INPUT_GAMMA = 3,
  D2D1_HIGHLIGHTSANDSHADOWS_PROP_MASK_BLUR_RADIUS = 4,
  D2D1_HIGHLIGHTSANDSHADOWS_PROP_FORCE_DWORD = 0xffffffff
} ;