typedef enum D2D1_HIGHLIGHTSANDSHADOWS_INPUT_GAMMA {
  D2D1_HIGHLIGHTSANDSHADOWS_INPUT_GAMMA_LINEAR = 0,
  D2D1_HIGHLIGHTSANDSHADOWS_INPUT_GAMMA_SRGB = 1,
  D2D1_HIGHLIGHTSANDSHADOWS_INPUT_GAMMA_FORCE_DWORD = 0xffffffff
} ;