typedef enum D2D1_POSTERIZE_PROP {
  D2D1_POSTERIZE_PROP_RED_VALUE_COUNT = 0,
  D2D1_POSTERIZE_PROP_GREEN_VALUE_COUNT = 1,
  D2D1_POSTERIZE_PROP_BLUE_VALUE_COUNT = 2,
  D2D1_POSTERIZE_PROP_FORCE_DWORD = 0xffffffff
} ;