typedef enum D2D1_HDRTONEMAP_PROP {
  D2D1_HDRTONEMAP_PROP_INPUT_MAX_LUMINANCE,
  D2D1_HDRTONEMAP_PROP_OUTPUT_MAX_LUMINANCE,
  D2D1_HDRTONEMAP_PROP_DISPLAY_MODE,
  D2D1_HDRTONEMAP_PROP_FORCE_DWORD
} ;