typedef enum D2D1_PATCH_EDGE_MODE {
  D2D1_PATCH_EDGE_MODE_ALIASED = 0,
  D2D1_PATCH_EDGE_MODE_ANTIALIASED = 1,
  D2D1_PATCH_EDGE_MODE_ALIASED_INFLATED = 2,
  D2D1_PATCH_EDGE_MODE_FORCE_DWORD = 0xffffffff
} ;