typedef enum D2D1_TRANSFORMED_IMAGE_SOURCE_OPTIONS {
  D2D1_TRANSFORMED_IMAGE_SOURCE_OPTIONS_NONE = 0,
  D2D1_TRANSFORMED_IMAGE_SOURCE_OPTIONS_DISABLE_DPI_SCALE = 1,
  D2D1_TRANSFORMED_IMAGE_SOURCE_OPTIONS_FORCE_DWORD = 0xffffffff
} ;