typedef enum D2D1_IMAGE_SOURCE_LOADING_OPTIONS {
  D2D1_IMAGE_SOURCE_LOADING_OPTIONS_NONE = 0,
  D2D1_IMAGE_SOURCE_LOADING_OPTIONS_RELEASE_SOURCE = 1,
  D2D1_IMAGE_SOURCE_LOADING_OPTIONS_CACHE_ON_DEMAND = 2,
  D2D1_IMAGE_SOURCE_LOADING_OPTIONS_FORCE_DWORD = 0xffffffff
} ;