typedef enum D2D1_IMAGE_SOURCE_FROM_DXGI_OPTIONS {
  D2D1_IMAGE_SOURCE_FROM_DXGI_OPTIONS_NONE = 0,
  D2D1_IMAGE_SOURCE_FROM_DXGI_OPTIONS_LOW_QUALITY_PRIMARY_CONVERSION = 1,
  D2D1_IMAGE_SOURCE_FROM_DXGI_OPTIONS_FORCE_DWORD = 0xffffffff
} ;