typedef struct _BTH_SDP_SERVICE_SEARCH_REQUEST {
  HANDLE_SDP_TYPE HANDLE_SDP_FIELD_NAME;
  SdpQueryUuid    uuids[MAX_UUIDS_IN_QUERY];
} BTH_SDP_SERVICE_SEARCH_REQUEST, *PBTH_SDP_SERVICE_SEARCH_REQUEST;