typedef struct _BTH_SDP_SERVICE_ATTRIBUTE_SEARCH_REQUEST {
  HANDLE_SDP_TYPE   HANDLE_SDP_FIELD_NAME;
  ULONG             searchFlags;
  SdpQueryUuid      uuids[MAX_UUIDS_IN_QUERY];
  SdpAttributeRange range[1];
} BTH_SDP_SERVICE_ATTRIBUTE_SEARCH_REQUEST, *PBTH_SDP_SERVICE_ATTRIBUTE_SEARCH_REQUEST;