typedef enum _XHR_CERT_ERROR_FLAG {
  XHR_CERT_ERROR_REVOCATION_FAILED = 0x800000UL,
  XHR_CERT_ERROR_UNKNOWN_CA,
  XHR_CERT_ERROR_CERT_CN_INVALID,
  XHR_CERT_ERROR_CERT_DATE_INVALID,
  XHR_CERT_ERROR_ALL_SERVER_ERRORS
} XHR_CERT_ERROR_FLAG;