typedef enum _XHR_PROPERTY {
  XHR_PROP_NO_CRED_PROMPT = 0,
  XHR_PROP_NO_AUTH = 0x1,
  XHR_PROP_TIMEOUT = 0x2,
  XHR_PROP_NO_DEFAULT_HEADERS = 0x3,
  XHR_PROP_REPORT_REDIRECT_STATUS = 0x4,
  XHR_PROP_NO_CACHE = 0x5,
  XHR_PROP_EXTENDED_ERROR = 0x6,
  XHR_PROP_QUERY_STRING_UTF8 = 0x7,
  XHR_PROP_IGNORE_CERT_ERRORS = 0x8,
  XHR_PROP_ONDATA_THRESHOLD = 0x9,
  XHR_PROP_SET_ENTERPRISEID = 0xa,
  XHR_PROP_MAX_CONNECTIONS = 0xb
} XHR_PROPERTY;