typedef enum _XHR_CERT_IGNORE_FLAG {
  XHR_CERT_IGNORE_REVOCATION_FAILED = 0x80UL,
  XHR_CERT_IGNORE_UNKNOWN_CA = 0x100UL,
  XHR_CERT_IGNORE_CERT_CN_INVALID = 0x1000UL,
  XHR_CERT_IGNORE_CERT_DATE_INVALID = 0x2000UL,
  XHR_CERT_IGNORE_ALL_SERVER_ERRORS
} XHR_CERT_IGNORE_FLAG;