typedef enum _XHR_COOKIE_STATE {
  XHR_COOKIE_STATE_UNKNOWN = 0,
  XHR_COOKIE_STATE_ACCEPT = 0x1,
  XHR_COOKIE_STATE_PROMPT = 0x2,
  XHR_COOKIE_STATE_LEASH = 0x3,
  XHR_COOKIE_STATE_DOWNGRADE = 0x4,
  XHR_COOKIE_STATE_REJECT = 0x5
} XHR_COOKIE_STATE;