typedef enum D3D12_SHADER_CACHE_KIND_FLAGS {
  D3D12_SHADER_CACHE_KIND_FLAG_IMPLICIT_D3D_CACHE_FOR_DRIVER = 0x1,
  D3D12_SHADER_CACHE_KIND_FLAG_IMPLICIT_D3D_CONVERSIONS = 0x2,
  D3D12_SHADER_CACHE_KIND_FLAG_IMPLICIT_DRIVER_MANAGED = 0x4,
  D3D12_SHADER_CACHE_KIND_FLAG_APPLICATION_MANAGED = 0x8
} ;