typedef enum D3D12_PROGRAMMABLE_SAMPLE_POSITIONS_TIER {
  D3D12_PROGRAMMABLE_SAMPLE_POSITIONS_TIER_NOT_SUPPORTED = 0,
  D3D12_PROGRAMMABLE_SAMPLE_POSITIONS_TIER_1 = 1,
  D3D12_PROGRAMMABLE_SAMPLE_POSITIONS_TIER_2 = 2
} ;