typedef enum D3D12_ROOT_PARAMETER_TYPE {
  D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE = 0,
  D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS,
  D3D12_ROOT_PARAMETER_TYPE_CBV,
  D3D12_ROOT_PARAMETER_TYPE_SRV,
  D3D12_ROOT_PARAMETER_TYPE_UAV
} ;