typedef enum D3D12_COMMAND_LIST_SUPPORT_FLAGS {
  D3D12_COMMAND_LIST_SUPPORT_FLAG_NONE = 0,
  D3D12_COMMAND_LIST_SUPPORT_FLAG_DIRECT,
  D3D12_COMMAND_LIST_SUPPORT_FLAG_BUNDLE,
  D3D12_COMMAND_LIST_SUPPORT_FLAG_COMPUTE,
  D3D12_COMMAND_LIST_SUPPORT_FLAG_COPY,
  D3D12_COMMAND_LIST_SUPPORT_FLAG_VIDEO_DECODE,
  D3D12_COMMAND_LIST_SUPPORT_FLAG_VIDEO_PROCESS,
  D3D12_COMMAND_LIST_SUPPORT_FLAG_VIDEO_ENCODE
} ;