typedef enum D3D12_META_COMMAND_PARAMETER_STAGE {
  D3D12_META_COMMAND_PARAMETER_STAGE_CREATION = 0,
  D3D12_META_COMMAND_PARAMETER_STAGE_INITIALIZATION = 1,
  D3D12_META_COMMAND_PARAMETER_STAGE_EXECUTION = 2
} ;