typedef enum D3D12_PIPELINE_STATE_FLAGS {
  D3D12_PIPELINE_STATE_FLAG_NONE = 0,
  D3D12_PIPELINE_STATE_FLAG_TOOL_DEBUG = 0x1,
  D3D12_PIPELINE_STATE_FLAG_DYNAMIC_DEPTH_BIAS,
  D3D12_PIPELINE_STATE_FLAG_DYNAMIC_INDEX_BUFFER_STRIP_CUT
} ;