typedef enum D3D12_SHADING_RATE_COMBINER {
  D3D12_SHADING_RATE_COMBINER_PASSTHROUGH = 0,
  D3D12_SHADING_RATE_COMBINER_OVERRIDE = 1,
  D3D12_SHADING_RATE_COMBINER_MIN = 2,
  D3D12_SHADING_RATE_COMBINER_MAX = 3,
  D3D12_SHADING_RATE_COMBINER_SUM = 4
} ;