typedef enum D3D12_STATIC_BORDER_COLOR {
  D3D12_STATIC_BORDER_COLOR_TRANSPARENT_BLACK = 0,
  D3D12_STATIC_BORDER_COLOR_OPAQUE_BLACK,
  D3D12_STATIC_BORDER_COLOR_OPAQUE_WHITE,
  D3D12_STATIC_BORDER_COLOR_OPAQUE_BLACK_UINT,
  D3D12_STATIC_BORDER_COLOR_OPAQUE_WHITE_UINT
} ;