typedef enum D3D12_RENDER_PASS_FLAGS {
  D3D12_RENDER_PASS_FLAG_NONE = 0,
  D3D12_RENDER_PASS_FLAG_ALLOW_UAV_WRITES = 0x1,
  D3D12_RENDER_PASS_FLAG_SUSPENDING_PASS = 0x2,
  D3D12_RENDER_PASS_FLAG_RESUMING_PASS = 0x4,
  D3D12_RENDER_PASS_FLAG_BIND_READ_ONLY_DEPTH,
  D3D12_RENDER_PASS_FLAG_BIND_READ_ONLY_STENCIL
} ;