typedef enum D3D12_DRIVER_MATCHING_IDENTIFIER_STATUS {
  D3D12_DRIVER_MATCHING_IDENTIFIER_COMPATIBLE_WITH_DEVICE = 0,
  D3D12_DRIVER_MATCHING_IDENTIFIER_UNSUPPORTED_TYPE = 0x1,
  D3D12_DRIVER_MATCHING_IDENTIFIER_UNRECOGNIZED = 0x2,
  D3D12_DRIVER_MATCHING_IDENTIFIER_INCOMPATIBLE_VERSION = 0x3,
  D3D12_DRIVER_MATCHING_IDENTIFIER_INCOMPATIBLE_TYPE = 0x4
} ;