typedef enum D3D12_MEASUREMENTS_ACTION {
  D3D12_MEASUREMENTS_ACTION_KEEP_ALL = 0,
  D3D12_MEASUREMENTS_ACTION_COMMIT_RESULTS,
  D3D12_MEASUREMENTS_ACTION_COMMIT_RESULTS_HIGH_PRIORITY,
  D3D12_MEASUREMENTS_ACTION_DISCARD_PREVIOUS
} ;