typedef struct D3D12_RENDER_PASS_DEPTH_STENCIL_DESC {
  D3D12_CPU_DESCRIPTOR_HANDLE        cpuDescriptor;
  D3D12_RENDER_PASS_BEGINNING_ACCESS DepthBeginningAccess;
  D3D12_RENDER_PASS_BEGINNING_ACCESS StencilBeginningAccess;
  D3D12_RENDER_PASS_ENDING_ACCESS    DepthEndingAccess;
  D3D12_RENDER_PASS_ENDING_ACCESS    StencilEndingAccess;
} D3D12_RENDER_PASS_DEPTH_STENCIL_DESC;