typedef struct D3D12_GLOBAL_BARRIER {
  D3D12_BARRIER_SYNC   SyncBefore;
  D3D12_BARRIER_SYNC   SyncAfter;
  D3D12_BARRIER_ACCESS AccessBefore;
  D3D12_BARRIER_ACCESS AccessAfter;
} D3D12_GLOBAL_BARRIER;