typedef struct D3D12_VERSIONED_DEVICE_REMOVED_EXTENDED_DATA {
  D3D12_DRED_VERSION Version;
  union {
    D3D12_DEVICE_REMOVED_EXTENDED_DATA  Dred_1_0;
    D3D12_DEVICE_REMOVED_EXTENDED_DATA1 Dred_1_1;
    D3D12_DEVICE_REMOVED_EXTENDED_DATA2 Dred_1_2;
    D3D12_DEVICE_REMOVED_EXTENDED_DATA3 Dred_1_3;
  };
} D3D12_VERSIONED_DEVICE_REMOVED_EXTENDED_DATA;