typedef struct D3D12_RENDER_PASS_BEGINNING_ACCESS {
  D3D12_RENDER_PASS_BEGINNING_ACCESS_TYPE Type;
  union {
    D3D12_RENDER_PASS_BEGINNING_ACCESS_CLEAR_PARAMETERS          Clear;
    D3D12_RENDER_PASS_BEGINNING_ACCESS_PRESERVE_LOCAL_PARAMETERS PreserveLocal;
  };
} D3D12_RENDER_PASS_BEGINNING_ACCESS;