typedef struct D3D12_RENDER_PASS_ENDING_ACCESS {
  D3D12_RENDER_PASS_ENDING_ACCESS_TYPE Type;
  union {
    D3D12_RENDER_PASS_ENDING_ACCESS_RESOLVE_PARAMETERS        Resolve;
    D3D12_RENDER_PASS_ENDING_ACCESS_PRESERVE_LOCAL_PARAMETERS PreserveLocal;
  };
} D3D12_RENDER_PASS_ENDING_ACCESS;