typedef struct D3D12_RENDER_PASS_RENDER_TARGET_DESC {
  D3D12_CPU_DESCRIPTOR_HANDLE        cpuDescriptor;
  D3D12_RENDER_PASS_BEGINNING_ACCESS BeginningAccess;
  D3D12_RENDER_PASS_ENDING_ACCESS    EndingAccess;
} D3D12_RENDER_PASS_RENDER_TARGET_DESC;