typedef struct D3D12_VERSIONED_ROOT_SIGNATURE_DESC {
  D3D_ROOT_SIGNATURE_VERSION Version;
  union {
    D3D12_ROOT_SIGNATURE_DESC  Desc_1_0;
    D3D12_ROOT_SIGNATURE_DESC1 Desc_1_1;
    D3D12_ROOT_SIGNATURE_DESC2 Desc_1_2;
  };
} D3D12_VERSIONED_ROOT_SIGNATURE_DESC;