typedef enum GROUPPROP {
  GROUPPROP_PRIORITY = 0,
  GROUPPROP_REMOTEUSERID = 1,
  GROUPPROP_REMOTEUSERPWD = 2,
  GROUPPROP_LOCALUSERID = 3,
  GROUPPROP_LOCALUSERPWD = 4,
  GROUPPROP_PROTOCOLFLAGS = 5,
  GROUPPROP_NOTIFYFLAGS = 6,
  GROUPPROP_NOTIFYCLSID = 7,
  GROUPPROP_PROGRESSSIZE = 8,
  GROUPPROP_PROGRESSPERCENT = 9,
  GROUPPROP_PROGRESSTIME = 10,
  GROUPPROP_DISPLAYNAME = 11,
  GROUPPROP_DESCRIPTION = 12
} ;