typedef enum CLUSPROP_PIFLAGS {
  CLUSPROP_PIFLAG_STICKY = 0x1,
  CLUSPROP_PIFLAG_REMOVABLE = 0x2,
  CLUSPROP_PIFLAG_USABLE = 0x4,
  CLUSPROP_PIFLAG_DEFAULT_QUORUM = 0x8,
  CLUSPROP_PIFLAG_USABLE_FOR_CSV = 0x10,
  CLUSPROP_PIFLAG_ENCRYPTION_ENABLED = 0x20,
  CLUSPROP_PIFLAG_RAW,
  CLUSPROP_PIFLAG_UNKNOWN = 0x80000000
} ;