typedef enum CLUSTER_CHANGE_NETWORK_V2 {
  CLUSTER_CHANGE_NETWORK_DELETED_V2 = 0x1,
  CLUSTER_CHANGE_NETWORK_COMMON_PROPERTY_V2 = 0x2,
  CLUSTER_CHANGE_NETWORK_PRIVATE_PROPERTY_V2 = 0x4,
  CLUSTER_CHANGE_NETWORK_STATE_V2 = 0x8,
  CLUSTER_CHANGE_NETWORK_HANDLE_CLOSE_V2 = 0x10,
  CLUSTER_CHANGE_NETWORK_ALL_V2
} ;