typedef enum __MIDL___MIDL_itf_msclus_0000_0000_0002 {
  CLUSTER_MGMT_POINT_TYPE_NONE = 0,
  CLUSTER_MGMT_POINT_TYPE_CNO,
  CLUSTER_MGMT_POINT_TYPE_DNS_ONLY,
  CLUSTER_MGMT_POINT_TYPE_CNO_ONLY
} CLUSTER_MGMT_POINT_TYPE;