typedef enum CLUSTER_CONTROL_OBJECT {
  CLUS_OBJECT_INVALID = 0,
  CLUS_OBJECT_RESOURCE,
  CLUS_OBJECT_RESOURCE_TYPE,
  CLUS_OBJECT_GROUP,
  CLUS_OBJECT_NODE,
  CLUS_OBJECT_NETWORK,
  CLUS_OBJECT_NETINTERFACE,
  CLUS_OBJECT_CLUSTER,
  CLUS_OBJECT_GROUPSET,
  CLUS_OBJECT_AFFINITYRULE,
  CLUS_OBJECT_USER = 128
} ;