typedef enum CLUSTER_OBJECT_TYPE {
  CLUSTER_OBJECT_TYPE_NONE = 0,
  CLUSTER_OBJECT_TYPE_CLUSTER = 0x1,
  CLUSTER_OBJECT_TYPE_GROUP = 0x2,
  CLUSTER_OBJECT_TYPE_RESOURCE = 0x3,
  CLUSTER_OBJECT_TYPE_RESOURCE_TYPE = 0x4,
  CLUSTER_OBJECT_TYPE_NETWORK_INTERFACE = 0x5,
  CLUSTER_OBJECT_TYPE_NETWORK = 0x6,
  CLUSTER_OBJECT_TYPE_NODE = 0x7,
  CLUSTER_OBJECT_TYPE_REGISTRY = 0x8,
  CLUSTER_OBJECT_TYPE_QUORUM = 0x9,
  CLUSTER_OBJECT_TYPE_SHARED_VOLUME = 0xa,
  CLUSTER_OBJECT_TYPE_GROUPSET = 0xd,
  CLUSTER_OBJECT_TYPE_AFFINITYRULE,
  CLUSTER_OBJECT_TYPE_FAULTDOMAIN
} ;