typedef enum CLUSTER_CHANGE_NODE_V2 {
  CLUSTER_CHANGE_NODE_NETINTERFACE_ADDED_V2 = 0x1,
  CLUSTER_CHANGE_NODE_DELETED_V2 = 0x2,
  CLUSTER_CHANGE_NODE_COMMON_PROPERTY_V2 = 0x4,
  CLUSTER_CHANGE_NODE_PRIVATE_PROPERTY_V2 = 0x8,
  CLUSTER_CHANGE_NODE_STATE_V2 = 0x10,
  CLUSTER_CHANGE_NODE_GROUP_GAINED_V2 = 0x20,
  CLUSTER_CHANGE_NODE_GROUP_LOST_V2 = 0x40,
  CLUSTER_CHANGE_NODE_HANDLE_CLOSE_V2 = 0x80,
  CLUSTER_CHANGE_NODE_ALL_V2
} ;