typedef enum CLUSTER_CHANGE_SHARED_VOLUME_V2 {
  CLUSTER_CHANGE_SHARED_VOLUME_STATE_V2 = 0x1,
  CLUSTER_CHANGE_SHARED_VOLUME_ADDED_V2 = 0x2,
  CLUSTER_CHANGE_SHARED_VOLUME_REMOVED_V2 = 0x4,
  CLUSTER_CHANGE_SHARED_VOLUME_ALL_V2
} ;