typedef enum CLUSTER_CHANGE_CLUSTER_V2 {
  CLUSTER_CHANGE_CLUSTER_RECONNECT_V2 = 0x1,
  CLUSTER_CHANGE_CLUSTER_STATE_V2 = 0x2,
  CLUSTER_CHANGE_CLUSTER_GROUP_ADDED_V2 = 0x4,
  CLUSTER_CHANGE_CLUSTER_HANDLE_CLOSE_V2 = 0x8,
  CLUSTER_CHANGE_CLUSTER_NETWORK_ADDED_V2 = 0x10,
  CLUSTER_CHANGE_CLUSTER_NODE_ADDED_V2 = 0x20,
  CLUSTER_CHANGE_CLUSTER_RESOURCE_TYPE_ADDED_V2 = 0x40,
  CLUSTER_CHANGE_CLUSTER_COMMON_PROPERTY_V2 = 0x80,
  CLUSTER_CHANGE_CLUSTER_PRIVATE_PROPERTY_V2 = 0x100,
  CLUSTER_CHANGE_CLUSTER_LOST_NOTIFICATIONS_V2 = 0x200,
  CLUSTER_CHANGE_CLUSTER_RENAME_V2 = 0x400,
  CLUSTER_CHANGE_CLUSTER_MEMBERSHIP_V2 = 0x800,
  CLUSTER_CHANGE_CLUSTER_UPGRADED_V2 = 0x1000,
  CLUSTER_CHANGE_CLUSTER_ALL_V2
} ;