typedef enum CLUSTER_CHANGE_GROUP_V2 {
  CLUSTER_CHANGE_GROUP_DELETED_V2 = 0x1,
  CLUSTER_CHANGE_GROUP_COMMON_PROPERTY_V2 = 0x2,
  CLUSTER_CHANGE_GROUP_PRIVATE_PROPERTY_V2 = 0x4,
  CLUSTER_CHANGE_GROUP_STATE_V2 = 0x8,
  CLUSTER_CHANGE_GROUP_OWNER_NODE_V2 = 0x10,
  CLUSTER_CHANGE_GROUP_PREFERRED_OWNERS_V2 = 0x20,
  CLUSTER_CHANGE_GROUP_RESOURCE_ADDED_V2 = 0x40,
  CLUSTER_CHANGE_GROUP_RESOURCE_GAINED_V2 = 0x80,
  CLUSTER_CHANGE_GROUP_RESOURCE_LOST_V2 = 0x100,
  CLUSTER_CHANGE_GROUP_HANDLE_CLOSE_V2 = 0x200,
  CLUSTER_CHANGE_GROUP_ALL_V2
} ;