typedef enum CLUSTER_CHANGE_GROUPSET_V2 {
  CLUSTER_CHANGE_GROUPSET_DELETED_v2 = 0x1,
  CLUSTER_CHANGE_GROUPSET_COMMON_PROPERTY_V2 = 0x2,
  CLUSTER_CHANGE_GROUPSET_PRIVATE_PROPERTY_V2 = 0x4,
  CLUSTER_CHANGE_GROUPSET_STATE_V2 = 0x8,
  CLUSTER_CHANGE_GROUPSET_GROUP_ADDED = 0x10,
  CLUSTER_CHANGE_GROUPSET_GROUP_REMOVED = 0x20,
  CLUSTER_CHANGE_GROUPSET_DEPENDENCIES_V2 = 0x40,
  CLUSTER_CHANGE_GROUPSET_DEPENDENTS_V2 = 0x80,
  CLUSTER_CHANGE_GROUPSET_HANDLE_CLOSE_v2 = 0x100,
  CLUSTER_CHANGE_GROUPSET_ALL_V2
} ;