typedef enum CLUSTER_CHANGE_RESOURCE_V2 {
  CLUSTER_CHANGE_RESOURCE_COMMON_PROPERTY_V2 = 0x1,
  CLUSTER_CHANGE_RESOURCE_PRIVATE_PROPERTY_V2 = 0x2,
  CLUSTER_CHANGE_RESOURCE_STATE_V2 = 0x4,
  CLUSTER_CHANGE_RESOURCE_OWNER_GROUP_V2 = 0x8,
  CLUSTER_CHANGE_RESOURCE_DEPENDENCIES_V2 = 0x10,
  CLUSTER_CHANGE_RESOURCE_DEPENDENTS_V2 = 0x20,
  CLUSTER_CHANGE_RESOURCE_POSSIBLE_OWNERS_V2 = 0x40,
  CLUSTER_CHANGE_RESOURCE_DELETED_V2 = 0x80,
  CLUSTER_CHANGE_RESOURCE_DLL_UPGRADED_V2 = 0x100,
  CLUSTER_CHANGE_RESOURCE_HANDLE_CLOSE_V2 = 0x200,
  CLUSTER_CHANGE_RESOURCE_TERMINAL_STATE_V2 = 0x400,
  CLUSTER_CHANGE_RESOURCE_ALL_V2
} ;