typedef enum CLUSTER_CHANGE_NODE_UPGRADE_PHASE_V2 {
  CLUSTER_CHANGE_UPGRADE_NODE_PREPARE = 0x1,
  CLUSTER_CHANGE_UPGRADE_NODE_COMMIT = 0x2,
  CLUSTER_CHANGE_UPGRADE_NODE_POSTCOMMIT = 0x4,
  CLUSTER_CHANGE_UPGRADE_ALL
} ;