typedef enum CLUSTER_CHANGE_RESOURCE_TYPE_V2 {
  CLUSTER_CHANGE_RESOURCE_TYPE_DELETED_V2 = 0x1,
  CLUSTER_CHANGE_RESOURCE_TYPE_COMMON_PROPERTY_V2 = 0x2,
  CLUSTER_CHANGE_RESOURCE_TYPE_PRIVATE_PROPERTY_V2 = 0x4,
  CLUSTER_CHANGE_RESOURCE_TYPE_POSSIBLE_OWNERS_V2 = 0x8,
  CLUSTER_CHANGE_RESOURCE_TYPE_DLL_UPGRADED_V2 = 0x10,
  CLUSTER_RESOURCE_TYPE_SPECIFIC_V2 = 0x20,
  CLUSTER_CHANGE_RESOURCE_TYPE_ALL_V2
} ;