typedef enum CLUSCTL_NETWORK_CODES {
  CLUSCTL_NETWORK_UNKNOWN,
  CLUSCTL_NETWORK_GET_CHARACTERISTICS,
  CLUSCTL_NETWORK_GET_FLAGS,
  CLUSCTL_NETWORK_GET_NAME,
  CLUSCTL_NETWORK_GET_ID,
  CLUSCTL_NETWORK_ENUM_COMMON_PROPERTIES,
  CLUSCTL_NETWORK_GET_RO_COMMON_PROPERTIES,
  CLUSCTL_NETWORK_GET_COMMON_PROPERTIES,
  CLUSCTL_NETWORK_SET_COMMON_PROPERTIES,
  CLUSCTL_NETWORK_VALIDATE_COMMON_PROPERTIES,
  CLUSCTL_NETWORK_ENUM_PRIVATE_PROPERTIES,
  CLUSCTL_NETWORK_GET_RO_PRIVATE_PROPERTIES,
  CLUSCTL_NETWORK_GET_PRIVATE_PROPERTIES,
  CLUSCTL_NETWORK_SET_PRIVATE_PROPERTIES,
  CLUSCTL_NETWORK_VALIDATE_PRIVATE_PROPERTIES,
  CLUSCTL_NETWORK_GET_COMMON_PROPERTY_FMTS,
  CLUSCTL_NETWORK_GET_PRIVATE_PROPERTY_FMTS
} ;