typedef enum CLUSTER_CHANGE_NETINTERFACE_V2 {
  CLUSTER_CHANGE_NETINTERFACE_DELETED_V2 = 0x1,
  CLUSTER_CHANGE_NETINTERFACE_COMMON_PROPERTY_V2 = 0x2,
  CLUSTER_CHANGE_NETINTERFACE_PRIVATE_PROPERTY_V2 = 0x4,
  CLUSTER_CHANGE_NETINTERFACE_STATE_V2 = 0x8,
  CLUSTER_CHANGE_NETINTERFACE_HANDLE_CLOSE_V2 = 0x10,
  CLUSTER_CHANGE_NETINTERFACE_ALL_V2
} ;