typedef enum CLUSTER_CHANGE_REGISTRY_V2 {
  CLUSTER_CHANGE_REGISTRY_ATTRIBUTES_V2 = 0x1,
  CLUSTER_CHANGE_REGISTRY_NAME_V2 = 0x2,
  CLUSTER_CHANGE_REGISTRY_SUBTREE_V2 = 0x4,
  CLUSTER_CHANGE_REGISTRY_VALUE_V2 = 0x8,
  CLUSTER_CHANGE_REGISTRY_HANDLE_CLOSE_V2 = 0x10,
  CLUSTER_CHANGE_REGISTRY_ALL_V2
} ;