typedef enum CLUSTER_ENUM {
  CLUSTER_ENUM_NODE = 0x1,
  CLUSTER_ENUM_RESTYPE = 0x2,
  CLUSTER_ENUM_RESOURCE = 0x4,
  CLUSTER_ENUM_GROUP = 0x8,
  CLUSTER_ENUM_NETWORK = 0x10,
  CLUSTER_ENUM_NETINTERFACE = 0x20,
  CLUSTER_ENUM_CAPACITY_NODE,
  CLUSTER_ENUM_SHARED_VOLUME_GROUP = 0x20000000,
  CLUSTER_ENUM_SHARED_VOLUME_RESOURCE = 0x40000000,
  CLUSTER_ENUM_INTERNAL_NETWORK = 0x80000000,
  CLUSTER_ENUM_ALL
} ;