typedef enum _EC_SUBSCRIPTION_PROPERTY_ID {
  EcSubscriptionEnabled = 0,
  EcSubscriptionEventSources,
  EcSubscriptionEventSourceAddress,
  EcSubscriptionEventSourceEnabled,
  EcSubscriptionEventSourceUserName,
  EcSubscriptionEventSourcePassword,
  EcSubscriptionDescription,
  EcSubscriptionURI,
  EcSubscriptionConfigurationMode,
  EcSubscriptionExpires,
  EcSubscriptionQuery,
  EcSubscriptionTransportName,
  EcSubscriptionTransportPort,
  EcSubscriptionDeliveryMode,
  EcSubscriptionDeliveryMaxItems,
  EcSubscriptionDeliveryMaxLatencyTime,
  EcSubscriptionHeartbeatInterval,
  EcSubscriptionLocale,
  EcSubscriptionContentFormat,
  EcSubscriptionLogFile,
  EcSubscriptionPublisherName,
  EcSubscriptionCredentialsType,
  EcSubscriptionCommonUserName,
  EcSubscriptionCommonPassword,
  EcSubscriptionHostName,
  EcSubscriptionReadExistingEvents,
  EcSubscriptionDialect,
  EcSubscriptionType,
  EcSubscriptionAllowedIssuerCAs,
  EcSubscriptionAllowedSubjects,
  EcSubscriptionDeniedSubjects,
  EcSubscriptionAllowedSourceDomainComputers,
  EcSubscriptionPropertyIdEND
} EC_SUBSCRIPTION_PROPERTY_ID;