typedef enum {
  CPST_PERCEPTUAL,
  CPST_RELATIVE_COLORIMETRIC,
  CPST_SATURATION,
  CPST_ABSOLUTE_COLORIMETRIC,
  CPST_NONE,
  CPST_RGB_WORKING_SPACE,
  CPST_CUSTOM_WORKING_SPACE,
  CPST_STANDARD_DISPLAY_COLOR_MODE,
  CPST_EXTENDED_DISPLAY_COLOR_MODE
} COLORPROFILESUBTYPE;