typedef enum {
  COLOR_GRAY = 1,
  COLOR_RGB,
  COLOR_XYZ,
  COLOR_Yxy,
  COLOR_Lab,
  COLOR_3_CHANNEL,
  COLOR_CMYK,
  COLOR_5_CHANNEL,
  COLOR_6_CHANNEL,
  COLOR_7_CHANNEL,
  COLOR_8_CHANNEL,
  COLOR_NAMED
} COLORTYPE;