typedef struct tagENUMTYPEA {
  DWORD dwSize;
  DWORD dwVersion;
  DWORD dwFields;
  PCSTR pDeviceName;
  DWORD dwMediaType;
  DWORD dwDitheringMode;
  DWORD dwResolution[2];
  DWORD dwCMMType;
  DWORD dwClass;
  DWORD dwDataColorSpace;
  DWORD dwConnectionSpace;
  DWORD dwSignature;
  DWORD dwPlatform;
  DWORD dwProfileFlags;
  DWORD dwManufacturer;
  DWORD dwModel;
  DWORD dwAttributes[2];
  DWORD dwRenderingIntent;
  DWORD dwCreator;
  DWORD dwDeviceClass;
} ENUMTYPEA, *PENUMTYPEA, *LPENUMTYPEA;