typedef enum _DXGK_VGPU_CAPABILITY_TYPE {
  DXGK_VGPU_CAPABILITY_MEMORY,
  DXGK_VGPU_CAPABILITY_ENCODE,
  DXGK_VGPU_CAPABILITY_DECODE,
  DXGK_VGPU_CAPABILITY_COMPUTE,
  DXGK_VGPU_CAPABILITY_MAX
} DXGK_VGPU_CAPABILITY_TYPE;