typedef enum _DXGK_DIAG_MONITOR_STATE {
  DXGK_DIAG_MONITOR_STATE_UNINITIALIZED,
  DXGK_DIAG_MONITOR_READY,
  DXGK_DIAG_MONITOR_NOT_READY,
  DXGK_DIAG_MONITOR_READY_NOTAPPLICABLE
} DXGK_DIAG_MONITOR_STATE;