typedef struct _DXGKARG_SETTARGETADJUSTEDCOLORIMETRY2 {
  D3DDDI_VIDEO_PRESENT_TARGET_ID TargetId;
  DXGK_COLORIMETRY               AdjustedColorimetry;
  UINT                           SdrWhiteLevel;
} DXGKARG_SETTARGETADJUSTEDCOLORIMETRY2, *PDXGKARG_SETTARGETADJUSTEDCOLORIMETRY2;