typedef struct _DXGK_DIAG_SCANOUT_BUFFER_CONTENT {
  [out] DXGK_DIAG_DISPLAY_SCANOUT_BUFFER_CRC       ScanoutBufferCrc;
  [out] DXGK_DIAG_DISPLAY_SCANOUT_BUFFER_HISTOGRAM ScanoutBufferHistogram;
} DXGK_DIAG_SCANOUT_BUFFER_CONTENT;