typedef struct _DXGK_MIRACAST_DISPLAY_CALLBACKS {
  HANDLE                            MiracastHandle;
  DXGKCB_MIRACAST_SEND_MESSAGE      DxgkCbMiracastSendMessage;
  DXGKCB_MIRACAST_REPORT_CHUNK_INFO DxgkCbReportChunkInfo;
} DXGK_MIRACAST_DISPLAY_CALLBACKS, *PDXGK_MIRACAST_DISPLAY_CALLBACKS;