typedef struct _DXGKARG_WRITEVIRTUALFUNCTIONCONFIG {
  PVOID Data;
  ULONG VirtualFunctionIndex;
  ULONG Offset;
  ULONG Length;
} DXGKARG_WRITEVIRTUALFUNCTIONCONFIG, *PDXGKARG_WRITEVIRTUALFUNCTIONCONFIG;