typedef struct _DXGK_DIAG_DISPLAY_SAMPLED_GAMMA {
        float Red[MAX_NUM_OF_GAMMA_SAMPLES_FOR_DIAGNOSTICS];
        float Green[MAX_NUM_OF_GAMMA_SAMPLES_FOR_DIAGNOSTICS];
        float Blue[MAX_NUM_OF_GAMMA_SAMPLES_FOR_DIAGNOSTICS];
        float ColorMatrix[3][3];
} DXGK_DIAG_DISPLAY_SAMPLED_GAMMA;