typedef struct _DXGKARG_READVIRTUALFUNCTIONCONFIG {
  PVOID Data;
  ULONG VirtualFunctionIndex;
  ULONG Offset;
  ULONG Length;
} DXGKARG_READVIRTUALFUNCTIONCONFIG, *PDXGKARG_READVIRTUALFUNCTIONCONFIG;