typedef struct _DXGKARG_READVIRTUALFUNCTIONCONFIGBLOCK {
  PVOID Data;
  ULONG VirtualFunctionIndex;
  ULONG BlockId;
  ULONG Length;
} DXGKARG_READVIRTUALFUNCTIONCONFIGBLOCK, *PDXGKARG_READVIRTUALFUNCTIONCONFIGBLOCK;