typedef struct _DXGKARG_QUERYDIAGNOSTICTYPESSUPPORT {
  [in]  DXGK_DIAGNOSTIC_CATEGORIES DiagnosticCategory;
  [out] DXGK_DIAGNOSTIC_TYPES      NoninvasiveTypes;
  [out] DXGK_DIAGNOSTIC_TYPES      InvasiveTypes;
} DXGKARG_QUERYDIAGNOSTICTYPESSUPPORT, *PDXGKARG_QUERYDIAGNOSTICTYPESSUPPORT;