typedef struct _DXGKARG_WRITEVIRTUALFUNCTIONCONFIGBLOCK {
  PVOID Data;
  ULONG VirtualFunctionIndex;
  ULONG BlockId;
  ULONG Length;
} DXGKARG_WRITEVIRTUALFUNCTIONCONFIGBLOCK, *PDXGKARG_WRITEVIRTUALFUNCTIONCONFIGBLOCK;