typedef struct _DXGKARG_CONTROLDIAGNOSTICREPORTING {
  [in]  DXGK_DIAGNOSTIC_CATEGORIES DiagnosticCategory;
  [out] DXGK_DIAGNOSTIC_TYPES      RequestedDiagnostics;
} DXGKARG_CONTROLDIAGNOSTICREPORTING, *PDXGKARG_CONTROLDIAGNOSTICREPORTING;