typedef struct _DXGKARG_SETVIRTUALFUNCTIONPOWERSTATE {
  ULONG              VirtualFunctionIndex;
  DEVICE_POWER_STATE PowerState;
  BOOLEAN            Wake;
} DXGKARG_SETVIRTUALFUNCTIONPOWERSTATE, *PDXGKARG_SETVIRTUALFUNCTIONPOWERSTATE;