typedef struct _PKTMON_PACKET_HEADER_INFORMATION {
  SOCKADDR_INET              SockAddrLocal;
  SOCKADDR_INET              SockAddrRemote;
  UCHAR                      IpProtocol;
  union {
    struct {
      USHORT PortLocal;
      USHORT PortRemote;
    } Udp;
    struct {
      USHORT PortLocal;
      USHORT PortRemote;
      UCHAR  Flags;
    } Tcp;
    struct {
      UCHAR Type;
      UCHAR Code;
    } Icmp;
  } Transport;
  _PKTMON_TRANSPORT_PROTOCOL _PKTMON_TRANSPORT_PROTOCOL;
} PKTMON_PACKET_HEADER_INFORMATION;