typedef enum tagWPD_STORAGE_TYPE_VALUES {
  WPD_STORAGE_TYPE_UNDEFINED,
  WPD_STORAGE_TYPE_FIXED_ROM,
  WPD_STORAGE_TYPE_REMOVABLE_ROM,
  WPD_STORAGE_TYPE_FIXED_RAM,
  WPD_STORAGE_TYPE_REMOVABLE_RAM
} WPD_STORAGE_TYPE_VALUES;