typedef enum tagWPD_WHITE_BALANCE_SETTINGS {
  WPD_WHITE_BALANCE_UNDEFINED,
  WPD_WHITE_BALANCE_MANUAL,
  WPD_WHITE_BALANCE_AUTOMATIC,
  WPD_WHITE_BALANCE_ONE_PUSH_AUTOMATIC,
  WPD_WHITE_BALANCE_DAYLIGHT,
  WPD_WHITE_BALANCE_FLORESCENT,
  WPD_WHITE_BALANCE_TUNGSTEN,
  WPD_WHITE_BALANCE_FLASH
} WPD_WHITE_BALANCE_SETTINGS;