typedef enum tagWPD_DEVICE_TYPES {
  WPD_DEVICE_TYPE_GENERIC,
  WPD_DEVICE_TYPE_CAMERA,
  WPD_DEVICE_TYPE_MEDIA_PLAYER,
  WPD_DEVICE_TYPE_PHONE,
  WPD_DEVICE_TYPE_VIDEO,
  WPD_DEVICE_TYPE_PERSONAL_INFORMATION_MANAGER,
  WPD_DEVICE_TYPE_AUDIO_RECORDER
} WPD_DEVICE_TYPES;