typedef enum tagWPD_FLASH_MODES {
  WPD_FLASH_MODE_UNDEFINED,
  WPD_FLASH_MODE_AUTO,
  WPD_FLASH_MODE_OFF,
  WPD_FLASH_MODE_FILL,
  WPD_FLASH_MODE_RED_EYE_AUTO,
  WPD_FLASH_MODE_RED_EYE_FILL,
  WPD_FLASH_MODE_EXTERNAL_SYNC
} WPD_FLASH_MODES;