typedef enum tagWPD_EXPOSURE_PROGRAM_MODES {
  WPD_EXPOSURE_PROGRAM_MODE_UNDEFINED,
  WPD_EXPOSURE_PROGRAM_MODE_MANUAL,
  WPD_EXPOSURE_PROGRAM_MODE_AUTO,
  WPD_EXPOSURE_PROGRAM_MODE_APERTURE_PRIORITY,
  WPD_EXPOSURE_PROGRAM_MODE_SHUTTER_PRIORITY,
  WPD_EXPOSURE_PROGRAM_MODE_CREATIVE,
  WPD_EXPOSURE_PROGRAM_MODE_ACTION,
  WPD_EXPOSURE_PROGRAM_MODE_PORTRAIT
} WPD_EXPOSURE_PROGRAM_MODES;