typedef enum tagWPD_OPERATION_STATES {
  WPD_OPERATION_STATE_UNSPECIFIED,
  WPD_OPERATION_STATE_STARTED,
  WPD_OPERATION_STATE_RUNNING,
  WPD_OPERATION_STATE_PAUSED,
  WPD_OPERATION_STATE_CANCELLED,
  WPD_OPERATION_STATE_FINISHED,
  WPD_OPERATION_STATE_ABORTED
} WPD_OPERATION_STATES;