typedef enum DWRITE_BASELINE {
  DWRITE_BASELINE_DEFAULT,
  DWRITE_BASELINE_ROMAN,
  DWRITE_BASELINE_CENTRAL,
  DWRITE_BASELINE_MATH,
  DWRITE_BASELINE_HANGING,
  DWRITE_BASELINE_IDEOGRAPHIC_BOTTOM,
  DWRITE_BASELINE_IDEOGRAPHIC_TOP,
  DWRITE_BASELINE_MINIMUM,
  DWRITE_BASELINE_MAXIMUM
} ;