typedef enum DWRITE_PANOSE_ASPECT_RATIO {
  DWRITE_PANOSE_ASPECT_RATIO_ANY = 0,
  DWRITE_PANOSE_ASPECT_RATIO_NO_FIT = 1,
  DWRITE_PANOSE_ASPECT_RATIO_VERY_CONDENSED = 2,
  DWRITE_PANOSE_ASPECT_RATIO_CONDENSED = 3,
  DWRITE_PANOSE_ASPECT_RATIO_NORMAL = 4,
  DWRITE_PANOSE_ASPECT_RATIO_EXPANDED = 5,
  DWRITE_PANOSE_ASPECT_RATIO_VERY_EXPANDED = 6
} ;