typedef enum DWRITE_PANOSE_XASCENT {
  DWRITE_PANOSE_XASCENT_ANY = 0,
  DWRITE_PANOSE_XASCENT_NO_FIT = 1,
  DWRITE_PANOSE_XASCENT_VERY_LOW = 2,
  DWRITE_PANOSE_XASCENT_LOW = 3,
  DWRITE_PANOSE_XASCENT_MEDIUM = 4,
  DWRITE_PANOSE_XASCENT_HIGH = 5,
  DWRITE_PANOSE_XASCENT_VERY_HIGH = 6
} ;