typedef enum DWRITE_PANOSE_CHARACTER_RANGES {
  DWRITE_PANOSE_CHARACTER_RANGES_ANY = 0,
  DWRITE_PANOSE_CHARACTER_RANGES_NO_FIT = 1,
  DWRITE_PANOSE_CHARACTER_RANGES_EXTENDED_COLLECTION = 2,
  DWRITE_PANOSE_CHARACTER_RANGES_LITERALS = 3,
  DWRITE_PANOSE_CHARACTER_RANGES_NO_LOWER_CASE = 4,
  DWRITE_PANOSE_CHARACTER_RANGES_SMALL_CAPS = 5
} ;