PFND3D10_1DDI_CALCPRIVATESHADERRESOURCEVIEWSIZE Pfnd3d101DdiCalcprivateshaderresourceviewsize;

SIZE_T Pfnd3d101DdiCalcprivateshaderresourceviewsize(
  D3D10DDI_HDEVICE unnamedParam1,
  const D3D10_1DDIARG_CREATESHADERRESOURCEVIEW *unnamedParam2
)
{...}