PFND3D11_1DDI_GETVIDEOPROCESSORFILTERRANGE Pfnd3d111DdiGetvideoprocessorfilterrange;

VOID Pfnd3d111DdiGetvideoprocessorfilterrange(
  D3D10DDI_HDEVICE unnamedParam1,
  D3D11_1DDI_HVIDEOPROCESSORENUM unnamedParam2,
  D3D11_1DDI_VIDEO_PROCESSOR_FILTER unnamedParam3,
  D3D11_1DDI_VIDEO_PROCESSOR_FILTER_RANGE *unnamedParam4
)
{...}