PFND3D10_1DDI_CREATESHADERRESOURCEVIEW Pfnd3d101DdiCreateshaderresourceview;

VOID Pfnd3d101DdiCreateshaderresourceview(
  D3D10DDI_HDEVICE unnamedParam1,
  const D3D10_1DDIARG_CREATESHADERRESOURCEVIEW *unnamedParam2,
  D3D10DDI_HSHADERRESOURCEVIEW unnamedParam3,
  D3D10DDI_HRTSHADERRESOURCEVIEW unnamedParam4
)
{...}