PFND3D11_1DDI_CREATEVIDEOPROCESSORENUM Pfnd3d111DdiCreatevideoprocessorenum;

HRESULT Pfnd3d111DdiCreatevideoprocessorenum(
  D3D10DDI_HDEVICE unnamedParam1,
  const D3D11_1DDIARG_CREATEVIDEOPROCESSORENUM *unnamedParam2,
  D3D11_1DDI_HVIDEOPROCESSORENUM unnamedParam3,
  D3D11_1DDI_HRTVIDEOPROCESSORENUM unnamedParam4
)
{...}