PFND3D11_1DDI_CREATEAUTHENTICATEDCHANNEL Pfnd3d111DdiCreateauthenticatedchannel;

HRESULT Pfnd3d111DdiCreateauthenticatedchannel(
  D3D10DDI_HDEVICE hDevice,
  D3D11_1DDIARG_CREATEAUTHENTICATEDCHANNEL *pCreateData,
  D3D11_1DDI_HAUTHCHANNEL hAuthChannel,
  D3D11_1DDI_HRTAUTHCHANNEL hRTAuthChannel
)
{...}