PFND3D11_1DDI_CALCPRIVATEVIDEOPROCESSORINPUTVIEWSIZE Pfnd3d111DdiCalcprivatevideoprocessorinputviewsize;

SIZE_T Pfnd3d111DdiCalcprivatevideoprocessorinputviewsize(
  D3D10DDI_HDEVICE unnamedParam1,
  const D3D11_1DDIARG_CREATEVIDEOPROCESSORINPUTVIEW *unnamedParam2
)
{...}