PFND3D11_1DDI_CALCPRIVATEVIDEOPROCESSORENUMSIZE Pfnd3d111DdiCalcprivatevideoprocessorenumsize;

SIZE_T Pfnd3d111DdiCalcprivatevideoprocessorenumsize(
  D3D10DDI_HDEVICE unnamedParam1,
  const D3D11_1DDIARG_CREATEVIDEOPROCESSORENUM *unnamedParam2
)
{...}