PFND3DWDDM2_0DDI_CALCPRIVATEUNORDEREDACCESSVIEWSIZE Pfnd3dwddm20DdiCalcprivateunorderedaccessviewsize;

SIZE_T Pfnd3dwddm20DdiCalcprivateunorderedaccessviewsize(
  D3D10DDI_HDEVICE unnamedParam1,
  const D3DWDDM2_0DDIARG_CREATEUNORDEREDACCESSVIEW *unnamedParam2
)
{...}