PFND3D11_1DDI_CALCPRIVATEGEOMETRYSHADERWITHSTREAMOUTPUT Pfnd3d111DdiCalcprivategeometryshaderwithstreamoutput;

SIZE_T Pfnd3d111DdiCalcprivategeometryshaderwithstreamoutput(
  D3D10DDI_HDEVICE unnamedParam1,
  const D3D11DDIARG_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT *unnamedParam2,
  const D3D11_1DDIARG_STAGE_IO_SIGNATURES *unnamedParam3
)
{...}