typedef enum D3D10_DDI_RESOURCE_BIND_FLAG {
  D3D10_DDI_BIND_VERTEX_BUFFER,
  D3D10_DDI_BIND_INDEX_BUFFER,
  D3D10_DDI_BIND_CONSTANT_BUFFER,
  D3D10_DDI_BIND_SHADER_RESOURCE,
  D3D10_DDI_BIND_STREAM_OUTPUT,
  D3D10_DDI_BIND_RENDER_TARGET,
  D3D10_DDI_BIND_DEPTH_STENCIL,
  D3D10_DDI_BIND_PIPELINE_MASK,
  D3D10_DDI_BIND_PRESENT,
  D3D10_DDI_BIND_MASK,
  D3D11_DDI_BIND_UNORDERED_ACCESS,
  D3D11_DDI_BIND_DECODER,
  D3D11_DDI_BIND_VIDEO_ENCODER,
  D3D11_DDI_BIND_CAPTURE,
  D3D11_DDI_BIND_PIPELINE_MASK,
  D3D11_DDI_BIND_MASK
} ;