typedef enum D3D10_DDI_TEXTURE_ADDRESS_MODE {
  D3D10_DDI_TEXTURE_ADDRESS_WRAP,
  D3D10_DDI_TEXTURE_ADDRESS_MIRROR,
  D3D10_DDI_TEXTURE_ADDRESS_CLAMP,
  D3D10_DDI_TEXTURE_ADDRESS_BORDER,
  D3D10_DDI_TEXTURE_ADDRESS_MIRRORONCE
} ;