typedef enum D3DWDDM2_4DDI_VIDEO_DECODER_HISTOGRAM_COMPONENT_FLAGS
{
    D3DWDDM2_4DDI_VIDEO_DECODER_HISTOGRAM_COMPONENT_FLAG_NONE = 0x0,
    D3DWDDM2_4DDI_VIDEO_DECODER_HISTOGRAM_COMPONENT_FLAG_Y = (1 << D3DWDDM2_4DDI_VIDEO_DECODER_HISTOGRAM_COMPONENT_Y),
    D3DWDDM2_4DDI_VIDEO_DECODER_HISTOGRAM_COMPONENT_FLAG_U = (1 << D3DWDDM2_4DDI_VIDEO_DECODER_HISTOGRAM_COMPONENT_U),
    D3DWDDM2_4DDI_VIDEO_DECODER_HISTOGRAM_COMPONENT_FLAG_V = (1 << D3DWDDM2_4DDI_VIDEO_DECODER_HISTOGRAM_COMPONENT_V),

    D3DWDDM2_4DDI_VIDEO_DECODER_HISTOGRAM_COMPONENT_FLAG_R = (1 << D3DWDDM2_4DDI_VIDEO_DECODER_HISTOGRAM_COMPONENT_R),
    D3DWDDM2_4DDI_VIDEO_DECODER_HISTOGRAM_COMPONENT_FLAG_G = (1 << D3DWDDM2_4DDI_VIDEO_DECODER_HISTOGRAM_COMPONENT_G),
    D3DWDDM2_4DDI_VIDEO_DECODER_HISTOGRAM_COMPONENT_FLAG_B = (1 << D3DWDDM2_4DDI_VIDEO_DECODER_HISTOGRAM_COMPONENT_B),

    D3DWDDM2_4DDI_VIDEO_DECODER_HISTOGRAM_COMPONENT_FLAG_A = (1 << D3DWDDM2_4DDI_VIDEO_DECODER_HISTOGRAM_COMPONENT_A),

// ;begin_internal
    D3DWDDM2_4DDI_VIDEO_DECODE_HISTOGRAM_COMPONENT_FLAG_MASK = D3DWDDM2_4DDI_VIDEO_DECODER_HISTOGRAM_COMPONENT_FLAG_Y
                                                             | D3DWDDM2_4DDI_VIDEO_DECODER_HISTOGRAM_COMPONENT_FLAG_U
                                                             | D3DWDDM2_4DDI_VIDEO_DECODER_HISTOGRAM_COMPONENT_FLAG_V
                                                             | D3DWDDM2_4DDI_VIDEO_DECODER_HISTOGRAM_COMPONENT_FLAG_R
                                                             | D3DWDDM2_4DDI_VIDEO_DECODER_HISTOGRAM_COMPONENT_FLAG_G
                                                             | D3DWDDM2_4DDI_VIDEO_DECODER_HISTOGRAM_COMPONENT_FLAG_B
                                                             | D3DWDDM2_4DDI_VIDEO_DECODER_HISTOGRAM_COMPONENT_FLAG_A,

// ;end_internal
} D3DWDDM2_4DDI_VIDEO_DECODER_HISTOGRAM_COMPONENT_FLAGS;