typedef enum D3D10_DDI_COMPARISON_FUNC {
  D3D10_DDI_COMPARISON_NEVER,
  D3D10_DDI_COMPARISON_LESS,
  D3D10_DDI_COMPARISON_EQUAL,
  D3D10_DDI_COMPARISON_LESS_EQUAL,
  D3D10_DDI_COMPARISON_GREATER,
  D3D10_DDI_COMPARISON_NOT_EQUAL,
  D3D10_DDI_COMPARISON_GREATER_EQUAL,
  D3D10_DDI_COMPARISON_ALWAYS
} ;