typedef struct D3DWDDM2_0DDIARG_CREATESHADERRESOURCEVIEW {
  D3D10DDI_HRESOURCE    hDrvResource;
  DXGI_FORMAT           Format;
  D3D10DDIRESOURCE_TYPE ResourceDimension;
  union {
    D3D10DDIARG_BUFFER_SHADERRESOURCEVIEW     Buffer;
    D3D10DDIARG_TEX1D_SHADERRESOURCEVIEW      Tex1D;
    D3DWDDM2_0DDIARG_TEX2D_SHADERRESOURCEVIEW Tex2D;
    D3D10DDIARG_TEX3D_SHADERRESOURCEVIEW      Tex3D;
    D3D10_1DDIARG_TEXCUBE_SHADERRESOURCEVIEW  TexCube;
    D3D11DDIARG_BUFFEREX_SHADERRESOURCEVIEW   BufferEx;
  };
} D3DWDDM2_0DDIARG_CREATESHADERRESOURCEVIEW;