typedef struct D3DWDDM2_0DDI_VIDEO_PROCESSOR_STREAM_BEHAVIOR_HINT {
  BOOL        Enable;
  UINT        Width;
  UINT        Height;
  DXGI_FORMAT Format;
} D3DWDDM2_0DDI_VIDEO_PROCESSOR_STREAM_BEHAVIOR_HINT;