typedef struct D3D10DDIARG_CREATERENDERTARGETVIEW {
  [in] D3D10DDI_HRESOURCE    hDrvResource;
  [in] DXGI_FORMAT           Format;
  [in] D3D10DDIRESOURCE_TYPE ResourceDimension;
  union {
    [in] D3D10DDIARG_BUFFER_RENDERTARGETVIEW  Buffer;
    [in] D3D10DDIARG_TEX1D_RENDERTARGETVIEW   Tex1D;
    [in] D3D10DDIARG_TEX2D_RENDERTARGETVIEW   Tex2D;
    [in] D3D10DDIARG_TEX3D_RENDERTARGETVIEW   Tex3D;
    [in] D3D10DDIARG_TEXCUBE_RENDERTARGETVIEW TexCube;
  };
} D3D10DDIARG_CREATERENDERTARGETVIEW;