typedef struct D3D11DDIARG_CREATEDEPTHSTENCILVIEW {
  [in] D3D10DDI_HRESOURCE    hDrvResource;
  [in] DXGI_FORMAT           Format;
  [in] D3D10DDIRESOURCE_TYPE ResourceDimension;
  [in] UINT                  Flags;
  union {
    [in] D3D10DDIARG_TEX1D_DEPTHSTENCILVIEW   Tex1D;
    [in] D3D10DDIARG_TEX2D_DEPTHSTENCILVIEW   Tex2D;
    [in] D3D10DDIARG_TEXCUBE_DEPTHSTENCILVIEW TexCube;
  };
} D3D11DDIARG_CREATEDEPTHSTENCILVIEW;