typedef struct D3D11_1DDIARG_CREATEAUTHENTICATEDCHANNEL {
  D3D11_1DDI_AUTHENTICATED_CHANNEL_TYPE ChannelType;
  HANDLE                                hChannel;
} D3D11_1DDIARG_CREATEAUTHENTICATEDCHANNEL;