typedef struct D3DWDDM2_4DDIARG_VIDEODECODERBEGINFRAME_RS4_0 {
  D3D11_1DDI_HVIDEODECODEROUTPUTVIEW          hOutputView;
  const void                                  *pContentKey;
  UINT                                        ContentKeySize;
  D3DWDDM2_4DDI_VIDEO_DECODER_HISTOGRAM_RS4_0 Histograms[D3DWDDM2_4DDI_VIDEO_DECODER_MAX_HISTOGRAM_COMPONENTS];
} D3DWDDM2_4DDIARG_VIDEODECODERBEGINFRAME_RS4_0;