typedef struct D3DWDDM2_0DDIARG_CREATEUNORDEREDACCESSVIEW {
  D3D10DDI_HRESOURCE    hDrvResource;
  DXGI_FORMAT           Format;
  D3D10DDIRESOURCE_TYPE ResourceDimension;
  union {
    D3D11DDIARG_BUFFER_UNORDEREDACCESSVIEW     Buffer;
    D3D11DDIARG_TEX1D_UNORDEREDACCESSVIEW      Tex1D;
    D3DWDDM2_0DDIARG_TEX2D_UNORDEREDACCESSVIEW Tex2D;
    D3D11DDIARG_TEX3D_UNORDEREDACCESSVIEW      Tex3D;
  };
} D3DWDDM2_0DDIARG_CREATEUNORDEREDACCESSVIEW;