typedef struct D3D10_2DDI_ADAPTERFUNCS {
  PFND3D10DDI_CALCPRIVATEDEVICESIZE  pfnCalcPrivateDeviceSize;
  PFND3D10DDI_CREATEDEVICE           pfnCreateDevice;
  PFND3D10DDI_CLOSEADAPTER           pfnCloseAdapter;
  PFND3D10_2DDI_GETSUPPORTEDVERSIONS pfnGetSupportedVersions;
  PFND3D10_2DDI_GETCAPS              pfnGetCaps;
} D3D10_2DDI_ADAPTERFUNCS;