typedef struct D3D11DDIARG_CREATESHADERRESOURCEVIEW {
  [in] D3D10DDI_HRESOURCE    hDrvResource;
       DXGI_FORMAT           Format;
  [in] D3D10DDIRESOURCE_TYPE ResourceDimension;
  union {
    [in] D3D10DDIARG_BUFFER_SHADERRESOURCEVIEW    Buffer;
    [in] D3D10DDIARG_TEX1D_SHADERRESOURCEVIEW     Tex1D;
    [in] D3D10DDIARG_TEX2D_SHADERRESOURCEVIEW     Tex2D;
    [in] D3D10DDIARG_TEX3D_SHADERRESOURCEVIEW     Tex3D;
    [in] D3D10_1DDIARG_TEXCUBE_SHADERRESOURCEVIEW TexCube;
    [in] D3D11DDIARG_BUFFEREX_SHADERRESOURCEVIEW  BufferEx;
  };
} D3D11DDIARG_CREATESHADERRESOURCEVIEW;