typedef struct D3D11DDIARG_CREATEUNORDEREDACCESSVIEW {
  [in] D3D10DDI_HRESOURCE    hDrvResource;
  [in] DXGI_FORMAT           Format;
  [in] D3D10DDIRESOURCE_TYPE ResourceDimension;
  union {
    [in] D3D11DDIARG_BUFFER_UNORDEREDACCESSVIEW Buffer;
    [in] D3D11DDIARG_TEX1D_UNORDEREDACCESSVIEW  Tex1D;
    [in] D3D11DDIARG_TEX2D_UNORDEREDACCESSVIEW  Tex2D;
    [in] D3D11DDIARG_TEX3D_UNORDEREDACCESSVIEW  Tex3D;
  };
} D3D11DDIARG_CREATEUNORDEREDACCESSVIEW;