typedef enum peer_graph_event_type_tag {
  PEER_GRAPH_EVENT_STATUS_CHANGED = 1,
  PEER_GRAPH_EVENT_PROPERTY_CHANGED = 2,
  PEER_GRAPH_EVENT_RECORD_CHANGED = 3,
  PEER_GRAPH_EVENT_DIRECT_CONNECTION = 4,
  PEER_GRAPH_EVENT_NEIGHBOR_CONNECTION = 5,
  PEER_GRAPH_EVENT_INCOMING_DATA = 6,
  PEER_GRAPH_EVENT_CONNECTION_REQUIRED = 7,
  PEER_GRAPH_EVENT_NODE_CHANGED = 8,
  PEER_GRAPH_EVENT_SYNCHRONIZED = 9
} PEER_GRAPH_EVENT_TYPE;