typedef enum peer_presence_status_tag {
  PEER_PRESENCE_OFFLINE = 0,
  PEER_PRESENCE_OUT_TO_LUNCH = 1,
  PEER_PRESENCE_AWAY = 2,
  PEER_PRESENCE_BE_RIGHT_BACK = 3,
  PEER_PRESENCE_IDLE = 4,
  PEER_PRESENCE_BUSY = 5,
  PEER_PRESENCE_ON_THE_PHONE = 6,
  PEER_PRESENCE_ONLINE = 7
} PEER_PRESENCE_STATUS;