typedef enum peer_publication_scope_tag {
  PEER_PUBLICATION_SCOPE_NONE = 0x0,
  PEER_PUBLICATION_SCOPE_NEAR_ME = 0x1,
  PEER_PUBLICATION_SCOPE_INTERNET = 0x2,
  PEER_PUBLICATION_SCOPE_ALL
} PEER_PUBLICATION_SCOPE;