typedef enum peer_collab_event_type_tag {
  PEER_EVENT_WATCHLIST_CHANGED = 1,
  PEER_EVENT_ENDPOINT_CHANGED = 2,
  PEER_EVENT_ENDPOINT_PRESENCE_CHANGED = 3,
  PEER_EVENT_ENDPOINT_APPLICATION_CHANGED = 4,
  PEER_EVENT_ENDPOINT_OBJECT_CHANGED = 5,
  PEER_EVENT_MY_ENDPOINT_CHANGED = 6,
  PEER_EVENT_MY_PRESENCE_CHANGED = 7,
  PEER_EVENT_MY_APPLICATION_CHANGED = 8,
  PEER_EVENT_MY_OBJECT_CHANGED = 9,
  PEER_EVENT_PEOPLE_NEAR_ME_CHANGED = 10,
  PEER_EVENT_REQUEST_STATUS_CHANGED = 11
} PEER_COLLAB_EVENT_TYPE;