typedef enum peer_invitation_response_type_tag {
  PEER_INVITATION_RESPONSE_DECLINED = 0,
  PEER_INVITATION_RESPONSE_ACCEPTED = 1,
  PEER_INVITATION_RESPONSE_EXPIRED = 2,
  PEER_INVITATION_RESPONSE_ERROR = 3
} PEER_INVITATION_RESPONSE_TYPE;