typedef enum peer_graph_scope_tag {
  PEER_GRAPH_SCOPE_ANY = 0,
  PEER_GRAPH_SCOPE_GLOBAL = 1,
  PEER_GRAPH_SCOPE_SITELOCAL = 2,
  PEER_GRAPH_SCOPE_LINKLOCAL = 3,
  PEER_GRAPH_SCOPE_LOOPBACK = 4
} PEER_GRAPH_SCOPE;