typedef enum peer_member_change_type_tag {
  PEER_MEMBER_CONNECTED = 1,
  PEER_MEMBER_DISCONNECTED = 2,
  PEER_MEMBER_UPDATED = 3,
  PEER_MEMBER_JOINED = 4,
  PEER_MEMBER_LEFT = 5
} PEER_MEMBER_CHANGE_TYPE;