typedef enum peer_group_event_type_tag {
  PEER_GROUP_EVENT_STATUS_CHANGED = 1,
  PEER_GROUP_EVENT_PROPERTY_CHANGED = 2,
  PEER_GROUP_EVENT_RECORD_CHANGED = 3,
  PEER_GROUP_EVENT_DIRECT_CONNECTION = 4,
  PEER_GROUP_EVENT_NEIGHBOR_CONNECTION = 5,
  PEER_GROUP_EVENT_INCOMING_DATA = 6,
  PEER_GROUP_EVENT_MEMBER_CHANGED = 8,
  PEER_GROUP_EVENT_CONNECTION_FAILED = 10,
  PEER_GROUP_EVENT_AUTHENTICATION_FAILED = 11
} PEER_GROUP_EVENT_TYPE;