typedef enum D2D1_COLORMANAGEMENT_ALPHA_MODE {
  D2D1_COLORMANAGEMENT_ALPHA_MODE_PREMULTIPLIED = 1,
  D2D1_COLORMANAGEMENT_ALPHA_MODE_STRAIGHT = 2,
  D2D1_COLORMANAGEMENT_ALPHA_MODE_FORCE_DWORD = 0xffffffff
} ;