typedef enum D2D1_GAUSSIANBLUR_OPTIMIZATION {
  D2D1_GAUSSIANBLUR_OPTIMIZATION_SPEED = 0,
  D2D1_GAUSSIANBLUR_OPTIMIZATION_BALANCED = 1,
  D2D1_GAUSSIANBLUR_OPTIMIZATION_QUALITY = 2,
  D2D1_GAUSSIANBLUR_OPTIMIZATION_FORCE_DWORD = 0xffffffff
} ;