typedef enum D2D1_HISTOGRAM_PROP {
  D2D1_HISTOGRAM_PROP_NUM_BINS = 0,
  D2D1_HISTOGRAM_PROP_CHANNEL_SELECT = 1,
  D2D1_HISTOGRAM_PROP_HISTOGRAM_OUTPUT = 2,
  D2D1_HISTOGRAM_PROP_FORCE_DWORD = 0xffffffff
} ;