typedef enum D2D1_ARITHMETICCOMPOSITE_PROP {
  D2D1_ARITHMETICCOMPOSITE_PROP_COEFFICIENTS = 0,
  D2D1_ARITHMETICCOMPOSITE_PROP_CLAMP_OUTPUT = 1,
  D2D1_ARITHMETICCOMPOSITE_PROP_FORCE_DWORD = 0xffffffff
} ;