typedef enum D2D1_COLORMANAGEMENT_RENDERING_INTENT {
  D2D1_COLORMANAGEMENT_RENDERING_INTENT_PERCEPTUAL = 0,
  D2D1_COLORMANAGEMENT_RENDERING_INTENT_RELATIVE_COLORIMETRIC = 1,
  D2D1_COLORMANAGEMENT_RENDERING_INTENT_SATURATION = 2,
  D2D1_COLORMANAGEMENT_RENDERING_INTENT_ABSOLUTE_COLORIMETRIC = 3,
  D2D1_COLORMANAGEMENT_RENDERING_INTENT_FORCE_DWORD = 0xffffffff
} ;