typedef enum D2D1_COLORMANAGEMENT_QUALITY {
  D2D1_COLORMANAGEMENT_QUALITY_PROOF = 0,
  D2D1_COLORMANAGEMENT_QUALITY_NORMAL = 1,
  D2D1_COLORMANAGEMENT_QUALITY_BEST = 2,
  D2D1_COLORMANAGEMENT_QUALITY_FORCE_DWORD = 0xffffffff
} ;