typedef enum D2D1_3DTRANSFORM_PROP {
  D2D1_3DTRANSFORM_PROP_INTERPOLATION_MODE = 0,
  D2D1_3DTRANSFORM_PROP_BORDER_MODE = 1,
  D2D1_3DTRANSFORM_PROP_TRANSFORM_MATRIX = 2,
  D2D1_3DTRANSFORM_PROP_FORCE_DWORD = 0xffffffff
} ;