typedef enum SYNCMGR_PRESENTER_CHOICE {
  SYNCMGR_PC_NO_CHOICE = 0,
  SYNCMGR_PC_KEEP_ONE,
  SYNCMGR_PC_KEEP_MULTIPLE,
  SYNCMGR_PC_KEEP_RECENT,
  SYNCMGR_PC_REMOVE_FROM_SYNC_SET,
  SYNCMGR_PC_SKIP
} ;