typedef enum SYNCMGR_RESOLUTION_ABILITIES {
  SYNCMGR_RA_KEEPOTHER = 0x1,
  SYNCMGR_RA_KEEPRECENT = 0x2,
  SYNCMGR_RA_REMOVEFROMSYNCSET = 0x4,
  SYNCMGR_RA_KEEP_SINGLE = 0x8,
  SYNCMGR_RA_KEEP_MULTIPLE = 0x10,
  SYNCMGR_RA_VALID = 0x1f
} ;