typedef struct _INTERNAL_I8042_START_INFORMATION {
  ULONG       Size;
  PKINTERRUPT InterruptObject;
  ULONG       Reserved[8];
} INTERNAL_I8042_START_INFORMATION, *PINTERNAL_I8042_START_INFORMATION;