typedef struct _WLAN_HOSTED_NETWORK_STATE_CHANGE {
  WLAN_HOSTED_NETWORK_STATE  OldState;
  WLAN_HOSTED_NETWORK_STATE  NewState;
  WLAN_HOSTED_NETWORK_REASON StateChangeReason;
} WLAN_HOSTED_NETWORK_STATE_CHANGE, *PWLAN_HOSTED_NETWORK_STATE_CHANGE;