typedef struct _WLAN_HOSTED_NETWORK_DATA_PEER_STATE_CHANGE {
  WLAN_HOSTED_NETWORK_PEER_STATE OldState;
  WLAN_HOSTED_NETWORK_PEER_STATE NewState;
  WLAN_HOSTED_NETWORK_REASON     PeerStateChangeReason;
} WLAN_HOSTED_NETWORK_DATA_PEER_STATE_CHANGE, *PWLAN_HOSTED_NETWORK_DATA_PEER_STATE_CHANGE;