typedef enum _tagAVC_FUNCTION {
  AVC_FUNCTION_COMMAND,
  AVC_FUNCTION_GET_PIN_COUNT,
  AVC_FUNCTION_GET_PIN_DESCRIPTOR,
  AVC_FUNCTION_GET_CONNECTINFO,
  AVC_FUNCTION_SET_CONNECTINFO,
  AVC_FUNCTION_ACQUIRE,
  AVC_FUNCTION_RELEASE,
  AVC_FUNCTION_CLR_CONNECTINFO,
  AVC_FUNCTION_GET_EXT_PLUG_COUNTS,
  AVC_FUNCTION_GET_UNIQUE_ID,
  AVC_FUNCTION_GET_REQUEST,
  AVC_FUNCTION_SEND_RESPONSE,
  AVC_FUNCTION_FIND_PEER_DO,
  AVC_FUNCTION_PEER_DO_LIST,
  AVC_FUNCTION_GET_SUBUNIT_INFO
} AVC_FUNCTION;