typedef enum _tagAvcSubunitType {
  AVC_SUBUNITTYPE_VIDEO_MONITOR,
  AVC_SUBUNITTYPE_AUDIO,
  AVC_SUBUNITTYPE_PRINTER,
  AVC_SUBUNITTYPE_DISC_PLAYER,
  AVC_SUBUNITTYPE_TAPE_PLAYER,
  AVC_SUBUNITTYPE_TUNER,
  AVC_SUBUNITTYPE_CA,
  AVC_SUBUNITTYPE_VIDEO_CAMERA,
  AVC_SUBUNITTYPE_PANEL,
  AVC_SUBUNITTYPE_BULLETINBOARD,
  AVC_SUBUNITTYPE_CAMERASTORAGE,
  AVC_SUBUNITTYPE_VENDOR_UNIQUE,
  AVC_SUBUNITTYPE_EXTENDED,
  AVC_SUBUNITTYPE_EXTENDED_FULL,
  AVC_SUBUNITTYPE_UNIT
} AvcSubunitType;