typedef enum _tagAvcResponseCode {
  AVC_RESPONSE_NOTIMPL,
  AVC_RESPONSE_ACCEPTED,
  AVC_RESPONSE_REJECTED,
  AVC_RESPONSE_IN_TRANSITION,
  AVC_RESPONSE_STABLE,
  AVC_RESPONSE_IMPLEMENTED,
  AVC_RESPONSE_CHANGED,
  AVC_RESPONSE_INTERIM
} AvcResponseCode;