typedef enum {
  DFS_NAMESPACE_VERSION_ORIGIN_COMBINED = 0,
  DFS_NAMESPACE_VERSION_ORIGIN_SERVER,
  DFS_NAMESPACE_VERSION_ORIGIN_DOMAIN
} DFS_NAMESPACE_VERSION_ORIGIN, *PDFS_NAMESPACE_VERSION_ORIGIN;