typedef enum IKEEXT_MM_SA_STATE_ {
  IKEEXT_MM_SA_STATE_NONE = 0,
  IKEEXT_MM_SA_STATE_SA_SENT,
  IKEEXT_MM_SA_STATE_SSPI_SENT,
  IKEEXT_MM_SA_STATE_FINAL,
  IKEEXT_MM_SA_STATE_FINAL_SENT,
  IKEEXT_MM_SA_STATE_COMPLETE,
  IKEEXT_MM_SA_STATE_MAX
} IKEEXT_MM_SA_STATE;