typedef enum IKEEXT_CERT_CRITERIA_NAME_TYPE_ {
  IKEEXT_CERT_CRITERIA_DNS = 0,
  IKEEXT_CERT_CRITERIA_UPN,
  IKEEXT_CERT_CRITERIA_RFC822,
  IKEEXT_CERT_CRITERIA_CN,
  IKEEXT_CERT_CRITERIA_OU,
  IKEEXT_CERT_CRITERIA_O,
  IKEEXT_CERT_CRITERIA_DC,
  IKEEXT_CERT_CRITERIA_NAME_TYPE_MAX
} IKEEXT_CERT_CRITERIA_NAME_TYPE;