typedef enum IKEEXT_AUTHENTICATION_IMPERSONATION_TYPE_ {
  IKEEXT_IMPERSONATION_NONE = 0,
  IKEEXT_IMPERSONATION_SOCKET_PRINCIPAL,
  IKEEXT_IMPERSONATION_MAX
} IKEEXT_AUTHENTICATION_IMPERSONATION_TYPE;