typedef enum IKEEXT_QM_SA_STATE_ {
  IKEEXT_QM_SA_STATE_NONE = 0,
  IKEEXT_QM_SA_STATE_INITIAL,
  IKEEXT_QM_SA_STATE_FINAL,
  IKEEXT_QM_SA_STATE_COMPLETE,
  IKEEXT_QM_SA_STATE_MAX
} IKEEXT_QM_SA_STATE;