typedef enum IKEEXT_DH_GROUP_ {
  IKEEXT_DH_GROUP_NONE = 0,
  IKEEXT_DH_GROUP_1,
  IKEEXT_DH_GROUP_2,
  IKEEXT_DH_GROUP_14,
  IKEEXT_DH_GROUP_2048,
  IKEEXT_DH_ECP_256,
  IKEEXT_DH_ECP_384,
  IKEEXT_DH_GROUP_24,
  IKEEXT_DH_GROUP_MAX
} IKEEXT_DH_GROUP;