typedef enum IKEEXT_EM_SA_STATE_ {
  IKEEXT_EM_SA_STATE_NONE = 0,
  IKEEXT_EM_SA_STATE_SENT_ATTS,
  IKEEXT_EM_SA_STATE_SSPI_SENT,
  IKEEXT_EM_SA_STATE_AUTH_COMPLETE,
  IKEEXT_EM_SA_STATE_FINAL,
  IKEEXT_EM_SA_STATE_COMPLETE,
  IKEEXT_EM_SA_STATE_MAX
} IKEEXT_EM_SA_STATE;