typedef enum IKEEXT_AUTHENTICATION_METHOD_TYPE_ {
  IKEEXT_PRESHARED_KEY = 0,
  IKEEXT_CERTIFICATE,
  IKEEXT_KERBEROS,
  IKEEXT_ANONYMOUS,
  IKEEXT_SSL,
  IKEEXT_NTLM_V2,
  IKEEXT_IPV6_CGA,
  IKEEXT_CERTIFICATE_ECDSA_P256,
  IKEEXT_CERTIFICATE_ECDSA_P384,
  IKEEXT_SSL_ECDSA_P256,
  IKEEXT_SSL_ECDSA_P384,
  IKEEXT_EAP,
  IKEEXT_RESERVED,
  IKEEXT_AUTHENTICATION_METHOD_TYPE_MAX
} IKEEXT_AUTHENTICATION_METHOD_TYPE;