typedef enum IKEEXT_CIPHER_TYPE_ {
  IKEEXT_CIPHER_DES = 0,
  IKEEXT_CIPHER_3DES,
  IKEEXT_CIPHER_AES_128,
  IKEEXT_CIPHER_AES_192,
  IKEEXT_CIPHER_AES_256,
  IKEEXT_CIPHER_AES_GCM_128_16ICV,
  IKEEXT_CIPHER_AES_GCM_256_16ICV,
  IKEEXT_CIPHER_TYPE_MAX
} IKEEXT_CIPHER_TYPE;