typedef enum IKEEXT_CERT_CONFIG_TYPE_ {
  IKEEXT_CERT_CONFIG_EXPLICIT_TRUST_LIST = 0,
  IKEEXT_CERT_CONFIG_ENTERPRISE_STORE,
  IKEEXT_CERT_CONFIG_TRUSTED_ROOT_STORE,
  IKEEXT_CERT_CONFIG_UNSPECIFIED,
  IKEEXT_CERT_CONFIG_TYPE_MAX
} IKEEXT_CERT_CONFIG_TYPE;