typedef struct IKEEXT_STATISTICS1_ {
  IKEEXT_KEYMODULE_STATISTICS1 ikeStatistics;
  IKEEXT_KEYMODULE_STATISTICS1 authipStatistics;
  IKEEXT_KEYMODULE_STATISTICS1 ikeV2Statistics;
  IKEEXT_COMMON_STATISTICS1    commonStatistics;
} IKEEXT_STATISTICS1;