typedef struct IKEEXT_STATISTICS0_ {
  IKEEXT_KEYMODULE_STATISTICS0 ikeStatistics;
  IKEEXT_KEYMODULE_STATISTICS0 authipStatistics;
  IKEEXT_COMMON_STATISTICS0    commonStatistics;
} IKEEXT_STATISTICS0;