typedef enum _TRANSPORTCLIENT_CALLBACK_ID {
  WDS_TRANSPORTCLIENT_SESSION_START = 0,
  WDS_TRANSPORTCLIENT_RECEIVE_CONTENTS,
  WDS_TRANSPORTCLIENT_SESSION_COMPLETE,
  WDS_TRANSPORTCLIENT_RECEIVE_METADATA,
  WDS_TRANSPORTCLIENT_SESSION_STARTEX,
  WDS_TRANSPORTCLIENT_SESSION_NEGOTIATE,
  WDS_TRANSPORTCLIENT_MAX_CALLBACKS
} TRANSPORTCLIENT_CALLBACK_ID, *PTRANSPORTCLIENT_CALLBACK_ID;