typedef enum _FA_ENTRY_TYPE {
  DEBUG_FA_ENTRY_NO_TYPE,
  DEBUG_FA_ENTRY_ULONG,
  DEBUG_FA_ENTRY_ULONG64,
  DEBUG_FA_ENTRY_INSTRUCTION_OFFSET,
  DEBUG_FA_ENTRY_POINTER,
  DEBUG_FA_ENTRY_ANSI_STRING,
  DEBUG_FA_ENTRY_ANSI_STRINGs,
  DEBUG_FA_ENTRY_EXTENSION_CMD,
  DEBUG_FA_ENTRY_STRUCTURED_DATA,
  DEBUG_FA_ENTRY_UNICODE_STRING,
  DEBUG_FA_ENTRY_ARRAY
} FA_ENTRY_TYPE;