typedef enum CLUSCTL_GROUPSET_CODES {
  CLUSCTL_GROUPSET_GET_COMMON_PROPERTIES,
  CLUSCTL_GROUPSET_GET_RO_COMMON_PROPERTIES,
  CLUSCTL_GROUPSET_SET_COMMON_PROPERTIES,
  CLUSCTL_GROUPSET_GET_GROUPS,
  CLUSCTL_GROUPSET_GET_PROVIDER_GROUPS,
  CLUSCTL_GROUPSET_GET_PROVIDER_GROUPSETS,
  CLUSCTL_GROUP_GET_PROVIDER_GROUPS,
  CLUSCTL_GROUP_GET_PROVIDER_GROUPSETS,
  CLUSCTL_GROUPSET_GET_ID
} ;