typedef enum {
  ClusGroupTypeCoreCluster = 1,
  ClusGroupTypeAvailableStorage = 2,
  ClusGroupTypeTemporary = 3,
  ClusGroupTypeSharedVolume = 4,
  ClusGroupTypeStoragePool = 5,
  ClusGroupTypeFileServer = 100,
  ClusGroupTypePrintServer = 101,
  ClusGroupTypeDhcpServer = 102,
  ClusGroupTypeDtc = 103,
  ClusGroupTypeMsmq = 104,
  ClusGroupTypeWins = 105,
  ClusGroupTypeStandAloneDfs = 106,
  ClusGroupTypeGenericApplication = 107,
  ClusGroupTypeGenericService = 108,
  ClusGroupTypeGenericScript = 109,
  ClusGroupTypeIScsiNameService = 110,
  ClusGroupTypeVirtualMachine = 111,
  ClusGroupTypeTsSessionBroker = 112,
  ClusGroupTypeIScsiTarget = 113,
  ClusGroupTypeScaleoutFileServer = 114,
  ClusGroupTypeVMReplicaBroker = 115,
  ClusGroupTypeTaskScheduler = 116,
  ClusGroupTypeClusterUpdateAgent = 117,
  ClusGroupTypeScaleoutCluster = 118,
  ClusGroupTypeStorageReplica = 119,
  ClusGroupTypeVMReplicaCoordinator = 120,
  ClusGroupTypeCrossClusterOrchestrator = 121,
  ClusGroupTypeInfrastructureFileServer = 122,
  ClusGroupTypeCoreSddc,
  ClusGroupTypeUserManager,
  ClusGroupTypeKeyValueStoreManager,
  ClusGroupTypeHcsVirtualMachine,
  ClusGroupTypeMetaVirtualMachine,
  ClusGroupTypeUnknown = 9999
} CLUSGROUP_TYPE, *PCLUSGROUP_TYPE;