typedef enum CLUSTER_PROPERTY_FORMAT {
  CLUSPROP_FORMAT_UNKNOWN = 0,
  CLUSPROP_FORMAT_BINARY,
  CLUSPROP_FORMAT_DWORD,
  CLUSPROP_FORMAT_SZ,
  CLUSPROP_FORMAT_EXPAND_SZ,
  CLUSPROP_FORMAT_MULTI_SZ,
  CLUSPROP_FORMAT_ULARGE_INTEGER,
  CLUSPROP_FORMAT_LONG,
  CLUSPROP_FORMAT_EXPANDED_SZ,
  CLUSPROP_FORMAT_SECURITY_DESCRIPTOR,
  CLUSPROP_FORMAT_LARGE_INTEGER,
  CLUSPROP_FORMAT_WORD,
  CLUSPROP_FORMAT_FILETIME,
  CLUSPROP_FORMAT_VALUE_LIST,
  CLUSPROP_FORMAT_PROPERTY_LIST,
  CLUSPROP_FORMAT_USER = 32768
} ;