typedef struct CLUS_NETNAME_IP_INFO_FOR_MULTICHANNEL {
  WCHAR                      szName[DNS_LENGTH];
  DWORD                      NumEntries;
  CLUS_NETNAME_IP_INFO_ENTRY IpInfo[ANYSIZE_ARRAY];
} CLUS_NETNAME_IP_INFO_FOR_MULTICHANNEL, *PCLUS_NETNAME_IP_INFO_FOR_MULTICHANNEL;