typedef struct CLUS_NETNAME_PWD_INFO {
  DWORD Flags;
  WCHAR Password[MAX_CO_PASSWORD_LENGTH];
  WCHAR CreatingDC[MAX_CREATINGDC_LENGTH + 2];
  WCHAR ObjectGuid[MAX_OBJECTID];
} CLUS_NETNAME_PWD_INFO, *PCLUS_NETNAME_PWD_INFO, CLUS_RLUA_PWD_INFO, *PCLUS_RLUA_PWD_INFO;