typedef union CLUSPROP_REQUIRED_DEPENDENCY {
  CLUSPROP_VALUE          Value;
  CLUSPROP_RESOURCE_CLASS ResClass;
  CLUSPROP_SZ             ResTypeName;
} CLUSPROP_REQUIRED_DEPENDENCY, *PCLUSPROP_REQUIRED_DEPENDENCY;