typedef struct _SR_RESOURCE_TYPE_ELIGIBLE_TARGET_DATADISKS {
  GUID    SourceDataDiskGuid;
  GUID    TargetReplicationGroupGuid;
  BOOLEAN SkipConnectivityCheck;
  BOOLEAN IncludeOfflineDisks;
} SR_RESOURCE_TYPE_QUERY_ELIGIBLE_TARGET_DATADISKS, *PSR_RESOURCE_TYPE_QUERY_ELIGIBLE_TARGET_DATADISKS;