typedef struct _SR_RESOURCE_TYPE_QUERY_ELIGIBLE_LOGDISKS {
  GUID    DataDiskGuid;
  BOOLEAN IncludeOfflineDisks;
} SR_RESOURCE_TYPE_QUERY_ELIGIBLE_LOGDISKS, *PSR_RESOURCE_TYPE_QUERY_ELIGIBLE_LOGDISKS;