typedef struct _SR_RESOURCE_TYPE_ELIGIBLE_SOURCE_DATADISKS {
  GUID    DataDiskGuid;
  BOOLEAN IncludeAvailableStoargeDisks;
} SR_RESOURCE_TYPE_QUERY_ELIGIBLE_SOURCE_DATADISKS, *PSR_RESOURCE_TYPE_QUERY_ELIGIBLE_SOURCE_DATADISKS;