typedef struct _SR_RESOURCE_TYPE_REPLICATED_PARTITION_INFO {
  ULONGLONG PartitionOffset;
  ULONG     Capabilities;
} SR_RESOURCE_TYPE_REPLICATED_PARTITION_INFO, *PSR_RESOURCE_TYPE_REPLICATED_PARTITION_INFO;