typedef struct CLUS_NETNAME_VS_TOKEN_INFO {
  DWORD ProcessID;
  DWORD DesiredAccess;
  BOOL  InheritHandle;
} CLUS_NETNAME_VS_TOKEN_INFO, CLUS_VS_TOKEN_INFO, *PCLUS_NETNAME_VS_TOKEN_INFO, *PCLUS_VS_TOKEN_INFO;