typedef struct _SR_RESOURCE_TYPE_REPLICATED_PARTITION_ARRAY {
  DWORD                                      Count;
  SR_RESOURCE_TYPE_REPLICATED_PARTITION_INFO PartitionArray[1];
} SR_RESOURCE_TYPE_REPLICATED_PARTITION_ARRAY, *PSR_RESOURCE_TYPE_REPLICATED_PARTITION_ARRAY;