typedef struct _CLUSCTL_GROUP_GET_LAST_MOVE_TIME_OUTPUT {
  ULONGLONG  GetTickCount64;
  SYSTEMTIME GetSystemTime;
  DWORD      NodeId;
} CLUSCTL_GROUP_GET_LAST_MOVE_TIME_OUTPUT, *PCLUSCTL_GROUP_GET_LAST_MOVE_TIME_OUTPUT;