typedef struct CLUSPROP_SECURITY_DESCRIPTOR : CLUSPROP_VALUE {
  union {
    SECURITY_DESCRIPTOR_RELATIVE sd;
    BYTE                         rgbSecurityDescriptor[];
  } DUMMYUNIONNAME;
} CLUSPROP_SECURITY_DESCRIPTOR, *PCLUSPROP_SECURITY_DESCRIPTOR;