typedef struct _CLUSCTL_RESOURCE_STATE_CHANGE_REASON_STRUCT {
  DWORD                                dwSize;
  DWORD                                dwVersion;
  CLUSTER_RESOURCE_STATE_CHANGE_REASON eReason;
} CLUSCTL_RESOURCE_STATE_CHANGE_REASON_STRUCT, *PCLUSCTL_RESOURCE_STATE_CHANGE_REASON_STRUCT;