typedef enum MF_CAPTURE_ENGINE_STREAM_CATEGORY {
  MF_CAPTURE_ENGINE_STREAM_CATEGORY_VIDEO_PREVIEW = 0,
  MF_CAPTURE_ENGINE_STREAM_CATEGORY_VIDEO_CAPTURE = 0x1,
  MF_CAPTURE_ENGINE_STREAM_CATEGORY_PHOTO_INDEPENDENT = 0x2,
  MF_CAPTURE_ENGINE_STREAM_CATEGORY_PHOTO_DEPENDENT = 0x3,
  MF_CAPTURE_ENGINE_STREAM_CATEGORY_AUDIO = 0x4,
  MF_CAPTURE_ENGINE_STREAM_CATEGORY_UNSUPPORTED = 0x5,
  MF_CAPTURE_ENGINE_STREAM_CATEGORY_METADATA
} ;