typedef enum ENCLAVE_SEALING_IDENTITY_POLICY {
  ENCLAVE_IDENTITY_POLICY_SEAL_INVALID = 0,
  ENCLAVE_IDENTITY_POLICY_SEAL_EXACT_CODE,
  ENCLAVE_IDENTITY_POLICY_SEAL_SAME_PRIMARY_CODE,
  ENCLAVE_IDENTITY_POLICY_SEAL_SAME_IMAGE,
  ENCLAVE_IDENTITY_POLICY_SEAL_SAME_FAMILY,
  ENCLAVE_IDENTITY_POLICY_SEAL_SAME_AUTHOR
} ;