typedef enum D3D10_COLOR_WRITE_ENABLE {
  D3D10_COLOR_WRITE_ENABLE_RED = 1,
  D3D10_COLOR_WRITE_ENABLE_GREEN = 2,
  D3D10_COLOR_WRITE_ENABLE_BLUE = 4,
  D3D10_COLOR_WRITE_ENABLE_ALPHA = 8,
  D3D10_COLOR_WRITE_ENABLE_ALL
} ;