typedef enum _WRDS_SETTING_STATUS {
  WRDS_SETTING_STATUS_NOTAPPLICABLE = -1,
  WRDS_SETTING_STATUS_DISABLED,
  WRDS_SETTING_STATUS_ENABLED,
  WRDS_SETTING_STATUS_NOTCONFIGURED
} WRDS_SETTING_STATUS, *PWRDS_SETTING_STATUS;