typedef enum _WTS_LOGON_ERROR_REDIRECTOR_RESPONSE {
  WTS_LOGON_ERR_INVALID = 0,
  WTS_LOGON_ERR_NOT_HANDLED,
  WTS_LOGON_ERR_HANDLED_SHOW,
  WTS_LOGON_ERR_HANDLED_DONT_SHOW,
  WTS_LOGON_ERR_HANDLED_DONT_SHOW_START_OVER
} WTS_LOGON_ERROR_REDIRECTOR_RESPONSE;