typedef struct _WTS_USER_CREDENTIAL {
  WCHAR UserName[WTS_USERNAME_LENGTH + 1];
  WCHAR Password[WTS_PASSWORD_LENGTH + 1];
  WCHAR Domain[WTS_DOMAIN_LENGTH + 1];
} _WTS_USER_CREDENTIAL, WTS_USER_CREDENTIAL, *PWTS_USER_CREDENTIAL, _WRDS_USER_CREDENTIAL;