typedef struct _WTS_DISPLAY_IOCTL {
  BYTE  pDisplayIOCtlData[WTS_MAX_DISPLAY_IOCTL_DATA];
  ULONG cbDisplayIOCtlData;
} _WTS_DISPLAY_IOCTL, WTS_DISPLAY_IOCTL, *PWTS_DISPLAY_IOCTL, _WRDS_DISPLAY_IOCTL;