typedef struct _WTS_CLIENT_DATA {
  BOOLEAN                   fDisableCtrlAltDel;
  BOOLEAN                   fDoubleClickDetect;
  BOOLEAN                   fEnableWindowsKey;
  BOOLEAN                   fHideTitleBar;
  BOOL                      fInheritAutoLogon;
  BOOLEAN                   fPromptForPassword;
  BOOLEAN                   fUsingSavedCreds;
  WCHAR                     Domain[WTS_DOMAIN_LENGTH + 1];
  WCHAR                     UserName[WTS_USERNAME_LENGTH + 1];
  WCHAR                     Password[WTS_PASSWORD_LENGTH + 1];
  BOOLEAN                   fPasswordIsScPin;
  BOOL                      fInheritInitialProgram;
  WCHAR                     WorkDirectory[WTS_DIRECTORY_LENGTH + 1];
  WCHAR                     InitialProgram[WTS_INITIALPROGRAM_LENGTH + 1];
  BOOLEAN                   fMaximizeShell;
  BYTE                      EncryptionLevel;
  ULONG                     PerformanceFlags;
  WCHAR                     ProtocolName[WTS_PROTOCOL_NAME_LENGTH + 1];
  USHORT                    ProtocolType;
  BOOL                      fInheritColorDepth;
  USHORT                    HRes;
  USHORT                    VRes;
  USHORT                    ColorDepth;
  WCHAR                     DisplayDriverName[WTS_DRIVER_NAME_LENGTH + 1];
  WCHAR                     DisplayDeviceName[WTS_DEVICE_NAME_LENGTH + 1];
  BOOLEAN                   fMouse;
  ULONG                     KeyboardLayout;
  ULONG                     KeyboardType;
  ULONG                     KeyboardSubType;
  ULONG                     KeyboardFunctionKey;
  WCHAR                     imeFileName[WTS_IMEFILENAME_LENGTH + 1];
  ULONG                     ActiveInputLocale;
  BOOLEAN                   fNoAudioPlayback;
  BOOLEAN                   fRemoteConsoleAudio;
  WCHAR                     AudioDriverName[WTS_DRIVER_NAME_LENGTH + 1];
  WTS_TIME_ZONE_INFORMATION ClientTimeZone;
  WCHAR                     ClientName[WTS_CLIENTNAME_LENGTH + 1];
  ULONG                     SerialNumber;
  ULONG                     ClientAddressFamily;
  WCHAR                     ClientAddress[WTS_CLIENTADDRESS_LENGTH + 1];
  WTS_SOCKADDR              ClientSockAddress;
  WCHAR                     ClientDirectory[WTS_DIRECTORY_LENGTH + 1];
  ULONG                     ClientBuildNumber;
  USHORT                    ClientProductId;
  USHORT                    OutBufCountHost;
  USHORT                    OutBufCountClient;
  USHORT                    OutBufLength;
  ULONG                     ClientSessionId;
  WCHAR                     ClientDigProductId[WTS_CLIENT_PRODUCT_ID_LENGTH + 1];
  BOOLEAN                   fDisableCpm;
  BOOLEAN                   fDisableCdm;
  BOOLEAN                   fDisableCcm;
  BOOLEAN                   fDisableLPT;
  BOOLEAN                   fDisableClip;
  BOOLEAN                   fDisablePNP;
} _WTS_CLIENT_DATA, WTS_CLIENT_DATA, *PWTS_CLIENT_DATA, _WRDS_CLIENT_DATA;