typedef struct _WRDS_CONNECTION_SETTINGS {
  WRDS_CONNECTION_SETTING_LEVEL WRdsConnectionSettingLevel;
  WRDS_CONNECTION_SETTING       WRdsConnectionSetting;
} WRDS_CONNECTION_SETTINGS, *PWRDS_CONNECTION_SETTINGS;