typedef struct _WTS_SERIALIZED_USER_CREDENTIAL {
  ULONG SerializationLength;
  BYTE  *Serialization;
} WTS_SERIALIZED_USER_CREDENTIAL, *PWTS_SERIALIZED_USER_CREDENTIAL, WRDS_SERIALIZED_USER_CREDENTIAL, *PWRDS_SERIALIZED_USER_CREDENTIAL;