typedef union _WTS_CACHE_STATS_UN {
  WTS_PROTOCOL_CACHE ProtocolCache[WTS_MAX_PROTOCOL_CACHE];
  ULONG              TShareCacheStats;
  ULONG              Reserved[WTS_MAX_CACHE_RESERVED];
} _WTS_CACHE_STATS_UN, WTS_CACHE_STATS_UN, *PWTS_CACHE_STATS_UN, _WRDS_CACHE_STATS_UN;