typedef enum _IMAPI_BURN_VERIFICATION_LEVEL {
  IMAPI_BURN_VERIFICATION_NONE = 0,
  IMAPI_BURN_VERIFICATION_QUICK = 1,
  IMAPI_BURN_VERIFICATION_FULL = 2
} IMAPI_BURN_VERIFICATION_LEVEL, *PIMAPI_BURN_VERIFICATION_LEVEL;