typedef enum _IMAPI_MODE_PAGE_TYPE {
  IMAPI_MODE_PAGE_TYPE_READ_WRITE_ERROR_RECOVERY = 0x1,
  IMAPI_MODE_PAGE_TYPE_MRW = 0x3,
  IMAPI_MODE_PAGE_TYPE_WRITE_PARAMETERS = 0x5,
  IMAPI_MODE_PAGE_TYPE_CACHING = 0x8,
  IMAPI_MODE_PAGE_TYPE_INFORMATIONAL_EXCEPTIONS = 0x1c,
  IMAPI_MODE_PAGE_TYPE_TIMEOUT_AND_PROTECT = 0x1d,
  IMAPI_MODE_PAGE_TYPE_POWER_CONDITION = 0x1a,
  IMAPI_MODE_PAGE_TYPE_LEGACY_CAPABILITIES = 0x2a
} IMAPI_MODE_PAGE_TYPE, *PIMAPI_MODE_PAGE_TYPE;