typedef enum _IMAPI_CD_SECTOR_TYPE {
  IMAPI_CD_SECTOR_AUDIO = 0,
  IMAPI_CD_SECTOR_MODE_ZERO = 0x1,
  IMAPI_CD_SECTOR_MODE1 = 0x2,
  IMAPI_CD_SECTOR_MODE2FORM0 = 0x3,
  IMAPI_CD_SECTOR_MODE2FORM1 = 0x4,
  IMAPI_CD_SECTOR_MODE2FORM2 = 0x5,
  IMAPI_CD_SECTOR_MODE1RAW = 0x6,
  IMAPI_CD_SECTOR_MODE2FORM0RAW = 0x7,
  IMAPI_CD_SECTOR_MODE2FORM1RAW = 0x8,
  IMAPI_CD_SECTOR_MODE2FORM2RAW = 0x9
} IMAPI_CD_SECTOR_TYPE, *PIMAPI_CD_SECTOR_TYPE;