typedef enum _IMAPI_FORMAT2_RAW_CD_DATA_SECTOR_TYPE {
  IMAPI_FORMAT2_RAW_CD_SUBCODE_PQ_ONLY = 0x1,
  IMAPI_FORMAT2_RAW_CD_SUBCODE_IS_COOKED = 0x2,
  IMAPI_FORMAT2_RAW_CD_SUBCODE_IS_RAW = 0x3
} IMAPI_FORMAT2_RAW_CD_DATA_SECTOR_TYPE, *PIMAPI_FORMAT2_RAW_CD_DATA_SECTOR_TYPE;