typedef enum _IMAPI_FORMAT2_RAW_CD_WRITE_ACTION {
  IMAPI_FORMAT2_RAW_CD_WRITE_ACTION_UNKNOWN = 0,
  IMAPI_FORMAT2_RAW_CD_WRITE_ACTION_PREPARING = 0x1,
  IMAPI_FORMAT2_RAW_CD_WRITE_ACTION_WRITING = 0x2,
  IMAPI_FORMAT2_RAW_CD_WRITE_ACTION_FINISHING = 0x3
} IMAPI_FORMAT2_RAW_CD_WRITE_ACTION, *PIMAPI_FORMAT2_RAW_CD_WRITE_ACTION;