typedef enum _IMAPI_CD_TRACK_DIGITAL_COPY_SETTING {
  IMAPI_CD_TRACK_DIGITAL_COPY_PERMITTED = 0,
  IMAPI_CD_TRACK_DIGITAL_COPY_PROHIBITED = 0x1,
  IMAPI_CD_TRACK_DIGITAL_COPY_SCMS = 0x2
} IMAPI_CD_TRACK_DIGITAL_COPY_SETTING, *PIMAPI_CD_TRACK_DIGITAL_COPY_SETTING;