typedef enum _IMAPI_READ_TRACK_ADDRESS_TYPE {
  IMAPI_READ_TRACK_ADDRESS_TYPE_LBA = 0,
  IMAPI_READ_TRACK_ADDRESS_TYPE_TRACK = 1,
  IMAPI_READ_TRACK_ADDRESS_TYPE_SESSION = 2
} IMAPI_READ_TRACK_ADDRESS_TYPE, *PIMAPI_READ_TRACK_ADDRESS_TYPE;