typedef enum _IMAPI_MODE_PAGE_REQUEST_TYPE {
  IMAPI_MODE_PAGE_REQUEST_TYPE_CURRENT_VALUES = 0,
  IMAPI_MODE_PAGE_REQUEST_TYPE_CHANGEABLE_VALUES = 1,
  IMAPI_MODE_PAGE_REQUEST_TYPE_DEFAULT_VALUES = 2,
  IMAPI_MODE_PAGE_REQUEST_TYPE_SAVED_VALUES = 3
} IMAPI_MODE_PAGE_REQUEST_TYPE, *PIMAPI_MODE_PAGE_REQUEST_TYPE;