typedef enum _IMAPI_MEDIA_WRITE_PROTECT_STATE {
  IMAPI_WRITEPROTECTED_UNTIL_POWERDOWN = 0x1,
  IMAPI_WRITEPROTECTED_BY_CARTRIDGE = 0x2,
  IMAPI_WRITEPROTECTED_BY_MEDIA_SPECIFIC_REASON = 0x4,
  IMAPI_WRITEPROTECTED_BY_SOFTWARE_WRITE_PROTECT = 0x8,
  IMAPI_WRITEPROTECTED_BY_DISC_CONTROL_BLOCK = 0x10,
  IMAPI_WRITEPROTECTED_READ_ONLY_MEDIA = 0x4000
} IMAPI_MEDIA_WRITE_PROTECT_STATE, *PIMAPI_MEDIA_WRITE_PROTECT_STATE;