typedef enum FWPS_FIELDS_IPSEC_V6_ {
  FWPS_FIELD_IPSEC_V6_IP_PROTOCOL,
  FWPS_FIELD_IPSEC_V6_IP_LOCAL_ADDRESS,
  FWPS_FIELD_IPSEC_V6_IP_REMOTE_ADDRESS,
  FWPS_FIELD_IPSEC_V6_IP_LOCAL_PORT,
  FWPS_FIELD_IPSEC_V6_IP_REMOTE_PORT,
  FWPS_FIELD_IPSEC_V6_IP_LOCAL_INTERFACE,
  FWPS_FIELD_IPSEC_V6_PROFILE_ID,
  FWPS_FIELD_IPSEC_V6_IPSEC_SECURITY_REALM_ID,
  FWPS_FIELD_IPSEC_V6_MAX
} FWPS_FIELDS_IPSEC_V6;