typedef enum FWPS_FIELDS_STREAM_V4_ {
  FWPS_FIELD_STREAM_V4_IP_LOCAL_ADDRESS,
  FWPS_FIELD_STREAM_V4_IP_LOCAL_ADDRESS_TYPE,
  FWPS_FIELD_STREAM_V4_IP_REMOTE_ADDRESS,
  FWPS_FIELD_STREAM_V4_IP_LOCAL_PORT,
  FWPS_FIELD_STREAM_V4_IP_REMOTE_PORT,
  FWPS_FIELD_STREAM_V4_DIRECTION,
  FWPS_FIELD_STREAM_V4_FLAGS,
  FWPS_FIELD_STREAM_V4_COMPARTMENT_ID,
  FWPS_FIELD_STREAM_V4_MAX
} FWPS_FIELDS_STREAM_V4;