VOID USBPM_ASSIGN_CONNECTOR_POWER_LEVEL_PARAMS_INIT(
  [Out] PUSBPM_ASSIGN_CONNECTOR_POWER_LEVEL_PARAMS Params,
  [In]  USBC_POWER_ROLE                            PowerRole,
  [In]  USBPM_ASSIGN_POWER_LEVEL_PARAMS_FORMAT     Format
);