typedef enum ShellFolderViewOptions {
  SFVVO_SHOWALLOBJECTS = 0x1,
  SFVVO_SHOWEXTENSIONS = 0x2,
  SFVVO_SHOWCOMPCOLOR = 0x8,
  SFVVO_SHOWSYSFILES = 0x20,
  SFVVO_WIN95CLASSIC = 0x40,
  SFVVO_DOUBLECLICKINWEBVIEW = 0x80,
  SFVVO_DESKTOPHTML = 0x200
} ;