typedef enum _tagAUTOCOMPLETEOPTIONS {
  ACO_NONE = 0,
  ACO_AUTOSUGGEST = 0x1,
  ACO_AUTOAPPEND = 0x2,
  ACO_SEARCH = 0x4,
  ACO_FILTERPREFIXES = 0x8,
  ACO_USETAB = 0x10,
  ACO_UPDOWNKEYDROPSLIST = 0x20,
  ACO_RTLREADING = 0x40,
  ACO_WORD_FILTER = 0x80,
  ACO_NOPREFIXFILTERING = 0x100
} AUTOCOMPLETEOPTIONS;