typedef enum _MC_COLOR_TEMPERATURE {
  MC_COLOR_TEMPERATURE_UNKNOWN,
  MC_COLOR_TEMPERATURE_4000K,
  MC_COLOR_TEMPERATURE_5000K,
  MC_COLOR_TEMPERATURE_6500K,
  MC_COLOR_TEMPERATURE_7500K,
  MC_COLOR_TEMPERATURE_8200K,
  MC_COLOR_TEMPERATURE_9300K,
  MC_COLOR_TEMPERATURE_10000K,
  MC_COLOR_TEMPERATURE_11500K
} MC_COLOR_TEMPERATURE, *LPMC_COLOR_TEMPERATURE;