typedef enum _XBL_IDP_AUTH_TOKEN_STATUS {
  XBL_IDP_AUTH_TOKEN_STATUS_SUCCESS = 0,
  XBL_IDP_AUTH_TOKEN_STATUS_OFFLINE_SUCCESS,
  XBL_IDP_AUTH_TOKEN_STATUS_NO_ACCOUNT_SET,
  XBL_IDP_AUTH_TOKEN_STATUS_LOAD_MSA_ACCOUNT_FAILED,
  XBL_IDP_AUTH_TOKEN_STATUS_XBOX_VETO,
  XBL_IDP_AUTH_TOKEN_STATUS_MSA_INTERRUPT,
  XBL_IDP_AUTH_TOKEN_STATUS_OFFLINE_NO_CONSENT,
  XBL_IDP_AUTH_TOKEN_STATUS_VIEW_NOT_SET,
  XBL_IDP_AUTH_TOKEN_STATUS_UNKNOWN = 0xffffffff
} XBL_IDP_AUTH_TOKEN_STATUS;