typedef enum _WDI_TX_PAUSE_REASON {
  WDI_TX_PAUSE_REASON_NULL,
  WDI_TX_PAUSE_REASON_CREDIT,
  WDI_TX_PAUSE_REASON_PEER_CREATE,
  WDI_TX_PAUSE_REASON_PS,
  WDI_TX_PAUSE_REASON_IHV_START,
  WDI_TX_PAUSE_REASON_IHV_END
} WDI_TX_PAUSE_REASON;