typedef enum _PosDeviceControlType {
  _MinDeviceControlType,
  Invalid,
  GetProperty,
  SetProperty,
  ClaimDevice,
  ReleaseDevice,
  RetainDevice,
  RetrieveStatistics,
  ResetStatistics,
  UpdateStatistics,
  CheckHealth,
  GetDeviceBasics,
  BarcodeScannerInjectEvent,
  MsrRetrieveDeviceAuthentication,
  MsrAuthenticateDevice,
  MsrDeAuthenticateDevice,
  MsrUpdateKey,
  StartBarcodeScannerSoftwareTrigger,
  StopBarcodeScannerSoftwareTrigger,
  BarcodeScannerGetSymbologyAttributes,
  BarcodeScannerSetSymbologyAttributes,
  _MaxDeviceControlType
} PosDeviceControlType;