typedef struct _MSR_RETRIEVE_DEVICE_AUTHENTICATION_DATA {
  unsigned char KeySerialNumber[MSR_KEY_SERIAL_NUMBER_SIZE];
  unsigned char Challenge1[MSR_CHALLENGE_SIZE];
  unsigned char Challenge2[MSR_CHALLENGE_SIZE];
} MSR_RETRIEVE_DEVICE_AUTHENTICATION_DATA, *PMSR_RETRIEVE_DEVICE_AUTHENTICATION_DATA;