typedef enum tagWPC_ARGS_GAMESTARTEVENT {
  WPC_ARGS_GAMESTARTEVENT_APPID = 0,
  WPC_ARGS_GAMESTARTEVENT_INSTANCEID,
  WPC_ARGS_GAMESTARTEVENT_APPVERSION,
  WPC_ARGS_GAMESTARTEVENT_PATH,
  WPC_ARGS_GAMESTARTEVENT_RATING,
  WPC_ARGS_GAMESTARTEVENT_RATINGSYSTEM,
  WPC_ARGS_GAMESTARTEVENT_REASON,
  WPC_ARGS_GAMESTARTEVENT_DESCCOUNT,
  WPC_ARGS_GAMESTARTEVENT_DESCRIPTOR,
  WPC_ARGS_GAMESTARTEVENT_PID,
  WPC_ARGS_GAMESTARTEVENT_CARGS
} WPC_ARGS_GAMESTARTEVENT;