typedef enum tagWPC_ARGS_URLVISITEVENT {
  WPC_ARGS_URLVISITEVENT_URL = 0,
  WPC_ARGS_URLVISITEVENT_APPNAME,
  WPC_ARGS_URLVISITEVENT_VERSION,
  WPC_ARGS_URLVISITEVENT_REASON,
  WPC_ARGS_URLVISITEVENT_RATINGSYSTEMID,
  WPC_ARGS_URLVISITEVENT_CATCOUNT,
  WPC_ARGS_URLVISITEVENT_CATEGORY,
  WPC_ARGS_URLVISITEVENT_CARGS
} WPC_ARGS_URLVISITEVENT;