typedef enum tagWPC_ARGS_EMAILSENTEVENT {
  WPC_ARGS_EMAILSENTEVENT_SENDER = 0,
  WPC_ARGS_EMAILSENTEVENT_APPNAME,
  WPC_ARGS_EMAILSENTEVENT_APPVERSION,
  WPC_ARGS_EMAILSENTEVENT_SUBJECT,
  WPC_ARGS_EMAILSENTEVENT_REASON,
  WPC_ARGS_EMAILSENTEVENT_RECIPCOUNT,
  WPC_ARGS_EMAILSENTEVENT_RECIPIENT,
  WPC_ARGS_EMAILSENTEVENT_ATTACHCOUNT,
  WPC_ARGS_EMAILSENTEVENT_ATTACHMENTNAME,
  WPC_ARGS_EMAILSENTEVENT_EMAILACCOUNT,
  WPC_ARGS_EMAILSENTEVENT_CARGS
} WPC_ARGS_EMAILSENTEVENT;