typedef enum tagWPC_ARGS_MEDIAPLAYBACKEVENT {
  WPC_ARGS_MEDIAPLAYBACKEVENT_APPNAME = 0,
  WPC_ARGS_MEDIAPLAYBACKEVENT_APPVERSION,
  WPC_ARGS_MEDIAPLAYBACKEVENT_MEDIATYPE,
  WPC_ARGS_MEDIAPLAYBACKEVENT_PATH,
  WPC_ARGS_MEDIAPLAYBACKEVENT_TITLE,
  WPC_ARGS_MEDIAPLAYBACKEVENT_PML,
  WPC_ARGS_MEDIAPLAYBACKEVENT_ALBUM,
  WPC_ARGS_MEDIAPLAYBACKEVENT_EXPLICIT,
  WPC_ARGS_MEDIAPLAYBACKEVENT_REASON,
  WPC_ARGS_MEDIAPLAYBACKEVENT_CARGS
} WPC_ARGS_MEDIAPLAYBACKEVENT;