typedef enum tagWPC_ARGS_IMCONTACTEVENT {
  WPC_ARGS_IMCONTACTEVENT_APPNAME = 0,
  WPC_ARGS_IMCONTACTEVENT_APPVERSION,
  WPC_ARGS_IMCONTACTEVENT_ACCOUNTNAME,
  WPC_ARGS_IMCONTACTEVENT_OLDNAME,
  WPC_ARGS_IMCONTACTEVENT_OLDID,
  WPC_ARGS_IMCONTACTEVENT_NEWNAME,
  WPC_ARGS_IMCONTACTEVENT_NEWID,
  WPC_ARGS_IMCONTACTEVENT_REASON,
  WPC_ARGS_IMCONTACTEVENT_CARGS
} WPC_ARGS_IMCONTACTEVENT;