typedef enum tagWPC_ARGS_EMAILCONTACTEVENT {
  WPC_ARGS_EMAILCONTACTEVENT_APPNAME = 0,
  WPC_ARGS_EMAILCONTACTEVENT_APPVERSION,
  WPC_ARGS_EMAILCONTACTEVENT_OLDNAME,
  WPC_ARGS_EMAILCONTACTEVENT_OLDID,
  WPC_ARGS_EMAILCONTACTEVENT_NEWNAME,
  WPC_ARGS_EMAILCONTACTEVENT_NEWID,
  WPC_ARGS_EMAILCONTACTEVENT_REASON,
  WPC_ARGS_EMAILCONTACTEVENT_EMAILACCOUNT,
  WPC_ARGS_EMAILCONTACTEVENT_CARGS
} WPC_ARGS_EMAILCONTACTEVENT;