typedef enum tagWPCFLAG_IM_FEATURE {
  WPCFLAG_IM_FEATURE_NONE = 0x00,
  WPCFLAG_IM_FEATURE_VIDEO = 0x01,
  WPCFLAG_IM_FEATURE_AUDIO = 0x02,
  WPCFLAG_IM_FEATURE_GAME = 0x04,
  WPCFLAG_IM_FEATURE_SMS = 0x08,
  WPCFLAG_IM_FEATURE_FILESWAP = 0x10,
  WPCFLAG_IM_FEATURE_URLSWAP = 0x20,
  WPCFLAG_IM_FEATURE_SENDING = 0x80000000,
  WPCFLAG_IM_FEATURE_ALL = 0xFFFFFFFF
} WPCFLAG_IM_FEATURE;