typedef enum tagWPC_ARGS_MEDIADOWNLOADEVENT {
  WPC_ARGS_MEDIADOWNLOADEVENT_APPNAME = 0,
  WPC_ARGS_MEDIADOWNLOADEVENT_APPVERSION,
  WPC_ARGS_MEDIADOWNLOADEVENT_MEDIATYPE,
  WPC_ARGS_MEDIADOWNLOADEVENT_PATH,
  WPC_ARGS_MEDIADOWNLOADEVENT_TITLE,
  WPC_ARGS_MEDIADOWNLOADEVENT_PML,
  WPC_ARGS_MEDIADOWNLOADEVENT_ALBUM,
  WPC_ARGS_MEDIADOWNLOADEVENT_EXPLICIT,
  WPC_ARGS_MEDIADOWNLOADEVENT_REASON,
  WPC_ARGS_MEDIADOWNLOADEVENT_CARGS
} WPC_ARGS_MEDIADOWNLOADEVENT;