typedef enum tagWPC_ARGS_FILEDOWNLOADEVENT {
  WPC_ARGS_FILEDOWNLOADEVENT_URL = 0,
  WPC_ARGS_FILEDOWNLOADEVENT_APPNAME,
  WPC_ARGS_FILEDOWNLOADEVENT_VERSION,
  WPC_ARGS_FILEDOWNLOADEVENT_BLOCKED,
  WPC_ARGS_FILEDOWNLOADEVENT_PATH,
  WPC_ARGS_FILEDOWNLOADEVENT_CARGS
} WPC_ARGS_FILEDOWNLOADEVENT;