typedef enum tagWPC_ARGS_IMFEATUREEVENT {
  WPC_ARGS_IMFEATUREEVENT_APPNAME = 0,
  WPC_ARGS_IMFEATUREEVENT_APPVERSION,
  WPC_ARGS_IMFEATUREEVENT_ACCOUNTNAME,
  WPC_ARGS_IMFEATUREEVENT_CONVID,
  WPC_ARGS_IMFEATUREEVENT_MEDIATYPE,
  WPC_ARGS_IMFEATUREEVENT_REASON,
  WPC_ARGS_IMFEATUREEVENT_RECIPCOUNT,
  WPC_ARGS_IMFEATUREEVENT_RECIPIENT,
  WPC_ARGS_IMFEATUREEVENT_SENDER,
  WPC_ARGS_IMFEATUREEVENT_SENDERIP,
  WPC_ARGS_IMFEATUREEVENT_DATA,
  WPC_ARGS_IMFEATUREEVENT_CARGS
} WPC_ARGS_IMFEATUREEVENT;