typedef enum tagWPC_ARGS_SAFERAPPBLOCKED {
  WPC_ARGS_SAFERAPPBLOCKED_TIMESTAMP = 0,
  WPC_ARGS_SAFERAPPBLOCKED_USERID,
  WPC_ARGS_SAFERAPPBLOCKED_PATH,
  WPC_ARGS_SAFERAPPBLOCKED_RULEID,
  WPC_ARGS_SAFERAPPBLOCKED_CARGS
} WPC_ARGS_SAFERAPPBLOCKED;