typedef enum tagWPC_ARGS_CUSTOMEVENT {
  WPC_ARGS_CUSTOMEVENT_PUBLISHER = 0,
  WPC_ARGS_CUSTOMEVENT_APPNAME,
  WPC_ARGS_CUSTOMEVENT_APPVERSION,
  WPC_ARGS_CUSTOMEVENT_EVENT,
  WPC_ARGS_CUSTOMEVENT_VALUE1,
  WPC_ARGS_CUSTOMEVENT_VALUE2,
  WPC_ARGS_CUSTOMEVENT_VALUE3,
  WPC_ARGS_CUSTOMEVENT_BLOCKED,
  WPC_ARGS_CUSTOMEVENT_REASON,
  WPC_ARGS_CUSTOMEVENT_CARGS
} WPC_ARGS_CUSTOMEVENT;