typedef enum tagWPC_MEDIA_TYPE {
  WPC_MEDIA_TYPE_OTHER = 0,
  WPC_MEDIA_TYPE_DVD,
  WPC_MEDIA_TYPE_RECORDED_TV,
  WPC_MEDIA_TYPE_AUDIO_FILE,
  WPC_MEDIA_TYPE_CD_AUDIO,
  WPC_MEDIA_TYPE_VIDEO_FILE,
  WPC_MEDIA_TYPE_PICTURE_FILE,
  WPC_MEDIA_TYPE_MAX
} WPC_MEDIA_TYPE;