typedef enum tagWPC_ARGS_SETTINGSCHANGEEVENT {
  WPC_ARGS_SETTINGSCHANGEEVENT_CLASS = 0,
  WPC_ARGS_SETTINGSCHANGEEVENT_SETTING,
  WPC_ARGS_SETTINGSCHANGEEVENT_OWNER,
  WPC_ARGS_SETTINGSCHANGEEVENT_OLDVAL,
  WPC_ARGS_SETTINGSCHANGEEVENT_NEWVAL,
  WPC_ARGS_SETTINGSCHANGEEVENT_REASON,
  WPC_ARGS_SETTINGSCHANGEEVENT_OPTIONAL,
  WPC_ARGS_SETTINGSCHANGEEVENT_CARGS
} WPC_ARGS_SETTINGSCHANGEEVENT;