typedef enum __MIDL___MIDL_itf_winsatcominterfacei_0000_0000_0002 {
  WINSAT_ASSESSMENT_STATE_MIN = 0,
  WINSAT_ASSESSMENT_STATE_UNKNOWN = 0,
  WINSAT_ASSESSMENT_STATE_VALID = 1,
  WINSAT_ASSESSMENT_STATE_INCOHERENT_WITH_HARDWARE = 2,
  WINSAT_ASSESSMENT_STATE_NOT_AVAILABLE = 3,
  WINSAT_ASSESSMENT_STATE_INVALID = 4,
  WINSAT_ASSESSMENT_STATE_MAX = 4
} WINSAT_ASSESSMENT_STATE;