typedef enum __MIDL___MIDL_itf_winsatcominterfacei_0000_0000_0003 {
  WINSAT_ASSESSMENT_MEMORY = 0,
  WINSAT_ASSESSMENT_CPU = 1,
  WINSAT_ASSESSMENT_DISK = 2,
  WINSAT_ASSESSMENT_D3D = 3,
  WINSAT_ASSESSMENT_GRAPHICS = 4
} WINSAT_ASSESSMENT_TYPE;