typedef enum {
  WSL_DISTRIBUTION_FLAGS_NONE = 0x0,
  WSL_DISTRIBUTION_FLAGS_ENABLE_INTEROP = 0x1,
  WSL_DISTRIBUTION_FLAGS_APPEND_NT_PATH = 0x2,
  WSL_DISTRIBUTION_FLAGS_ENABLE_DRIVE_MOUNTING = 0x4
} WSL_DISTRIBUTION_FLAGS;