typedef struct _IPSEC_OFFLOAD_V2_DELETE_SA {
  NDIS_OBJECT_HEADER          Header;
  PIPSEC_OFFLOAD_V2_DELETE_SA Next;
  NDIS_HANDLE                 OffloadHandle;
} IPSEC_OFFLOAD_V2_DELETE_SA, *PIPSEC_OFFLOAD_V2_DELETE_SA;