typedef struct _NDIS_MINIPORT_ADAPTER_NDK_ATTRIBUTES {
  NDIS_OBJECT_HEADER     Header;
  BOOLEAN                Enabled;
  PNDIS_NDK_CAPABILITIES NdkCapabilities;
} NDIS_MINIPORT_ADAPTER_NDK_ATTRIBUTES, *PNDIS_MINIPORT_ADAPTER_NDK_ATTRIBUTES;