typedef enum __MIDL___MIDL_itf_rdpencomapi_0000_0000_0009 {
  RDPSRAPI_MOUSE_BUTTON_BUTTON1 = 0,
  RDPSRAPI_MOUSE_BUTTON_BUTTON2 = 1,
  RDPSRAPI_MOUSE_BUTTON_BUTTON3 = 2,
  RDPSRAPI_MOUSE_BUTTON_XBUTTON1 = 3,
  RDPSRAPI_MOUSE_BUTTON_XBUTTON2 = 4,
  RDPSRAPI_MOUSE_BUTTON_XBUTTON3 = 5
} RDPSRAPI_MOUSE_BUTTON_TYPE;