typedef enum __MIDL___MIDL_itf_rdpencomapi_0000_0000_0011 {
  RDPSRAPI_KBD_SYNC_FLAG_SCROLL_LOCK = 1,
  RDPSRAPI_KBD_SYNC_FLAG_NUM_LOCK = 2,
  RDPSRAPI_KBD_SYNC_FLAG_CAPS_LOCK = 4,
  RDPSRAPI_KBD_SYNC_FLAG_KANA_LOCK = 8
} RDPSRAPI_KBD_SYNC_FLAG;