typedef enum __MIDL___MIDL_itf_rdpencomapi_0000_0000_0001 {
  CTRL_LEVEL_MIN = 0,
  CTRL_LEVEL_INVALID = 0,
  CTRL_LEVEL_NONE = 1,
  CTRL_LEVEL_VIEW = 2,
  CTRL_LEVEL_INTERACTIVE = 3,
  CTRL_LEVEL_REQCTRL_VIEW = 4,
  CTRL_LEVEL_REQCTRL_INTERACTIVE = 5,
  CTRL_LEVEL_MAX = 5
} CTRL_LEVEL;