typedef enum {
  rsna_akm_none = AKM_FROM_TYPE(RSNA_OUI_PREFIX, 0),
  rsna_akm_1x = AKM_FROM_TYPE(RSNA_OUI_PREFIX, 1),
  rsna_akm_psk = AKM_FROM_TYPE(RSNA_OUI_PREFIX, 2),
  rsna_akm_ft_1x_sha256 = AKM_FROM_TYPE(RSNA_OUI_PREFIX, 3),
  rsna_akm_ft_psk_sha256 = AKM_FROM_TYPE(RSNA_OUI_PREFIX, 4),
  rsna_akm_1x_sha256 = AKM_FROM_TYPE(RSNA_OUI_PREFIX, 5),
  rsna_akm_psk_sha256 = AKM_FROM_TYPE(RSNA_OUI_PREFIX, 6),
  rsna_akm_tdls_sha256 = AKM_FROM_TYPE(RSNA_OUI_PREFIX, 7),
  rsna_akm_sae_pmk256 = AKM_FROM_TYPE(RSNA_OUI_PREFIX, 8),
  rsna_akm_ft_sae_pmk256 = AKM_FROM_TYPE(RSNA_OUI_PREFIX, 9),
  rsna_akm_peerkey_sha256 = AKM_FROM_TYPE(RSNA_OUI_PREFIX, 10),
  rsna_akm_1x_suite_b_sha256 = AKM_FROM_TYPE(RSNA_OUI_PREFIX, 11),
  rsna_akm_1x_suite_b_sha384 = AKM_FROM_TYPE(RSNA_OUI_PREFIX, 12),
  rsna_akm_ft_1x_sha384_cmp_256 = AKM_FROM_TYPE(RSNA_OUI_PREFIX, 13),
  rsna_akm_fils_1x_sha256 = AKM_FROM_TYPE(RSNA_OUI_PREFIX, 14),
  rsna_akm_fils_1x_sha384 = AKM_FROM_TYPE(RSNA_OUI_PREFIX, 15),
  rsna_akm_ft_fils_1x_sha256 = AKM_FROM_TYPE(RSNA_OUI_PREFIX, 16),
  rsna_akm_ft_fils_sha384 = AKM_FROM_TYPE(RSNA_OUI_PREFIX, 17),
  rsna_akm_owe = AKM_FROM_TYPE(RSNA_OUI_PREFIX, 18),
  rsna_akm_ft_psk_sha384 = AKM_FROM_TYPE(RSNA_OUI_PREFIX, 19),
  rsna_akm_psk_sha384 = AKM_FROM_TYPE(RSNA_OUI_PREFIX, 20),
  rsna_akm_ft_1x_sha384 = AKM_FROM_TYPE(RSNA_OUI_PREFIX, 22),
  rsna_akm_1x_sha384 = AKM_FROM_TYPE(RSNA_OUI_PREFIX, 23),
  rsna_akm_sae_pmk384 = AKM_FROM_TYPE(RSNA_OUI_PREFIX, 24),
  rsna_akm_ft_sae_pmk384 = AKM_FROM_TYPE(RSNA_OUI_PREFIX, 25),
  rsna_akm_max = rsna_akm_ft_sae_pmk384
} RSNA_AKM_SUITE;