typedef enum _SCO_RETRANSMISSION_EFFORT {
  SCO_RETRANSMISSION_NONE,
  SCO_RETRANSMISSION_MIN1_POWER,
  SCO_RETRANSMISSION_MIN1_QUALITY,
  SCO_RETRANSMISSION_DONT_CARE
} SCO_RETRANSMISSION_EFFORT, *PSCO_RETRANSMISSION_EFFORT;