typedef enum _ACL_MODE {
  ACL_MODE_ACTIVE,
  ACL_MODE_HOLD,
  ACL_MODE_SNIFF,
  ACL_MODE_PARK,
  ACL_MODE_ENTER_ACTIVE,
  ACL_MODE_ENTER_HOLD,
  ACL_MODE_ENTER_SNIFF,
  ACL_MODE_ENTER_PARK,
  ACL_DISCONNECTED
} ACL_MODE;