typedef struct _L2CAP_RETRANSMISSION_AND_FLOW_CONTROL {
  UCHAR  Mode;
  UCHAR  TxWindowSize;
  UCHAR  MaxTransmit;
  USHORT RetransmissionTO;
  USHORT MonitorTO;
  USHORT MaxPDUSize;
} L2CAP_RETRANSMISSION_AND_FLOW_CONTROL, *PL2CAP_RETRANSMISSION_AND_FLOW_CONTROL;