typedef struct _ENCRYPTION_CERTIFICATE_HASH_LIST {
  DWORD                        nCert_Hash;
  PENCRYPTION_CERTIFICATE_HASH *pUsers;
} ENCRYPTION_CERTIFICATE_HASH_LIST, *PENCRYPTION_CERTIFICATE_HASH_LIST;