typedef struct {
  ULONG  Size;
  ULONG  Version;
  double HorizontalAccuracy;
  double HorizontalErrorMajorAxis;
  double HorizontalErrorMinorAxis;
  double HorizontalErrorAngle;
  double HeadingAccuracy;
  double AltitudeAccuracy;
  double SpeedAccuracy;
  ULONG  HorizontalConfidence;
  ULONG  HeadingConfidence;
  ULONG  AltitudeConfidence;
  ULONG  SpeedConfidence;
  double PositionDilutionOfPrecision;
  double HorizontalDilutionOfPrecision;
  double VerticalDilutionOfPrecision;
  double GeometricDilutionOfPrecision;
  double TimeDilutionOfPrecision;
} GNSS_FIXDATA_ACCURACY_2, *PGNSS_FIXDATA_ACCURACY_2;