typedef enum CIM_MOUNT_IMAGE_FLAGS {
  CIM_MOUNT_IMAGE_NONE = 0x00000000,
  CIM_MOUNT_CHILD_ONLY = 0x00000001,
  CIM_MOUNT_ENABLE_DAX,
  CIM_MOUNT_CACHE_FILES,
  CIM_MOUNT_CACHE_REGIONS,
  CIM_MOUNT_BLOCK_CIM
} ;