typedef enum tagCRMFLAGS {
  CRMFLAG_FORGETTARGET = 0x1,
  CRMFLAG_WRITTENDURINGPREPARE = 0x2,
  CRMFLAG_WRITTENDURINGCOMMIT = 0x4,
  CRMFLAG_WRITTENDURINGABORT = 0x8,
  CRMFLAG_WRITTENDURINGRECOVERY = 0x10,
  CRMFLAG_WRITTENDURINGREPLAY = 0x20,
  CRMFLAG_REPLAYINPROGRESS = 0x40
} CRMFLAGS;