typedef enum _GetAppTrackerDataFlags {
  GATD_INCLUDE_PROCESS_EXE_NAME = 0x1,
  GATD_INCLUDE_LIBRARY_APPS = 0x2,
  GATD_INCLUDE_SWC = 0x4,
  GATD_INCLUDE_CLASS_NAME = 0x8,
  GATD_INCLUDE_APPLICATION_NAME = 0x10
} GetAppTrackerDataFlags;