typedef enum tagCRMREGFLAGS {
  CRMREGFLAG_PREPAREPHASE = 0x1,
  CRMREGFLAG_COMMITPHASE = 0x2,
  CRMREGFLAG_ABORTPHASE = 0x4,
  CRMREGFLAG_ALLPHASES = 0x7,
  CRMREGFLAG_FAILIFINDOUBTSREMAIN = 0x10
} CRMREGFLAGS;