typedef struct _CHARGINGSTATUSCOMPLETE {
  POWERSOURCESTATUS UsbFnStatus;
  POWERSOURCESTATUS UsbTypeCStatus;
  POWERSOURCESTATUS KDStatus;
  POWERSOURCESTATUS WirelessStatus;
  ULONG             ForceDisableChargingRefCount;
} CHARGINGSTATUSCOMPLETE, *PCHARGINGSTATUSCOMPLETE;