typedef enum _RDV_TASK_STATUS {
  RDV_TASK_STATUS_UNKNOWN = 0,
  RDV_TASK_STATUS_SEARCHING,
  RDV_TASK_STATUS_DOWNLOADING,
  RDV_TASK_STATUS_APPLYING,
  RDV_TASK_STATUS_REBOOTING,
  RDV_TASK_STATUS_REBOOTED,
  RDV_TASK_STATUS_SUCCESS,
  RDV_TASK_STATUS_FAILED,
  RDV_TASK_STATUS_TIMEOUT
} RDV_TASK_STATUS;