typedef enum _TARGET_STATE {
  TARGET_UNKNOWN = 0x1,
  TARGET_INITIALIZING,
  TARGET_RUNNING,
  TARGET_DOWN,
  TARGET_HIBERNATED,
  TARGET_CHECKED_OUT,
  TARGET_STOPPED,
  TARGET_INVALID,
  TARGET_STARTING,
  TARGET_STOPPING,
  TARGET_MAXSTATE
} TARGET_STATE;