typedef enum _TARGET_CHANGE_TYPE {
  TARGET_CHANGE_UNSPEC = 0x1,
  TARGET_EXTERNALIP_CHANGED = 0x2,
  TARGET_INTERNALIP_CHANGED = 0x4,
  TARGET_JOINED = 0x8,
  TARGET_REMOVED = 0x10,
  TARGET_STATE_CHANGED = 0x20,
  TARGET_IDLE = 0x40,
  TARGET_PENDING = 0x80,
  TARGET_INUSE = 0x100,
  TARGET_PATCH_STATE_CHANGED = 0x200,
  TARGET_FARM_MEMBERSHIP_CHANGED = 0x400
} TARGET_CHANGE_TYPE;