typedef enum _TSSESSION_STATE {
  STATE_INVALID = -1,
  STATE_ACTIVE,
  STATE_CONNECTED,
  STATE_CONNECTQUERY,
  STATE_SHADOW,
  STATE_DISCONNECTED,
  STATE_IDLE,
  STATE_LISTEN,
  STATE_RESET,
  STATE_DOWN,
  STATE_INIT,
  STATE_MAX
} TSSESSION_STATE;