typedef enum _WDF_DISPATCH_IRP_TO_IO_QUEUE_FLAGS {
  WDF_DISPATCH_IRP_TO_IO_QUEUE_NO_FLAGS = 0x00000000,
  WDF_DISPATCH_IRP_TO_IO_QUEUE_INVOKE_INCALLERCTX_CALLBACK = 0x00000001,
  WDF_DISPATCH_IRP_TO_IO_QUEUE_PREPROCESSED_IRP = 0x00000002
} WDF_DISPATCH_IRP_TO_IO_QUEUE_FLAGS;