typedef enum FAX_ACCESS_RIGHTS_ENUM {
  farSUBMIT_LOW = 0x1,
  farSUBMIT_NORMAL = 0x2,
  farSUBMIT_HIGH = 0x4,
  farQUERY_JOBS = 0x8,
  farMANAGE_JOBS = 0x10,
  farQUERY_CONFIG = 0x20,
  farMANAGE_CONFIG = 0x40,
  farQUERY_IN_ARCHIVE = 0x80,
  farMANAGE_IN_ARCHIVE = 0x100,
  farQUERY_OUT_ARCHIVE = 0x200,
  farMANAGE_OUT_ARCHIVE = 0x400
} ;