typedef enum {
  AUTHZ_SID_OPERATION_NONE = 0,
  AUTHZ_SID_OPERATION_REPLACE_ALL,
  AUTHZ_SID_OPERATION_ADD,
  AUTHZ_SID_OPERATION_DELETE,
  AUTHZ_SID_OPERATION_REPLACE
} AUTHZ_SID_OPERATION, *PAUTHZ_SID_OPERATION;