typedef struct _AUTHZ_SECURITY_ATTRIBUTES_INFORMATION {
  USHORT Version;
  USHORT Reserved;
  ULONG  AttributeCount;
  union {
    PAUTHZ_SECURITY_ATTRIBUTE_V1 pAttributeV1;
  } Attribute;
} AUTHZ_SECURITY_ATTRIBUTES_INFORMATION, *PAUTHZ_SECURITY_ATTRIBUTES_INFORMATION;