typedef struct _NTMS_DRIVETYPEINFORMATIONA {
  CHAR  szVendor[NTMS_VENDORNAME_LENGTH];
  CHAR  szProduct[NTMS_PRODUCTNAME_LENGTH];
  DWORD NumberOfHeads;
  DWORD DeviceType;
} NTMS_DRIVETYPEINFORMATIONA;