typedef struct _NTMS_DRIVETYPEINFORMATIONW {
  WCHAR szVendor[NTMS_VENDORNAME_LENGTH];
  WCHAR szProduct[NTMS_PRODUCTNAME_LENGTH];
  DWORD NumberOfHeads;
  DWORD DeviceType;
} NTMS_DRIVETYPEINFORMATIONW;