typedef enum CF_OPERATION_TRANSFER_PLACEHOLDERS_FLAGS {
  CF_OPERATION_TRANSFER_PLACEHOLDERS_FLAG_NONE = 0x00000000,
  CF_OPERATION_TRANSFER_PLACEHOLDERS_FLAG_STOP_ON_ERROR = 0x00000001,
  CF_OPERATION_TRANSFER_PLACEHOLDERS_FLAG_DISABLE_ON_DEMAND_POPULATION = 0x00000002
} ;