typedef enum CF_OPERATION_TYPE {
  CF_OPERATION_TYPE_TRANSFER_DATA,
  CF_OPERATION_TYPE_RETRIEVE_DATA,
  CF_OPERATION_TYPE_ACK_DATA,
  CF_OPERATION_TYPE_RESTART_HYDRATION,
  CF_OPERATION_TYPE_TRANSFER_PLACEHOLDERS,
  CF_OPERATION_TYPE_ACK_DEHYDRATE,
  CF_OPERATION_TYPE_ACK_DELETE,
  CF_OPERATION_TYPE_ACK_RENAME
} ;