typedef enum CF_UPDATE_FLAGS {
  CF_UPDATE_FLAG_NONE,
  CF_UPDATE_FLAG_VERIFY_IN_SYNC,
  CF_UPDATE_FLAG_MARK_IN_SYNC,
  CF_UPDATE_FLAG_DEHYDRATE,
  CF_UPDATE_FLAG_ENABLE_ON_DEMAND_POPULATION,
  CF_UPDATE_FLAG_DISABLE_ON_DEMAND_POPULATION,
  CF_UPDATE_FLAG_REMOVE_FILE_IDENTITY,
  CF_UPDATE_FLAG_CLEAR_IN_SYNC,
  CF_UPDATE_FLAG_REMOVE_PROPERTY,
  CF_UPDATE_FLAG_PASSTHROUGH_FS_METADATA,
  CF_UPDATE_FLAG_ALWAYS_FULL,
  CF_UPDATE_FLAG_ALLOW_PARTIAL
} ;