typedef enum _MPRAPI_OBJECT_TYPE {
  MPRAPI_OBJECT_TYPE_RAS_CONNECTION_OBJECT = 1,
  MPRAPI_OBJECT_TYPE_MPR_SERVER_OBJECT = 2,
  MPRAPI_OBJECT_TYPE_MPR_SERVER_SET_CONFIG_OBJECT = 3,
  MPRAPI_OBJECT_TYPE_AUTH_VALIDATION_OBJECT = 4,
  MPRAPI_OBJECT_TYPE_UPDATE_CONNECTION_OBJECT = 5,
  MPRAPI_OBJECT_TYPE_IF_CUSTOM_CONFIG_OBJECT = 6
} MPRAPI_OBJECT_TYPE, *PMPRAPI_OBJECT_TYPE;