typedef enum _RAS_PORT_CONDITION {
  RAS_PORT_NON_OPERATIONAL,
  RAS_PORT_DISCONNECTED,
  RAS_PORT_CALLING_BACK,
  RAS_PORT_LISTENING,
  RAS_PORT_AUTHENTICATING,
  RAS_PORT_AUTHENTICATED,
  RAS_PORT_INITIALIZING
} RAS_PORT_CONDITION;