typedef enum _ROUTER_INTERFACE_TYPE {
  ROUTER_IF_TYPE_CLIENT,
  ROUTER_IF_TYPE_HOME_ROUTER,
  ROUTER_IF_TYPE_FULL_ROUTER,
  ROUTER_IF_TYPE_DEDICATED,
  ROUTER_IF_TYPE_INTERNAL,
  ROUTER_IF_TYPE_LOOPBACK,
  ROUTER_IF_TYPE_TUNNEL1,
  ROUTER_IF_TYPE_DIALOUT,
  ROUTER_IF_TYPE_MAX
} ROUTER_INTERFACE_TYPE;