typedef struct _BLUETOOTH_GATT_VALUE_CHANGED_EVENT_REGISTRATION {
  USHORT                     NumCharacteristics;
  BTH_LE_GATT_CHARACTERISTIC Characteristics[1];
} BLUETOOTH_GATT_VALUE_CHANGED_EVENT_REGISTRATION, *PBLUETOOTH_GATT_VALUE_CHANGED_EVENT_REGISTRATION;