VOID UCMTCPCI_PORT_CONTROLLER_CONFIG_INIT(
  [out] PUCMTCPCI_PORT_CONTROLLER_CONFIG         Config,
  [in]  PUCMTCPCI_PORT_CONTROLLER_IDENTIFICATION Identification,
  [in]  PUCMTCPCI_PORT_CONTROLLER_CAPABILITIES   Capabilities
);