typedef struct _UCMTCPCI_PORT_CONTROLLER_CONFIG {
  ULONG                                    Size;
  PUCMTCPCI_PORT_CONTROLLER_IDENTIFICATION Identification;
  PUCMTCPCI_PORT_CONTROLLER_CAPABILITIES   Capabilities;
} UCMTCPCI_PORT_CONTROLLER_CONFIG, *PUCMTCPCI_PORT_CONTROLLER_CONFIG;