typedef struct _UCMTCPCI_PORT_CONTROLLER_IDENTIFICATION {
  ULONG  Size;
  UINT16 VendorId;
  UINT16 ProductId;
  UINT16 DeviceId;
  UINT16 TypeCRevisionInBcd;
  UINT16 PDRevisionAndVersionInBcd;
  UINT16 PDInterfaceRevisionAndVersionInBcd;
} UCMTCPCI_PORT_CONTROLLER_IDENTIFICATION, *PUCMTCPCI_PORT_CONTROLLER_IDENTIFICATION;