typedef struct _UCMTCPCI_PORT_CONTROLLER_CAPABILITIES {
  ULONG                                                 Size;
  BOOLEAN                                               IsPowerDeliveryCapable;
  UCMTCPCI_PORT_CONTROLLER_DEVICE_CAPABILITIES_1        DeviceCapabilities1;
  UCMTCPCI_PORT_CONTROLLER_DEVICE_CAPABILITIES_2        DeviceCapabilities2;
  UCMTCPCI_PORT_CONTROLLER_STANDARD_INPUT_CAPABILITIES  StandardInputCapabilities;
  UCMTCPCI_PORT_CONTROLLER_STANDARD_OUTPUT_CAPABILITIES StandardOutputCapabilities;
} UCMTCPCI_PORT_CONTROLLER_CAPABILITIES, *PUCMTCPCI_PORT_CONTROLLER_CAPABILITIES;