typedef enum _VSS_FILE_SPEC_BACKUP_TYPE {
  VSS_FSBT_FULL_BACKUP_REQUIRED = 0x1,
  VSS_FSBT_DIFFERENTIAL_BACKUP_REQUIRED = 0x2,
  VSS_FSBT_INCREMENTAL_BACKUP_REQUIRED = 0x4,
  VSS_FSBT_LOG_BACKUP_REQUIRED = 0x8,
  VSS_FSBT_FULL_SNAPSHOT_REQUIRED = 0x100,
  VSS_FSBT_DIFFERENTIAL_SNAPSHOT_REQUIRED = 0x200,
  VSS_FSBT_INCREMENTAL_SNAPSHOT_REQUIRED = 0x400,
  VSS_FSBT_LOG_SNAPSHOT_REQUIRED = 0x800,
  VSS_FSBT_CREATED_DURING_BACKUP = 0x10000,
  VSS_FSBT_ALL_BACKUP_REQUIRED = 0xf,
  VSS_FSBT_ALL_SNAPSHOT_REQUIRED = 0xf00
} VSS_FILE_SPEC_BACKUP_TYPE, *PVSS_FILE_SPEC_BACKUP_TYPE;