typedef enum _VSS_APPLICATION_LEVEL {
  VSS_APP_UNKNOWN = 0,
  VSS_APP_SYSTEM = 1,
  VSS_APP_BACK_END = 2,
  VSS_APP_FRONT_END = 3,
  VSS_APP_SYSTEM_RM = 4,
  VSS_APP_AUTO = -1
} VSS_APPLICATION_LEVEL, *PVSS_APPLICATION_LEVEL;