typedef enum _VSS_SNAPSHOT_STATE {
  VSS_SS_UNKNOWN = 0,
  VSS_SS_PREPARING,
  VSS_SS_PROCESSING_PREPARE,
  VSS_SS_PREPARED,
  VSS_SS_PROCESSING_PRECOMMIT,
  VSS_SS_PRECOMMITTED,
  VSS_SS_PROCESSING_COMMIT,
  VSS_SS_COMMITTED,
  VSS_SS_PROCESSING_POSTCOMMIT,
  VSS_SS_PROCESSING_PREFINALCOMMIT,
  VSS_SS_PREFINALCOMMITTED,
  VSS_SS_PROCESSING_POSTFINALCOMMIT,
  VSS_SS_CREATED,
  VSS_SS_ABORTED,
  VSS_SS_DELETED,
  VSS_SS_POSTCOMMITTED,
  VSS_SS_COUNT
} VSS_SNAPSHOT_STATE, *PVSS_SNAPSHOT_STATE;