typedef enum _VSS_OBJECT_TYPE {
  VSS_OBJECT_UNKNOWN = 0,
  VSS_OBJECT_NONE,
  VSS_OBJECT_SNAPSHOT_SET,
  VSS_OBJECT_SNAPSHOT,
  VSS_OBJECT_PROVIDER,
  VSS_OBJECT_TYPE_COUNT
} VSS_OBJECT_TYPE, *PVSS_OBJECT_TYPE;