typedef enum _VSS_WRITER_STATE {
  VSS_WS_UNKNOWN = 0,
  VSS_WS_STABLE,
  VSS_WS_WAITING_FOR_FREEZE,
  VSS_WS_WAITING_FOR_THAW,
  VSS_WS_WAITING_FOR_POST_SNAPSHOT,
  VSS_WS_WAITING_FOR_BACKUP_COMPLETE,
  VSS_WS_FAILED_AT_IDENTIFY,
  VSS_WS_FAILED_AT_PREPARE_BACKUP,
  VSS_WS_FAILED_AT_PREPARE_SNAPSHOT,
  VSS_WS_FAILED_AT_FREEZE,
  VSS_WS_FAILED_AT_THAW,
  VSS_WS_FAILED_AT_POST_SNAPSHOT,
  VSS_WS_FAILED_AT_BACKUP_COMPLETE,
  VSS_WS_FAILED_AT_PRE_RESTORE,
  VSS_WS_FAILED_AT_POST_RESTORE,
  VSS_WS_FAILED_AT_BACKUPSHUTDOWN,
  VSS_WS_COUNT
} VSS_WRITER_STATE, *PVSS_WRITER_STATE;