typedef enum _VSS_HARDWARE_OPTIONS {
  VSS_BREAKEX_FLAG_MASK_LUNS = 0x1,
  VSS_BREAKEX_FLAG_MAKE_READ_WRITE = 0x2,
  VSS_BREAKEX_FLAG_REVERT_IDENTITY_ALL = 0x4,
  VSS_BREAKEX_FLAG_REVERT_IDENTITY_NONE = 0x8,
  VSS_ONLUNSTATECHANGE_NOTIFY_READ_WRITE = 0x100,
  VSS_ONLUNSTATECHANGE_NOTIFY_LUN_PRE_RECOVERY = 0x200,
  VSS_ONLUNSTATECHANGE_NOTIFY_LUN_POST_RECOVERY = 0x400,
  VSS_ONLUNSTATECHANGE_DO_MASK_LUNS = 0x800
} VSS_HARDWARE_OPTIONS, *PVSS_HARDWARE_OPTIONS;