typedef enum _VSS_SNAPSHOT_CONTEXT {
  VSS_CTX_BACKUP = 0,
  VSS_CTX_FILE_SHARE_BACKUP,
  VSS_CTX_NAS_ROLLBACK,
  VSS_CTX_APP_ROLLBACK,
  VSS_CTX_CLIENT_ACCESSIBLE,
  VSS_CTX_CLIENT_ACCESSIBLE_WRITERS,
  VSS_CTX_ALL = 0xffffffff
} VSS_SNAPSHOT_CONTEXT, *PVSS_SNAPSHOT_CONTEXT;