typedef enum IPSEC_PFS_GROUP_ {
  IPSEC_PFS_NONE = 0,
  IPSEC_PFS_1,
  IPSEC_PFS_2,
  IPSEC_PFS_2048,
  IPSEC_PFS_14,
  IPSEC_PFS_ECP_256,
  IPSEC_PFS_ECP_384,
  IPSEC_PFS_MM,
  IPSEC_PFS_24,
  IPSEC_PFS_MAX
} IPSEC_PFS_GROUP;