typedef enum IPSEC_TRANSFORM_TYPE_ {
  IPSEC_TRANSFORM_AH = 1,
  IPSEC_TRANSFORM_ESP_AUTH,
  IPSEC_TRANSFORM_ESP_CIPHER,
  IPSEC_TRANSFORM_ESP_AUTH_AND_CIPHER,
  IPSEC_TRANSFORM_ESP_AUTH_FW,
  IPSEC_TRANSFORM_TYPE_MAX
} IPSEC_TRANSFORM_TYPE;