typedef enum _WCM_CONNECTION_COST_SOURCE {
  WCM_CONNECTION_COST_SOURCE_DEFAULT = 0,
  WCM_CONNECTION_COST_SOURCE_GP = 1,
  WCM_CONNECTION_COST_SOURCE_USER = 2,
  WCM_CONNECTION_COST_SOURCE_OPERATOR = 3
} WCM_CONNECTION_COST_SOURCE, *PWCM_CONNECTION_COST_SOURCE;