typedef enum _WCM_CONNECTION_COST {
  WCM_CONNECTION_COST_UNKNOWN = 0x0,
  WCM_CONNECTION_COST_UNRESTRICTED = 0x1,
  WCM_CONNECTION_COST_FIXED = 0x2,
  WCM_CONNECTION_COST_VARIABLE = 0x4,
  WCM_CONNECTION_COST_OVERDATALIMIT = 0x10000,
  WCM_CONNECTION_COST_CONGESTED = 0x20000,
  WCM_CONNECTION_COST_ROAMING = 0x40000,
  WCM_CONNECTION_COST_APPROACHINGDATALIMIT = 0x80000
} WCM_CONNECTION_COST, *PWCM_CONNECTION_COST;