typedef struct _UCX_ENDPOINT_CHARACTERISTIC {
  ULONG                            Size;
  UCX_ENDPOINT_CHARACTERISTIC_TYPE CharacteristicType;
  union {
    UCX_CONTROLLER_ENDPOINT_CHARACTERISTIC_PRIORITY Priority;
  };
} UCX_ENDPOINT_CHARACTERISTIC, *PUCX_ENDPOINT_CHARACTERISTIC;