typedef enum _VDS_NOTIFICATION_TARGET_TYPE {
  VDS_NTT_UNKNOWN = 0,
  VDS_NTT_PACK,
  VDS_NTT_VOLUME,
  VDS_NTT_DISK,
  VDS_NTT_PARTITION = 60,
  VDS_NTT_DRIVE_LETTER = 61,
  VDS_NTT_FILE_SYSTEM = 62,
  VDS_NTT_MOUNT_POINT = 63,
  VDS_NTT_SUB_SYSTEM,
  VDS_NTT_CONTROLLER,
  VDS_NTT_DRIVE,
  VDS_NTT_LUN = VDS_OT_LUN,
  VDS_NTT_PORT,
  VDS_NTT_PORTAL,
  VDS_NTT_TARGET,
  VDS_NTT_PORTAL_GROUP,
  VDS_NTT_SERVICE = 200
} VDS_NOTIFICATION_TARGET_TYPE;