typedef enum _VDS_HBAPORT_TYPE {
  VDS_HPT_UNKNOWN = 1,
  VDS_HPT_OTHER = 2,
  VDS_HPT_NOTPRESENT = 3,
  VDS_HPT_NPORT = 5,
  VDS_HPT_NLPORT = 6,
  VDS_HPT_FLPORT = 7,
  VDS_HPT_FPORT = 8,
  VDS_HPT_EPORT = 9,
  VDS_HPT_GPORT = 10,
  VDS_HPT_LPORT = 20,
  VDS_HPT_PTP = 21
} VDS_HBAPORT_TYPE;