typedef enum _VDS_VDISK_STATE {
  VDS_VST_UNKNOWN = 0,
  VDS_VST_ADDED,
  VDS_VST_OPEN,
  VDS_VST_ATTACH_PENDING,
  VDS_VST_ATTACHED_NOT_OPEN,
  VDS_VST_ATTACHED,
  VDS_VST_DETACH_PENDING,
  VDS_VST_COMPACTING,
  VDS_VST_MERGING,
  VDS_VST_EXPANDING,
  VDS_VST_DELETED,
  VDS_VST_MAX
} VDS_VDISK_STATE;