typedef enum _VDS_CONTROLLER_STATUS {
  VDS_CS_UNKNOWN = 0,
  VDS_CS_ONLINE = 1,
  VDS_CS_NOT_READY = 2,
  VDS_CS_OFFLINE = 4,
  VDS_CS_FAILED = 5,
  VDS_CS_REMOVED = 8
} VDS_CONTROLLER_STATUS, *PVDS_CONTROLLER_STATUS;