typedef enum _VDS_DISK_STATUS {
  VDS_DS_UNKNOWN = 0,
  VDS_DS_ONLINE = 1,
  VDS_DS_NOT_READY = 2,
  VDS_DS_NO_MEDIA = 3,
  VDS_DS_FAILED = 5,
  VDS_DS_MISSING = 6,
  VDS_DS_OFFLINE = 4
} VDS_DISK_STATUS;