typedef enum _VDS_SUB_SYSTEM_STATUS {
  VDS_SSS_UNKNOWN = 0,
  VDS_SSS_ONLINE = 1,
  VDS_SSS_NOT_READY = 2,
  VDS_SSS_OFFLINE = 4,
  VDS_SSS_FAILED = 5,
  VDS_SSS_PARTIALLY_MANAGED = 9
} VDS_SUB_SYSTEM_STATUS, *PVDS_SUB_SYSTEM_STATUS;