typedef enum _VDS_SAN_POLICY {
  VDS_SP_UNKNOWN = 0,
  VDS_SP_ONLINE = 0x1,
  VDS_SP_OFFLINE_SHARED = 0x2,
  VDS_SP_OFFLINE = 0x3,
  VDS_SP_OFFLINE_INTERNAL = 0x4,
  VDS_SP_MAX = 0x5
} VDS_SAN_POLICY;