typedef enum _VDS_LUN_FLAG {
  VDS_LF_LBN_REMAP_ENABLED = 0x1,
  VDS_LF_READ_BACK_VERIFY_ENABLED = 0x2,
  VDS_LF_WRITE_THROUGH_CACHING_ENABLED = 0x4,
  VDS_LF_HARDWARE_CHECKSUM_ENABLED = 0x8,
  VDS_LF_READ_CACHE_ENABLED = 0x10,
  VDS_LF_WRITE_CACHE_ENABLED = 0x20,
  VDS_LF_MEDIA_SCAN_ENABLED = 0x40,
  VDS_LF_CONSISTENCY_CHECK_ENABLED = 0x80,
  VDS_LF_SNAPSHOT = 0x100
} VDS_LUN_FLAG, *PVDS_LUN_FLAG;