typedef enum _VDS_FORMAT_OPTION_FLAGS {
  VDS_FSOF_NONE = 0,
  VDS_FSOF_FORCE = 0x1,
  VDS_FSOF_QUICK = 0x2,
  VDS_FSOF_COMPRESSION = 0x4,
  VDS_FSOF_DUPLICATE_METADATA = 0x8
} VDS_FORMAT_OPTION_FLAGS;