typedef enum _VDS_DISK_EXTENT_TYPE {
  VDS_DET_UNKNOWN = 0,
  VDS_DET_FREE = 1,
  VDS_DET_DATA = 2,
  VDS_DET_OEM = 3,
  VDS_DET_ESP = 4,
  VDS_DET_MSR = 5,
  VDS_DET_LDM = 6,
  VDS_DET_CLUSTER = 7,
  VDS_DET_UNUSABLE = 0x7fff
} VDS_DISK_EXTENT_TYPE;