typedef enum _VDS_HBAPORT_STATUS {
  VDS_HPS_UNKNOWN = 1,
  VDS_HPS_ONLINE = 2,
  VDS_HPS_OFFLINE = 3,
  VDS_HPS_BYPASSED = 4,
  VDS_HPS_DIAGNOSTICS = 5,
  VDS_HPS_LINKDOWN = 6,
  VDS_HPS_ERROR = 7,
  VDS_HPS_LOOPBACK = 8
} VDS_HBAPORT_STATUS;