typedef struct _VDS_NOTIFICATION {
  VDS_NOTIFICATION_TARGET_TYPE objectType;
  union {
    VDS_PACK_NOTIFICATION         Pack;
    VDS_DISK_NOTIFICATION         Disk;
    VDS_VOLUME_NOTIFICATION       Volume;
    VDS_PARTITION_NOTIFICATION    Partition;
    VDS_DRIVE_LETTER_NOTIFICATION Letter;
    VDS_FILE_SYSTEM_NOTIFICATION  FileSystem;
    VDS_MOUNT_POINT_NOTIFICATION  MountPoint;
    VDS_SUB_SYSTEM_NOTIFICATION   SubSystem;
    VDS_CONTROLLER_NOTIFICATION   Controller;
    VDS_DRIVE_NOTIFICATION        Drive;
    VDS_LUN_NOTIFICATION          Lun;
    VDS_PORT_NOTIFICATION         Port;
    VDS_PORTAL_NOTIFICATION       Portal;
    VDS_TARGET_NOTIFICATION       Target;
    VDS_PORTAL_GROUP_NOTIFICATION PortalGroup;
    VDS_SERVICE_NOTIFICATION      Service;
  };
} VDS_NOTIFICATION;