typedef enum _SEARCH_KIND_OF_CHANGE {
  SEARCH_CHANGE_ADD = 0,
  SEARCH_CHANGE_DELETE = 1,
  SEARCH_CHANGE_MODIFY = 2,
  SEARCH_CHANGE_MOVE_RENAME = 3,
  SEARCH_CHANGE_SEMANTICS_DIRECTORY = 0x40000,
  SEARCH_CHANGE_SEMANTICS_SHALLOW = 0x80000,
  SEARCH_CHANGE_SEMANTICS_UPDATE_SECURITY = 0x400000
} SEARCH_KIND_OF_CHANGE;