typedef enum _CatalogPausedReason {
  CATALOG_PAUSED_REASON_NONE = 0,
  CATALOG_PAUSED_REASON_HIGH_IO = 1,
  CATALOG_PAUSED_REASON_HIGH_CPU = 2,
  CATALOG_PAUSED_REASON_HIGH_NTF_RATE = 3,
  CATALOG_PAUSED_REASON_LOW_BATTERY = 4,
  CATALOG_PAUSED_REASON_LOW_MEMORY = 5,
  CATALOG_PAUSED_REASON_LOW_DISK = 6,
  CATALOG_PAUSED_REASON_DELAYED_RECOVERY = 7,
  CATALOG_PAUSED_REASON_USER_ACTIVE = 8,
  CATALOG_PAUSED_REASON_EXTERNAL = 9,
  CATALOG_PAUSED_REASON_UPGRADING = 10
} CatalogPausedReason;