typedef enum _WINBIO_ASYNC_NOTIFICATION_METHOD {
  WINBIO_ASYNC_NOTIFY_NONE = 0,
  WINBIO_ASYNC_NOTIFY_CALLBACK,
  WINBIO_ASYNC_NOTIFY_MESSAGE,
  WINBIO_ASYNC_NOTIFY_MAXIMUM_VALUE
} WINBIO_ASYNC_NOTIFICATION_METHOD, *PWINBIO_ASYNC_NOTIFICATION_METHOD;