typedef enum __MIDL___MIDL_itf_sensorsapi_0000_0000_0002 {
  SENSOR_CONNECTION_TYPE_PC_INTEGRATED = 0,
  SENSOR_CONNECTION_TYPE_PC_ATTACHED,
  SENSOR_CONNECTION_TYPE_PC_EXTERNAL
} SensorConnectionType;