typedef enum _MMC_TASK_DISPLAY_TYPE {
  MMC_TASK_DISPLAY_UNINITIALIZED = 0,
  MMC_TASK_DISPLAY_TYPE_SYMBOL,
  MMC_TASK_DISPLAY_TYPE_VANILLA_GIF,
  MMC_TASK_DISPLAY_TYPE_CHOCOLATE_GIF,
  MMC_TASK_DISPLAY_TYPE_BITMAP
} MMC_TASK_DISPLAY_TYPE;