typedef enum _COLORSPACE_TRANSFORM_TYPE {
  COLORSPACE_TRANSFORM_TYPE_UNINITIALIZED,
  COLORSPACE_TRANSFORM_TYPE_DEFAULT,
  COLORSPACE_TRANSFORM_TYPE_RGB256x3x16,
  COLORSPACE_TRANSFORM_TYPE_DXGI_1,
  COLORSPACE_TRANSFORM_TYPE_MATRIX_3x4,
  COLORSPACE_TRANSFORM_TYPE_MATRIX_V2
} COLORSPACE_TRANSFORM_TYPE;