typedef enum _OUTPUT_COLOR_ENCODING {
  OUTPUT_COLOR_ENCODING_RGB,
  OUTPUT_COLOR_ENCODING_YCBCR444,
  OUTPUT_COLOR_ENCODING_YCBCR422,
  OUTPUT_COLOR_ENCODING_YCBCR420,
  OUTPUT_COLOR_ENCODING_INTENSITY,
  OUTPUT_COLOR_ENCODING_FORCE_UINT32
} OUTPUT_COLOR_ENCODING;