typedef struct _PANEL_QUERY_BRIGHTNESS_RANGES {
  BRIGHTNESS_INTERFACE_VERSION Version;
  union {
    BRIGHTNESS_LEVEL      BrightnessLevel;
    BRIGHTNESS_NIT_RANGES NitRanges;
  };
} PANEL_QUERY_BRIGHTNESS_RANGES, *PPANEL_QUERY_BRIGHTNESS_RANGES;