typedef struct _VIDEO_POINTER_CAPABILITIES {
  ULONG Flags;
  ULONG MaxWidth;
  ULONG MaxHeight;
  ULONG HWPtrBitmapStart;
  ULONG HWPtrBitmapEnd;
} VIDEO_POINTER_CAPABILITIES, *PVIDEO_POINTER_CAPABILITIES;