typedef struct _COLORSPACE_TRANSFORM_1DLUT_CAP {
  ULONG                         NumberOfLUTEntries;
  COLORSPACE_TRANSFORM_DATA_CAP DataCap;
} COLORSPACE_TRANSFORM_1DLUT_CAP, *PCOLORSPACE_TRANSFORM_1DLUT_CAP;