typedef struct _COLORSPACE_TRANSFORM {
  COLORSPACE_TRANSFORM_TYPE Type;
  union {
    GAMMA_RAMP_RGB256x3x16         Rgb256x3x16;
    GAMMA_RAMP_DXGI_1              Dxgi1;
    COLORSPACE_TRANSFORM_3x4       T3x4;
    COLORSPACE_TRANSFORM_MATRIX_V2 MatrixV2;
  } Data;
} COLORSPACE_TRANSFORM, *PCOLORSPACE_TRANSFORM;