typedef struct _COLORSPACE_TRANSFORM_TARGET_CAPS {
  COLORSPACE_TRANSFORM_TARGET_CAPS_VERSION Version;
  COLORSPACE_TRANSFORM_1DLUT_CAP           LookupTable1DDegammaCap;
  COLORSPACE_TRANSFORM_MATRIX_CAP          ColorMatrix3x3Cap;
  COLORSPACE_TRANSFORM_1DLUT_CAP           LookupTable1DRegammaCap;
} COLORSPACE_TRANSFORM_TARGET_CAPS, *PCOLORSPACE_TRANSFORM_TARGET_CAPS;