typedef struct _COLORSPACE_TRANSFORM_SET_INPUT {
  OUTPUT_WIRE_COLOR_SPACE_TYPE OutputWireColorSpaceExpected;
  OUTPUT_WIRE_FORMAT           OutputWireFormatExpected;
  COLORSPACE_TRANSFORM         ColorSpaceTransform;
} COLORSPACE_TRANSFORM_SET_INPUT, *PCOLORSPACE_TRANSFORM_SET_INPUT;