typedef enum {
  PRINT_EXECUTION_CONTEXT_APPLICATION,
  PRINT_EXECUTION_CONTEXT_SPOOLER_SERVICE,
  PRINT_EXECUTION_CONTEXT_SPOOLER_ISOLATION_HOST,
  PRINT_EXECUTION_CONTEXT_FILTER_PIPELINE,
  PRINT_EXECUTION_CONTEXT_WOW64
} PRINT_EXECUTION_CONTEXT;