typedef struct _WWAN_AUTH_SIM_RESPONSE {
  BYTE  Sres1[WWAN_AUTH_SRES_LEN];
  BYTE  Kc1[WWAN_AUTH_KC_LEN];
  BYTE  Sres2[WWAN_AUTH_SRES_LEN];
  BYTE  Kc2[WWAN_AUTH_KC_LEN];
  BYTE  Sres3[WWAN_AUTH_SRES_LEN];
  BYTE  Kc3[WWAN_AUTH_KC_LEN];
  ULONG n;
} WWAN_AUTH_SIM_RESPONSE, *PWWAN_AUTH_SIM_RESPONSE;