typedef struct _WWAN_NR_SERVING_CELLS_INFO {
  ULONG  ProviderIdOffset;
  ULONG  ProviderIdSize;
  UINT64 NCI;
  UINT32 PhysicalCellID;
  UINT32 NRARFCN;
  UINT32 TAC;
  UINT32 RSRP;
  UINT32 RSRQ;
  UINT32 SINR;
  UINT64 TimingAdvance;
  BYTE   Data[ANYSIZE_ARRAY];
} WWAN_NR_SERVING_CELLS_INFO, *PWWAN_NR_SERVING_CELLS_INFO;