typedef struct _WWAN_NETWORK_BLACKLIST_PROVIDER {
  ULONG                       MCC;
  ULONG                       MNC;
  WWAN_NETWORK_BLACKLIST_TYPE NetworkBlacklistType;
} WWAN_NETWORK_BLACKLIST_PROVIDER, *PWWAN_NETWORK_BLACKLIST_PROVIDER;