typedef struct _WWAN_NETWORK_BLACKLIST_INFO {
  WWAN_NETWORK_BLACKLIST_STATE BlacklistState;
  WWAN_LIST_HEADER             BlacklistProviderList;
} WWAN_NETWORK_BLACKLIST_INFO, *PWWAN_NETWORK_BLACKLIST_INFO;