typedef struct _WWAN_DEVICE_SERVICE_SUPPORTED_COMMANDS {
  GUID             DeviceServiceGuid;
  WWAN_LIST_HEADER ListHeader;
} WWAN_DEVICE_SERVICE_SUPPORTED_COMMANDS, *PWWAN_DEVICE_SERVICE_SUPPORTED_COMMANDS;