typedef struct _WWAN_AUTH_AKAP_CHALLENGE {
  BYTE  Rand[WWAN_AUTH_RAND_LEN];
  BYTE  Autn[WWAN_AUTH_AUTN_LEN];
  BYTE  NetworkName[WWAN_AUTH_NETWORK_NAME_MAX_LEN];
  ULONG NetworkNameLength;
} WWAN_AUTH_AKAP_CHALLENGE, *PWWAN_AUTH_AKAP_CHALLENGE;