typedef enum _VDS_STORAGE_BUS_TYPE {
  VDSBusTypeUnknown = 0,
  VDSBusTypeScsi = 0x1,
  VDSBusTypeAtapi = 0x2,
  VDSBusTypeAta = 0x3,
  VDSBusType1394 = 0x4,
  VDSBusTypeSsa = 0x5,
  VDSBusTypeFibre = 0x6,
  VDSBusTypeUsb = 0x7,
  VDSBusTypeRAID = 0x8,
  VDSBusTypeiScsi = 0x9,
  VDSBusTypeSas = 0xa,
  VDSBusTypeSata = 0xb,
  VDSBusTypeSd = 0xc,
  VDSBusTypeMmc = 0xd,
  VDSBusTypeMax = 0xe,
  VDSBusTypeVirtual = 0xe,
  VDSBusTypeFileBackedVirtual = 0xf,
  VDSBusTypeSpaces = 0x10,
  VDSBusTypeNVMe = 0x11,
  VDSBusTypeScm = 0x12,
  VDSBusTypeUfs = 0x13,
  VDSBusTypeMaxReserved = 0x7f
} VDS_STORAGE_BUS_TYPE;