typedef enum _DRT_ADDRESS_FLAGS {
  DRT_ADDRESS_FLAG_ACCEPTED = 0x01,
  DRT_ADDRESS_FLAG_REJECTED = 0x02,
  DRT_ADDRESS_FLAG_UNREACHABLE = 0x04,
  DRT_ADDRESS_FLAG_LOOP = 0x08,
  DRT_ADDRESS_FLAG_TOO_BUSY = 0x10,
  DRT_ADDRESS_FLAG_BAD_VALIDATE_ID = 0x20,
  DRT_ADDRESS_FLAG_SUSPECT_UNREGISTERED_ID = 0x40,
  DRT_ADDRESS_FLAG_INQUIRE = 0x80
} DRT_ADDRESS_FLAGS, *PDRT_ADDRESS_FLAGS;