typedef enum __MIDL___MIDL_itf_msopc_0001_0076_0004 {
  OPC_CERTIFICATE_IN_CERTIFICATE_PART = 0,
  OPC_CERTIFICATE_IN_SIGNATURE_PART = 1,
  OPC_CERTIFICATE_NOT_EMBEDDED = 2
} OPC_CERTIFICATE_EMBEDDING_OPTION;