typedef enum __MIDL___MIDL_itf_msopc_0001_0076_0005 {
  OPC_SIGNATURE_TIME_FORMAT_MILLISECONDS = 0,
  OPC_SIGNATURE_TIME_FORMAT_SECONDS = 1,
  OPC_SIGNATURE_TIME_FORMAT_MINUTES = 2,
  OPC_SIGNATURE_TIME_FORMAT_DAYS = 3,
  OPC_SIGNATURE_TIME_FORMAT_MONTHS = 4,
  OPC_SIGNATURE_TIME_FORMAT_YEARS = 5
} OPC_SIGNATURE_TIME_FORMAT;