typedef enum __MIDL___MIDL_itf_msopc_0000_0002_0002 {
  OPC_COMPRESSION_NONE = -1,
  OPC_COMPRESSION_NORMAL = 0,
  OPC_COMPRESSION_MAXIMUM = 1,
  OPC_COMPRESSION_FAST = 2,
  OPC_COMPRESSION_SUPERFAST = 3
} OPC_COMPRESSION_OPTIONS;