typedef enum __MIDL___MIDL_itf_tom_0000_0000_0002 {
  tomSimpleText = 0,
  tomRuby,
  tomHorzVert,
  tomWarichu,
  tomEq = 9,
  tomMath = 10,
  tomAccent = tomMath,
  tomBox,
  tomBoxedFormula,
  tomBrackets,
  tomBracketsWithSeps,
  tomEquationArray,
  tomFraction,
  tomFunctionApply,
  tomLeftSubSup,
  tomLowerLimit,
  tomMatrix,
  tomNary,
  tomOpChar,
  tomOverbar,
  tomPhantom,
  tomRadical,
  tomSlashedFraction,
  tomStack,
  tomStretchStack,
  tomSubscript,
  tomSubSup,
  tomSuperscript,
  tomUnderbar,
  tomUpperLimit,
  tomObjectMax
} OBJECTTYPE;