typedef enum __MIDL_IWTSSBPlugin_0003 {
  WTSSBX_ADDRESS_FAMILY_AF_UNSPEC = 0,
  WTSSBX_ADDRESS_FAMILY_AF_INET = 0x1,
  WTSSBX_ADDRESS_FAMILY_AF_INET6 = 0x2,
  WTSSBX_ADDRESS_FAMILY_AF_IPX = 0x3,
  WTSSBX_ADDRESS_FAMILY_AF_NETBIOS = 0x4
} WTSSBX_ADDRESS_FAMILY;