typedef enum __MIDL_IWTSSBPlugin_0002 {
  WTSSBX_MACHINE_SESSION_MODE_UNSPEC = 0,
  WTSSBX_MACHINE_SESSION_MODE_SINGLE = 0x1,
  WTSSBX_MACHINE_SESSION_MODE_MULTIPLE = 0x2
} WTSSBX_MACHINE_SESSION_MODE;