typedef enum __MIDL_IWTSSBPlugin_0010 {
  WTSSBX_NOTIFICATION_REMOVED = 0x1,
  WTSSBX_NOTIFICATION_CHANGED = 0x2,
  WTSSBX_NOTIFICATION_ADDED = 0x4,
  WTSSBX_NOTIFICATION_RESYNC = 0x8
} WTSSBX_NOTIFICATION_TYPE;