typedef struct _WIFI_POWER_OFFLOAD_80211RSNREKEY_PARAMETERS {
  ULONG  Size;
  ULONG  ProtocolOffloadId;
  UINT64 ReplayCounter;
  ULONG  KCKLength;
  ULONG  KEKLength;
  UCHAR  KCK[WIFI_RSN_MAX_CIPHER_KEY_LENGTH];
  UCHAR  KEK[WIFI_RSN_MAX_CIPHER_KEY_LENGTH];
} WIFI_POWER_OFFLOAD_80211RSNREKEY_PARAMETERS;