typedef struct _WIFI_POWER_OFFLOAD_ACTION_FRAME_WAKE_PATTERN_PARAMETERS {
  ULONG   Size;
  BOOLEAN FilterOnFrameAction;
  UINT8   ActionFrameCategory;
  UINT8   ActionFrameAction;
} WIFI_POWER_OFFLOAD_ACTION_FRAME_WAKE_PATTERN_PARAMETERS;