typedef struct _UCX_CONTROLLER_TRANSPORT_CHARACTERISTICS {
  ULONG   TransportCharacteristicsFlags;
  ULONG64 CurrentRoundtripLatencyInMilliSeconds;
  ULONG64 MaxPotentialBandwidth;
} UCX_CONTROLLER_TRANSPORT_CHARACTERISTICS, *PUCX_CONTROLLER_TRANSPORT_CHARACTERISTICS;