typedef struct _UCX_CONTROLLER_RESET_COMPLETE_INFO {
  ULONG                Size;
  UCX_CONTROLLER_STATE UcxControllerState;
  BOOLEAN              UcxCoordinated;
} UCX_CONTROLLER_RESET_COMPLETE_INFO, *PUCX_CONTROLLER_RESET_COMPLETE_INFO;