typedef struct _DHCPCAPI_PARAMS_ARARAY {
  ULONG             nParams;
#if ...
  LPDHCPCAPI_PARAMS Params;
#else
  LPDHCPCAPI_PARAMS Params;
#endif
} DHCPCAPI_PARAMS_ARRAY, *PDHCPCAPI_PARAMS_ARRAY, *LPDHCPCAPI_PARAMS_ARRAY;