typedef union _PCI_EXPRESS_LINK_STATUS_2_REGISTER {
  struct {
    USHORT Rsvd0_15 : 16;
  } DUMMYSTRUCTNAME;
  USHORT AsUSHORT;
} PCI_EXPRESS_LINK_STATUS_2_REGISTER, *PPCI_EXPRESS_LINK_STATUS_2_REGISTER;