typedef union _PCI_EXPRESS_LINK_CONTROL_2_REGISTER {
  struct {
    USHORT TargetLinkSpeed : 4;
    USHORT Rsvd4_15 : 12;
  } DUMMYSTRUCTNAME;
  USHORT AsUSHORT;
} PCI_EXPRESS_LINK_CONTROL_2_REGISTER, *PPCI_EXPRESS_LINK_CONTROL_2_REGISTER;