typedef struct _PCI_EXPRESS_ROOTPORT_AER_CAPABILITY {
  PCI_EXPRESS_ENHANCED_CAPABILITY_HEADER   Header;
  PCI_EXPRESS_UNCORRECTABLE_ERROR_STATUS   UncorrectableErrorStatus;
  PCI_EXPRESS_UNCORRECTABLE_ERROR_MASK     UncorrectableErrorMask;
  PCI_EXPRESS_UNCORRECTABLE_ERROR_SEVERITY UncorrectableErrorSeverity;
  PCI_EXPRESS_CORRECTABLE_ERROR_STATUS     CorrectableErrorStatus;
  PCI_EXPRESS_CORRECTABLE_ERROR_MASK       CorrectableErrorMask;
  PCI_EXPRESS_AER_CAPABILITIES             CapabilitiesAndControl;
  ULONG                                    HeaderLog[4];
  PCI_EXPRESS_ROOT_ERROR_COMMAND           RootErrorCommand;
  PCI_EXPRESS_ROOT_ERROR_STATUS            RootErrorStatus;
  PCI_EXPRESS_ERROR_SOURCE_ID              ErrorSourceId;
} PCI_EXPRESS_ROOTPORT_AER_CAPABILITY, *PPCI_EXPRESS_ROOTPORT_AER_CAPABILITY;