typedef enum D3D11_CONSERVATIVE_RASTERIZATION_TIER {
  D3D11_CONSERVATIVE_RASTERIZATION_NOT_SUPPORTED = 0,
  D3D11_CONSERVATIVE_RASTERIZATION_TIER_1 = 1,
  D3D11_CONSERVATIVE_RASTERIZATION_TIER_2 = 2,
  D3D11_CONSERVATIVE_RASTERIZATION_TIER_3 = 3
} ;