typedef enum D3D11_SHADER_CACHE_SUPPORT_FLAGS {
  D3D11_SHADER_CACHE_SUPPORT_NONE = 0,
  D3D11_SHADER_CACHE_SUPPORT_AUTOMATIC_INPROC_CACHE = 0x1,
  D3D11_SHADER_CACHE_SUPPORT_AUTOMATIC_DISK_CACHE = 0x2
} ;