typedef enum D3D11_VIDEO_FRAME_FORMAT {
  D3D11_VIDEO_FRAME_FORMAT_PROGRESSIVE = 0,
  D3D11_VIDEO_FRAME_FORMAT_INTERLACED_TOP_FIELD_FIRST = 1,
  D3D11_VIDEO_FRAME_FORMAT_INTERLACED_BOTTOM_FIELD_FIRST = 2
} ;