typedef struct D3D11_VIDEO_PROCESSOR_OUTPUT_VIEW_DESC {
  D3D11_VPOV_DIMENSION ViewDimension;
  union {
    D3D11_TEX2D_VPOV       Texture2D;
    D3D11_TEX2D_ARRAY_VPOV Texture2DArray;
  };
} D3D11_VIDEO_PROCESSOR_OUTPUT_VIEW_DESC;