typedef struct D3D11_AUTHENTICATED_QUERY_PROTECTION_OUTPUT {
  D3D11_AUTHENTICATED_QUERY_OUTPUT     Output;
  D3D11_AUTHENTICATED_PROTECTION_FLAGS ProtectionFlags;
} D3D11_AUTHENTICATED_QUERY_PROTECTION_OUTPUT;