typedef struct D3D11_AUTHENTICATED_QUERY_CRYPTO_SESSION_INPUT {
  D3D11_AUTHENTICATED_QUERY_INPUT Input;
  HANDLE                          DecoderHandle;
} D3D11_AUTHENTICATED_QUERY_CRYPTO_SESSION_INPUT;