typedef struct _WEBAUTHN_CREDENTIAL_DETAILS_LIST {
  DWORD                        cCredentialDetails;
  PWEBAUTHN_CREDENTIAL_DETAILS *ppCredentialDetails;
} WEBAUTHN_CREDENTIAL_DETAILS_LIST, *PWEBAUTHN_CREDENTIAL_DETAILS_LIST;