typedef struct _WEBAUTHN_USER_ENTITY_INFORMATION {
  DWORD  dwVersion;
  DWORD  cbId;
  PBYTE  pbId;
  PCWSTR pwszName;
  PCWSTR pwszIcon;
  PCWSTR pwszDisplayName;
} WEBAUTHN_USER_ENTITY_INFORMATION, *PWEBAUTHN_USER_ENTITY_INFORMATION;