typedef struct _WEBAUTHN_COSE_CREDENTIAL_PARAMETERS {
  DWORD                               cCredentialParameters;
  PWEBAUTHN_COSE_CREDENTIAL_PARAMETER pCredentialParameters;
} WEBAUTHN_COSE_CREDENTIAL_PARAMETERS, *PWEBAUTHN_COSE_CREDENTIAL_PARAMETERS;