typedef enum
{
    EDP_CONTEXT_NONE = 0x0,
    EDP_CONTEXT_IS_EXEMPT = 0x1,
    EDP_CONTEXT_IS_ENLIGHTENED = 0x2,
    EDP_CONTEXT_IS_UNENLIGHTENED_ALLOWED = 0x4,
    EDP_CONTEXT_IS_PERMISSIVE = 0x8,
    EDP_CONTEXT_IS_COPY_EXEMPT = 0x10,
    EDP_CONTEXT_IS_DENIED = 0x20,
} EDP_CONTEXT_STATES;