typedef struct _PHY_CONFIGURATION_PACKET {
  ULONG PCP_Phys_ID : 6;
  ULONG PCP_Packet_ID : 2;
  ULONG PCP_Gap_Count : 6;
  ULONG PCP_Set_Gap_Count : 1;
  ULONG PCP_Force_Root : 1;
  ULONG PCP_Reserved1 : 8;
  ULONG PCP_Reserved2 : 8;
  ULONG PCP_Inverse;
} PHY_CONFIGURATION_PACKET, *PPHY_CONFIGURATION_PACKET;