typedef struct _UFX_INTERFACE_PROPRIETARY_CHARGER {
  INTERFACE                                   InterfaceHeader;
  PFN_UFX_PROPRIETARY_CHARGER_DETECT          ProprietaryChargerDetect;
  PFN_UFX_PROPRIETARY_CHARGER_SET_PROPERTY    ProprietaryChargerSetProperty;
  PFN_UFX_PROPRIETARY_CHARGER_ABORT_OPERATION ProprietaryChargerAbortOperation;
  PFN_UFX_PROPRIETARY_CHARGER_RESET_OPERATION ProprietaryChargerResetOperation;
} UFX_INTERFACE_PROPRIETARY_CHARGER, *PUFX_INTERFACE_PROPRIETARY_CHARGER;