typedef struct _T2_COMMAND_DURATION_LIMIT_DESCRIPTOR {
  UCHAR T2CDLUNITS : 4;
  UCHAR Reserved : 4;
  UCHAR Reserved1;
  UCHAR MAX_INACTIVE_TIME[2];
  UCHAR MAX_ACTIVE_TIME[2];
  UCHAR MAX_ACTIVE_TIME_POLICY : 4;
  UCHAR MAX_INACTIVE_TIME_POLICY : 4;
  UCHAR Reserved2[3];
  UCHAR COMMAND_DURATION_GUIDELINE[2];
  UCHAR Reserved3[2];
  UCHAR COMMAND_DURATION_GUIDELINE_POLICY : 4;
  UCHAR Reserved4 : 4;
  UCHAR BypassSequestration : 1;
  UCHAR Reserved5 : 7;
  UCHAR Reserved6[16];
} T2_COMMAND_DURATION_LIMIT_DESCRIPTOR, *PT2_COMMAND_DURATION_LIMIT_DESCRIPTOR;