typedef enum EmfPlusRecordType {
  WmfRecordTypeSetBkColor,
  WmfRecordTypeSetBkMode,
  WmfRecordTypeSetMapMode,
  WmfRecordTypeSetROP2,
  WmfRecordTypeSetRelAbs,
  WmfRecordTypeSetPolyFillMode,
  WmfRecordTypeSetStretchBltMode,
  WmfRecordTypeSetTextCharExtra,
  WmfRecordTypeSetTextColor,
  WmfRecordTypeSetTextJustification,
  WmfRecordTypeSetWindowOrg,
  WmfRecordTypeSetWindowExt,
  WmfRecordTypeSetViewportOrg,
  WmfRecordTypeSetViewportExt,
  WmfRecordTypeOffsetWindowOrg,
  WmfRecordTypeScaleWindowExt,
  WmfRecordTypeOffsetViewportOrg,
  WmfRecordTypeScaleViewportExt,
  WmfRecordTypeLineTo,
  WmfRecordTypeMoveTo,
  WmfRecordTypeExcludeClipRect,
  WmfRecordTypeIntersectClipRect,
  WmfRecordTypeArc,
  WmfRecordTypeEllipse,
  WmfRecordTypeFloodFill,
  WmfRecordTypePie,
  WmfRecordTypeRectangle,
  WmfRecordTypeRoundRect,
  WmfRecordTypePatBlt,
  WmfRecordTypeSaveDC,
  WmfRecordTypeSetPixel,
  WmfRecordTypeOffsetClipRgn,
  WmfRecordTypeTextOut,
  WmfRecordTypeBitBlt,
  WmfRecordTypeStretchBlt,
  WmfRecordTypePolygon,
  WmfRecordTypePolyline,
  WmfRecordTypeEscape,
  WmfRecordTypeRestoreDC,
  WmfRecordTypeFillRegion,
  WmfRecordTypeFrameRegion,
  WmfRecordTypeInvertRegion,
  WmfRecordTypePaintRegion,
  WmfRecordTypeSelectClipRegion,
  WmfRecordTypeSelectObject,
  WmfRecordTypeSetTextAlign,
  WmfRecordTypeDrawText,
  WmfRecordTypeChord,
  WmfRecordTypeSetMapperFlags,
  WmfRecordTypeExtTextOut,
  WmfRecordTypeSetDIBToDev,
  WmfRecordTypeSelectPalette,
  WmfRecordTypeRealizePalette,
  WmfRecordTypeAnimatePalette,
  WmfRecordTypeSetPalEntries,
  WmfRecordTypePolyPolygon,
  WmfRecordTypeResizePalette,
  WmfRecordTypeDIBBitBlt,
  WmfRecordTypeDIBStretchBlt,
  WmfRecordTypeDIBCreatePatternBrush,
  WmfRecordTypeStretchDIB,
  WmfRecordTypeExtFloodFill,
  WmfRecordTypeSetLayout,
  WmfRecordTypeResetDC,
  WmfRecordTypeStartDoc,
  WmfRecordTypeStartPage,
  WmfRecordTypeEndPage,
  WmfRecordTypeAbortDoc,
  WmfRecordTypeEndDoc,
  WmfRecordTypeDeleteObject,
  WmfRecordTypeCreatePalette,
  WmfRecordTypeCreateBrush,
  WmfRecordTypeCreatePatternBrush,
  WmfRecordTypeCreatePenIndirect,
  WmfRecordTypeCreateFontIndirect,
  WmfRecordTypeCreateBrushIndirect,
  WmfRecordTypeCreateBitmapIndirect,
  WmfRecordTypeCreateBitmap,
  WmfRecordTypeCreateRegion,
  EmfRecordTypeHeader = EMR_HEADER,
  EmfRecordTypePolyBezier,
  EmfRecordTypePolygon,
  EmfRecordTypePolyline,
  EmfRecordTypePolyBezierTo,
  EmfRecordTypePolyLineTo,
  EmfRecordTypePolyPolyline,
  EmfRecordTypePolyPolygon,
  EmfRecordTypeSetWindowExtEx,
  EmfRecordTypeSetWindowOrgEx,
  EmfRecordTypeSetViewportExtEx,
  EmfRecordTypeSetViewportOrgEx,
  EmfRecordTypeSetBrushOrgEx,
  EmfRecordTypeEOF = EMR_EOF,
  EmfRecordTypeSetPixelV,
  EmfRecordTypeSetMapperFlags,
  EmfRecordTypeSetMapMode,
  EmfRecordTypeSetBkMode,
  EmfRecordTypeSetPolyFillMode,
  EmfRecordTypeSetROP2,
  EmfRecordTypeSetStretchBltMode,
  EmfRecordTypeSetTextAlign,
  EmfRecordTypeSetColorAdjustment,
  EmfRecordTypeSetTextColor,
  EmfRecordTypeSetBkColor,
  EmfRecordTypeOffsetClipRgn,
  EmfRecordTypeMoveToEx,
  EmfRecordTypeSetMetaRgn,
  EmfRecordTypeExcludeClipRect,
  EmfRecordTypeIntersectClipRect,
  EmfRecordTypeScaleViewportExtEx,
  EmfRecordTypeScaleWindowExtEx,
  EmfRecordTypeSaveDC = EMR_SAVEDC,
  EmfRecordTypeRestoreDC,
  EmfRecordTypeSetWorldTransform,
  EmfRecordTypeModifyWorldTransform,
  EmfRecordTypeSelectObject,
  EmfRecordTypeCreatePen,
  EmfRecordTypeCreateBrushIndirect,
  EmfRecordTypeDeleteObject,
  EmfRecordTypeAngleArc,
  EmfRecordTypeEllipse,
  EmfRecordTypeRectangle,
  EmfRecordTypeRoundRect,
  EmfRecordTypeArc = EMR_ARC,
  EmfRecordTypeChord = EMR_CHORD,
  EmfRecordTypePie = EMR_PIE,
  EmfRecordTypeSelectPalette,
  EmfRecordTypeCreatePalette,
  EmfRecordTypeSetPaletteEntries,
  EmfRecordTypeResizePalette,
  EmfRecordTypeRealizePalette,
  EmfRecordTypeExtFloodFill,
  EmfRecordTypeLineTo = EMR_LINETO,
  EmfRecordTypeArcTo = EMR_ARCTO,
  EmfRecordTypePolyDraw,
  EmfRecordTypeSetArcDirection,
  EmfRecordTypeSetMiterLimit,
  EmfRecordTypeBeginPath,
  EmfRecordTypeEndPath,
  EmfRecordTypeCloseFigure,
  EmfRecordTypeFillPath,
  EmfRecordTypeStrokeAndFillPath,
  EmfRecordTypeStrokePath,
  EmfRecordTypeFlattenPath,
  EmfRecordTypeWidenPath,
  EmfRecordTypeSelectClipPath,
  EmfRecordTypeAbortPath,
  EmfRecordTypeReserved_069 = 69,
  EmfRecordTypeGdiComment,
  EmfRecordTypeFillRgn,
  EmfRecordTypeFrameRgn,
  EmfRecordTypeInvertRgn,
  EmfRecordTypePaintRgn,
  EmfRecordTypeExtSelectClipRgn,
  EmfRecordTypeBitBlt = EMR_BITBLT,
  EmfRecordTypeStretchBlt,
  EmfRecordTypeMaskBlt,
  EmfRecordTypePlgBlt = EMR_PLGBLT,
  EmfRecordTypeSetDIBitsToDevice,
  EmfRecordTypeStretchDIBits,
  EmfRecordTypeExtCreateFontIndirect,
  EmfRecordTypeExtTextOutA,
  EmfRecordTypeExtTextOutW,
  EmfRecordTypePolyBezier16,
  EmfRecordTypePolygon16,
  EmfRecordTypePolyline16,
  EmfRecordTypePolyBezierTo16,
  EmfRecordTypePolylineTo16,
  EmfRecordTypePolyPolyline16,
  EmfRecordTypePolyPolygon16,
  EmfRecordTypePolyDraw16,
  EmfRecordTypeCreateMonoBrush,
  EmfRecordTypeCreateDIBPatternBrushPt,
  EmfRecordTypeExtCreatePen,
  EmfRecordTypePolyTextOutA,
  EmfRecordTypePolyTextOutW,
  EmfRecordTypeSetICMMode = 98,
  EmfRecordTypeCreateColorSpace = 99,
  EmfRecordTypeSetColorSpace = 100,
  EmfRecordTypeDeleteColorSpace = 101,
  EmfRecordTypeGLSRecord = 102,
  EmfRecordTypeGLSBoundedRecord = 103,
  EmfRecordTypePixelFormat = 104,
  EmfRecordTypeDrawEscape = 105,
  EmfRecordTypeExtEscape = 106,
  EmfRecordTypeStartDoc = 107,
  EmfRecordTypeSmallTextOut = 108,
  EmfRecordTypeForceUFIMapping = 109,
  EmfRecordTypeNamedEscape = 110,
  EmfRecordTypeColorCorrectPalette = 111,
  EmfRecordTypeSetICMProfileA = 112,
  EmfRecordTypeSetICMProfileW = 113,
  EmfRecordTypeAlphaBlend = 114,
  EmfRecordTypeSetLayout = 115,
  EmfRecordTypeTransparentBlt = 116,
  EmfRecordTypeReserved_117 = 117,
  EmfRecordTypeGradientFill = 118,
  EmfRecordTypeSetLinkedUFIs = 119,
  EmfRecordTypeSetTextJustification = 120,
  EmfRecordTypeColorMatchToTargetW = 121,
  EmfRecordTypeCreateColorSpaceW = 122,
  EmfRecordTypeMax = 122,
  EmfRecordTypeMin = 1,
  EmfPlusRecordTypeInvalid,
  EmfPlusRecordTypeHeader,
  EmfPlusRecordTypeEndOfFile,
  EmfPlusRecordTypeComment,
  EmfPlusRecordTypeGetDC,
  EmfPlusRecordTypeMultiFormatStart,
  EmfPlusRecordTypeMultiFormatSection,
  EmfPlusRecordTypeMultiFormatEnd,
  EmfPlusRecordTypeObject,
  EmfPlusRecordTypeClear,
  EmfPlusRecordTypeFillRects,
  EmfPlusRecordTypeDrawRects,
  EmfPlusRecordTypeFillPolygon,
  EmfPlusRecordTypeDrawLines,
  EmfPlusRecordTypeFillEllipse,
  EmfPlusRecordTypeDrawEllipse,
  EmfPlusRecordTypeFillPie,
  EmfPlusRecordTypeDrawPie,
  EmfPlusRecordTypeDrawArc,
  EmfPlusRecordTypeFillRegion,
  EmfPlusRecordTypeFillPath,
  EmfPlusRecordTypeDrawPath,
  EmfPlusRecordTypeFillClosedCurve,
  EmfPlusRecordTypeDrawClosedCurve,
  EmfPlusRecordTypeDrawCurve,
  EmfPlusRecordTypeDrawBeziers,
  EmfPlusRecordTypeDrawImage,
  EmfPlusRecordTypeDrawImagePoints,
  EmfPlusRecordTypeDrawString,
  EmfPlusRecordTypeSetRenderingOrigin,
  EmfPlusRecordTypeSetAntiAliasMode,
  EmfPlusRecordTypeSetTextRenderingHint,
  EmfPlusRecordTypeSetTextContrast,
  EmfPlusRecordTypeSetInterpolationMode,
  EmfPlusRecordTypeSetPixelOffsetMode,
  EmfPlusRecordTypeSetCompositingMode,
  EmfPlusRecordTypeSetCompositingQuality,
  EmfPlusRecordTypeSave,
  EmfPlusRecordTypeRestore,
  EmfPlusRecordTypeBeginContainer,
  EmfPlusRecordTypeBeginContainerNoParams,
  EmfPlusRecordTypeEndContainer,
  EmfPlusRecordTypeSetWorldTransform,
  EmfPlusRecordTypeResetWorldTransform,
  EmfPlusRecordTypeMultiplyWorldTransform,
  EmfPlusRecordTypeTranslateWorldTransform,
  EmfPlusRecordTypeScaleWorldTransform,
  EmfPlusRecordTypeRotateWorldTransform,
  EmfPlusRecordTypeSetPageTransform,
  EmfPlusRecordTypeResetClip,
  EmfPlusRecordTypeSetClipRect,
  EmfPlusRecordTypeSetClipPath,
  EmfPlusRecordTypeSetClipRegion,
  EmfPlusRecordTypeOffsetClip,
  EmfPlusRecordTypeDrawDriverString,
  EmfPlusRecordTypeStrokeFillPath,
  EmfPlusRecordTypeSerializableObject,
  EmfPlusRecordTypeSetTSGraphics,
  EmfPlusRecordTypeSetTSClip,
  EmfPlusRecordTotal,
  EmfPlusRecordTypeMax,
  EmfPlusRecordTypeMin
} ;