typedef enum __MIDL___MIDL_itf_tpmvscmgr_0000_0000_0001 {
  TPMVSCMGR_STATUS_VTPMSMARTCARD_INITIALIZING = 0,
  TPMVSCMGR_STATUS_VTPMSMARTCARD_CREATING,
  TPMVSCMGR_STATUS_VTPMSMARTCARD_DESTROYING,
  TPMVSCMGR_STATUS_VGIDSSIMULATOR_INITIALIZING,
  TPMVSCMGR_STATUS_VGIDSSIMULATOR_CREATING,
  TPMVSCMGR_STATUS_VGIDSSIMULATOR_DESTROYING,
  TPMVSCMGR_STATUS_VREADER_INITIALIZING,
  TPMVSCMGR_STATUS_VREADER_CREATING,
  TPMVSCMGR_STATUS_VREADER_DESTROYING,
  TPMVSCMGR_STATUS_GENERATE_WAITING,
  TPMVSCMGR_STATUS_GENERATE_AUTHENTICATING,
  TPMVSCMGR_STATUS_GENERATE_RUNNING,
  TPMVSCMGR_STATUS_CARD_CREATED,
  TPMVSCMGR_STATUS_CARD_DESTROYED
} TPMVSCMGR_STATUS;