typedef struct _WSK_CLIENT_LISTEN_DISPATCH {
  PFN_WSK_ACCEPT_EVENT  WskAcceptEvent;
  PFN_WSK_INSPECT_EVENT WskInspectEvent;
  PFN_WSK_ABORT_EVENT   WskAbortEvent;
} WSK_CLIENT_LISTEN_DISPATCH, *PWSK_CLIENT_LISTEN_DISPATCH;