typedef struct _WSK_CLIENT_STREAM_DISPATCH {
  const WSK_CLIENT_LISTEN_DISPATCH     *Listen;
  const WSK_CLIENT_CONNECTION_DISPATCH *Connect;
} WSK_CLIENT_STREAM_DISPATCH, *PWSK_CLIENT_STREAM_DISPATCH;