typedef struct _DOMAIN_CONFIGURATION {
  DOMAIN_CONFIGURATION_ARCH Type;
  union {
    DOMAIN_CONFIGURATION_ARM64 Arm64;
    DOMAIN_CONFIGURATION_X64   X64;
  };
} DOMAIN_CONFIGURATION, *PDOMAIN_CONFIGURATION;