typedef struct MEM_EXTENDED_PARAMETER {
  struct {
    ULONG64 Type : MEM_EXTENDED_PARAMETER_TYPE_BITS;
    ULONG64 Reserved : 64 - MEM_EXTENDED_PARAMETER_TYPE_BITS;
  } DUMMYSTRUCTNAME;
  union {
    ULONG64 ULong64;
    PVOID   Pointer;
    SIZE_T  Size;
    HANDLE  Handle;
    ULONG   ULong;
  } DUMMYUNIONNAME;
} MEM_EXTENDED_PARAMETER, *PMEM_EXTENDED_PARAMETER;