typedef struct _DMA_IOMMU_INTERFACE_EX {
  SIZE_T Size;
  ULONG  Version;
  union {
    DMA_IOMMU_INTERFACE_V1 V1;
    DMA_IOMMU_INTERFACE_V2 V2;
    DMA_IOMMU_INTERFACE_V3 V3;
  };
} DMA_IOMMU_INTERFACE_EX, *PDMA_IOMMU_INTERFACE_EX;