typedef struct _DRIVER_PROXY_ENDPOINT_INFORMATION {
  DRIVER_PROXY_ENDPOINT_FUNCTION_ID Id;
  PDRIVER_PROXY_ENDPOINT_FUNCTION   EndpointFunction;
  ULONG                             ParameterCount;
} DRIVER_PROXY_ENDPOINT_INFORMATION, *PDRIVER_PROXY_ENDPOINT_INFORMATION;