typedef struct _IOMMU_DEVICE_CREATION_CONFIGURATION {
  LIST_ENTRY                               NextConfiguration;
  IOMMU_DEVICE_CREATION_CONFIGURATION_TYPE ConfigType;
  union {
    IOMMU_DEVICE_CREATION_CONFIGURATION_ACPI  Acpi;
    PVOID                                     DeviceId;
    IOMMU_DEVICE_CREATION_CONFIGURATION_PASID Pasid;
  };
} IOMMU_DEVICE_CREATION_CONFIGURATION, *PIOMMU_DEVICE_CREATION_CONFIGURATION;