typedef struct _IOMMU_DMA_LOGICAL_ADDRESS_TOKEN {
  IOMMU_DMA_LOGICAL_ADDRESS LogicalAddressBase;
  SIZE_T                    Size;
} IOMMU_DMA_LOGICAL_ADDRESS_TOKEN, *PIOMMU_DMA_LOGICAL_ADDRESS_TOKEN;