typedef struct _POOL_CREATE_EXTENDED_PARAMETER {
  POOL_CREATE_EXTENDED_PARAMETER_TYPE Type;
  union {
    UNICODE_STRING PoolName;
  } DUMMYUNIONNAME;
} POOL_CREATE_EXTENDED_PARAMETER, *PPOOL_CREATE_EXTENDED_PARAMETER;