typedef struct _RESOURCEMANAGER_COMPLETION_INFORMATION {
  HANDLE    IoCompletionPortHandle;
  ULONG_PTR CompletionKey;
} RESOURCEMANAGER_COMPLETION_INFORMATION, *PRESOURCEMANAGER_COMPLETION_INFORMATION;