typedef struct _DEVICE_BUS_SPECIFIC_RESET_INFO {
  GUID                           BusTypeGuid;
  DEVICE_BUS_SPECIFIC_RESET_TYPE ResetTypeSupported;
} DEVICE_BUS_SPECIFIC_RESET_INFO, *PDEVICE_BUS_SPECIFIC_RESET_INFO;