typedef struct _IOMMU_DEVICE_CREATION_CONFIGURATION_PASID {
  IOMMU_PASID_CONFIGURATION_TYPE ConfigType;
  BOOLEAN                        SuppressPasidFaults;
} IOMMU_DEVICE_CREATION_CONFIGURATION_PASID, *PIOMMU_DEVICE_CREATION_CONFIGURATION_PASID;