typedef struct _PCI_EXPRESS_PTM_CAPABILITY {
  PCI_EXPRESS_ENHANCED_CAPABILITY_HEADER Header;
  PCI_EXPRESS_PTM_CAPABILITY_REGISTER    PtmCapability;
  PCI_EXPRESS_PTM_CONTROL_REGISTER       PtmControl;
} PCI_EXPRESS_PTM_CAPABILITY, *PPCI_EXPRESS_PTM_CAPABILITY;