typedef union _IOMMU_INTERFACE_STATE_CHANGE_FIELDS {
  struct {
    ULONG AvailableDomainTypes : 1;
    ULONG Reserved : 31;
  } DUMMYSTRUCTNAME;
  ULONG  AsULONG;
} IOMMU_INTERFACE_STATE_CHANGE_FIELDS, *PIOMMU_INTERFACE_STATE_CHANGE_FIELDS;