typedef struct _FAULT_INFORMATION {
  FAULT_INFORMATION_ARCH Type;
  BOOLEAN                IsStage1;
  union {
    FAULT_INFORMATION_ARM64 Arm64;
    FAULT_INFORMATION_X64   X64;
  };
} FAULT_INFORMATION, *PFAULT_INFORMATION;