typedef struct _MEMORY_PARTITION_DEDICATED_MEMORY_OPEN_INFORMATION {
  ULONG64     DedicatedMemoryTypeId;
  ULONG       HandleAttributes;
  ACCESS_MASK DesiredAccess;
  HANDLE      DedicatedMemoryPartitionHandle;
} MEMORY_PARTITION_DEDICATED_MEMORY_OPEN_INFORMATION, *PMEMORY_PARTITION_DEDICATED_MEMORY_OPEN_INFORMATION;