typedef enum DWRITE_RENDERING_MODE1 {
  DWRITE_RENDERING_MODE1_DEFAULT,
  DWRITE_RENDERING_MODE1_ALIASED,
  DWRITE_RENDERING_MODE1_GDI_CLASSIC,
  DWRITE_RENDERING_MODE1_GDI_NATURAL,
  DWRITE_RENDERING_MODE1_NATURAL,
  DWRITE_RENDERING_MODE1_NATURAL_SYMMETRIC,
  DWRITE_RENDERING_MODE1_OUTLINE,
  DWRITE_RENDERING_MODE1_NATURAL_SYMMETRIC_DOWNSAMPLED
} ;