typedef enum DWRITE_FONT_SOURCE_TYPE {
  DWRITE_FONT_SOURCE_TYPE_UNKNOWN,
  DWRITE_FONT_SOURCE_TYPE_PER_MACHINE,
  DWRITE_FONT_SOURCE_TYPE_PER_USER,
  DWRITE_FONT_SOURCE_TYPE_APPX_PACKAGE,
  DWRITE_FONT_SOURCE_TYPE_REMOTE_FONT_PROVIDER
} ;