typedef enum NS_CMD_FLAGS {
  CMD_FLAG_PRIVATE = 0x01,
  CMD_FLAG_INTERACTIVE = 0x02,
  CMD_FLAG_LOCAL = 0x08,
  CMD_FLAG_ONLINE = 0x10,
  CMD_FLAG_HIDDEN = 0x20,
  CMD_FLAG_LIMIT_MASK = 0xffff,
  CMD_FLAG_PRIORITY
} ;