typedef enum D3D11_MESSAGE_CATEGORY {
  D3D11_MESSAGE_CATEGORY_APPLICATION_DEFINED = 0,
  D3D11_MESSAGE_CATEGORY_MISCELLANEOUS,
  D3D11_MESSAGE_CATEGORY_INITIALIZATION,
  D3D11_MESSAGE_CATEGORY_CLEANUP,
  D3D11_MESSAGE_CATEGORY_COMPILATION,
  D3D11_MESSAGE_CATEGORY_STATE_CREATION,
  D3D11_MESSAGE_CATEGORY_STATE_SETTING,
  D3D11_MESSAGE_CATEGORY_STATE_GETTING,
  D3D11_MESSAGE_CATEGORY_RESOURCE_MANIPULATION,
  D3D11_MESSAGE_CATEGORY_EXECUTION,
  D3D11_MESSAGE_CATEGORY_SHADER
} ;