PFND3D12DDI_INITIALIZE_VIDEO_EXTENSION_COMMAND_0063 Pfnd3d12ddiInitializeVideoExtensionCommand0063;

HRESULT Pfnd3d12ddiInitializeVideoExtensionCommand0063(
  D3D12DDI_HCOMMANDLIST hDrvCommandList,
  D3D12DDI_HVIDEOEXTENSIONCOMMAND_0063 hDrvVideoExtensionCommand,
  const void *pInitializationParameters,
  SIZE_T InitializationParametersSizeInBytes
)
{...}