typedef enum D3D12DDI_RESOURCE_OPTIMIZATION_FLAGS {
  D3D12DDI_RESOURCE_OPTIMIZATION_FLAG_NONE = 0x0,
  D3D12DDI_RESOURCE_OPTIMIZATION_FLAG_SHADER_RESOURCE = 0x1,
  D3D12DDI_RESOURCE_OPTIMIZATION_FLAG_UNORDERED_ACCESS = 0x2,
  D3D12DDI_RESOURCE_OPTIMIZATION_FLAG_PRIMARY = 0x4,
  D3D12DDI_RESOURCE_OPTIMIZATION_FLAG_DETERMINISTIC = 0x8
} ;