typedef enum D3D12DDI_WAVE_MMA_INPUT_DATATYPE {
  D3D12DDI_WAVE_MMA_INPUT_DATATYPE_INVALID,
  D3D12DDI_WAVE_MMA_INPUT_DATATYPE_BYTE,
  D3D12DDI_WAVE_MMA_INPUT_DATATYPE_FLOAT16,
  D3D12DDI_WAVE_MMA_INPUT_DATATYPE_FLOAT
} ;