typedef enum D3D12DDI_CREATE_DEPTH_STENCIL_VIEW_FLAGS {
  D3D12DDI_CREATE_DSV_FLAG_NONE,
  D3D12DDI_CREATE_DSV_FLAG_READ_ONLY_DEPTH,
  D3D12DDI_CREATE_DSV_FLAG_READ_ONLY_STENCIL,
  D3D12DDI_CREATE_DSV_FLAG_MASK
} ;