typedef enum D3D12DDI_RESOURCE_LAYOUT {
  D3D12DDI_RL_UNDEFINED,
  D3D12DDI_RL_PLACED_PHYSICAL_SUBRESOURCE_PITCHED,
  D3D12DDI_RL_PLACED_VIRTUAL_SUBRESOURCE_PITCHED,
  D3D12DDI_RL_SELECT_SUBRESOURCE
} ;