typedef enum D3D12DDI_NODE_IO_FLAGS_0108 {
  D3D12DDI_NODE_IO_FLAG_INPUT,
  D3D12DDI_NODE_IO_FLAG_OUTPUT,
  D3D12DDI_NODE_IO_FLAG_READ_WRITE,
  D3D12DDI_NODE_IO_FLAG_EMPTY_RECORD,
  D3D12DDI_NODE_IO_FLAG_NODE_ARRAY,
  D3D12DDI_NODE_IO_FLAG_THREAD_RECORD,
  D3D12DDI_NODE_IO_FLAG_GROUP_RECORD,
  D3D12DDI_NODE_IO_FLAG_DISPATCH_RECORD,
  D3D12DDI_NODE_IO_FLAG_RECORD_GRANULARITY_MASK,
  D3D12DDI_NODE_IO_FLAG_KIND_MASK,
  D3D12DDI_NODE_IO_FLAG_TRACK_RW_INPUT_SHARING,
  D3D12DDI_NODE_IO_FLAG_NODE_FLAGS_MASK,
  D3D12DDI_NODE_IO_FLAG_RECORD_FLAGS_MASK
} ;