typedef enum D3D12DDI_COMPARISON_FUNC {
  D3D12DDI_COMPARISON_FUNC_NEVER,
  D3D12DDI_COMPARISON_FUNC_LESS,
  D3D12DDI_COMPARISON_FUNC_EQUAL,
  D3D12DDI_COMPARISON_FUNC_LESS_EQUAL,
  D3D12DDI_COMPARISON_FUNC_GREATER,
  D3D12DDI_COMPARISON_FUNC_NOT_EQUAL,
  D3D12DDI_COMPARISON_FUNC_GREATER_EQUAL,
  D3D12DDI_COMPARISON_FUNC_ALWAYS
} ;