typedef enum D3D12DDI_STENCIL_OP {
  D3D12DDI_STENCIL_OP_KEEP,
  D3D12DDI_STENCIL_OP_ZERO,
  D3D12DDI_STENCIL_OP_REPLACE,
  D3D12DDI_STENCIL_OP_INCR_SAT,
  D3D12DDI_STENCIL_OP_DECR_SAT,
  D3D12DDI_STENCIL_OP_INVERT,
  D3D12DDI_STENCIL_OP_INCR,
  D3D12DDI_STENCIL_OP_DECR
} ;