typedef struct D3D12DDICAPS_VIDEO_ENCODER_OUTPUT_RESOLUTION_RATIOS_COUNT_DATA_0080_2 {
  UINT                              NodeIndex;
  D3D12DDI_VIDEO_ENCODER_CODEC_0080 Codec;
  UINT                              ResolutionRatiosCount;
} D3D12DDICAPS_VIDEO_ENCODER_OUTPUT_RESOLUTION_RATIOS_COUNT_DATA_0080_2;