typedef struct D3D12DDI_CRYPTO_SESSION_TRANSFORM_DECRYPT_OUTPUT_ARGUMENTS_0030 {
  BOOL               Enable;
  D3D12DDI_HRESOURCE hDrvBuffer;
  UINT64             Size;
  UINT64             Offset;
} D3D12DDI_CRYPTO_SESSION_TRANSFORM_DECRYPT_OUTPUT_ARGUMENTS_0030;