typedef struct D3D12DDI_VIDEO_ENCODER_CODEC_PICTURE_CONTROL_SUPPORT_H264_0080_2 {
  UINT MaxL0ReferencesForP;
  UINT MaxL0ReferencesForB;
  UINT MaxL1ReferencesForB;
  UINT MaxLongTermReferences;
  UINT MaxDPBCapacity;
} D3D12DDI_VIDEO_ENCODER_CODEC_PICTURE_CONTROL_SUPPORT_H264_0080_2;