typedef struct D3D12DDI_RAYTRACING_GEOMETRY_AABBS_DESC_0054 {
  UINT64                                  AABBCount;
  D3D12DDI_GPU_VIRTUAL_ADDRESS_AND_STRIDE AABBs;
} D3D12DDI_RAYTRACING_GEOMETRY_AABBS_DESC_0054;