typedef struct D3D12DDI_VIDEO_ENCODER_AV1_CODEC_CONFIGURATION_0095 {
  D3D12DDI_VIDEO_ENCODER_AV1_FEATURE_0095_FLAGS FeatureFlags;
  UINT                                          OrderHintBitsMinus1;
} D3D12DDI_VIDEO_ENCODER_AV1_CODEC_CONFIGURATION_0095;