typedef struct D3D12DDI_VIDEO_DECODE_PROTECTED_RESOURCES_DATA_0072 {
  [in]  UINT                                                 NodeIndex;
  [in]  D3D12DDI_VIDEO_DECODE_CONFIGURATION_0020             Configuration;
  [out] D3D12DDI_VIDEO_PROTECTED_RESOURCE_SUPPORT_FLAGS_0072 SupportFlags;
} D3D12DDI_VIDEO_DECODE_PROTECTED_RESOURCES_DATA_0072;