typedef struct D3D12DDIARG_CREATECOMMANDALLOCATOR {
  D3D12DDI_HCOMMANDALLOCATOR   hDrvCommandAllocator;
  D3D12DDI_COMMAND_LIST_TYPE   Type;
  D3D12DDI_COMMAND_QUEUE_FLAGS QueueFlags;
} D3D12DDIARG_CREATECOMMANDALLOCATOR;