typedef struct D3D12DDICAPS_VIDEO_ENCODER_INTRA_REFRESH_MODE_DATA_0080_2 {
  UINT                                           NodeIndex;
  D3D12DDI_VIDEO_ENCODER_CODEC_0080              Codec;
  D3D12DDI_VIDEO_ENCODER_PROFILE_DESC_0080_2     Profile;
  D3D12DDI_VIDEO_ENCODER_LEVEL_SETTING_0080_2    Level;
  D3D12DDI_VIDEO_ENCODER_INTRA_REFRESH_MODE_0080 IntraRefreshMode;
  BOOL                                           IsSupported;
} D3D12DDICAPS_VIDEO_ENCODER_INTRA_REFRESH_MODE_DATA_0080_2;