typedef struct D3D12DDI_VIDEO_EXTENSION_COMMAND_PARAMETER_INFO_0063 {
  LPCWSTR                                               Name;
  D3D12DDI_VIDEO_EXTENSION_COMMAND_PARAMETER_TYPE_0063  Type;
  D3D12DDI_VIDEO_EXTENSION_COMMAND_PARAMETER_FLAGS_0063 Flags;
} D3D12DDI_VIDEO_EXTENSION_COMMAND_PARAMETER_INFO_0063;