typedef struct D3D12DDIARG_META_COMMAND_PARAMETER_DESC {
  LPCWSTR                               Name;
  D3D12DDI_META_COMMAND_PARAMETER_TYPE  Type;
  D3D12DDI_META_COMMAND_PARAMETER_FLAGS Flags;
  D3D12DDI_RESOURCE_STATES              RequiredResourceState;
} D3D12DDIARG_META_COMMAND_PARAMETER_DESC;