typedef struct D3D12DDI_DEPTH_STENCILOP_DESC {
  D3D12DDI_STENCIL_OP      StencilFailOp;
  D3D12DDI_STENCIL_OP      StencilDepthFailOp;
  D3D12DDI_STENCIL_OP      StencilPassOp;
  D3D12DDI_COMPARISON_FUNC StencilFunc;
} D3D12DDI_DEPTH_STENCILOP_DESC;