typedef struct D3D12DDIARG_COPY_RAYTRACING_ACCELERATION_STRUCTURE_0054 {
  D3D12DDI_GPU_VIRTUAL_ADDRESS                         DestAccelerationStructureData;
  D3D12DDI_GPU_VIRTUAL_ADDRESS                         SourceAccelerationStructureData;
  D3D12DDI_RAYTRACING_ACCELERATION_STRUCTURE_COPY_MODE Mode;
} D3D12DDIARG_COPY_RAYTRACING_ACCELERATION_STRUCTURE_0054;