typedef struct D3D12DDI_RENDER_PASS_BEGINNING_ACCESS {
  D3D12DDI_RENDER_PASS_BEGINNING_ACCESS_TYPE Type;
  union {
    D3D12DDI_RENDER_PASS_BEGINNING_ACCESS_CLEAR_PARAMETERS             Clear;
    D3D12DDI_RENDER_PASS_BEGINNING_ACCESS_RESUME_LOCAL_READ_PARAMETERS ResumeLocalRead;
  };
} D3D12DDI_RENDER_PASS_BEGINNING_ACCESS;