typedef struct D3D12DDI_VIDEO_ENCODER_RATE_CONTROL_CONFIGURATION_PARAMS_0080_2 {
  UINT  DataSize;
  union {
    const D3D12DDI_VIDEO_ENCODER_RATE_CONTROL_CQP_0080             *pConfiguration_CQP;
    const D3D12DDI_VIDEO_ENCODER_RATE_CONTROL_CBR_0080             *pConfiguration_CBR;
    const D3D12DDI_VIDEO_ENCODER_RATE_CONTROL_VBR_0080             *pConfiguration_VBR;
    const D3D12DDI_VIDEO_ENCODER_RATE_CONTROL_QVBR_0080_2          *pConfiguration_QVBR;
    const D3D12DDI_VIDEO_ENCODER_RATE_CONTROL_CQP1_0096            *pConfiguration_CQP1;
    const D3D12DDI_VIDEO_ENCODER_RATE_CONTROL_CBR1_0096            *pConfiguration_CBR1;
    const D3D12DDI_VIDEO_ENCODER_RATE_CONTROL_VBR1_0096            *pConfiguration_VBR1;
    const D3D12DDI_VIDEO_ENCODER_RATE_CONTROL_QVBR1_0096           *pConfiguration_QVBR1;
    const D3D12DDI_VIDEO_ENCODER_RATE_CONTROL_ABSOLUTE_QP_MAP_0096 *pConfiguration_AbsoluteQPMap;
  };
} D3D12DDI_VIDEO_ENCODER_RATE_CONTROL_CONFIGURATION_PARAMS_0080_2;