typedef struct D3D12DDI_VIDEO_ENCODER_SEQUENCE_GOP_STRUCTURE_HEVC_0082_0 {
  UINT  GOPLength;
  UINT  PPicturePeriod;
  UCHAR log2_max_pic_order_cnt_lsb_minus4;
} D3D12DDI_VIDEO_ENCODER_SEQUENCE_GOP_STRUCTURE_HEVC_0082_0;