typedef struct D3D12DDI_VIDEO_DECODE_BITSTREAM_ENCRYPTION_SCHEMES_DATA_0020 {
  UINT NodeIndex;
  GUID DecodeProfile;
  UINT EncryptionSchemeCount;
  GUID *pEncryptionSchemes;
} D3D12DDI_VIDEO_DECODE_BITSTREAM_ENCRYPTION_SCHEMES_DATA_0020;