typedef struct D3D12DDICB_CREATESYNCHRONIZATIONOBJECT2 {
  [in, out] D3DDDI_SYNCHRONIZATIONOBJECTINFO2 Info;
  [out]     D3DKMT_HANDLE                     hSyncObject;
} D3D12DDICB_CREATESYNCHRONIZATIONOBJECT2;