typedef struct D3D12DDI_DEVICE_FUNCS_CONTENT_PROTECTION_RESOURCES_0074 {
  PFND3D12DDI_CALCPRIVATEPROTECTEDRESOURCESESSIONSIZE_0074       pfnCalcPrivateProtectedResourceSessionSize;
  PFND3D12DDI_CREATEPROTECTEDRESOURCESESSION_0074                pfnCreateProtectedResourceSession;
  PFND3D12DDI_CALCPRIVATEOPENEDPROTECTEDRESOURCESESSIONSIZE_0030 pfnCalcPrivateOpenedProtectedResourceSessionSize;
  PFND3D12DDI_OPENPROTECTEDRESOURCESESSION_0030                  pfnOpenProtectedResourceSession;
  PFND3D12DDI_DESTROYPROTECTEDRESOURCESESSION_0030               pfnDestroyProtectedResourceSession;
} D3D12DDI_DEVICE_FUNCS_CONTENT_PROTECTION_RESOURCES_0074;