typedef struct D3D12DDI_COMMAND_LIST_FUNCS_VIDEO_DECODE_0032 {
  PFND3D12DDI_CLOSECOMMANDLIST                 pfnCloseCommandList;
  PFND3D12DDI_RESETCOMMANDLIST                 pfnResetCommandList;
  PFND3D12DDI_DISCARD_RESOURCE_0003            pfnDiscardResource;
  PFND3D12DDI_SET_MARKER                       pfnSetMarker;
  PFND3D12DDI_SET_PREDICATION                  pfnSetPredication;
  PFND3D12DDI_BEGIN_END_QUERY_0003             pfnBeginQuery;
  PFND3D12DDI_BEGIN_END_QUERY_0003             pfnEndQuery;
  PFND3D12DDI_RESOLVE_QUERY_DATA               pfnResolveQueryData;
  PFND3D12DDI_RESOURCEBARRIER_0022             pfnResourceBarrier;
  PFND3D12DDI_VIDEO_DECODE_FRAME_0032          pfnDecodeFrame;
  PFND3D12DDI_SETPROTECTEDRESOURCESESSION_0030 pfnSetProtectedResourceSession;
  PFND3D12DDI_WRITEBUFFERIMMEDIATE_0032        pfnWriteBufferImmediate;
} D3D12DDI_COMMAND_LIST_FUNCS_VIDEO_DECODE_0032;