typedef struct D3D12DDI_RENDER_PASS_ENDING_ACCESS {
  D3D12DDI_RENDER_PASS_ENDING_ACCESS_TYPE Type;
  union {
    D3D12DDI_RENDER_PASS_ENDING_ACCESS_RESOLVE_PARAMETERS            Resolve;
    D3D12DDI_RENDER_PASS_ENDING_ACCESS_SUSPEND_LOCAL_READ_PARAMETERS SuspendLocalRead;
  };
} D3D12DDI_RENDER_PASS_ENDING_ACCESS;