typedef struct D3D12DDI_BUILD_RAYTRACING_ACCELERATION_STRUCTURE_INPUTS_0054 {
  D3D12DDI_RAYTRACING_ACCELERATION_STRUCTURE_TYPE        Type;
  D3D12DDI_RAYTRACING_ACCELERATION_STRUCTURE_BUILD_FLAGS Flags;
  UINT                                                   NumDescs;
  D3D12DDI_ELEMENTS_LAYOUT                               DescsLayout;
  union {
    D3D12DDI_GPU_VIRTUAL_ADDRESS                 InstanceDescs;
    const D3D12DDI_RAYTRACING_GEOMETRY_DESC_0054 *pGeometryDescs;
    const D3D12DDI_RAYTRACING_GEOMETRY_DESC_0054 const * * ppGeometryDescs;
  };
} D3D12DDI_BUILD_RAYTRACING_ACCELERATION_STRUCTURE_INPUTS_0054;