typedef struct D3D12DDICAPS_VIDEO_ENCODER_PROFILE_LEVEL_DATA_0080_2 {
  UINT                                        NodeIndex;
  D3D12DDI_VIDEO_ENCODER_CODEC_0080           Codec;
  D3D12DDI_VIDEO_ENCODER_PROFILE_DESC_0080_2  Profile;
  BOOL                                        IsSupported;
  D3D12DDI_VIDEO_ENCODER_LEVEL_SETTING_0080_2 MinSupportedLevel;
  D3D12DDI_VIDEO_ENCODER_LEVEL_SETTING_0080_2 MaxSupportedLevel;
} D3D12DDICAPS_VIDEO_ENCODER_PROFILE_LEVEL_DATA_0080_2;