typedef struct D3D12DDI_VIDEO_DECODE_OUTPUT_STREAM_ARGUMENTS_0041_1 {
  D3D12DDI_HRESOURCE                              hDrvOutputTexture2D;
  UINT                                            OutputSubresource;
  D3D12DDI_VIDEO_DECODE_CONVERSION_ARGUMENTS_0041 ConversionArguments;
  D3D12DDI_VIDEO_DECODE_COMPONENT_HISTOGRAM_0041  Histograms[D3D12DDI_VIDEO_DECODE_MAX_HISTOGRAM_COMPONENTS];
} D3D12DDI_VIDEO_DECODE_OUTPUT_STREAM_ARGUMENTS_0041_1;