typedef struct D3D12DDI_SET_WORK_GRAPH_DESC_0108 {
  D3D12DDI_PROGRAM_IDENTIFIER_0108              ProgramIdentifier;
  D3D12DDI_SET_WORK_GRAPH_FLAGS_0108            Flags;
  D3D12DDI_GPU_VIRTUAL_ADDRESS_RANGE            BackingMemory;
  D3D12DDI_GPU_VIRTUAL_ADDRESS_RANGE_AND_STRIDE NodeLocalRootArgumentsTable;
} D3D12DDI_SET_WORK_GRAPH_DESC_0108;