typedef struct D3D12DDI_VIDEO_ENCODER_RATE_CONTROL_0080_2 {
  D3D12DDI_VIDEO_ENCODER_RATE_CONTROL_MODE_0080                   Mode;
  D3D12DDI_VIDEO_ENCODER_RATE_CONTROL_FLAGS_0080                  Flags;
  D3D12DDI_VIDEO_ENCODER_RATE_CONTROL_CONFIGURATION_PARAMS_0080_2 ConfigParams;
  DXGI_RATIONAL                                                   TargetFrameRate;
} D3D12DDI_VIDEO_ENCODER_RATE_CONTROL_0080_2;