typedef struct D3D12DDI_VIDEO_ENCODER_RATE_CONTROL_VBR_0080 {
  UINT   InitialQP;
  UINT   MinQP;
  UINT   MaxQP;
  UINT64 MaxFrameBitSize;
  UINT64 TargetAvgBitRate;
  UINT64 PeakBitRate;
  UINT64 VBVCapacity;
  UINT64 InitialVBVFullness;
} D3D12DDI_VIDEO_ENCODER_RATE_CONTROL_VBR_0080;