typedef struct D3D12DDIARG_CREATECOMMANDQUEUE_0023 {
  D3D12DDI_COMMAND_QUEUE_FLAGS          QueueFlags;
  UINT                                  NodeMask;
  D3D12DDI_COMMAND_QUEUE_CREATION_FLAGS QueueCreationFlags;
} D3D12DDIARG_CREATECOMMANDQUEUE_0023;