typedef struct D3D12DDI_RENDER_PASS_ENDING_ACCESS_RESOLVE_SUBRESOURCE_PARAMETERS {
  UINT          SrcSubresource;
  UINT          DstSubresource;
  UINT          DstX;
  UINT          DstY;
  D3D12DDI_RECT SrcRect;
} D3D12DDI_RENDER_PASS_ENDING_ACCESS_RESOLVE_SUBRESOURCE_PARAMETERS;