typedef struct D3D12DDI_BUILD_RAYTRACING_ACCELERATION_STRUCTURE_TOOLS_VISUALIZATION_HEADER_0054 {
  D3D12DDI_RAYTRACING_ACCELERATION_STRUCTURE_TYPE Type;
  UINT                                            NumDescs;
} D3D12DDI_BUILD_RAYTRACING_ACCELERATION_STRUCTURE_TOOLS_VISUALIZATION_HEADER_0054;