typedef struct D3D12DDI_VIDEO_ENCODER_RATE_CONTROL_CQP_0080 {
  UINT ConstantQP_FullIntracodedFrame;
  UINT ConstantQP_InterPredictedFrame_PrevRefOnly;
  UINT ConstantQP_InterPredictedFrame_BiDirectionalRef;
} D3D12DDI_VIDEO_ENCODER_RATE_CONTROL_CQP_0080;