typedef struct D3D12DDIARG_CREATE_DEPTH_STENCIL_VIEW {
  D3D12DDI_HRESOURCE                       hDrvResource;
  DXGI_FORMAT                              Format;
  D3D12DDI_RESOURCE_DIMENSION              ResourceDimension;
  D3D12DDI_CREATE_DEPTH_STENCIL_VIEW_FLAGS Flags;
  union {
    D3D12DDIARG_TEX1D_DEPTH_STENCIL_VIEW   Tex1D;
    D3D12DDIARG_TEX2D_DEPTH_STENCIL_VIEW   Tex2D;
    D3D12DDIARG_TEXCUBE_DEPTH_STENCIL_VIEW TexCube;
  };
} D3D12DDIARG_CREATE_DEPTH_STENCIL_VIEW;