typedef struct D3D12DDI_RAYTRACING_PIPELINE_CONFIG_0075 {
  UINT                               MaxTraceRecursionDepth;
  D3D12DDI_RAYTRACING_PIPELINE_FLAGS Flags;
} D3D12DDI_RAYTRACING_PIPELINE_CONFIG_0075;