typedef struct D3D12DDI_VIDEO_ENCODER_ENCODEFRAME_OUTPUT_STREAM_ARGUMENTS_0080_2 {
  D3D12DDI_VIDEO_ENCODER_COMPRESSED_BITSTREAM_0080               CompressedBitstream;
  D3D12DDI_VIDEO_ENCODE_RECONSTRUCTED_PICTURE_0080               ReconstructedPicture;
  D3D12DDI_VIDEO_ENCODER_ENCODE_OPERATION_METADATA_BUFFER_0080_2 HWLayoutEncoderMetadataDrvBuffer;
} D3D12DDI_VIDEO_ENCODER_ENCODEFRAME_OUTPUT_STREAM_ARGUMENTS_0080_2;