typedef enum tagOLEUIPASTEFLAG {
  OLEUIPASTE_ENABLEICON = 2048,
  OLEUIPASTE_PASTEONLY = 0,
  OLEUIPASTE_PASTE = 512,
  OLEUIPASTE_LINKANYTYPE = 1024,
  OLEUIPASTE_LINKTYPE1 = 1,
  OLEUIPASTE_LINKTYPE2 = 2,
  OLEUIPASTE_LINKTYPE3 = 4,
  OLEUIPASTE_LINKTYPE4 = 8,
  OLEUIPASTE_LINKTYPE5 = 16,
  OLEUIPASTE_LINKTYPE6 = 32,
  OLEUIPASTE_LINKTYPE7 = 64,
  OLEUIPASTE_LINKTYPE8 = 128
} OLEUIPASTEFLAG;