typedef struct _SIDEBANDAUDIO_SUPPORTED_FORMATS {
  ULONG         CbSize;
  ULONG         EpIndex;
  ULONG         NumFormats;
  PKSDATAFORMAT *Formats;
} SIDEBANDAUDIO_SUPPORTED_FORMATS, *PSIDEBANDAUDIO_SUPPORTED_FORMATS;