typedef enum __MIDL___MIDL_itf_wsdbase_0000_0000_0001 {
  WSD_CONFIG_MAX_INBOUND_MESSAGE_SIZE = 1,
  WSD_CONFIG_MAX_OUTBOUND_MESSAGE_SIZE = 2,
  WSD_SECURITY_SSL_CERT_FOR_CLIENT_AUTH = 3,
  WSD_SECURITY_SSL_SERVER_CERT_VALIDATION = 4,
  WSD_SECURITY_SSL_CLIENT_CERT_VALIDATION = 5,
  WSD_SECURITY_SSL_NEGOTIATE_CLIENT_CERT = 6,
  WSD_SECURITY_COMPACTSIG_SIGNING_CERT = 7,
  WSD_SECURITY_COMPACTSIG_VALIDATION = 8,
  WSD_CONFIG_HOSTING_ADDRESSES = 9,
  WSD_CONFIG_DEVICE_ADDRESSES = 10,
  WSD_SECURITY_REQUIRE_HTTP_CLIENT_AUTH = 11,
  WSD_SECURITY_REQUIRE_CLIENT_CERT_OR_HTTP_CLIENT_AUTH = 12,
  WSD_SECURITY_USE_HTTP_CLIENT_AUTH = 13
} WSD_CONFIG_PARAM_TYPE;