typedef enum RILCALLMEDIAVIDEOFLAGPARAMMASK {
  RIL_CALLMEDIAVIDEOFLAG_NONE,
  RIL_CALLMEDIAVIDEOFLAG_CAPABILITY_UNKNOWN,
  RIL_CALLMEDIAVIDEOFLAG_PAUSE,
  RIL_CALLMEDIAVIDEOFLAG_TEMPORARILY_UNAVAILABLE,
  RIL_CALLMEDIAVIDEOFLAG_ALL
} ;