typedef enum _RILUICCAPPTYPE {
  RIL_UICCAPPTYPE_MF,
  RIL_UICCAPPTYPE_MF_SIM,
  RIL_UICCAPPTYPE_MF_RUIM,
  RIL_UICCAPPTYPE_USIM,
  RIL_UICCAPPTYPE_CSIM,
  RIL_UICCAPPTYPE_ISIM,
  RIL_UICCAPPTYPE_MAX
} RILUICCAPPTYPE;