typedef enum _RILPOSITIONINFOGSMPARAMMASK {
  RIL_PARAM_POSITION_GSM_MNC,
  RIL_PARAM_POSITION_GSM_LAC,
  RIL_PARAM_POSITION_GSM_CELLID,
  RIL_PARAM_POSITION_GSM_TA,
  RIL_PARAM_POSITION_GSM_ARFCN,
  RIL_PARAM_POSITION_GSM_BSID,
  RIL_PARAM_POSITION_GSM_RXLEVEL,
  RIL_PARAM_POSITION_GSM_ALL
} RILPOSITIONINFOGSMPARAMMASK;