typedef enum RIL3GPP2ISDNALERTING {
  RIL_3GPP2ISDNALERTING_ALERTINGOFF,
  RIL_3GPP2ISDNALERTING_NORMAL,
  RIL_3GPP2ISDNALERTING_INTERGROUP,
  RIL_3GPP2ISDNALERTING_SPECIAL,
  RIL_3GPP2ISDNALERTING_PINGRING,
  RIL_3GPP2ISDNALERTING_MAX
} ;