typedef enum _RILADDRESSNUMPLAN {
  RIL_NUMPLAN_TELEPHONE,
  RIL_NUMPLAN_DATA,
  RIL_NUMPLAN_TELEX,
  RIL_NUMPLAN_NATIONAL,
  RIL_NUMPLAN_PRIVATE,
  RIL_NUMPLAN_ERMES,
  RIL_NUMPLAN_MAX
} RILADDRESSNUMPLAN;