typedef enum _RILIMSSERVICE {
  RIL_IMS_SERVICE_VOICE,
  RIL_IMS_SERVICE_VIDEO,
  RIL_IMS_SERVICE_CUSTOM,
  RIL_IMS_SERVICE_SUPSVC,
  RIL_IMS_SERVICE_RCS,
  RIL_IMS_SERVICE_USSD,
  RIL_IMS_SERVICE_E_VOICE,
  RIL_IMS_SERVICE_ALL
} RILIMSSERVICE;