typedef enum _RILC2KMRLPARAMMASK {
  RIL_PARAM_C2KMRL_NID,
  RIL_PARAM_C2KMRL_SID,
  RIL_PARAM_C2KMRL_BSID,
  RIL_PARAM_C2KMRL_BASELAT,
  RIL_PARAM_C2KMRL_BASELONG,
  RIL_PARAM_C2KMRL_REFPN,
  RIL_PARAM_C2KMRL_GPSSECONDS,
  RIL_PARAM_C2KMRL_PILOTSTRENGTH,
  RIL_PARAM_C2KRML_ALL
} RILC2KMRLPARAMMASK;