typedef enum RILADDITIONALCALLERINFOPARAMMASK {
  RIL_PARAM_ADDTLCI_EXECUTOR,
  RIL_PARAM_ADDTLCI_CALLID,
  RIL_PARAM_ADDTLCI_CALLERINFOLENGTH,
  RIL_PARAM_ADDTLCI_CALLERINFO,
  RIL_PARAM_ADDTLCI_ALL
} ;