typedef enum RILMSGCDMAMSGPRIVACY {
  RIL_MSGPRIVACYCLASS_NOTRESTRICTED,
  RIL_MSGPRIVACYCLASS_RESTRICTED,
  RIL_MSGPRIVACYCLASS_CONFIDENTIAL,
  RIL_MSGPRIVACYCLASS_SECRET,
  RIL_MSGPRIVACYCLASS_MAX
} ;