typedef enum RILMSGCDMABROADCASTSERVICEID {
  RIL_1xBROADCAST_CMAS_PRESIDENTIAL,
  RIL_1xBROADCAST_CMAS_EXTREME,
  RIL_1xBROADCAST_CMAS_SEVERE,
  RIL_1xBROADCAST_CMAS_AMBER,
  RIL_1xBROADCAST_CMAS_TEST
} ;