typedef enum _RILDEVICEINFORMATION {
  RIL_DEVICEINFO_MODEL,
  RIL_DEVICEINFO_REVISION,
  RIL_DEVICEINFO_SERIALNUMBER_GW,
  RIL_DEVICEINFO_SERIALNUMBER_CDMA,
  RIL_DEVICEINFO_ARG_SMALLEST,
  RIL_DEVICEINFO_ARG_LARGEST,
  RIL_DEVICEINFO_MIN,
  RIL_DEVICEINFO_MAX
} RILDEVICEINFORMATION;