typedef enum RILDISPLAYINFOPARAMMASK {
  RIL_PARAM_DISPLAY_EXECUTOR,
  RIL_PARAM_DISPLAY_TYPE,
  RIL_PARAM_DISPLAY_TAG,
  RIL_PARAM_DISPLAY_MESSAGESIZE,
  RIL_PARAM_DISPLAY_MESSAGE,
  RIL_PARAM_DISPLAY_ALL
} ;