typedef enum RILSUPSERVICEDATASTATUS {
  RIL_SUPSVCDATASTATUS_NOINFOREQUIRED,
  RIL_SUPSVCDATASTATUS_FURTHERINFOREQUIRED,
  RIL_SUPSVCDATASTATUS_TIMEOUT,
  RIL_SUPSVCDATASTATUS_ERROR,
  RIL_SUPSVCDATASTATUS_MAX
} ;