typedef enum _RILPOSITIONINFOTDSCDMAPARAMMASK {
  RIL_PARAM_POSITION_TDSCDMA_MNC,
  RIL_PARAM_POSITION_TDSCDMA_LAC,
  RIL_PARAM_POSITION_TDSCDMA_CELLID,
  RIL_PARAM_POSITION_TDSCDMA_UARFCN,
  RIL_PARAM_POSITION_TDSCDMA_CELLPARAM,
  RIL_PARAM_POSITION_TDSCDMA_TA,
  RIL_PARAM_POSITION_TDSCDMA_RSCP,
  RIL_PARAM_POSITION_TDSCDMA_PATHLOSS,
  RIL_PARAM_POSITION_TDSCDMA_ALL
} RILPOSITIONINFOTDSCDMAPARAMMASK;