typedef enum _RILSYSTEMTYPE {
  RIL_SYSTEMTYPE_1XRTT,
  RIL_SYSTEMTYPE_EVDO,
  RIL_SYSTEMTYPE_GSM,
  RIL_SYSTEMTYPE_UMTS,
  RIL_SYSTEMTYPE_LTE,
  RIL_SYSTEMTYPE_TDSCDMA,
  RIL_SYSTEMTYPE_CDMA,
  RIL_SYSTEMTYPE_GSMUMTS,
  RIL_SYSTEMTYPE_GSMTDS,
  RIL_SYSTEMTYPE_GSMUMTSTDS,
  RIL_SYSTEMTYPE_3GPP,
  RIL_SYSTEMTYPE_ALL
} RILSYSTEMTYPE;