typedef enum _RILEUTRAMRLPARAMMASK {
  RIL_PARAM_EUTRAMRL_MNC,
  RIL_PARAM_EUTRAMRL_CELLID,
  RIL_PARAM_EUTRAMRL_EARFCN,
  RIL_PARAM_EUTRAMRL_PHYSCELLID,
  RIL_PARAM_EUTRAMRL_TAC,
  RIL_PARAM_EUTRAMRL_RSRP,
  RIL_PARAM_EUTRAMRL_RSRQ,
  RIL_PARAM_EUTRAMRL_ALL
} RILEUTRAMRLPARAMMASK;