typedef enum RILPERSODEACTIVATIONSTATEDEPERSOSTATE {
  RIL_DEPERSOSTATE_READY,
  RIL_DEPERSOSTATE_CK_REQUIRED,
  RIL_DEPERSOSTATE_PUK_REQUIRED,
  RIL_DEPERSOSTATE_PUK_BLOCKED,
  RIL_DEPERSOSTATE_MAX
} ;