typedef struct RILTONESIGNALINFO_V2 {
  DWORD                cbSize;
  DWORD                dwParams;
  DWORD                dwExecutor;
  RIL3GPPTONE          dwGPPTone;
  RIL3GPP2TONE         dwGPP2Tone;
  RIL3GPP2ISDNALERTING dwGPP2IsdnAlerting;
} RILTONESIGNALINFO_V2, *LPRILTONESIGNALINFO_V2, RILTONESIGNALINFO, *LPRILTONESIGNALINFO;