typedef struct RILGETPREFERREDOPERATORLISTPARAMS {
  HUICCAPP                            hUiccApp;
  RILGETPREFERENCEDOPERATORLISTFORMAT dwFormat;
} RILGETPREFERREDOPERATORLISTPARAMS, *LPRILGETPREFERREDOPERATORLISTPARAMS;