typedef struct RILWRITEADDITIONALNUMBERSTRINGPARAMS {
  HUICCAPP                           hUiccApp;
  RILPHONEBOOKADDITIONALNUMBERSTRING RilPBANS;
} RILWRITEADDITIONALNUMBERSTRINGPARAMS, *LPRILWRITEADDITIONALNUMBERSTRINGPARAMS;