typedef struct RILOPENUICCLOGICALCHANNELINFO {
  DWORD cbSize;
  DWORD dwParams;
  DWORD dwChannelId;
  DWORD dwSelectResponseLength;
  BYTE  bSelectResponse[1];
} RILOPENUICCLOGICALCHANNELINFO, *LPRILOPENUICCLOGICALCHANNELINFO;