typedef struct RILEMERGENCYMODECONTROLPARAMS {
  DWORD                                dwExecutor;
  RILEMERGENCYMODECONTROLPARAMSCONTROL dwEmergencyModeControl;
} RILEMERGENCYMODECONTROLPARAMS, *LPRILEMERGENCYMODECONTROLPARAMS;