typedef struct RILIMSHANDOVERATTEMPT {
  DWORD            cbSize;
  RILIMSSYSTEMTYPE dwOldSystemType;
  RILIMSSYSTEMTYPE dwDestSystemType;
  HRESULT          hrHandOverResult;
} RILIMSHANDOVERATTEMPT, *LPRILIMSHANDOVERATTEMPT;