typedef struct RILOPENUICCLOGICALCHANNELPARAMS {
  DWORD dwSlotIndex;
  DWORD dwChannelGroup;
  DWORD dwAppIdLength;
  BYTE  bAppId[32];
  DWORD dwSelectP2Arg;
} RILOPENUICCLOGICALCHANNELPARAMS, *LPRILOPENUICCLOGICALCHANNELPARAMS;