typedef struct RILREMOVECALLFORWARDINGPARAMS {
  DWORD                           dwExecutor;
  RILCALLFORWARDINGSETTINGSREASON dwReason;
  DWORD                           dwInfoClasses;
} RILREMOVECALLFORWARDINGPARAMS, *LPRILREMOVECALLFORWARDINGPARAMS;