typedef struct X3DAUDIO_LISTENER {
  X3DAUDIO_VECTOR OrientFront;
  X3DAUDIO_VECTOR OrientTop;
  X3DAUDIO_VECTOR Position;
  X3DAUDIO_VECTOR Velocity;
  X3DAUDIO_CONE   *pCone;
} X3DAUDIO_LISTENER, *LPX3DAUDIO_LISTENER;