typedef struct _ISCSI_UNIQUE_SESSION_ID {
  ULONGLONG AdapterUnique;
  ULONGLONG AdapterSpecific;
} ISCSI_UNIQUE_SESSION_ID, *PISCSI_UNIQUE_SESSION_ID, ISCSI_UNIQUE_CONNECTION_ID, *PISCSI_UNIQUE_CONNECTION_ID;