typedef struct _WTSLISTENERCONFIGA {
  ULONG version;
  ULONG fEnableListener;
  ULONG MaxConnectionCount;
  ULONG fPromptForPassword;
  ULONG fInheritColorDepth;
  ULONG ColorDepth;
  ULONG fInheritBrokenTimeoutSettings;
  ULONG BrokenTimeoutSettings;
  ULONG fDisablePrinterRedirection;
  ULONG fDisableDriveRedirection;
  ULONG fDisableComPortRedirection;
  ULONG fDisableLPTPortRedirection;
  ULONG fDisableClipboardRedirection;
  ULONG fDisableAudioRedirection;
  ULONG fDisablePNPRedirection;
  ULONG fDisableDefaultMainClientPrinter;
  ULONG LanAdapter;
  ULONG PortNumber;
  ULONG fInheritShadowSettings;
  ULONG ShadowSettings;
  ULONG TimeoutSettingsConnection;
  ULONG TimeoutSettingsDisconnection;
  ULONG TimeoutSettingsIdle;
  ULONG SecurityLayer;
  ULONG MinEncryptionLevel;
  ULONG UserAuthentication;
  CHAR  Comment[WTS_COMMENT_LENGTH + 1];
  CHAR  LogonUserName[USERNAME_LENGTH + 1];
  CHAR  LogonDomain[DOMAIN_LENGTH + 1];
  CHAR  WorkDirectory[MAX_PATH + 1];
  CHAR  InitialProgram[MAX_PATH + 1];
} WTSLISTENERCONFIGA, *PWTSLISTENERCONFIGA;