typedef struct _ETW_TRACE_PARTITION_INFORMATION {
  GUID   PartitionId;
  GUID   ParentId;
  LONG64 QpcOffsetFromRoot;
  ULONG  PartitionType;
} ETW_TRACE_PARTITION_INFORMATION, *PETW_TRACE_PARTITION_INFORMATION;