typedef enum _EATTRIBUTE_DATATYPE {
  kADT_UNKNOWN,
  kADT_BOOL,
  kADT_INT,
  kADT_LONG,
  kADT_DWORD,
  kADT_ASCII,
  kADT_UNICODE,
  kADT_BINARY,
  kADT_SIZE,
  kADT_RECT,
  kADT_CUSTOMSIZEPARAMS
} EATTRIBUTE_DATATYPE;