typedef struct _DEVICE_WRITE_AGGREGATION_DESCRIPTOR {
  DWORD   Version;
  DWORD   Size;
  BOOLEAN BenefitsFromWriteAggregation;
} DEVICE_WRITE_AGGREGATION_DESCRIPTOR, *PDEVICE_WRITE_AGGREGATION_DESCRIPTOR;