typedef struct _DEVICE_DSM_NOTIFICATION_PARAMETERS {
  DWORD Size;
  DWORD Flags;
  DWORD NumFileTypeIDs;
  GUID  FileTypeID[ANYSIZE_ARRAY];
} DEVICE_DSM_NOTIFICATION_PARAMETERS, *PDEVICE_DSM_NOTIFICATION_PARAMETERS;