typedef struct _STORAGE_HW_BOOT_PARTITION_ACTIVATE {
  DWORD Version;
  DWORD Size;
  DWORD Flags;
  BYTE  BPID;
  BYTE  Reserved[3];
} STORAGE_HW_BOOT_PARTITION_ACTIVATE, *PSTORAGE_HW_BOOT_PARTITION_ACTIVATE;