typedef struct _DEVICE_MEDIA_INFO {
  union {
    struct {
      LARGE_INTEGER      Cylinders;
      STORAGE_MEDIA_TYPE MediaType;
      DWORD              TracksPerCylinder;
      DWORD              SectorsPerTrack;
      DWORD              BytesPerSector;
      DWORD              NumberMediaSides;
      DWORD              MediaCharacteristics;
    } DiskInfo;
    struct {
      LARGE_INTEGER      Cylinders;
      STORAGE_MEDIA_TYPE MediaType;
      DWORD              TracksPerCylinder;
      DWORD              SectorsPerTrack;
      DWORD              BytesPerSector;
      DWORD              NumberMediaSides;
      DWORD              MediaCharacteristics;
    } RemovableDiskInfo;
    struct {
      STORAGE_MEDIA_TYPE MediaType;
      DWORD              MediaCharacteristics;
      DWORD              CurrentBlockSize;
      STORAGE_BUS_TYPE   BusType;
      union {
        struct {
          BYTE MediumType;
          BYTE DensityCode;
        } ScsiInformation;
      } BusSpecificData;
    } TapeInfo;
  } DeviceSpecific;
} DEVICE_MEDIA_INFO, *PDEVICE_MEDIA_INFO;