typedef struct _TXFS_LIST_TRANSACTION_LOCKED_FILES_ENTRY {
  DWORDLONG Offset;
  DWORD     NameFlags;
  LONGLONG  FileId;
  DWORD     Reserved1;
  DWORD     Reserved2;
  LONGLONG  Reserved3;
  WCHAR     FileName[1];
} TXFS_LIST_TRANSACTION_LOCKED_FILES_ENTRY, *PTXFS_LIST_TRANSACTION_LOCKED_FILES_ENTRY;