typedef struct _STORAGE_DEVICE_IO_CAPABILITY_DESCRIPTOR {
  DWORD Version;
  DWORD Size;
  DWORD LunMaxIoCount;
  DWORD AdapterMaxIoCount;
} STORAGE_DEVICE_IO_CAPABILITY_DESCRIPTOR, *PSTORAGE_DEVICE_IO_CAPABILITY_DESCRIPTOR;