typedef struct _FSCTL_QUERY_REGION_INFO_INPUT {
  DWORD Version;
  DWORD Size;
  DWORD Flags;
  DWORD NumberOfTierIds;
  GUID  TierIds[ANYSIZE_ARRAY];
} FSCTL_QUERY_REGION_INFO_INPUT, *PFSCTL_QUERY_REGION_INFO_INPUT;