typedef struct _TXFS_QUERY_RM_INFORMATION {
  DWORD         BytesRequired;
  DWORDLONG     TailLsn;
  DWORDLONG     CurrentLsn;
  DWORDLONG     ArchiveTailLsn;
  DWORDLONG     LogContainerSize;
  LARGE_INTEGER HighestVirtualClock;
  DWORD         LogContainerCount;
  DWORD         LogContainerCountMax;
  DWORD         LogContainerCountMin;
  DWORD         LogGrowthIncrement;
  DWORD         LogAutoShrinkPercentage;
  DWORD         Flags;
  WORD          LoggingMode;
  WORD          Reserved;
  DWORD         RmState;
  DWORDLONG     LogCapacity;
  DWORDLONG     LogFree;
  DWORDLONG     TopsSize;
  DWORDLONG     TopsUsed;
  DWORDLONG     TransactionCount;
  DWORDLONG     OnePCCount;
  DWORDLONG     TwoPCCount;
  DWORDLONG     NumberLogFileFull;
  DWORDLONG     OldestTransactionAge;
  GUID          RMName;
  DWORD         TmLogPathOffset;
} TXFS_QUERY_RM_INFORMATION, *PTXFS_QUERY_RM_INFORMATION;