typedef struct _STORAGE_ADAPTER_SERIAL_NUMBER {
  DWORD Version;
  DWORD Size;
  WCHAR SerialNumber[STORAGE_ADAPTER_SERIAL_NUMBER_V1_MAX_LENGTH];
} STORAGE_ADAPTER_SERIAL_NUMBER, *PSTORAGE_ADAPTER_SERIAL_NUMBER;