typedef enum _D3D_SHADER_VARIABLE_CLASS {
  D3D_SVC_SCALAR = 0,
  D3D_SVC_VECTOR,
  D3D_SVC_MATRIX_ROWS,
  D3D_SVC_MATRIX_COLUMNS,
  D3D_SVC_OBJECT,
  D3D_SVC_STRUCT,
  D3D_SVC_INTERFACE_CLASS,
  D3D_SVC_INTERFACE_POINTER,
  D3D10_SVC_SCALAR,
  D3D10_SVC_VECTOR,
  D3D10_SVC_MATRIX_ROWS,
  D3D10_SVC_MATRIX_COLUMNS,
  D3D10_SVC_OBJECT,
  D3D10_SVC_STRUCT,
  D3D11_SVC_INTERFACE_CLASS,
  D3D11_SVC_INTERFACE_POINTER,
  D3D_SVC_FORCE_DWORD = 0x7fffffff
} D3D_SHADER_VARIABLE_CLASS;