typedef enum D3D_TESSELLATOR_OUTPUT_PRIMITIVE {
  D3D_TESSELLATOR_OUTPUT_UNDEFINED = 0,
  D3D_TESSELLATOR_OUTPUT_POINT = 1,
  D3D_TESSELLATOR_OUTPUT_LINE = 2,
  D3D_TESSELLATOR_OUTPUT_TRIANGLE_CW = 3,
  D3D_TESSELLATOR_OUTPUT_TRIANGLE_CCW = 4,
  D3D11_TESSELLATOR_OUTPUT_UNDEFINED,
  D3D11_TESSELLATOR_OUTPUT_POINT,
  D3D11_TESSELLATOR_OUTPUT_LINE,
  D3D11_TESSELLATOR_OUTPUT_TRIANGLE_CW,
  D3D11_TESSELLATOR_OUTPUT_TRIANGLE_CCW
} ;