typedef enum D3D_TESSELLATOR_DOMAIN {
  D3D_TESSELLATOR_DOMAIN_UNDEFINED = 0,
  D3D_TESSELLATOR_DOMAIN_ISOLINE = 1,
  D3D_TESSELLATOR_DOMAIN_TRI = 2,
  D3D_TESSELLATOR_DOMAIN_QUAD = 3,
  D3D11_TESSELLATOR_DOMAIN_UNDEFINED,
  D3D11_TESSELLATOR_DOMAIN_ISOLINE,
  D3D11_TESSELLATOR_DOMAIN_TRI,
  D3D11_TESSELLATOR_DOMAIN_QUAD
} ;