typedef enum _MAP_FLAGS {
  EVENTMAP_INFO_FLAG_MANIFEST_VALUEMAP = 0x1,
  EVENTMAP_INFO_FLAG_MANIFEST_BITMAP = 0x2,
  EVENTMAP_INFO_FLAG_MANIFEST_PATTERNMAP = 0x4,
  EVENTMAP_INFO_FLAG_WBEM_VALUEMAP = 0x8,
  EVENTMAP_INFO_FLAG_WBEM_BITMAP = 0x10,
  EVENTMAP_INFO_FLAG_WBEM_FLAG = 0x20,
  EVENTMAP_INFO_FLAG_WBEM_NO_MAP = 0x40
} MAP_FLAGS;