typedef enum _PAYLOAD_OPERATOR {
  PAYLOADFIELD_EQ,
  PAYLOADFIELD_NE,
  PAYLOADFIELD_LE,
  PAYLOADFIELD_GT,
  PAYLOADFIELD_LT,
  PAYLOADFIELD_GE,
  PAYLOADFIELD_BETWEEN,
  PAYLOADFIELD_NOTBETWEEN,
  PAYLOADFIELD_MODULO,
  PAYLOADFIELD_CONTAINS,
  PAYLOADFIELD_DOESNTCONTAIN,
  PAYLOADFIELD_IS,
  PAYLOADFIELD_ISNOT,
  PAYLOADFIELD_INVALID
} PAYLOAD_OPERATOR;