typedef enum _TDH_CONTEXT_TYPE {
  TDH_CONTEXT_WPP_TMFFILE,
  TDH_CONTEXT_WPP_TMFSEARCHPATH,
  TDH_CONTEXT_WPP_GMT,
  TDH_CONTEXT_POINTERSIZE,
  TDH_CONTEXT_PDB_PATH,
  TDH_CONTEXT_MAXIMUM
} TDH_CONTEXT_TYPE;