typedef enum _D3DDDI_GAMMARAMP_TYPE {
  D3DDDI_GAMMARAMP_UNINITIALIZED,
  D3DDDI_GAMMARAMP_DEFAULT,
  D3DDDI_GAMMARAMP_RGB256x3x16,
  D3DDDI_GAMMARAMP_DXGI_1,
  D3DDDI_GAMMARAMP_MATRIX_3x4,
  D3DDDI_GAMMARAMP_MATRIX_V2
} D3DDDI_GAMMARAMP_TYPE;