typedef enum _D3DDDI_SYNCHRONIZATIONOBJECT_TYPE {
  D3DDDI_SYNCHRONIZATION_MUTEX,
  D3DDDI_SEMAPHORE,
  D3DDDI_FENCE,
  D3DDDI_CPU_NOTIFICATION,
  D3DDDI_MONITORED_FENCE,
  D3DDDI_PERIODIC_MONITORED_FENCE,
  D3DDDI_NATIVE_FENCE,
  D3DDDI_SYNCHRONIZATION_TYPE_LIMIT
} D3DDDI_SYNCHRONIZATIONOBJECT_TYPE;