typedef enum _DXGKVGPU_ESCAPE_TYPE {
  DXGKVGPU_ESCAPE_TYPE_READ_PCI_CONFIG,
  DXGKVGPU_ESCAPE_TYPE_WRITE_PCI_CONFIG,
  DXGKVGPU_ESCAPE_TYPE_INITIALIZE,
  DXGKVGPU_ESCAPE_TYPE_RELEASE,
  DXGKVGPU_ESCAPE_TYPE_GET_VGPU_TYPE,
  DXGKVGPU_ESCAPE_TYPE_POWERTRANSITIONCOMPLETE,
  DXGKVGPU_ESCAPE_TYPE_PAUSE,
  DXGKVGPU_ESCAPE_TYPE_RESUME
} DXGKVGPU_ESCAPE_TYPE;