typedef enum D3DDDI_FLIPINTERVAL_TYPE {
  D3DDDI_FLIPINTERVAL_IMMEDIATE,
  D3DDDI_FLIPINTERVAL_ONE,
  D3DDDI_FLIPINTERVAL_TWO,
  D3DDDI_FLIPINTERVAL_THREE,
  D3DDDI_FLIPINTERVAL_FOUR,
  D3DDDI_FLIPINTERVAL_IMMEDIATE_ALLOW_TEARING
} ;