typedef enum _DXGK_FEATURE_ID {
  DXGK_FEATURE_HWSCH,
  DXGK_FEATURE_HWFLIPQUEUE,
  DXGK_FEATURE_LDA_GPUPV,
  DXGK_FEATURE_KMD_SIGNAL_CPU_EVENT,
  DXGK_FEATURE_USER_MODE_SUBMISSION,
  DXGK_FEATURE_SHARE_BACKING_STORE_WITH_KMD,
  DXGK_FEATURE_SAMPLE,
  DXGK_FEATURE_PAGE_BASED_MEMORY_MANAGER,
  DXGK_FEATURE_KERNEL_MODE_TESTING,
  DXGK_FEATURE_64K_PT_DEMOTION_FIX,
  DXGK_FEATURE_GPUPV_PRESENT_HWQUEUE,
  DXGK_FEATURE_GPUVAIOMMU,
  DXGK_FEATURE_NATIVE_FENCE,
  DXGK_FEATURE_QUERYSTATISTICS_EXTENSIONS,
  DXGK_FEATURE_RESERVE_GPUVA_ZERO_BASE_ADDRESS,
  DXGK_FEATURE_PER_PTE_PAGE_SIZE,
  DXGK_FEATURE_FENCE_SIGNAL_FROM_SWS_NODE
} DXGK_FEATURE_ID;