typedef enum _D3DDDI_QUERYREGISTRY_TYPE {
  D3DDDI_QUERYREGISTRY_SERVICEKEY,
  D3DDDI_QUERYREGISTRY_ADAPTERKEY,
  D3DDDI_QUERYREGISTRY_DRIVERSTOREPATH,
  D3DDDI_QUERYREGISTRY_DRIVERIMAGEPATH,
  D3DDDI_QUERYREGISTRY_MAX
} D3DDDI_QUERYREGISTRY_TYPE;