typedef enum _D3DDDI_TESTCOMMANDBUFFEROP {
  D3DDDI_TESTCOMMANDBUFFEROP_INVALID = 0,
  D3DDDI_TESTCOMMANDBUFFEROP_COPY = 1,
  D3DDDI_TESTCOMMANDBUFFEROP_FILL = 2,
  D3DDDI_TESTCOMMANDBUFFEROP_INFINITE_LOOP = 3,
  D3DDDI_TESTCOMMANDBUFFEROP_INFINITE_PREEMPTABLE_LOOP = 4,
  D3DDDI_TESTCOMMANDBUFFEROP_MAX
} D3DDDI_TESTCOMMANDBUFFEROP;