typedef enum _D3DDDI_DRIVERESCAPETYPE {
  D3DDDI_DRIVERESCAPETYPE_TRANSLATEALLOCATIONHANDLE = 0,
  D3DDDI_DRIVERESCAPETYPE_TRANSLATERESOURCEHANDLE = 1,
  D3DDDI_DRIVERESCAPETYPE_CPUEVENTUSAGE = 2,
  D3DDDI_DRIVERESCAPETYPE_BUILDTESTCOMMANDBUFFER = 3,
  D3DDDI_DRIVERESCAPETYPE_MAX
} D3DDDI_DRIVERESCAPETYPE;