typedef enum _D3DDDI_OFFER_PRIORITY {
  D3DDDI_OFFER_PRIORITY_NONE,
  D3DDDI_OFFER_PRIORITY_LOW,
  D3DDDI_OFFER_PRIORITY_NORMAL,
  D3DDDI_OFFER_PRIORITY_HIGH,
  D3DDDI_OFFER_PRIORITY_AUTO
} D3DDDI_OFFER_PRIORITY;