typedef enum _D3DDDI_VIDEO_SIGNAL_SCANLINE_ORDERING {
  D3DDDI_VSSLO_UNINITIALIZED,
  D3DDDI_VSSLO_PROGRESSIVE,
  D3DDDI_VSSLO_INTERLACED_UPPERFIELDFIRST,
  D3DDDI_VSSLO_INTERLACED_LOWERFIELDFIRST,
  D3DDDI_VSSLO_OTHER
} D3DDDI_VIDEO_SIGNAL_SCANLINE_ORDERING;