typedef struct _D3DDDI_TESTCOMMANDBUFFER_COPY {
  D3DKMT_ALIGN64 D3DGPU_VIRTUAL_ADDRESS SrcAddress;
  D3DKMT_ALIGN64 D3DGPU_VIRTUAL_ADDRESS DstAddress;
  UINT                                  NumBytes;
} D3DDDI_TESTCOMMANDBUFFER_COPY;