typedef enum _MFVideoFlags {
  MFVideoFlag_PAD_TO_Mask,
  MFVideoFlag_PAD_TO_None,
  MFVideoFlag_PAD_TO_4x3,
  MFVideoFlag_PAD_TO_16x9,
  MFVideoFlag_SrcContentHintMask,
  MFVideoFlag_SrcContentHintNone,
  MFVideoFlag_SrcContentHint16x9,
  MFVideoFlag_SrcContentHint235_1,
  MFVideoFlag_AnalogProtected = 0x20,
  MFVideoFlag_DigitallyProtected = 0x40,
  MFVideoFlag_ProgressiveContent = 0x80,
  MFVideoFlag_FieldRepeatCountMask,
  MFVideoFlag_FieldRepeatCountShift = 8,
  MFVideoFlag_ProgressiveSeqReset = 0x800,
  MFVideoFlag_PanScanEnabled = 0x20000,
  MFVideoFlag_LowerFieldFirst = 0x40000,
  MFVideoFlag_BottomUpLinearRep = 0x80000,
  MFVideoFlags_DXVASurface = 0x100000,
  MFVideoFlags_RenderTargetSurface = 0x400000,
  MFVideoFlags_ForceQWORD = 0x7fffffff
} MFVideoFlags;