typedef enum _MF_ATTRIBUTE_TYPE {
  MF_ATTRIBUTE_UINT32 = VT_UI4,
  MF_ATTRIBUTE_UINT64 = VT_UI8,
  MF_ATTRIBUTE_DOUBLE = VT_R8,
  MF_ATTRIBUTE_GUID = VT_CLSID,
  MF_ATTRIBUTE_STRING = VT_LPWSTR,
  MF_ATTRIBUTE_BLOB,
  MF_ATTRIBUTE_IUNKNOWN = VT_UNKNOWN
} MF_ATTRIBUTE_TYPE;