typedef enum _NETISO_ERROR_TYPE {
  NETISO_ERROR_TYPE_NONE = 0x00,
  NETISO_ERROR_TYPE_PRIVATE_NETWORK = 0x01,
  NETISO_ERROR_TYPE_INTERNET_CLIENT = 0x02,
  NETISO_ERROR_TYPE_INTERNET_CLIENT_SERVER = 0x03,
  NETISO_ERROR_TYPE_MAX = 0x04
} NETISO_ERROR_TYPE;