typedef struct APO_NOTIFICATION_DESCRIPTOR {
  APO_NOTIFICATION_TYPE type;
  union {
    AUDIO_ENDPOINT_VOLUME_APO_NOTIFICATION_DESCRIPTOR               audioEndpointVolume;
    AUDIO_ENDPOINT_PROPERTY_CHANGE_APO_NOTIFICATION_DESCRIPTOR      audioEndpointPropertyChange;
    AUDIO_SYSTEMEFFECTS_PROPERTY_CHANGE_APO_NOTIFICATION_DESCRIPTOR audioSystemEffectsPropertyChange;
    AUDIO_MICROPHONE_BOOST_APO_NOTIFICATION_DESCRIPTOR              audioMicrophoneBoost;
  } DUMMYUNIONNAME;
} APO_NOTIFICATION_DESCRIPTOR;