typedef enum X509PrivateKeyExportFlags {
  XCN_NCRYPT_ALLOW_EXPORT_NONE = 0,
  XCN_NCRYPT_ALLOW_EXPORT_FLAG = 0x1,
  XCN_NCRYPT_ALLOW_PLAINTEXT_EXPORT_FLAG = 0x2,
  XCN_NCRYPT_ALLOW_ARCHIVING_FLAG = 0x4,
  XCN_NCRYPT_ALLOW_PLAINTEXT_ARCHIVING_FLAG = 0x8
} ;