typedef enum AlgorithmType {
  XCN_BCRYPT_UNKNOWN_INTERFACE = 0,
  XCN_BCRYPT_CIPHER_INTERFACE = 0x1,
  XCN_BCRYPT_HASH_INTERFACE = 0x2,
  XCN_BCRYPT_ASYMMETRIC_ENCRYPTION_INTERFACE = 0x3,
  XCN_BCRYPT_SIGNATURE_INTERFACE = 0x5,
  XCN_BCRYPT_SECRET_AGREEMENT_INTERFACE = 0x4,
  XCN_BCRYPT_RNG_INTERFACE = 0x6,
  XCN_BCRYPT_KEY_DERIVATION_INTERFACE = 0x7
} ;