typedef enum X509CertificateTemplateEnrollmentFlag {
  EnrollmentIncludeSymmetricAlgorithms = 0x1,
  EnrollmentPendAllRequests = 0x2,
  EnrollmentPublishToKRAContainer = 0x4,
  EnrollmentPublishToDS = 0x8,
  EnrollmentAutoEnrollmentCheckUserDSCertificate = 0x10,
  EnrollmentAutoEnrollment = 0x20,
  EnrollmentDomainAuthenticationNotRequired = 0x80,
  EnrollmentPreviousApprovalValidateReenrollment = 0x40,
  EnrollmentUserInteractionRequired = 0x100,
  EnrollmentAddTemplateName = 0x200,
  EnrollmentRemoveInvalidCertificateFromPersonalStore = 0x400,
  EnrollmentAllowEnrollOnBehalfOf = 0x800,
  EnrollmentAddOCSPNoCheck = 0x1000,
  EnrollmentReuseKeyOnFullSmartCard = 0x2000,
  EnrollmentNoRevocationInfoInCerts = 0x4000,
  EnrollmentIncludeBasicConstraintsForEECerts = 0x8000,
  EnrollmentPreviousApprovalKeyBasedValidateReenrollment = 0x10000,
  EnrollmentCertificateIssuancePoliciesFromRequest = 0x20000,
  EnrollmentSkipAutoRenewal = 0x40000
} ;