typedef enum X509PrivateKeyUsageFlags {
  XCN_NCRYPT_ALLOW_USAGES_NONE = 0,
  XCN_NCRYPT_ALLOW_DECRYPT_FLAG = 0x1,
  XCN_NCRYPT_ALLOW_SIGNING_FLAG = 0x2,
  XCN_NCRYPT_ALLOW_KEY_AGREEMENT_FLAG = 0x4,
  XCN_NCRYPT_ALLOW_KEY_IMPORT_FLAG = 0x8,
  XCN_NCRYPT_ALLOW_ALL_USAGES = 0xffffff
} ;