typedef enum X509KeyUsageFlags {
  XCN_CERT_NO_KEY_USAGE = 0,
  XCN_CERT_DIGITAL_SIGNATURE_KEY_USAGE = 0x80,
  XCN_CERT_NON_REPUDIATION_KEY_USAGE = 0x40,
  XCN_CERT_KEY_ENCIPHERMENT_KEY_USAGE = 0x20,
  XCN_CERT_DATA_ENCIPHERMENT_KEY_USAGE = 0x10,
  XCN_CERT_KEY_AGREEMENT_KEY_USAGE = 0x8,
  XCN_CERT_KEY_CERT_SIGN_KEY_USAGE = 0x4,
  XCN_CERT_OFFLINE_CRL_SIGN_KEY_USAGE = 0x2,
  XCN_CERT_CRL_SIGN_KEY_USAGE = 0x2,
  XCN_CERT_ENCIPHER_ONLY_KEY_USAGE = 0x1,
  XCN_CERT_DECIPHER_ONLY_KEY_USAGE = 0x8000
} ;