typedef enum X509PrivateKeyProtection {
  XCN_NCRYPT_UI_NO_PROTECTION_FLAG = 0,
  XCN_NCRYPT_UI_PROTECT_KEY_FLAG = 0x1,
  XCN_NCRYPT_UI_FORCE_HIGH_PROTECTION_FLAG = 0x2,
  XCN_NCRYPT_UI_FINGERPRINT_PROTECTION_FLAG = 0x4,
  XCN_NCRYPT_UI_APPCONTAINER_ACCESS_MEDIUM_FLAG = 0x8
} ;