typedef enum __MIDL___MIDL_itf_tapi3_0000_0018_0002 {
  CALL_NEW_STREAM = 0,
  CALL_STREAM_FAIL,
  CALL_TERMINAL_FAIL,
  CALL_STREAM_NOT_USED,
  CALL_STREAM_ACTIVE,
  CALL_STREAM_INACTIVE
} MSP_CALL_EVENT;