typedef enum __MIDL___MIDL_itf_tapi3_0000_0018_0004 {
  ME_ADDRESS_EVENT = 0,
  ME_CALL_EVENT,
  ME_TSP_DATA,
  ME_PRIVATE_EVENT,
  ME_ASR_TERMINAL_EVENT,
  ME_TTS_TERMINAL_EVENT,
  ME_FILE_TERMINAL_EVENT,
  ME_TONE_TERMINAL_EVENT
} MSP_EVENT;