typedef struct _UART_HARDWARE_ACCESS {
  UART_HARDWARE_READ_UCHAR    ReadPort8;
  UART_HARDWARE_WRITE_UCHAR   WritePort8;
  UART_HARDWARE_READ_USHORT   ReadPort16;
  UART_HARDWARE_WRITE_USHORT  WritePort16;
  UART_HARDWARE_READ_ULONG    ReadPort32;
  UART_HARDWARE_WRITE_ULONG   WritePort32;
  UART_HARDWARE_READ_UCHAR    ReadRegister8;
  UART_HARDWARE_WRITE_UCHAR   WriteRegister8;
  UART_HARDWARE_READ_USHORT   ReadRegister16;
  UART_HARDWARE_WRITE_USHORT  WriteRegister16;
  UART_HARDWARE_READ_ULONG    ReadRegister32;
  UART_HARDWARE_WRITE_ULONG   WriteRegister32;
  UART_HARDWARE_READ_ULONG64  ReadRegister64;
  UART_HARDWARE_WRITE_ULONG64 WriteRegister64;
} UART_HARDWARE_ACCESS, *PUART_HARDWARE_ACCESS;