typedef enum MBN_SMS_CDMA_LANG {
  MBN_SMS_CDMA_LANG_NONE = 0,
  MBN_SMS_CDMA_LANG_ENGLISH,
  MBN_SMS_CDMA_LANG_FRENCH,
  MBN_SMS_CDMA_LANG_SPANISH,
  MBN_SMS_CDMA_LANG_JAPANESE,
  MBN_SMS_CDMA_LANG_KOREAN,
  MBN_SMS_CDMA_LANG_CHINESE,
  MBN_SMS_CDMA_LANG_HEBREW
} ;