typedef enum MBN_ACTIVATION_STATE {
  MBN_ACTIVATION_STATE_NONE = 0,
  MBN_ACTIVATION_STATE_ACTIVATED,
  MBN_ACTIVATION_STATE_ACTIVATING,
  MBN_ACTIVATION_STATE_DEACTIVATED,
  MBN_ACTIVATION_STATE_DEACTIVATING
} ;