typedef enum MBN_READY_STATE {
  MBN_READY_STATE_OFF = 0,
  MBN_READY_STATE_INITIALIZED,
  MBN_READY_STATE_SIM_NOT_INSERTED,
  MBN_READY_STATE_BAD_SIM,
  MBN_READY_STATE_FAILURE,
  MBN_READY_STATE_NOT_ACTIVATED,
  MBN_READY_STATE_DEVICE_LOCKED,
  MBN_READY_STATE_DEVICE_BLOCKED,
  MBN_READY_STATE_NO_ESIM_PROFILE
} ;