typedef enum MBN_REGISTER_STATE {
  MBN_REGISTER_STATE_NONE = 0,
  MBN_REGISTER_STATE_DEREGISTERED,
  MBN_REGISTER_STATE_SEARCHING,
  MBN_REGISTER_STATE_HOME,
  MBN_REGISTER_STATE_ROAMING,
  MBN_REGISTER_STATE_PARTNER,
  MBN_REGISTER_STATE_DENIED
} ;