typedef enum MBN_PROVIDER_STATE {
  MBN_PROVIDER_STATE_NONE = 0,
  MBN_PROVIDER_STATE_HOME = 0x1,
  MBN_PROVIDER_STATE_FORBIDDEN = 0x2,
  MBN_PROVIDER_STATE_PREFERRED = 0x4,
  MBN_PROVIDER_STATE_VISIBLE = 0x8,
  MBN_PROVIDER_STATE_REGISTERED = 0x10,
  MBN_PROVIDER_STATE_PREFERRED_MULTICARRIER = 0x20
} ;