typedef enum MBN_PIN_TYPE {
  MBN_PIN_TYPE_NONE = 0,
  MBN_PIN_TYPE_CUSTOM,
  MBN_PIN_TYPE_PIN1,
  MBN_PIN_TYPE_PIN2,
  MBN_PIN_TYPE_DEVICE_SIM_PIN,
  MBN_PIN_TYPE_DEVICE_FIRST_SIM_PIN,
  MBN_PIN_TYPE_NETWORK_PIN,
  MBN_PIN_TYPE_NETWORK_SUBSET_PIN,
  MBN_PIN_TYPE_SVC_PROVIDER_PIN,
  MBN_PIN_TYPE_CORPORATE_PIN,
  MBN_PIN_TYPE_SUBSIDY_LOCK
} ;