typedef enum MBN_SMS_CDMA_ENCODING {
  MBN_SMS_CDMA_ENCODING_OCTET = 0,
  MBN_SMS_CDMA_ENCODING_EPM,
  MBN_SMS_CDMA_ENCODING_7BIT_ASCII,
  MBN_SMS_CDMA_ENCODING_IA5,
  MBN_SMS_CDMA_ENCODING_UNICODE,
  MBN_SMS_CDMA_ENCODING_SHIFT_JIS,
  MBN_SMS_CDMA_ENCODING_KOREAN,
  MBN_SMS_CDMA_ENCODING_LATIN_HEBREW,
  MBN_SMS_CDMA_ENCODING_LATIN,
  MBN_SMS_CDMA_ENCODING_GSM_7BIT
} ;