typedef enum MBN_CONTEXT_TYPE {
  MBN_CONTEXT_TYPE_NONE = 0,
  MBN_CONTEXT_TYPE_INTERNET,
  MBN_CONTEXT_TYPE_VPN,
  MBN_CONTEXT_TYPE_VOICE,
  MBN_CONTEXT_TYPE_VIDEO_SHARE,
  MBN_CONTEXT_TYPE_CUSTOM,
  MBN_CONTEXT_TYPE_PURCHASE
} ;