typedef enum MBN_CTRL_CAPS {
  MBN_CTRL_CAPS_NONE = 0,
  MBN_CTRL_CAPS_REG_MANUAL = 0x1,
  MBN_CTRL_CAPS_HW_RADIO_SWITCH = 0x2,
  MBN_CTRL_CAPS_CDMA_MOBILE_IP = 0x4,
  MBN_CTRL_CAPS_CDMA_SIMPLE_IP = 0x8,
  MBN_CTRL_CAPS_PROTECT_UNIQUEID = 0x10,
  MBN_CTRL_CAPS_MODEL_MULTI_CARRIER = 0x20,
  MBN_CTRL_CAPS_USSD = 0x40,
  MBN_CTRL_CAPS_MULTI_MODE = 0x80
} ;