typedef enum DXGI_DDI_FLIP_INTERVAL_TYPE {
  DXGI_DDI_FLIP_INTERVAL_IMMEDIATE,
  DXGI_DDI_FLIP_INTERVAL_ONE,
  DXGI_DDI_FLIP_INTERVAL_TWO,
  DXGI_DDI_FLIP_INTERVAL_THREE,
  DXGI_DDI_FLIP_INTERVAL_FOUR,
  DXGI_DDI_FLIP_INTERVAL_IMMEDIATE_ALLOW_TEARING
} ;