typedef enum DXGI_DDI_MODE_ROTATION {
  DXGI_DDI_MODE_ROTATION_UNSPECIFIED,
  DXGI_DDI_MODE_ROTATION_IDENTITY,
  DXGI_DDI_MODE_ROTATION_ROTATE90,
  DXGI_DDI_MODE_ROTATION_ROTATE180,
  DXGI_DDI_MODE_ROTATION_ROTATE270
} ;