typedef struct DXGI_DDI_BASE_CALLBACKS {
  PFNDDXGIDDI_PRESENTCB                     pfnPresentCb;
  PFNDDXGIDDI_PRESENT_MULTIPLANE_OVERLAYCB  pfnPresentMultiplaneOverlayCb;
  PFNDDXGIDDI_PRESENT_MULTIPLANE_OVERLAY1CB pfnPresentMultiplaneOverlay1Cb;
  PFNDDXGIDDI_SUBMITPRESENTBLTTOHWQUEUECB   pfnSubmitPresentBltToHwQueueCb;
  PFNDDXGIDDI_SUBMITPRESENTTOHWQUEUECB      pfnSubmitPresentToHwQueueCb;
} DXGI_DDI_BASE_CALLBACKS;