typedef struct _DXGI_DDI_ARG_GETMULTIPLANEOVERLAYCAPS {
  [in]  DXGI_DDI_HDEVICE                 hDevice;
  [in]  D3DDDI_VIDEO_PRESENT_SOURCE_ID   VidPnSourceId;
  [out] DXGI_DDI_MULTIPLANE_OVERLAY_CAPS MultiplaneOverlayCaps;
} DXGI_DDI_ARG_GETMULTIPLANEOVERLAYCAPS;