typedef enum APPX_CAPABILITIES {
  APPX_CAPABILITY_INTERNET_CLIENT,
  APPX_CAPABILITY_INTERNET_CLIENT_SERVER,
  APPX_CAPABILITY_PRIVATE_NETWORK_CLIENT_SERVER,
  APPX_CAPABILITY_DOCUMENTS_LIBRARY,
  APPX_CAPABILITY_PICTURES_LIBRARY,
  APPX_CAPABILITY_VIDEOS_LIBRARY,
  APPX_CAPABILITY_MUSIC_LIBRARY,
  APPX_CAPABILITY_ENTERPRISE_AUTHENTICATION,
  APPX_CAPABILITY_SHARED_USER_CERTIFICATES,
  APPX_CAPABILITY_REMOVABLE_STORAGE,
  APPX_CAPABILITY_APPOINTMENTS,
  APPX_CAPABILITY_CONTACTS
} ;