typedef enum APPX_FOOTPRINT_FILE_TYPE {
  APPX_FOOTPRINT_FILE_TYPE_MANIFEST,
  APPX_FOOTPRINT_FILE_TYPE_BLOCKMAP,
  APPX_FOOTPRINT_FILE_TYPE_SIGNATURE,
  APPX_FOOTPRINT_FILE_TYPE_CODEINTEGRITY,
  APPX_FOOTPRINT_FILE_TYPE_CONTENTGROUPMAP
} ;