typedef enum APPX_PACKAGE_ARCHITECTURE2 {
  APPX_PACKAGE_ARCHITECTURE2_X86,
  APPX_PACKAGE_ARCHITECTURE2_ARM,
  APPX_PACKAGE_ARCHITECTURE2_X64,
  APPX_PACKAGE_ARCHITECTURE2_NEUTRAL,
  APPX_PACKAGE_ARCHITECTURE2_ARM64,
  APPX_PACKAGE_ARCHITECTURE2_X86_ON_ARM64,
  APPX_PACKAGE_ARCHITECTURE2_UNKNOWN
} ;