typedef enum APPX_COMPRESSION_OPTION {
  APPX_COMPRESSION_OPTION_NONE,
  APPX_COMPRESSION_OPTION_NORMAL,
  APPX_COMPRESSION_OPTION_MAXIMUM,
  APPX_COMPRESSION_OPTION_FAST,
  APPX_COMPRESSION_OPTION_SUPERFAST
} ;