typedef enum APPX_PACKAGE_ARCHITECTURE {
  APPX_PACKAGE_ARCHITECTURE_X86,
  APPX_PACKAGE_ARCHITECTURE_ARM,
  APPX_PACKAGE_ARCHITECTURE_X64,
  APPX_PACKAGE_ARCHITECTURE_NEUTRAL,
  APPX_PACKAGE_ARCHITECTURE_ARM64
} ;