typedef enum APPX_BUNDLE_FOOTPRINT_FILE_TYPE {
  APPX_BUNDLE_FOOTPRINT_FILE_TYPE_FIRST,
  APPX_BUNDLE_FOOTPRINT_FILE_TYPE_MANIFEST,
  APPX_BUNDLE_FOOTPRINT_FILE_TYPE_BLOCKMAP,
  APPX_BUNDLE_FOOTPRINT_FILE_TYPE_SIGNATURE,
  APPX_BUNDLE_FOOTPRINT_FILE_TYPE_LAST
} ;