typedef enum _VSS_MGMT_OBJECT_TYPE {
  VSS_MGMT_OBJECT_UNKNOWN = 0,
  VSS_MGMT_OBJECT_VOLUME,
  VSS_MGMT_OBJECT_DIFF_VOLUME,
  VSS_MGMT_OBJECT_DIFF_AREA
} VSS_MGMT_OBJECT_TYPE, *PVSS_MGMT_OBJECT_TYPE;