typedef enum _MF_QUALITY_DROP_MODE {
  MF_DROP_MODE_NONE = 0,
  MF_DROP_MODE_1 = 0x1,
  MF_DROP_MODE_2 = 0x2,
  MF_DROP_MODE_3 = 0x3,
  MF_DROP_MODE_4 = 0x4,
  MF_DROP_MODE_5 = 0x5,
  MF_NUM_DROP_MODES = 0x6
} MF_QUALITY_DROP_MODE;