typedef enum MF_MEDIAKEY_STATUS {
  MF_MEDIAKEY_STATUS_USABLE = 0,
  MF_MEDIAKEY_STATUS_EXPIRED,
  MF_MEDIAKEY_STATUS_OUTPUT_DOWNSCALED,
  MF_MEDIAKEY_STATUS_OUTPUT_NOT_ALLOWED,
  MF_MEDIAKEY_STATUS_STATUS_PENDING,
  MF_MEDIAKEY_STATUS_INTERNAL_ERROR,
  MF_MEDIAKEY_STATUS_RELEASED,
  MF_MEDIAKEY_STATUS_OUTPUT_RESTRICTED
} ;