typedef enum _MF_CONNECT_METHOD {
  MF_CONNECT_DIRECT = 0,
  MF_CONNECT_ALLOW_CONVERTER = 0x1,
  MF_CONNECT_ALLOW_DECODER = 0x3,
  MF_CONNECT_RESOLVE_INDEPENDENT_OUTPUTTYPES = 0x4,
  MF_CONNECT_AS_OPTIONAL = 0x10000,
  MF_CONNECT_AS_OPTIONAL_BRANCH = 0x20000
} MF_CONNECT_METHOD;