typedef enum MF_MEDIAKEYSESSION_TYPE {
  MF_MEDIAKEYSESSION_TYPE_TEMPORARY = 0,
  MF_MEDIAKEYSESSION_TYPE_PERSISTENT_LICENSE,
  MF_MEDIAKEYSESSION_TYPE_PERSISTENT_RELEASE_MESSAGE,
  MF_MEDIAKEYSESSION_TYPE_PERSISTENT_USAGE_RECORD
} ;