typedef enum _MF_OPM_CGMSA_PROTECTION_LEVEL {
  MF_OPM_CGMSA_OFF = 0,
  MF_OPM_CGMSA_COPY_FREELY = 0x1,
  MF_OPM_CGMSA_COPY_NO_MORE = 0x2,
  MF_OPM_CGMSA_COPY_ONE_GENERATION = 0x3,
  MF_OPM_CGMSA_COPY_NEVER = 0x4,
  MF_OPM_CGMSA_REDISTRIBUTION_CONTROL_REQUIRED = 0x8
} MF_OPM_CGMSA_PROTECTION_LEVEL;