typedef enum _MFNETSOURCE_PROTOCOL_TYPE {
  MFNETSOURCE_UNDEFINED = 0,
  MFNETSOURCE_HTTP = 0x1,
  MFNETSOURCE_RTSP = 0x2,
  MFNETSOURCE_FILE = 0x3,
  MFNETSOURCE_MULTICAST = 0x4
} MFNETSOURCE_PROTOCOL_TYPE;