typedef enum UI_FONTVERTICALPOSITION {
  UI_FONTVERTICALPOSITION_NOTAVAILABLE = 0,
  UI_FONTVERTICALPOSITION_NOTSET = 1,
  UI_FONTVERTICALPOSITION_SUPERSCRIPT = 2,
  UI_FONTVERTICALPOSITION_SUBSCRIPT = 3
} ;