typedef enum UI_COMMANDTYPE {
  UI_COMMANDTYPE_UNKNOWN = 0,
  UI_COMMANDTYPE_GROUP = 1,
  UI_COMMANDTYPE_ACTION = 2,
  UI_COMMANDTYPE_ANCHOR = 3,
  UI_COMMANDTYPE_CONTEXT = 4,
  UI_COMMANDTYPE_COLLECTION = 5,
  UI_COMMANDTYPE_COMMANDCOLLECTION = 6,
  UI_COMMANDTYPE_DECIMAL = 7,
  UI_COMMANDTYPE_BOOLEAN = 8,
  UI_COMMANDTYPE_FONT = 9,
  UI_COMMANDTYPE_RECENTITEMS = 10,
  UI_COMMANDTYPE_COLORANCHOR = 11,
  UI_COMMANDTYPE_COLORCOLLECTION = 12
} ;