typedef struct _DD_CREATESURFACEEXDATA {
  DWORD                dwFlags;
  PDD_DIRECTDRAW_LOCAL lpDDLcl;
  PDD_SURFACE_LOCAL    lpDDSLcl;
  HRESULT              ddRVal;
} *PDD_CREATESURFACEEXDATA, DD_CREATESURFACEEXDATA;