typedef struct _DD_QUERYMOCOMPSTATUSDATA {
  PDD_DIRECTDRAW_LOCAL lpDD;
  PDD_MOTIONCOMP_LOCAL lpMoComp;
  PDD_SURFACE_LOCAL    lpSurface;
  DWORD                dwFlags;
  HRESULT              ddRVal;
} *PDD_QUERYMOCOMPSTATUSDATA, DD_QUERYMOCOMPSTATUSDATA;