typedef enum D2D1_TEXT_ANTIALIAS_MODE {
  D2D1_TEXT_ANTIALIAS_MODE_DEFAULT = 0,
  D2D1_TEXT_ANTIALIAS_MODE_CLEARTYPE = 1,
  D2D1_TEXT_ANTIALIAS_MODE_GRAYSCALE = 2,
  D2D1_TEXT_ANTIALIAS_MODE_ALIASED = 3,
  D2D1_TEXT_ANTIALIAS_MODE_FORCE_DWORD = 0xffffffff
} ;