typedef enum D2D1_OPACITY_MASK_CONTENT {
  D2D1_OPACITY_MASK_CONTENT_GRAPHICS = 0,
  D2D1_OPACITY_MASK_CONTENT_TEXT_NATURAL = 1,
  D2D1_OPACITY_MASK_CONTENT_TEXT_GDI_COMPATIBLE = 2,
  D2D1_OPACITY_MASK_CONTENT_FORCE_DWORD = 0xffffffff
} ;