typedef enum D2D1_DEBUG_LEVEL {
  D2D1_DEBUG_LEVEL_NONE = 0,
  D2D1_DEBUG_LEVEL_ERROR = 1,
  D2D1_DEBUG_LEVEL_WARNING = 2,
  D2D1_DEBUG_LEVEL_INFORMATION = 3,
  D2D1_DEBUG_LEVEL_FORCE_DWORD = 0xffffffff
} ;