typedef enum tag_WBEM_COMPARISON_FLAG {
  WBEM_COMPARISON_INCLUDE_ALL = 0,
  WBEM_FLAG_IGNORE_QUALIFIERS = 0x1,
  WBEM_FLAG_IGNORE_OBJECT_SOURCE = 0x2,
  WBEM_FLAG_IGNORE_DEFAULT_VALUES = 0x4,
  WBEM_FLAG_IGNORE_CLASS = 0x8,
  WBEM_FLAG_IGNORE_CASE = 0x10,
  WBEM_FLAG_IGNORE_FLAVOR = 0x20
} WBEM_COMPARISON_FLAG;