typedef enum tag_WBEM_SECURITY_FLAGS {
  WBEM_ENABLE = 1,
  WBEM_METHOD_EXECUTE = 2,
  WBEM_FULL_WRITE_REP = 4,
  WBEM_PARTIAL_WRITE_REP = 8,
  WBEM_WRITE_PROVIDER = 0x10,
  WBEM_REMOTE_ACCESS = 0x20,
  WBEM_RIGHT_SUBSCRIBE = 0x40,
  WBEM_RIGHT_PUBLISH = 0x80
} WBEM_SECURITY_FLAGS;