typedef enum _PNRP_CLOUD_STATE {
  PNRP_CLOUD_STATE_VIRTUAL = 0,
  PNRP_CLOUD_STATE_SYNCHRONISING = 1,
  PNRP_CLOUD_STATE_ACTIVE = 2,
  PNRP_CLOUD_STATE_DEAD = 3,
  PNRP_CLOUD_STATE_DISABLED = 4,
  PNRP_CLOUD_STATE_NO_NET = 5,
  PNRP_CLOUD_STATE_ALONE = 6
} PNRP_CLOUD_STATE;