typedef enum _PNRP_RESOLVE_CRITERIA {
  PNRP_RESOLVE_CRITERIA_DEFAULT = 0,
  PNRP_RESOLVE_CRITERIA_REMOTE_PEER_NAME = 1,
  PNRP_RESOLVE_CRITERIA_NEAREST_REMOTE_PEER_NAME = 2,
  PNRP_RESOLVE_CRITERIA_NON_CURRENT_PROCESS_PEER_NAME = 3,
  PNRP_RESOLVE_CRITERIA_NEAREST_NON_CURRENT_PROCESS_PEER_NAME = 4,
  PNRP_RESOLVE_CRITERIA_ANY_PEER_NAME = 5,
  PNRP_RESOLVE_CRITERIA_NEAREST_PEER_NAME
} PNRP_RESOLVE_CRITERIA;