typedef enum {
  NVME_CMBSZ_SIZE_UNITS_4KB,
  NVME_CMBSZ_SIZE_UNITS_64KB,
  NVME_CMBSZ_SIZE_UNITS_1MB,
  NVME_CMBSZ_SIZE_UNITS_16MB,
  NVME_CMBSZ_SIZE_UNITS_256MB,
  NVME_CMBSZ_SIZE_UNITS_4GB,
  NVME_CMBSZ_SIZE_UNITS_64GB
} NVME_CMBSZ_SIZE_UNITS;