typedef enum {
  NVME_PROTECTION_INFORMATION_NOT_ENABLED,
  NVME_PROTECTION_INFORMATION_TYPE1,
  NVME_PROTECTION_INFORMATION_TYPE2,
  NVME_PROTECTION_INFORMATION_TYPE3
} NVME_PROTECTION_INFORMATION_TYPES;