typedef enum {
  NVME_ASYNC_EVENT_TYPE_ERROR_STATUS,
  NVME_ASYNC_EVENT_TYPE_HEALTH_STATUS,
  NVME_ASYNC_EVENT_TYPE_NOTICE,
  NVME_ASYNC_EVENT_TYPE_IO_COMMAND_SET_STATUS,
  NVME_ASYNC_EVENT_TYPE_VENDOR_SPECIFIC
} NVME_ASYNC_EVENT_TYPES;