typedef enum {
  NVME_ACCESS_FREQUENCY_NONE,
  NVME_ACCESS_FREQUENCY_TYPICAL,
  NVME_ACCESS_FREQUENCY_INFR_WRITE_INFR_READ,
  NVME_ACCESS_FREQUENCY_INFR_WRITE_FR_READ,
  NVME_ACCESS_FREQUENCY_FR_WRITE_INFR_READ,
  NVME_ACCESS_FREQUENCY_FR_WRITE_FR_READ,
  NVME_ACCESS_FREQUENCY_ONE_TIME_READ,
  NVME_ACCESS_FREQUENCY_SPECULATIVE_READ,
  NVME_ACCESS_FREQUENCY_WILL_BE_OVERWRITTEN
} NVME_ACCESS_FREQUENCIES;