typedef union {
  struct {
    ULONGLONG Reserved0 : 12;
    ULONGLONG ASQB : 52;
  } DUMMYSTRUCTNAME;
  ULONGLONG AsUlonglong;
} NVME_ADMIN_SUBMISSION_QUEUE_BASE_ADDRESS, *PNVME_ADMIN_SUBMISSION_QUEUE_BASE_ADDRESS;