typedef struct {
  USHORT MSL;
  USHORT NSSA;
  USHORT NSSO;
  UCHAR  Reserved0[10];
  ULONG  SWS;
  USHORT SGS;
  USHORT NSA;
  USHORT NSO;
  UCHAR  Reserved1[6];
} NVME_DIRECTIVE_STREAMS_RETURN_PARAMETERS, *PNVME_DIRECTIVE_STREAMS_RETURN_PARAMETERS;