typedef union {
  struct {
    ULONG SAVE : 1;
    ULONG NSS : 1;
    ULONG MOD : 1;
    ULONG Reserved0 : 29;
  } DUMMYSTRUCTNAME;
  ULONG  AsUlong;
} NVME_CDW11_FEATURE_SUPPORTED_CAPABILITY, *PNVME_CDW11_FEATURE_SUPPORTED_CAPABILITY;