typedef union {
  struct {
    ULONG IV : 16;
    ULONG CD : 1;
    ULONG Reserved0 : 15;
  } DUMMYSTRUCTNAME;
  ULONG  AsUlong;
} NVME_CDW11_FEATURE_INTERRUPT_VECTOR_CONFIG, *PNVME_CDW11_FEATURE_INTERRUPT_VECTOR_CONFIG;