typedef union {
  struct {
    ULONG BIR : 3;
    ULONG Reserved : 9;
    ULONG OFST : 20;
  } DUMMYSTRUCTNAME;
  ULONG  AsUlong;
} NVME_CONTROLLER_MEMORY_BUFFER_LOCATION, *PNVME_CONTROLLER_MEMORY_BUFFER_LOCATION;