typedef struct {
  UCHAR Identify : 1;
  UCHAR Streams : 1;
  UCHAR Reserved0 : 6;
  UCHAR Reserved1[31];
} NVME_DIRECTIVE_IDENTIFY_RETURN_PARAMETERS_DESCRIPTOR, *PNVME_DIRECTIVE_IDENTIFY_RETURN_PARAMETERS_DESCRIPTOR;