typedef struct {
  NVME_COMMAND_DWORD0 CDW0;
  ULONG               NSID;
  ULONG               Reserved0[2];
  ULONGLONG           MPTR;
  ULONGLONG           PRP1;
  ULONGLONG           PRP2;
  union {
    struct {
      ULONG CDW10;
      ULONG CDW11;
      ULONG CDW12;
      ULONG CDW13;
      ULONG CDW14;
      ULONG CDW15;
    } GENERAL;
    struct {
      NVME_CDW10_IDENTIFY CDW10;
      NVME_CDW11_IDENTIFY CDW11;
      ULONG               CDW12;
      ULONG               CDW13;
      ULONG               CDW14;
      ULONG               CDW15;
    } IDENTIFY;
    struct {
      NVME_CDW10_ABORT CDW10;
      ULONG            CDW11;
      ULONG            CDW12;
      ULONG            CDW13;
      ULONG            CDW14;
      ULONG            CDW15;
    } ABORT;
    struct {
      NVME_CDW10_GET_FEATURES CDW10;
      NVME_CDW11_FEATURES     CDW11;
      ULONG                   CDW12;
      ULONG                   CDW13;
      ULONG                   CDW14;
      ULONG                   CDW15;
    } GETFEATURES;
    struct {
      NVME_CDW10_SET_FEATURES CDW10;
      NVME_CDW11_FEATURES     CDW11;
      NVME_CDW12_FEATURES     CDW12;
      NVME_CDW13_FEATURES     CDW13;
      NVME_CDW14_FEATURES     CDW14;
      NVME_CDW15_FEATURES     CDW15;
    } SETFEATURES;
    struct {
      union {
        NVME_CDW10_GET_LOG_PAGE     CDW10;
        NVME_CDW10_GET_LOG_PAGE_V13 CDW10_V13;
      };
      NVME_CDW11_GET_LOG_PAGE CDW11;
      NVME_CDW12_GET_LOG_PAGE CDW12;
      NVME_CDW13_GET_LOG_PAGE CDW13;
      NVME_CDW14_GET_LOG_PAGE CDW14;
      ULONG                   CDW15;
    } GETLOGPAGE;
    struct {
      NVME_CDW10_CREATE_IO_QUEUE CDW10;
      NVME_CDW11_CREATE_IO_CQ    CDW11;
      ULONG                      CDW12;
      ULONG                      CDW13;
      ULONG                      CDW14;
      ULONG                      CDW15;
    } CREATEIOCQ;
    struct {
      NVME_CDW10_CREATE_IO_QUEUE CDW10;
      NVME_CDW11_CREATE_IO_SQ    CDW11;
      ULONG                      CDW12;
      ULONG                      CDW13;
      ULONG                      CDW14;
      ULONG                      CDW15;
    } CREATEIOSQ;
    struct {
      NVME_CDW10_DATASET_MANAGEMENT CDW10;
      NVME_CDW11_DATASET_MANAGEMENT CDW11;
      ULONG                         CDW12;
      ULONG                         CDW13;
      ULONG                         CDW14;
      ULONG                         CDW15;
    } DATASETMANAGEMENT;
    struct {
      NVME_CDW10_SECURITY_SEND_RECEIVE CDW10;
      NVME_CDW11_SECURITY_SEND         CDW11;
      ULONG                            CDW12;
      ULONG                            CDW13;
      ULONG                            CDW14;
      ULONG                            CDW15;
    } SECURITYSEND;
    struct {
      NVME_CDW10_SECURITY_SEND_RECEIVE CDW10;
      NVME_CDW11_SECURITY_RECEIVE      CDW11;
      ULONG                            CDW12;
      ULONG                            CDW13;
      ULONG                            CDW14;
      ULONG                            CDW15;
    } SECURITYRECEIVE;
    struct {
      NVME_CDW10_FIRMWARE_DOWNLOAD CDW10;
      NVME_CDW11_FIRMWARE_DOWNLOAD CDW11;
      ULONG                        CDW12;
      ULONG                        CDW13;
      ULONG                        CDW14;
      ULONG                        CDW15;
    } FIRMWAREDOWNLOAD;
    struct {
      NVME_CDW10_FIRMWARE_ACTIVATE CDW10;
      ULONG                        CDW11;
      ULONG                        CDW12;
      ULONG                        CDW13;
      ULONG                        CDW14;
      ULONG                        CDW15;
    } FIRMWAREACTIVATE;
    struct {
      NVME_CDW10_FORMAT_NVM CDW10;
      ULONG                 CDW11;
      ULONG                 CDW12;
      ULONG                 CDW13;
      ULONG                 CDW14;
      ULONG                 CDW15;
    } FORMATNVM;
    struct {
      NVME_CDW10_DIRECTIVE_RECEIVE CDW10;
      NVME_CDW11_DIRECTIVE_RECEIVE CDW11;
      NVME_CDW12_DIRECTIVE_RECEIVE CDW12;
      ULONG                        CDW13;
      ULONG                        CDW14;
      ULONG                        CDW15;
    } DIRECTIVERECEIVE;
    struct {
      NVME_CDW10_DIRECTIVE_SEND CDW10;
      NVME_CDW11_DIRECTIVE_SEND CDW11;
      NVME_CDW12_DIRECTIVE_SEND CDW12;
      ULONG                     CDW13;
      ULONG                     CDW14;
      ULONG                     CDW15;
    } DIRECTIVESEND;
    struct {
      NVME_CDW10_SANITIZE CDW10;
      NVME_CDW11_SANITIZE CDW11;
      ULONG               CDW12;
      ULONG               CDW13;
      ULONG               CDW14;
      ULONG               CDW15;
    } SANITIZE;
    struct {
      ULONG                 LBALOW;
      ULONG                 LBAHIGH;
      NVME_CDW12_READ_WRITE CDW12;
      NVME_CDW13_READ_WRITE CDW13;
      ULONG                 CDW14;
      NVME_CDW15_READ_WRITE CDW15;
    } READWRITE;
    struct {
      NVME_CDW10_RESERVATION_ACQUIRE CDW10;
      ULONG                          CDW11;
      ULONG                          CDW12;
      ULONG                          CDW13;
      ULONG                          CDW14;
      ULONG                          CDW15;
    } RESERVATIONACQUIRE;
    struct {
      NVME_CDW10_RESERVATION_REGISTER CDW10;
      ULONG                           CDW11;
      ULONG                           CDW12;
      ULONG                           CDW13;
      ULONG                           CDW14;
      ULONG                           CDW15;
    } RESERVATIONREGISTER;
    struct {
      NVME_CDW10_RESERVATION_RELEASE CDW10;
      ULONG                          CDW11;
      ULONG                          CDW12;
      ULONG                          CDW13;
      ULONG                          CDW14;
      ULONG                          CDW15;
    } RESERVATIONRELEASE;
    struct {
      NVME_CDW10_RESERVATION_REPORT CDW10;
      NVME_CDW11_RESERVATION_REPORT CDW11;
      ULONG                         CDW12;
      ULONG                         CDW13;
      ULONG                         CDW14;
      ULONG                         CDW15;
    } RESERVATIONREPORT;
    struct {
      NVME_CDW10_ZONE_MANAGEMENT_SEND CDW1011;
      ULONG                           CDW12;
      NVME_CDW13_ZONE_MANAGEMENT_SEND CDW13;
      ULONG                           CDW14;
      ULONG                           CDW15;
    } ZONEMANAGEMENTSEND;
    struct {
      NVME_CDW10_ZONE_MANAGEMENT_RECEIVE CDW1011;
      ULONG                              DWORDCOUNT;
      NVME_CDW13_ZONE_MANAGEMENT_RECEIVE CDW13;
      ULONG                              CDW14;
      ULONG                              CDW15;
    } ZONEMANAGEMENTRECEIVE;
    struct {
      NVME_CDW10_ZONE_APPEND CDW1011;
      NVME_CDW12_ZONE_APPEND CDW12;
      ULONG                  CDW13;
      ULONG                  ILBRT;
      NVME_CDW15_ZONE_APPEND CDW15;
    } ZONEAPPEND;
  } u;
} NVME_COMMAND, *PNVME_COMMAND;