typedef union {
  struct {
    ULONG NSR : 16;
    ULONG Reserved : 16;
  } DUMMYSTRUCTNAME;
  ULONG  AsUlong;
} NVME_CDW12_DIRECTIVE_RECEIVE_STREAMS_ALLOCATE_RESOURCES, *PNVME_CDW12_DIRECTIVE_RECEIVE_STREAMS_ALLOCATE_RESOURCES;