typedef union {
  struct {
    ULONG TMPTH : 16;
    ULONG TMPSEL : 4;
    ULONG THSEL : 2;
    ULONG Reserved0 : 10;
  } DUMMYSTRUCTNAME;
  ULONG  AsUlong;
} NVME_CDW11_FEATURE_TEMPERATURE_THRESHOLD, *PNVME_CDW11_FEATURE_TEMPERATURE_THRESHOLD;