typedef union {
  struct {
    ULONG ENDIR : 1;
    ULONG Reserved0 : 7;
    ULONG DTYPE : 8;
    ULONG Reserved1 : 16;
  } DUMMYSTRUCTNAME;
  ULONG  AsUlong;
} NVME_CDW12_DIRECTIVE_SEND_IDENTIFY_ENABLE_DIRECTIVE, *PNVME_CDW12_DIRECTIVE_SEND_IDENTIFY_ENABLE_DIRECTIVE;