typedef union {
  struct {
    ULONGLONG Reserved0 : 12;
    ULONGLONG ACQB : 52;
  } DUMMYSTRUCTNAME;
  ULONGLONG AsUlonglong;
} NVME_ADMIN_COMPLETION_QUEUE_BASE_ADDRESS, *PNVME_ADMIN_COMPLETION_QUEUE_BASE_ADDRESS;