typedef struct _RAS_PROJECTION_INFO {
  RASAPIVERSION           version;
  RASPROJECTION_INFO_TYPE type;
  union {
    RASPPP_PROJECTION_INFO   ppp;
    RASIKEV2_PROJECTION_INFO ikev2;
  };
} RAS_PROJECTION_INFO, *PRAS_PROJECTION_INFO;