typedef enum {
  KS_CAPTURE_ALLOC_INVALID,
  KS_CAPTURE_ALLOC_SYSTEM,
  KS_CAPTURE_ALLOC_VRAM,
  KS_CAPTURE_ALLOC_SYSTEM_AGP,
  KS_CAPTURE_ALLOC_VRAM_MAPPED,
  KS_CAPTURE_ALLOC_SECURE_BUFFER
} CAPTURE_MEMORY_ALLOCATION_FLAGS, *PCAPTURE_MEMORY_ALLOCATION_FLAGS;