typedef enum {
  KSPROPERTY_TELEPHONY_PROVIDERID,
  KSPROPERTY_TELEPHONY_CALLINFO,
  KSPROPERTY_TELEPHONY_CALLCONTROL,
  KSPROPERTY_TELEPHONY_PROVIDERCHANGE,
  KSPROPERTY_TELEPHONY_CALLHOLD,
  KSPROPERTY_TELEPHONY_MUTE_TX
} KSPROPERTY_TELEPHONY_CONTROL;