typedef enum {
  KSMICARRAY_MICTYPE_OMNIDIRECTIONAL,
  KSMICARRAY_MICTYPE_SUBCARDIOID,
  KSMICARRAY_MICTYPE_CARDIOID,
  KSMICARRAY_MICTYPE_SUPERCARDIOID,
  KSMICARRAY_MICTYPE_HYPERCARDIOID,
  KSMICARRAY_MICTYPE_8SHAPED,
  KSMICARRAY_MICTYPE_VENDORDEFINED
} KSMICARRAY_MICTYPE;