typedef enum {
  KSPROPERTY_OVERLAYUPDATE_INTERESTS,
  KSPROPERTY_OVERLAYUPDATE_CLIPLIST,
  KSPROPERTY_OVERLAYUPDATE_PALETTE,
  KSPROPERTY_OVERLAYUPDATE_COLORKEY,
  KSPROPERTY_OVERLAYUPDATE_VIDEOPOSITION,
  KSPROPERTY_OVERLAYUPDATE_DISPLAYCHANGE,
  KSPROPERTY_OVERLAYUPDATE_COLORREF
} KSPROPERTY_OVERLAYUPDATE;