typedef enum {
  KSPROPERTY_CROSSBAR_CAPS,
  KSPROPERTY_CROSSBAR_PININFO,
  KSPROPERTY_CROSSBAR_CAN_ROUTE,
  KSPROPERTY_CROSSBAR_ROUTE,
  KSPROPERTY_CROSSBAR_INPUT_ACTIVE
} KSPROPERTY_VIDCAP_CROSSBAR;