typedef enum {
  KSPROPERTY_SOUNDDETECTOR_SUPPORTEDPATTERNS,
  KSPROPERTY_SOUNDDETECTOR_PATTERNS,
  KSPROPERTY_SOUNDDETECTOR_ARMED,
  KSPROPERTY_SOUNDDETECTOR_MATCHRESULT,
  KSPROPERTY_SOUNDDETECTOR_RESET,
  KSPROPERTY_SOUNDDETECTOR_STREAMINGSUPPORT
} KSPROPERTY_SOUNDDETECTOR;