typedef enum {
  KSPROPERTY_TUNER_CAPS,
  KSPROPERTY_TUNER_MODE_CAPS,
  KSPROPERTY_TUNER_MODE,
  KSPROPERTY_TUNER_STANDARD,
  KSPROPERTY_TUNER_FREQUENCY,
  KSPROPERTY_TUNER_INPUT,
  KSPROPERTY_TUNER_STATUS,
  KSPROPERTY_TUNER_IF_MEDIUM,
  KSPROPERTY_TUNER_SCAN_CAPS,
  KSPROPERTY_TUNER_SCAN_STATUS,
  KSPROPERTY_TUNER_STANDARD_MODE,
  KSPROPERTY_TUNER_NETWORKTYPE_SCAN_CAPS
} KSPROPERTY_TUNER;