typedef enum {
  KSPROPERTY_SYSAUDIO_DEVICE_COUNT,
  KSPROPERTY_SYSAUDIO_DEVICE_FRIENDLY_NAME,
  KSPROPERTY_SYSAUDIO_DEVICE_INSTANCE,
  KSPROPERTY_SYSAUDIO_DEVICE_INTERFACE_NAME,
  KSPROPERTY_SYSAUDIO_SELECT_GRAPH,
  KSPROPERTY_SYSAUDIO_CREATE_VIRTUAL_SOURCE,
  KSPROPERTY_SYSAUDIO_DEVICE_DEFAULT,
  KSPROPERTY_SYSAUDIO_INSTANCE_INFO,
  KSPROPERTY_SYSAUDIO_COMPONENT_ID
} KSPROPERTY_SYSAUDIO;