typedef enum {
  KSPROPERTY_RTAUDIO_GETPOSITIONFUNCTION,
  KSPROPERTY_RTAUDIO_BUFFER,
  KSPROPERTY_RTAUDIO_HWLATENCY,
  KSPROPERTY_RTAUDIO_POSITIONREGISTER,
  KSPROPERTY_RTAUDIO_CLOCKREGISTER,
  KSPROPERTY_RTAUDIO_BUFFER_WITH_NOTIFICATION,
  KSPROPERTY_RTAUDIO_REGISTER_NOTIFICATION_EVENT,
  KSPROPERTY_RTAUDIO_UNREGISTER_NOTIFICATION_EVENT,
  KSPROPERTY_RTAUDIO_QUERY_NOTIFICATION_SUPPORT,
  KSPROPERTY_RTAUDIO_PACKETCOUNT,
  KSPROPERTY_RTAUDIO_PRESENTATION_POSITION,
  KSPROPERTY_RTAUDIO_GETREADPACKET,
  KSPROPERTY_RTAUDIO_SETWRITEPACKET,
  KSPROPERTY_RTAUDIO_PACKETVREGISTER
} KSPROPERTY_RTAUDIO;