typedef enum {
  KSPROPERTY_AUDIOENGINE_LFXENABLE,
  KSPROPERTY_AUDIOENGINE_GFXENABLE,
  KSPROPERTY_AUDIOENGINE_MIXFORMAT,
  KSPROPERTY_AUDIOENGINE_DEVICEFORMAT,
  KSPROPERTY_AUDIOENGINE_SUPPORTEDDEVICEFORMATS,
  KSPROPERTY_AUDIOENGINE_DESCRIPTOR,
  KSPROPERTY_AUDIOENGINE_BUFFER_SIZE_RANGE,
  KSPROPERTY_AUDIOENGINE_LOOPBACK_PROTECTION,
  KSPROPERTY_AUDIOENGINE_VOLUMELEVEL,
  KSPROPERTY_AUDIOENGINE_DEVICECONTROLS
} KSPROPERTY_AUDIOENGINE;