typedef struct tagKSCAMERA_EXTENDEDPROP_ROI_ISPCONTROL {
  ULONG ControlId;
  ULONG ROICount;
  ULONG Result;
  ULONG Reserved;
} KSCAMERA_EXTENDEDPROP_ROI_ISPCONTROL, *PKSCAMERA_EXTENDEDPROP_ROI_ISPCONTROL;