typedef struct tagKSCAMERA_EXTENDEDPROP_ROI_CONFIGCAPS {
  ULONG     ControlId;
  ULONG     MaxNumberOfROIs;
  ULONGLONG Capability;
} KSCAMERA_EXTENDEDPROP_ROI_CONFIGCAPS, *PKSCAMERA_EXTENDEDPROP_ROI_CONFIGCAPS;