typedef struct {
  ULONG                                        Size;
  KSPROPERTY_NETWORKCAMERACONTROL_NTPINFO_TYPE Type;
} KSPROPERTY_NETWORKCAMERACONTROL_NTPINFO_HEADER, *PKSPROPERTY_NETWORKCAMERACONTROL_NTPINFO_HEADER;