typedef struct tagKSCAMERA_EXTENDEDPROP_BACKGROUNDSEGMENTATION_CONFIGCAPS {
  SIZE   Resolution;
  struct {
    LONG Numerator;
    LONG Denominator;
  } MaxFrameRate;
  SIZE   MaskResolution;
  GUID   SubType;
} KSCAMERA_EXTENDEDPROP_BACKGROUNDSEGMENTATION_CONFIGCAPS, *PKSCAMERA_EXTENDEDPROP_BACKGROUNDSEGMENTATION_CONFIGCAPS;