typedef struct _KSPROPERTY_NETWORKCAMERACONTROL_EVENT_INFO {
  KSCAMERA_METADATA_ITEMHEADER Header;
  WCHAR                        EventFilter[1];
} KSPROPERTY_NETWORKCAMERACONTROL_EVENT_INFO, *PKSPROPERTY_NETWORKCAMERACONTROL_EVENT_INFO;