typedef struct tagKSCAMERA_EXTENDEDPROP_FIELDOFVIEW2_CONFIGCAPS {
  WORD  DefaultDiagonalFieldOfViewInDegrees;
  WORD  DiscreteFoVStopsCount;
  WORD  DiscreteFoVStops[360];
  ULONG Reserved;
} KSCAMERA_EXTENDEDPROP_FIELDOFVIEW2_CONFIGCAPS, *PKSCAMERA_EXTENDEDPROP_FIELDOFVIEW2_CONFIGCAPS;