typedef struct tagKSCAMERA_EXTENDEDPROP_CAMERAOFFSET {
  LONG  PitchAngle;
  LONG  YawAngle;
  ULONG Flag;
  ULONG Reserved;
} KSCAMERA_EXTENDEDPROP_CAMERAOFFSET, *PKSCAMERA_EXTENDEDPROP_CAMERAOFFSET;