typedef struct _KSPROPERTY_NETWORKCAMERACONTROL_METADATA_INFO {
  ULONG MetadataItems;
  ULONG Size;
  BOOL  PTZStatus;
  BOOL  Events;
  BOOL  Analytics;
  BOOL  Reserved;
} KSPROPERTY_NETWORKCAMERACONTROL_METADATA_INFO, *PKSPROPERTY_NETWORKCAMERACONTROL_METADATA_INFO;