typedef struct tagKSCAMERA_METADATA_DIGITALWINDOW {
  KSCAMERA_METADATA_ITEMHEADER                Header;
  KSCAMERA_EXTENDEDPROP_DIGITALWINDOW_SETTING Window;
} KSCAMERA_METADATA_DIGITALWINDOW, *PKSCAMERA_METADATA_DIGITALWINDOW;