typedef struct _KSAUDIOMODULE_DESCRIPTOR {
  GUID  ClassId;
  ULONG InstanceId;
  ULONG VersionMajor;
  ULONG VersionMinor;
  WCHAR Name[AUDIOMODULE_MAX_NAME_CCH_SIZE];
} KSAUDIOMODULE_DESCRIPTOR, *PKSAUDIOMODULE_DESCRIPTOR;