typedef struct tagKSCAMERA_EXTENDEDPROP_PHOTOMODE {
  ULONG RequestedHistoryFrames;
  ULONG MaxHistoryFrames;
  ULONG SubMode;
  ULONG Reserved;
} KSCAMERA_EXTENDEDPROP_PHOTOMODE, *PKSCAMERA_EXTENDEDPROP_PHOTOMODE;