typedef struct tagKSCAMERA_EXTENDEDPROP_DIGITALWINDOW_SETTING {
  LONG  OriginX;
  LONG  OriginY;
  LONG  WindowSize;
  ULONG Reserved;
} KSCAMERA_EXTENDEDPROP_DIGITALWINDOW_SETTING, *PKSCAMERA_EXTENDEDPROP_DIGITALWINDOW_SETTING;