typedef struct tagKSCAMERA_EXTENDEDPROP_FIELDOFVIEW {
  ULONG NormalizedFocalLengthX;
  ULONG NormalizedFocalLengthY;
  ULONG Flag;
  ULONG Reserved;
} KSCAMERA_EXTENDEDPROP_FIELDOFVIEW, *PKSCAMERA_EXTENDEDPROP_FIELDOFVIEW;