typedef struct tagKSATTRIBUTE_AUDIOSIGNALPROCESSING_MODE {
  KSATTRIBUTE AttributeHeader;
  GUID        SignalProcessingMode;
} KSATTRIBUTE_AUDIOSIGNALPROCESSING_MODE, *PKSATTRIBUTE_AUDIOSIGNALPROCESSING_MODE;