typedef struct tagKSATTRIBUTE_AUDIOLOOPBACK_TAPPOINT {
  KSATTRIBUTE                 AttributeHeader;
  AUDIOLOOPBACK_TAPPOINT_TYPE TapPoint;
} KSATTRIBUTE_AUDIOLOOPBACK_TAPPOINT, *PKSATTRIBUTE_AUDIOLOOPBACK_TAPPOINT;