typedef struct tagKSCAMERA_MAXVIDEOFPS_FORPHOTORES {
  ULONG PhotoResWidth;
  ULONG PhotoResHeight;
  ULONG PreviewFPSNum;
  ULONG PreviewFPSDenom;
  ULONG CaptureFPSNum;
  ULONG CaptureFPSDenom;
} KSCAMERA_MAXVIDEOFPS_FORPHOTORES, *PKSCAMERA_MAXVIDEOFPS_FORPHOTORES;