typedef struct tagKSCAMERA_EXTENDEDPROP_EVCOMPENSATION {
  ULONG     Mode;
  LONG      Min;
  LONG      Max;
  LONG      Value;
  ULONGLONG Reserved;
} KSCAMERA_EXTENDEDPROP_EVCOMPENSATION, *PKSCAMERA_EXTENDEDPROP_EVCOMPENSATION;