typedef enum D3D11_VIDEO_DECODER_HISTOGRAM_COMPONENT {
  D3D11_VIDEO_DECODER_HISTOGRAM_COMPONENT_Y = 0,
  D3D11_VIDEO_DECODER_HISTOGRAM_COMPONENT_U = 1,
  D3D11_VIDEO_DECODER_HISTOGRAM_COMPONENT_V = 2,
  D3D11_VIDEO_DECODER_HISTOGRAM_COMPONENT_R = 0,
  D3D11_VIDEO_DECODER_HISTOGRAM_COMPONENT_G = 1,
  D3D11_VIDEO_DECODER_HISTOGRAM_COMPONENT_B = 2,
  D3D11_VIDEO_DECODER_HISTOGRAM_COMPONENT_A = 3
} ;