typedef struct _KERB_QUERY_DOMAIN_EXTENDED_POLICIES_REQUEST {
  KERB_PROTOCOL_MESSAGE_TYPE MessageType;
  ULONG                      Flags;
  UNICODE_STRING             DomainName;
} KERB_QUERY_DOMAIN_EXTENDED_POLICIES_REQUEST, *PKERB_QUERY_DOMAIN_EXTENDED_POLICIES_REQUEST;