typedef struct _LSA_FOREST_TRUST_COLLISION_INFORMATION {
  ULONG                              RecordCount;
  PLSA_FOREST_TRUST_COLLISION_RECORD *Entries;
} LSA_FOREST_TRUST_COLLISION_INFORMATION, *PLSA_FOREST_TRUST_COLLISION_INFORMATION;