typedef struct _KERB_QUERY_BINDING_CACHE_RESPONSE {
  KERB_PROTOCOL_MESSAGE_TYPE     MessageType;
  ULONG                          CountOfEntries;
  PKERB_BINDING_CACHE_ENTRY_DATA Entries;
} KERB_QUERY_BINDING_CACHE_RESPONSE, *PKERB_QUERY_BINDING_CACHE_RESPONSE;