typedef struct _COMPRESS_ALLOCATION_ROUTINES {
  PFN_COMPRESS_ALLOCATE Allocate;
  PFN_COMPRESS_FREE     Free;
  PVOID                 UserContext;
} COMPRESS_ALLOCATION_ROUTINES, *PCOMPRESS_ALLOCATION_ROUTINES;