typedef struct _SP_POWERMESSAGEWAKE_PARAMS_A {
  SP_CLASSINSTALL_HEADER ClassInstallHeader;
  CHAR                   *PowerMessageWake[LINE_LEN  2];
} SP_POWERMESSAGEWAKE_PARAMS_A, *PSP_POWERMESSAGEWAKE_PARAMS_A;