typedef struct _SP_POWERMESSAGEWAKE_PARAMS_W {
  SP_CLASSINSTALL_HEADER ClassInstallHeader;
  WCHAR                  *PowerMessageWake[LINE_LEN  2];
} SP_POWERMESSAGEWAKE_PARAMS_W, *PSP_POWERMESSAGEWAKE_PARAMS_W;