typedef struct _SP_DEVINFO_LIST_DETAIL_DATA_W {
  DWORD  cbSize;
  GUID   ClassGuid;
  HANDLE RemoteMachineHandle;
  WCHAR  RemoteMachineName[SP_MAX_MACHINENAME_LENGTH];
} SP_DEVINFO_LIST_DETAIL_DATA_W, *PSP_DEVINFO_LIST_DETAIL_DATA_W;