typedef enum DXGI_OUTDUPL_POINTER_SHAPE_TYPE {
  DXGI_OUTDUPL_POINTER_SHAPE_TYPE_MONOCHROME = 0x1,
  DXGI_OUTDUPL_POINTER_SHAPE_TYPE_COLOR = 0x2,
  DXGI_OUTDUPL_POINTER_SHAPE_TYPE_MASKED_COLOR = 0x4
} ;