typedef enum DML_EXECUTION_FLAGS {
  DML_EXECUTION_FLAG_NONE = 0,
  DML_EXECUTION_FLAG_ALLOW_HALF_PRECISION_COMPUTATION = 0x1,
  DML_EXECUTION_FLAG_DISABLE_META_COMMANDS = 0x2,
  DML_EXECUTION_FLAG_DESCRIPTORS_VOLATILE = 0x4
} ;