typedef enum DML_REDUCE_FUNCTION {
  DML_REDUCE_FUNCTION_ARGMAX,
  DML_REDUCE_FUNCTION_ARGMIN,
  DML_REDUCE_FUNCTION_AVERAGE,
  DML_REDUCE_FUNCTION_L1,
  DML_REDUCE_FUNCTION_L2,
  DML_REDUCE_FUNCTION_LOG_SUM,
  DML_REDUCE_FUNCTION_LOG_SUM_EXP,
  DML_REDUCE_FUNCTION_MAX,
  DML_REDUCE_FUNCTION_MIN,
  DML_REDUCE_FUNCTION_MULTIPLY,
  DML_REDUCE_FUNCTION_SUM,
  DML_REDUCE_FUNCTION_SUM_SQUARE
} ;