typedef enum DML_TENSOR_DATA_TYPE {
  DML_TENSOR_DATA_TYPE_UNKNOWN,
  DML_TENSOR_DATA_TYPE_FLOAT32,
  DML_TENSOR_DATA_TYPE_FLOAT16,
  DML_TENSOR_DATA_TYPE_UINT32,
  DML_TENSOR_DATA_TYPE_UINT16,
  DML_TENSOR_DATA_TYPE_UINT8,
  DML_TENSOR_DATA_TYPE_INT32,
  DML_TENSOR_DATA_TYPE_INT16,
  DML_TENSOR_DATA_TYPE_INT8,
  DML_TENSOR_DATA_TYPE_FLOAT64,
  DML_TENSOR_DATA_TYPE_UINT64,
  DML_TENSOR_DATA_TYPE_INT64,
  DML_TENSOR_DATA_TYPE_UINT4,
  DML_TENSOR_DATA_TYPE_INT4
} ;