typedef enum WSC_SECURITY_PRODUCT_STATE {
  WSC_SECURITY_PRODUCT_STATE_ON = 0,
  WSC_SECURITY_PRODUCT_STATE_OFF = 1,
  WSC_SECURITY_PRODUCT_STATE_SNOOZED = 2,
  WSC_SECURITY_PRODUCT_STATE_EXPIRED = 3
} ;