typedef struct _MI_ContextFT {
  MI_Result()(MI_Context *context,MI_Result result) * PostResult;
  MI_Result((MI_Context *context, const MI_Instance *instance) * )PostInstance;
  MI_Result(MI_Context *context, const MI_Instance *indication,MI_Uint32 subscriptionIDCount, const MI_Char *bookmark) * )(PostIndication;
  MI_Result(MI_Context *context, const MI_ClassDecl *classDecl,MI_Instance *instance) * )(ConstructInstance;
  MI_Result(MI_Context *context, const MI_MethodDecl *methodDecl,MI_Instance *instance) * )(ConstructParameters;
  MI_Result(I_Context *context, const MI_ClassDecl *classDecl,MI_Instance **instance) * )(MNewInstance;
  MI_Result(I_Context *context, const MI_Char *className,MI_Uint32 flags,MI_Instance **instance) * )(MNewDynamicInstance;
  MI_Result(I_Context *context, const MI_MethodDecl *methodDecl,MI_Instance **instance) * )(MNewParameters;
  MI_Result((const MI_Context *context,MI_Boolean *flag) * )Canceled;
  MI_Result()(const MI_Context *context,MI_LocaleType localeType,MI_Char locale * GetLocale[MI_MAX_LOCALE_SIZE];
  MI_Result((MI_Context *context,MI_CancelCallback callback, void *callbackData) * )RegisterCancel;
  MI_Result()(MI_Context *context) * RequestUnload;
  MI_Result()(MI_Context *context) * RefuseUnload;
  MI_Result((const MI_Context *context,MI_Session *session) * )GetLocalSession;
  MI_Result(MI_Context *context, const MI_Char *name, const MI_Char *value) * )(SetStringOption;
  MI_Result(I_Context *context, const MI_Char *name, const MI_Char **value) * )(MGetStringOption;
  MI_Result(MI_Context *context, const MI_Char *name,MI_Uint32 *value) * )(GetNumberOption;
  MI_Result(I_Context *context, const MI_Char *name,MI_Type *valueType,MI_Value *value) * )(MGetCustomOption;
  MI_Result((MI_Context *context,MI_Uint32 *count) * )GetCustomOptionCount;
  MI_Result(_Context *context,MI_Uint32 index, const MI_Char **name,MI_Type *valueType,MI_Value *value) * )(MIGetCustomOptionAt;
  MI_Result((MI_Context *context,MI_Uint32 channel, const MI_Char *message) * )WriteMessage;
  MI_Result(I_Context *context, const MI_Char *activity, const MI_Char *currentOperation, const MI_Char *statusDescription,MI_Uint32 percentComplete,MI_Uint32 secondsRemaining) * )(MWriteProgress;
  MI_Result(MI_Context *context, const MI_Char *name, const MI_Value *value,MI_Type type,MI_Uint32 flags) * )(WriteStreamParameter;
  MI_Result(MI_Context *context, const MI_Instance *error,MI_Boolean *flag) * )(WriteCimError;
  MI_Result(MI_Context *context, const MI_Char *message,MI_PromptType promptType,MI_Boolean *result) * )(PromptUser;
  MI_Result(I_Context *context, const MI_Char *target, const MI_Char *action,MI_Boolean *result) * )(MShouldProcess;
  MI_Result(MI_Context *context, const MI_Char *message,MI_Boolean *result) * )(ShouldContinue;
  MI_Result(MI_Context *context,MI_Uint32 resultCode, const MI_Char *resultType, const MI_Char *errorMessage) * )(PostError;
  MI_Result((MI_Context *context, const MI_Instance *error) * )PostCimError;
  MI_Result(I_Context *context,MI_Uint32 resultCode, const MI_Char *resultType, const MI_Char *errorMessage,MI_Boolean *flag) * )(MWriteError;
} MI_ContextFT;