typedef enum NET_FW_AUTHENTICATE_TYPE_ {
  NET_FW_AUTHENTICATE_NONE = 0,
  NET_FW_AUTHENTICATE_NO_ENCAPSULATION,
  NET_FW_AUTHENTICATE_WITH_INTEGRITY,
  NET_FW_AUTHENTICATE_AND_NEGOTIATE_ENCRYPTION,
  NET_FW_AUTHENTICATE_AND_ENCRYPT
} NET_FW_AUTHENTICATE_TYPE;