typedef enum NET_FW_SERVICE_TYPE_ {
  NET_FW_SERVICE_FILE_AND_PRINT = 0,
  NET_FW_SERVICE_UPNP,
  NET_FW_SERVICE_REMOTE_DESKTOP,
  NET_FW_SERVICE_NONE,
  NET_FW_SERVICE_TYPE_MAX
} NET_FW_SERVICE_TYPE;