typedef enum NET_FW_RULE_CATEGORY_ {
  NET_FW_RULE_CATEGORY_BOOT = 0,
  NET_FW_RULE_CATEGORY_STEALTH,
  NET_FW_RULE_CATEGORY_FIREWALL,
  NET_FW_RULE_CATEGORY_CONSEC,
  NET_FW_RULE_CATEGORY_MAX
} NET_FW_RULE_CATEGORY;