typedef struct _NDIS_RECEIVE_FILTER_CLEAR_PARAMETERS {
  NDIS_OBJECT_HEADER     Header;
  ULONG                  Flags;
  NDIS_RECEIVE_QUEUE_ID  QueueId;
  NDIS_RECEIVE_FILTER_ID FilterId;
} NDIS_RECEIVE_FILTER_CLEAR_PARAMETERS, *PNDIS_RECEIVE_FILTER_CLEAR_PARAMETERS;