typedef struct _OFFLOAD_SECURITY_ASSOCIATION {
  OFFLOAD_OPERATION_E Operation;
  SPI_TYPE            SPI;
  OFFLOAD_ALGO_INFO   IntegrityAlgo;
  OFFLOAD_ALGO_INFO   ConfAlgo;
  OFFLOAD_ALGO_INFO   Reserved;
} OFFLOAD_SECURITY_ASSOCIATION, *POFFLOAD_SECURITY_ASSOCIATION;