typedef struct _NDIS_SRIOV_SET_VF_POWER_STATE_PARAMETERS {
  NDIS_OBJECT_HEADER      Header;
  NDIS_SRIOV_FUNCTION_ID  VFId;
  NDIS_DEVICE_POWER_STATE PowerState;
  BOOLEAN                 WakeEnable;
} NDIS_SRIOV_SET_VF_POWER_STATE_PARAMETERS, *PNDIS_SRIOV_SET_VF_POWER_STATE_PARAMETERS;