typedef struct _NDIS_RECEIVE_FILTER_MOVE_FILTER_PARAMETERS {
  NDIS_OBJECT_HEADER       Header;
  NDIS_RECEIVE_FILTER_ID   FilterId;
  NDIS_RECEIVE_QUEUE_ID    SourceQueueId;
  NDIS_NIC_SWITCH_VPORT_ID SourceVPortId;
  NDIS_RECEIVE_QUEUE_ID    DestQueueId;
  NDIS_NIC_SWITCH_VPORT_ID DestVPortId;
} NDIS_RECEIVE_FILTER_MOVE_FILTER_PARAMETERS, *PNDIS_RECEIVE_FILTER_MOVE_FILTER_PARAMETERS;