typedef enum _D3D10_SHADER_DEBUG_SCOPETYPE {
  D3D10_SHADER_DEBUG_SCOPE_GLOBAL,
  D3D10_SHADER_DEBUG_SCOPE_BLOCK,
  D3D10_SHADER_DEBUG_SCOPE_FORLOOP,
  D3D10_SHADER_DEBUG_SCOPE_STRUCT,
  D3D10_SHADER_DEBUG_SCOPE_FUNC_PARAMS,
  D3D10_SHADER_DEBUG_SCOPE_STATEBLOCK,
  D3D10_SHADER_DEBUG_SCOPE_NAMESPACE,
  D3D10_SHADER_DEBUG_SCOPE_ANNOTATION,
  D3D10_SHADER_DEBUG_SCOPE_FORCE_DWORD = 0x7fffffff
} D3D10_SHADER_DEBUG_SCOPETYPE;