typedef enum FWPS_FIELDS_RPC_EPMAP_ {
  FWPS_FIELD_RPC_EPMAP_REMOTE_USER_TOKEN,
  FWPS_FIELD_RPC_EPMAP_IF_UUID,
  FWPS_FIELD_RPC_EPMAP_IF_VERSION,
  FWPS_FIELD_RPC_EPMAP_PROTOCOL,
  FWPS_FIELD_RPC_EPMAP_AUTH_TYPE,
  FWPS_FIELD_RPC_EPMAP_AUTH_LEVEL,
  FWPS_FIELD_RPC_EPMAP_SEC_ENCRYPT_ALGORITHM,
  FWPS_FIELD_RPC_EPMAP_SEC_KEY_SIZE,
  FWPS_FIELD_RPC_EPMAP_LOCAL_ADDR_V4,
  FWPS_FIELD_RPC_EPMAP_LOCAL_ADDR_V6,
  FWPS_FIELD_RPC_EPMAP_LOCAL_PORT,
  FWPS_FIELD_RPC_EPMAP_PIPE,
  FWPS_FIELD_RPC_EPMAP_REMOTE_ADDR_V4,
  FWPS_FIELD_RPC_EPMAP_REMOTE_ADDR_V6,
  FWPS_FIELD_RPC_EPMAP_MAX
} FWPS_FIELDS_RPC_EPMAP;