typedef enum FWPS_FIELDS_IKEEXT_V6_ {
  FWPS_FIELD_IKEEXT_V6_IP_LOCAL_ADDRESS,
  FWPS_FIELD_IKEEXT_V6_IP_REMOTE_ADDRESS,
  FWPS_FIELD_IKEEXT_V6_IP_LOCAL_INTERFACE,
  FWPS_FIELD_IKEEXT_V6_PROFILE_ID,
  FWPS_FIELD_IKEEXT_V6_IPSEC_SECURITY_REALM_ID,
  FWPS_FIELD_IKEEXT_V6_MAX
} FWPS_FIELDS_IKEEXT_V6;