typedef enum FWPS_FIELDS_RPC_EP_ADD_ {
  FWPS_FIELD_RPC_EP_ADD_PROCESS_WITH_RPC_IF_UUID,
  FWPS_FIELD_RPC_EP_ADD_PROTOCOL,
  FWPS_FIELD_RPC_EP_ADD_EP_VALUE,
  FWPS_FIELD_RPC_EP_ADD_EP_FLAGS,
  FWPS_FIELD_RPC_EP_ADD_MAX
} FWPS_FIELDS_RPC_EP_ADD;