typedef enum FWPS_FIELDS_STREAM_V6_ {
  FWPS_FIELD_STREAM_V6_IP_LOCAL_ADDRESS,
  FWPS_FIELD_STREAM_V6_IP_LOCAL_ADDRESS_TYPE,
  FWPS_FIELD_STREAM_V6_IP_REMOTE_ADDRESS,
  FWPS_FIELD_STREAM_V6_IP_LOCAL_PORT,
  FWPS_FIELD_STREAM_V6_IP_REMOTE_PORT,
  FWPS_FIELD_STREAM_V6_DIRECTION,
  FWPS_FIELD_STREAM_V6_FLAGS,
  FWPS_FIELD_STREAM_V6_COMPARTMENT_ID,
  FWPS_FIELD_STREAM_V6_MAX
} FWPS_FIELDS_STREAM_V6;