typedef enum FWPS_VSWITCH_EVENT_TYPE_ {
  FWPS_VSWITCH_EVENT_VSWITCH_NONE,
  FWPS_VSWITCH_EVENT_VSWITCH_CREATE,
  FWPS_VSWITCH_EVENT_VSWITCH_DELETE,
  FWPS_VSWITCH_EVENT_PORT_CREATE,
  FWPS_VSWITCH_EVENT_PORT_DELETE,
  FWPS_VSWITCH_EVENT_INTERFACE_CREATE,
  FWPS_VSWITCH_EVENT_INTERFACE_DELETE,
  FWPS_VSWITCH_EVENT_INTERFACE_CONNECT,
  FWPS_VSWITCH_EVENT_INTERFACE_DISCONNECT,
  FWPS_VSWITCH_EVENT_POLICY_ADD,
  FWPS_VSWITCH_EVENT_POLICY_UPDATE,
  FWPS_VSWITCH_EVENT_POLICY_DELETE,
  FWPS_VSWITCH_EVENT_RUNTIME_STATE_SAVE,
  FWPS_VSWITCH_EVENT_RUNTIME_STATE_RESTORE
} FWPS_VSWITCH_EVENT_TYPE;