typedef struct FWPS_VSWITCH_EVENT_DISPATCH_TABLE0_ {
  FWPS_VSWITCH_LIFETIME_EVENT_CALLBACK0        vSwitchLifetimeNotifyFn;
  FWPS_VSWITCH_PORT_EVENT_CALLBACK0            vSwitchPortEventNotifyFn;
  FWPS_VSWITCH_INTERFACE_EVENT_CALLBACK0       vSwitchInterfaceEventNotifyFn;
  FWPS_VSWITCH_FILTER_ENGINE_REORDER_CALLBACK0 vSwitchFilterEngineReorderNotifyRn;
  FWPS_VSWITCH_POLICY_EVENT_CALLBACK0          vSwitchPolicyEventNotifyFn;
  FWPS_VSWITCH_RUNTIME_STATE_SAVE_CALLBACK0    vSwitchRuntimeStateSaveNotifyFn;
  FWPS_VSWITCH_RUNTIME_STATE_RESTORE_CALLBACK0 vSwitchRuntimeStateRestoreNotifyFn;
} FWPS_VSWITCH_EVENT_DISPATCH_TABLE0;