typedef enum D3D10_MESSAGE_SEVERITY {
  D3D10_MESSAGE_SEVERITY_CORRUPTION = 0,
  D3D10_MESSAGE_SEVERITY_ERROR,
  D3D10_MESSAGE_SEVERITY_WARNING,
  D3D10_MESSAGE_SEVERITY_INFO,
  D3D10_MESSAGE_SEVERITY_MESSAGE
} ;