typedef enum _tagAppActionFlags {
  APPACTION_INSTALL = 0x1,
  APPACTION_UNINSTALL = 0x2,
  APPACTION_MODIFY = 0x4,
  APPACTION_REPAIR = 0x8,
  APPACTION_UPGRADE = 0x10,
  APPACTION_CANGETSIZE = 0x20,
  APPACTION_MODIFYREMOVE = 0x80,
  APPACTION_ADDLATER = 0x100,
  APPACTION_UNSCHEDULE = 0x200
} APPACTIONFLAGS;