typedef enum {
  CRYPT_XML_PROPERTY_MAX_HEAP_SIZE = 1,
  CRYPT_XML_PROPERTY_SIGNATURE_LOCATION = 2,
  CRYPT_XML_PROPERTY_MAX_SIGNATURES = 3,
  CRYPT_XML_PROPERTY_DOC_DECLARATION = 4,
  CRYPT_XML_PROPERTY_XML_OUTPUT_CHARSET = 5
} CRYPT_XML_PROPERTY_ID;