typedef enum __MIDL___MIDL_itf_casetup_0000_0004_0001 {
  ENUM_CESSETUPPROP_USE_IISAPPPOOLIDENTITY = 0,
  ENUM_CESSETUPPROP_CACONFIG = 1,
  ENUM_CESSETUPPROP_AUTHENTICATION = 2,
  ENUM_CESSETUPPROP_SSLCERTHASH = 3,
  ENUM_CESSETUPPROP_URL = 4,
  ENUM_CESSETUPPROP_RENEWALONLY = 5,
  ENUM_CESSETUPPROP_ALLOW_KEYBASED_RENEWAL = 6
} CESSetupProperty;