typedef enum __MIDL___MIDL_itf_casetup_0000_0005_0001 {
  ENUM_CEPSETUPPROP_AUTHENTICATION = 0,
  ENUM_CEPSETUPPROP_SSLCERTHASH = 1,
  ENUM_CEPSETUPPROP_URL = 2,
  ENUM_CEPSETUPPROP_KEYBASED_RENEWAL = 3
} CEPSetupProperty;