typedef enum __MIDL___MIDL_itf_casetup_0000_0003_0001 {
  ENUM_CEPSETUPPROP_USELOCALSYSTEM = 0,
  ENUM_CEPSETUPPROP_USECHALLENGE = 1,
  ENUM_CEPSETUPPROP_RANAME_CN = 2,
  ENUM_CEPSETUPPROP_RANAME_EMAIL = 3,
  ENUM_CEPSETUPPROP_RANAME_COMPANY = 4,
  ENUM_CEPSETUPPROP_RANAME_DEPT = 5,
  ENUM_CEPSETUPPROP_RANAME_CITY = 6,
  ENUM_CEPSETUPPROP_RANAME_STATE = 7,
  ENUM_CEPSETUPPROP_RANAME_COUNTRY = 8,
  ENUM_CEPSETUPPROP_SIGNINGKEYINFORMATION = 9,
  ENUM_CEPSETUPPROP_EXCHANGEKEYINFORMATION = 10,
  ENUM_CEPSETUPPROP_CAINFORMATION = 11,
  ENUM_CEPSETUPPROP_MSCEPURL = 12,
  ENUM_CEPSETUPPROP_CHALLENGEURL = 13
} MSCEPSetupProperty;