typedef enum _WSC_SECURITY_PROVIDER {
  WSC_SECURITY_PROVIDER_FIREWALL = 0x1,
  WSC_SECURITY_PROVIDER_AUTOUPDATE_SETTINGS = 0x2,
  WSC_SECURITY_PROVIDER_ANTIVIRUS = 0x4,
  WSC_SECURITY_PROVIDER_ANTISPYWARE = 0x8,
  WSC_SECURITY_PROVIDER_INTERNET_SETTINGS = 0x10,
  WSC_SECURITY_PROVIDER_USER_ACCOUNT_CONTROL = 0x20,
  WSC_SECURITY_PROVIDER_SERVICE = 0x40,
  WSC_SECURITY_PROVIDER_NONE = 0,
  WSC_SECURITY_PROVIDER_ALL
} WSC_SECURITY_PROVIDER, *PWSC_SECURITY_PROVIDER;