typedef enum tagCONDITION_OPERATION {
  COP_IMPLICIT = 0,
  COP_EQUAL,
  COP_NOTEQUAL,
  COP_LESSTHAN,
  COP_GREATERTHAN,
  COP_LESSTHANOREQUAL,
  COP_GREATERTHANOREQUAL,
  COP_VALUE_STARTSWITH,
  COP_VALUE_ENDSWITH,
  COP_VALUE_CONTAINS,
  COP_VALUE_NOTCONTAINS,
  COP_DOSWILDCARDS,
  COP_WORD_EQUAL,
  COP_WORD_STARTSWITH,
  COP_APPLICATION_SPECIFIC
} CONDITION_OPERATION;