typedef enum {
  SYMOPT_EX_DISABLEACCESSTIMEUPDATE,
  SYMOPT_EX_LASTVALIDDEBUGDIRECTORY,
  SYMOPT_EX_NOIMPLICITPATTERNSEARCH,
  SYMOPT_EX_NEVERLOADSYMBOLS,
  SYMOPT_EX_MAX
} IMAGEHLP_EXTENDED_OPTIONS;