typedef enum _VDS_HBAPORT_SPEED_FLAG {
  VDS_HSF_UNKNOWN = 0,
  VDS_HSF_1GBIT = 0x1,
  VDS_HSF_2GBIT = 0x2,
  VDS_HSF_10GBIT = 0x4,
  VDS_HSF_4GBIT = 0x8,
  VDS_HSF_NOT_NEGOTIATED
} VDS_HBAPORT_SPEED_FLAG;