typedef enum _VDS_DRIVE_FLAG {
  VDS_DRF_HOTSPARE = 0x1,
  VDS_DRF_ASSIGNED = 0x2,
  VDS_DRF_UNASSIGNED = 0x4,
  VDS_DRF_HOTSPARE_IN_USE = 0x8,
  VDS_DRF_HOTSPARE_STANDBY = 0x10
} VDS_DRIVE_FLAG, *PVDS_DRIVE_FLAG;