typedef enum _VDS_FILE_SYSTEM_TYPE {
  VDS_FST_UNKNOWN = 0,
  VDS_FST_RAW,
  VDS_FST_FAT,
  VDS_FST_FAT32,
  VDS_FST_NTFS,
  VDS_FST_CDFS,
  VDS_FST_UDF,
  VDS_FST_EXFAT,
  VDS_FST_CSVFS,
  VDS_FST_REFS
} VDS_FILE_SYSTEM_TYPE;