typedef enum _VDS_PROVIDER_LBSUPPORT_FLAG {
  VDS_LBF_FAILOVER = 0x1,
  VDS_LBF_ROUND_ROBIN = 0x2,
  VDS_LBF_ROUND_ROBIN_WITH_SUBSET = 0x4,
  VDS_LBF_DYN_LEAST_QUEUE_DEPTH = 0x8,
  VDS_LBF_WEIGHTED_PATHS = 0x10,
  VDS_LBF_LEAST_BLOCKS = 0x20,
  VDS_LBF_VENDOR_SPECIFIC = 0x40
} VDS_PROVIDER_LBSUPPORT_FLAG;