typedef enum _VDS_LOADBALANCE_POLICY_ENUM {
  VDS_LBP_UNKNOWN = 0,
  VDS_LBP_FAILOVER = 1,
  VDS_LBP_ROUND_ROBIN = 2,
  VDS_LBP_ROUND_ROBIN_WITH_SUBSET = 3,
  VDS_LBP_DYN_LEAST_QUEUE_DEPTH = 4,
  VDS_LBP_WEIGHTED_PATHS = 5,
  VDS_LBP_LEAST_BLOCKS = 6,
  VDS_LBP_VENDOR_SPECIFIC = 7
} VDS_LOADBALANCE_POLICY_ENUM;