typedef enum _VDS_DRIVE_STATUS {
  VDS_DRS_UNKNOWN = 0,
  VDS_DRS_ONLINE = 1,
  VDS_DRS_NOT_READY = 2,
  VDS_DRS_OFFLINE = 4,
  VDS_DRS_FAILED = 5,
  VDS_DRS_REMOVED = 8
} VDS_DRIVE_STATUS, *PVDS_DRIVE_STATUS;