typedef enum _VDS_ISCSI_IPSEC_FLAG {
  VDS_IIF_VALID = 0x1,
  VDS_IIF_IKE = 0x2,
  VDS_IIF_MAIN_MODE = 0x4,
  VDS_IIF_AGGRESSIVE_MODE = 0x8,
  VDS_IIF_PFS_ENABLE = 0x10,
  VDS_IIF_TRANSPORT_MODE_PREFERRED = 0x20,
  VDS_IIF_TUNNEL_MODE_PREFERRED = 0x40
} VDS_ISCSI_IPSEC_FLAG;