typedef enum _VDS_TRANSITION_STATE {
  VDS_TS_UNKNOWN = 0,
  VDS_TS_STABLE = 1,
  VDS_TS_EXTENDING = 2,
  VDS_TS_SHRINKING = 3,
  VDS_TS_RECONFIGING = 4,
  VDS_TS_RESTRIPING = 5
} VDS_TRANSITION_STATE;