typedef enum _VDS_HEALTH {
  VDS_H_UNKNOWN = 0,
  VDS_H_HEALTHY = 1,
  VDS_H_REBUILDING = 2,
  VDS_H_STALE = 3,
  VDS_H_FAILING = 4,
  VDS_H_FAILING_REDUNDANCY = 5,
  VDS_H_FAILED_REDUNDANCY = 6,
  VDS_H_FAILED_REDUNDANCY_FAILING = 7,
  VDS_H_FAILED = 8,
  VDS_H_REPLACED = 9,
  VDS_H_PENDING_FAILURE = 10,
  VDS_H_DEGRADED = 11
} VDS_HEALTH;