typedef enum _VDS_PORT_STATUS {
  VDS_PRS_UNKNOWN = 0,
  VDS_PRS_ONLINE = 1,
  VDS_PRS_NOT_READY = 2,
  VDS_PRS_OFFLINE = 4,
  VDS_PRS_FAILED = 5,
  VDS_PRS_REMOVED = 8
} VDS_PORT_STATUS, *PVDS_PORT_STATUS;