typedef struct {
  UCHAR  bLength;
  UCHAR  bDescriptorIDN;
  UCHAR  bUnitIndex;
  UCHAR  bLUEnable;
  UCHAR  bBootLunID;
  UCHAR  bLUWriteProtect;
  UCHAR  bLUQueueDepth;
  UCHAR  bPSASensitive;
  UCHAR  bMemoryType;
  UCHAR  bDataReliability;
  UCHAR  bLogicalBlockSize;
  UCHAR  qLogicalBlockCount[8];
  UCHAR  dEraseBlockSize[4];
  UCHAR  bProvisioningType;
  UCHAR  qPhyMemResourceCount[8];
  UCHAR  wContextCapabilities[2];
  UCHAR  bLargeUnitGranularity_M1;
  USHORT wLUMaxActiveHPBRegions;
  USHORT wHPBPinnedRegionStartIdx;
  USHORT wNumHPBPinnedRegions;
  ULONG  dLUNumWriteBoosterBufferAllocUnits;
} UFS_UNIT_DESCRIPTOR, *PUFS_UNIT_DESCRIPTOR;