typedef struct {
  UCHAR                           bLength;
  UCHAR                           bDescriptorIDN;
  UCHAR                           bConfDescContinue;
  UCHAR                           bBootEnable;
  UCHAR                           bDescrAccessEn;
  UCHAR                           bInitPowerMode;
  UCHAR                           bHighPriorityLUN;
  UCHAR                           bSecureRemovalType;
  UCHAR                           bInitActiveICCLevel;
  UCHAR                           wPeriodicRTCUpdate[2];
  UCHAR                           Reserved2[1];
  UCHAR                           bRPMBRegionEnable;
  UCHAR                           bRPMBRegion1Size;
  UCHAR                           bRPMBRegion2Size;
  UCHAR                           bRPMBRegion3Size;
  UCHAR                           bWriteBoosterBufferPreserveUserSpaceEn;
  UCHAR                           bWriteBoosterBufferType;
  ULONG                           dNumSharedWriteBoosterBufferAllocUnits;
  UFS_UNIT_CONFIG_DESCRIPTOR_V3_1 UnitConfig[UFS_MAX_NUM_LU];
} UFS_CONFIG_DESCRIPTOR_V3_1, *PUFS_CONFIG_DESCRIPTOR_V3_1;