typedef enum __MIDL___MIDL_itf_ads_0000_0000_0024 {
  ADS_CHASE_REFERRALS_NEVER = 0,
  ADS_CHASE_REFERRALS_SUBORDINATE = 0x20,
  ADS_CHASE_REFERRALS_EXTERNAL = 0x40,
  ADS_CHASE_REFERRALS_ALWAYS
} ADS_CHASE_REFERRALS_ENUM;