typedef enum __MIDL___MIDL_itf_ads_0001_0048_0002 {
  ADS_ACETYPE_ACCESS_ALLOWED = 0,
  ADS_ACETYPE_ACCESS_DENIED = 0x1,
  ADS_ACETYPE_SYSTEM_AUDIT = 0x2,
  ADS_ACETYPE_ACCESS_ALLOWED_OBJECT = 0x5,
  ADS_ACETYPE_ACCESS_DENIED_OBJECT = 0x6,
  ADS_ACETYPE_SYSTEM_AUDIT_OBJECT = 0x7,
  ADS_ACETYPE_SYSTEM_ALARM_OBJECT = 0x8,
  ADS_ACETYPE_ACCESS_ALLOWED_CALLBACK = 0x9,
  ADS_ACETYPE_ACCESS_DENIED_CALLBACK = 0xa,
  ADS_ACETYPE_ACCESS_ALLOWED_CALLBACK_OBJECT = 0xb,
  ADS_ACETYPE_ACCESS_DENIED_CALLBACK_OBJECT = 0xc,
  ADS_ACETYPE_SYSTEM_AUDIT_CALLBACK = 0xd,
  ADS_ACETYPE_SYSTEM_ALARM_CALLBACK = 0xe,
  ADS_ACETYPE_SYSTEM_AUDIT_CALLBACK_OBJECT = 0xf,
  ADS_ACETYPE_SYSTEM_ALARM_CALLBACK_OBJECT = 0x10
} ADS_ACETYPE_ENUM;