typedef enum __MIDL___MIDL_itf_ads_0001_0048_0005 {
  ADS_SD_CONTROL_SE_OWNER_DEFAULTED = 0x1,
  ADS_SD_CONTROL_SE_GROUP_DEFAULTED = 0x2,
  ADS_SD_CONTROL_SE_DACL_PRESENT = 0x4,
  ADS_SD_CONTROL_SE_DACL_DEFAULTED = 0x8,
  ADS_SD_CONTROL_SE_SACL_PRESENT = 0x10,
  ADS_SD_CONTROL_SE_SACL_DEFAULTED = 0x20,
  ADS_SD_CONTROL_SE_DACL_AUTO_INHERIT_REQ = 0x100,
  ADS_SD_CONTROL_SE_SACL_AUTO_INHERIT_REQ = 0x200,
  ADS_SD_CONTROL_SE_DACL_AUTO_INHERITED = 0x400,
  ADS_SD_CONTROL_SE_SACL_AUTO_INHERITED = 0x800,
  ADS_SD_CONTROL_SE_DACL_PROTECTED = 0x1000,
  ADS_SD_CONTROL_SE_SACL_PROTECTED = 0x2000,
  ADS_SD_CONTROL_SE_SELF_RELATIVE = 0x8000
} ADS_SD_CONTROL_ENUM;