typedef enum __MIDL___MIDL_itf_ads_0001_0048_0003 {
  ADS_ACEFLAG_INHERIT_ACE = 0x2,
  ADS_ACEFLAG_NO_PROPAGATE_INHERIT_ACE = 0x4,
  ADS_ACEFLAG_INHERIT_ONLY_ACE = 0x8,
  ADS_ACEFLAG_INHERITED_ACE = 0x10,
  ADS_ACEFLAG_VALID_INHERIT_FLAGS = 0x1f,
  ADS_ACEFLAG_SUCCESSFUL_ACCESS = 0x40,
  ADS_ACEFLAG_FAILED_ACCESS = 0x80
} ADS_ACEFLAG_ENUM;