typedef enum __MIDL___MIDL_itf_ads_0001_0078_0002 {
  ADS_FORMAT_WINDOWS = 1,
  ADS_FORMAT_WINDOWS_NO_SERVER = 2,
  ADS_FORMAT_WINDOWS_DN = 3,
  ADS_FORMAT_WINDOWS_PARENT = 4,
  ADS_FORMAT_X500 = 5,
  ADS_FORMAT_X500_NO_SERVER = 6,
  ADS_FORMAT_X500_DN = 7,
  ADS_FORMAT_X500_PARENT = 8,
  ADS_FORMAT_SERVER = 9,
  ADS_FORMAT_PROVIDER = 10,
  ADS_FORMAT_LEAF = 11
} ADS_FORMAT_ENUM;