typedef enum __MIDL___MIDL_itf_ads_0001_0077_0001 {
  ADS_OPTION_SERVERNAME = 0,
  ADS_OPTION_REFERRALS,
  ADS_OPTION_PAGE_SIZE,
  ADS_OPTION_SECURITY_MASK,
  ADS_OPTION_MUTUAL_AUTH_STATUS,
  ADS_OPTION_QUOTA,
  ADS_OPTION_PASSWORD_PORTNUMBER,
  ADS_OPTION_PASSWORD_METHOD,
  ADS_OPTION_ACCUMULATIVE_MODIFICATION,
  ADS_OPTION_SKIP_SID_LOOKUP
} ADS_OPTION_ENUM;