typedef enum __MIDL___MIDL_itf_ads_0000_0000_0022 {
  ADSIPROP_ASYNCHRONOUS = 0,
  ADSIPROP_DEREF_ALIASES = 0x1,
  ADSIPROP_SIZE_LIMIT = 0x2,
  ADSIPROP_TIME_LIMIT = 0x3,
  ADSIPROP_ATTRIBTYPES_ONLY = 0x4,
  ADSIPROP_SEARCH_SCOPE = 0x5,
  ADSIPROP_TIMEOUT = 0x6,
  ADSIPROP_PAGESIZE = 0x7,
  ADSIPROP_PAGED_TIME_LIMIT = 0x8,
  ADSIPROP_CHASE_REFERRALS = 0x9,
  ADSIPROP_SORT_ON = 0xa,
  ADSIPROP_CACHE_RESULTS = 0xb,
  ADSIPROP_ADSIFLAG = 0xc
} ADS_PREFERENCES_ENUM;