typedef struct _DDHAL_DESTROYDDLOCALDATA {
  DWORD                   dwFlags;
  LPDDRAWI_DIRECTDRAW_LCL pDDLcl;
  HRESULT                 ddRVal;
} *LPDDHAL_DESTROYDDLOCALDATA, DDHAL_DESTROYDDLOCALDATA;