typedef struct _DEBUG_PROCESSOR_IDENTIFICATION_IA64 {
  ULONG Model;
  ULONG Revision;
  ULONG Family;
  ULONG ArchRev;
  CHAR  VendorString[16];
} DEBUG_PROCESSOR_IDENTIFICATION_IA64, *PDEBUG_PROCESSOR_IDENTIFICATION_IA64;