typedef enum D3D12_DEBUG_FEATURE {
  D3D12_DEBUG_FEATURE_NONE = 0,
  D3D12_DEBUG_FEATURE_ALLOW_BEHAVIOR_CHANGING_DEBUG_AIDS = 0x1,
  D3D12_DEBUG_FEATURE_CONSERVATIVE_RESOURCE_STATE_TRACKING = 0x2,
  D3D12_DEBUG_FEATURE_DISABLE_VIRTUALIZED_BUNDLES_VALIDATION = 0x4,
  D3D12_DEBUG_FEATURE_EMULATE_WINDOWS7
} ;