typedef enum _NEW_LOG_FILE_FREQUENCY {
  IAS_LOGGING_UNLIMITED_SIZE = 0,
  IAS_LOGGING_DAILY,
  IAS_LOGGING_WEEKLY,
  IAS_LOGGING_MONTHLY,
  IAS_LOGGING_WHEN_FILE_SIZE_REACHES
} NEW_LOG_FILE_FREQUENCY;