typedef enum _CLIENTPROPERTIES {
  PROPERTY_CLIENT_REQUIRE_SIGNATURE,
  PROPERTY_CLIENT_UNUSED,
  PROPERTY_CLIENT_SHARED_SECRET,
  PROPERTY_CLIENT_NAS_MANUFACTURER,
  PROPERTY_CLIENT_ADDRESS,
  PROPERTY_CLIENT_QUARANTINE_COMPATIBLE,
  PROPERTY_CLIENT_ENABLED,
  PROPERTY_CLIENT_SECRET_TEMPLATE_GUID
} CLIENTPROPERTIES;