typedef enum _IASPROPERTIES {
  PROPERTY_IAS_RADIUSSERVERGROUPS_COLLECTION,
  PROPERTY_IAS_POLICIES_COLLECTION,
  PROPERTY_IAS_PROFILES_COLLECTION,
  PROPERTY_IAS_PROTOCOLS_COLLECTION,
  PROPERTY_IAS_AUDITORS_COLLECTION,
  PROPERTY_IAS_REQUESTHANDLERS_COLLECTION,
  PROPERTY_IAS_PROXYPOLICIES_COLLECTION,
  PROPERTY_IAS_PROXYPROFILES_COLLECTION,
  PROPERTY_IAS_REMEDIATIONSERVERGROUPS_COLLECTION,
  PROPERTY_IAS_SHVTEMPLATES_COLLECTION
} IASPROPERTIES;