typedef enum _AUTHENTICATION_TYPE {
  IAS_AUTH_INVALID = 0,
  IAS_AUTH_PAP,
  IAS_AUTH_MD5CHAP,
  IAS_AUTH_MSCHAP,
  IAS_AUTH_MSCHAP2,
  IAS_AUTH_EAP,
  IAS_AUTH_ARAP,
  IAS_AUTH_NONE,
  IAS_AUTH_CUSTOM,
  IAS_AUTH_MSCHAP_CPW,
  IAS_AUTH_MSCHAP2_CPW,
  IAS_AUTH_PEAP
} AUTHENTICATION_TYPE;