typedef enum _ATTRIBUTERESTRICTIONS {
  MULTIVALUED = 0x1,
  ALLOWEDINPROFILE = 0x2,
  ALLOWEDINCONDITION = 0x4,
  ALLOWEDINPROXYPROFILE = 0x8,
  ALLOWEDINPROXYCONDITION = 0x10,
  ALLOWEDINVPNDIALUP = 0x20,
  ALLOWEDIN8021X = 0x40
} ATTRIBUTERESTRICTIONS;