typedef enum _POLICYPROPERTIES {
  PROPERTY_POLICY_CONSTRAINT,
  PROPERTY_POLICY_MERIT,
  PROPERTY_POLICY_UNUSED0,
  PROPERTY_POLICY_UNUSED1,
  PROPERTY_POLICY_PROFILE_NAME,
  PROPERTY_POLICY_ACTION,
  PROPERTY_POLICY_CONDITIONS_COLLECTION,
  PROPERTY_POLICY_ENABLED,
  PROPERTY_POLICY_SOURCETAG
} POLICYPROPERTIES;