typedef enum _ATTRIBUTESYNTAX {
  IAS_SYNTAX_BOOLEAN = 1,
  IAS_SYNTAX_INTEGER,
  IAS_SYNTAX_ENUMERATOR,
  IAS_SYNTAX_INETADDR,
  IAS_SYNTAX_STRING,
  IAS_SYNTAX_OCTETSTRING,
  IAS_SYNTAX_UTCTIME,
  IAS_SYNTAX_PROVIDERSPECIFIC,
  IAS_SYNTAX_UNSIGNEDINTEGER,
  IAS_SYNTAX_INETADDR6
} ATTRIBUTESYNTAX;