typedef enum _RADIUSSERVERPROPERTIES {
  PROPERTY_RADIUSSERVER_AUTH_PORT,
  PROPERTY_RADIUSSERVER_AUTH_SECRET,
  PROPERTY_RADIUSSERVER_ACCT_PORT,
  PROPERTY_RADIUSSERVER_ACCT_SECRET,
  PROPERTY_RADIUSSERVER_ADDRESS,
  PROPERTY_RADIUSSERVER_FORWARD_ACCT_ONOFF,
  PROPERTY_RADIUSSERVER_PRIORITY,
  PROPERTY_RADIUSSERVER_WEIGHT,
  PROPERTY_RADIUSSERVER_TIMEOUT,
  PROPERTY_RADIUSSERVER_MAX_LOST,
  PROPERTY_RADIUSSERVER_BLACKOUT,
  PROPERTY_RADIUSSERVER_SEND_SIGNATURE,
  PROPERTY_RADIUSSERVER_AUTH_SECRET_TEMPLATE_GUID,
  PROPERTY_RADIUSSERVER_ACCT_SECRET_TEMPLATE_GUID
} RADIUSSERVERPROPERTIES;