typedef enum _RADIUSPROPERTIES {
  PROPERTY_RADIUS_ACCOUNTING_PORT,
  PROPERTY_RADIUS_AUTHENTICATION_PORT,
  PROPERTY_RADIUS_CLIENTS_COLLECTION,
  PROPERTY_RADIUS_VENDORS_COLLECTION
} RADIUSPROPERTIES;