typedef enum _IASOSTYPE {
  SYSTEM_TYPE_NT4_WORKSTATION = 0,
  SYSTEM_TYPE_NT5_WORKSTATION,
  SYSTEM_TYPE_NT6_WORKSTATION,
  SYSTEM_TYPE_NT6_1_WORKSTATION,
  SYSTEM_TYPE_NT6_2_WORKSTATION,
  SYSTEM_TYPE_NT6_3_WORKSTATION,
  SYSTEM_TYPE_NT10_0_WORKSTATION,
  SYSTEM_TYPE_NT4_SERVER,
  SYSTEM_TYPE_NT5_SERVER,
  SYSTEM_TYPE_NT6_SERVER,
  SYSTEM_TYPE_NT6_1_SERVER,
  SYSTEM_TYPE_NT6_2_SERVER,
  SYSTEM_TYPE_NT6_3_SERVER,
  SYSTEM_TYPE_NT10_0_SERVER
} IASOSTYPE, *PIASOSTYPE;