typedef enum _SHV_COMBINATION_TYPE {
  SHV_COMBINATION_TYPE_ALL_PASS = 0,
  SHV_COMBINATION_TYPE_ALL_FAIL,
  SHV_COMBINATION_TYPE_ONE_OR_MORE_PASS,
  SHV_COMBINATION_TYPE_ONE_OR_MORE_FAIL,
  SHV_COMBINATION_TYPE_ONE_OR_MORE_INFECTED,
  SHV_COMBINATION_TYPE_ONE_OR_MORE_TRANSITIONAL,
  SHV_COMBINATION_TYPE_ONE_OR_MORE_UNKNOWN,
  SHV_COMBINATION_TYPE_MAX
} SHV_COMBINATION_TYPE;