typedef enum _IASCOMMONPROPERTIES {
  PROPERTY_SDO_RESERVED = 0,
  PROPERTY_SDO_CLASS,
  PROPERTY_SDO_NAME,
  PROPERTY_SDO_DESCRIPTION,
  PROPERTY_SDO_ID,
  PROPERTY_SDO_DATASTORE_NAME,
  PROPERTY_SDO_TEMPLATE_GUID,
  PROPERTY_SDO_OPAQUE,
  PROPERTY_SDO_START = 0x400
} IASCOMMONPROPERTIES;