typedef enum _EAP_METHOD_PROPERTY_TYPE {
  emptPropCipherSuiteNegotiation = 0,
  emptPropMutualAuth,
  emptPropIntegrity,
  emptPropReplayProtection,
  emptPropConfidentiality,
  emptPropKeyDerivation,
  emptPropKeyStrength64,
  emptPropKeyStrength128,
  emptPropKeyStrength256,
  emptPropKeyStrength512,
  emptPropKeyStrength1024,
  emptPropDictionaryAttackResistance,
  emptPropFastReconnect,
  emptPropCryptoBinding,
  emptPropSessionIndependence,
  emptPropFragmentation,
  emptPropChannelBinding,
  emptPropNap,
  emptPropStandalone,
  emptPropMppeEncryption,
  emptPropTunnelMethod,
  emptPropSupportsConfig,
  emptPropCertifiedMethod,
  emptPropHiddenMethod,
  emptPropMachineAuth,
  emptPropUserAuth,
  emptPropIdentityPrivacy,
  emptPropMethodChaining,
  emptPropSharedStateEquivalence,
  emptLegacyMethodPropertyFlag = 31,
  emptPropVendorSpecific
} EAP_METHOD_PROPERTY_TYPE;