typedef enum _EAP_ATTRIBUTE_TYPE {
  eatMinimum = 0,
  eatUserName,
  eatUserPassword,
  eatMD5CHAPPassword,
  eatNASIPAddress,
  eatNASPort,
  eatServiceType,
  eatFramedProtocol,
  eatFramedIPAddress,
  eatFramedIPNetmask,
  eatFramedRouting = 10,
  eatFilterId,
  eatFramedMTU,
  eatFramedCompression,
  eatLoginIPHost,
  eatLoginService,
  eatLoginTCPPort,
  eatUnassigned17,
  eatReplyMessage,
  eatCallbackNumber,
  eatCallbackId = 20,
  eatUnassigned21,
  eatFramedRoute,
  eatFramedIPXNetwork,
  eatState,
  eatClass,
  eatVendorSpecific,
  eatSessionTimeout,
  eatIdleTimeout,
  eatTerminationAction,
  eatCalledStationId = 30,
  eatCallingStationId,
  eatNASIdentifier,
  eatProxyState,
  eatLoginLATService,
  eatLoginLATNode,
  eatLoginLATGroup,
  eatFramedAppleTalkLink,
  eatFramedAppleTalkNetwork,
  eatFramedAppleTalkZone,
  eatAcctStatusType = 40,
  eatAcctDelayTime,
  eatAcctInputOctets,
  eatAcctOutputOctets,
  eatAcctSessionId,
  eatAcctAuthentic,
  eatAcctSessionTime,
  eatAcctInputPackets,
  eatAcctOutputPackets,
  eatAcctTerminateCause,
  eatAcctMultiSessionId = 50,
  eatAcctLinkCount,
  eatAcctEventTimeStamp = 55,
  eatMD5CHAPChallenge = 60,
  eatNASPortType,
  eatPortLimit,
  eatLoginLATPort,
  eatTunnelType,
  eatTunnelMediumType,
  eatTunnelClientEndpoint,
  eatTunnelServerEndpoint,
  eatARAPPassword = 70,
  eatARAPFeatures,
  eatARAPZoneAccess,
  eatARAPSecurity,
  eatARAPSecurityData,
  eatPasswordRetry,
  eatPrompt,
  eatConnectInfo,
  eatConfigurationToken,
  eatEAPMessage,
  eatSignature = 80,
  eatARAPChallengeResponse = 84,
  eatAcctInterimInterval = 85,
  eatNASIPv6Address = 95,
  eatFramedInterfaceId,
  eatFramedIPv6Prefix,
  eatLoginIPv6Host,
  eatFramedIPv6Route,
  eatFramedIPv6Pool,
  eatARAPGuestLogon = 8096,
  eatCertificateOID,
  eatEAPConfiguration,
  eatPEAPEmbeddedEAPTypeId,
  eatPEAPFastRoamedSession = 8100,
  eatFastRoamedSession = 8100,
  eatEAPTLV = 8102,
  eatCredentialsChanged,
  eatInnerEapMethodType,
  eatClearTextPassword = 8107,
  eatQuarantineSoH = 8150,
  eatCertificateThumbprint = 8250,
  eatPeerId = 9000,
  eatServerId,
  eatMethodId,
  eatEMSK,
  eatSessionId,
  eatReserved
} EAP_ATTRIBUTE_TYPE, EapAttributeType;