typedef union _EAP_METHOD_PROPERTY_VALUE {
  EAP_METHOD_PROPERTY_VALUE_BOOL   empvBool;
  EAP_METHOD_PROPERTY_VALUE_DWORD  empvDword;
  EAP_METHOD_PROPERTY_VALUE_STRING empvString;
} EAP_METHOD_PROPERTY_VALUE;