typedef enum __MIDL___MIDL_itf_syncregistration_0000_0007_0001 {
  SRE_PROVIDER_ADDED = 0,
  SRE_PROVIDER_REMOVED,
  SRE_PROVIDER_UPDATED,
  SRE_PROVIDER_STATE_CHANGED,
  SRE_CONFIGUI_ADDED,
  SRE_CONFIGUI_REMOVED,
  SRE_CONFIGUI_UPDATED
} SYNC_REGISTRATION_EVENT;