typedef enum _WINHTTP_CONNECTION_PROXY_INFO_SWITCH {
    WINHTTP_CONNECTION_PROXY_INFO_SWITCH_CONFIG = 0,
    WINHTTP_CONNECTION_PROXY_INFO_SWITCH_SCRIPT = 1,
    WINHTTP_CONNECTION_PROXY_INFO_SWITCH_WPAD   = 2
} WINHTTP_CONNECTION_PROXY_INFO_SWITCH;