typedef enum _WINHTTP_CONNECTION_POLICY_TAG {
    TAG_WINHTTP_CONNECTION_POLICY_TAG_DEFAULT            = 0,
    TAG_WINHTTP_CONNECTION_POLICY_TAG_CONNECTION_MANAGER = 1,
    TAG_WINHTTP_CONNECTION_POLICY_TAG_WWWPT              = 2
} WINHTTP_CONNECTION_POLICY_TAG;