typedef enum tagQACONTAINERFLAGS {
  QACONTAINER_SHOWHATCHING = 0x1,
  QACONTAINER_SHOWGRABHANDLES = 0x2,
  QACONTAINER_USERMODE = 0x4,
  QACONTAINER_DISPLAYASDEFAULT = 0x8,
  QACONTAINER_UIDEAD = 0x10,
  QACONTAINER_AUTOCLIP = 0x20,
  QACONTAINER_MESSAGEREFLECT = 0x40,
  QACONTAINER_SUPPORTSMNEMONICS = 0x80
} QACONTAINERFLAGS;