typedef enum D2D1_DEVICE_CONTEXT_OPTIONS {
  D2D1_DEVICE_CONTEXT_OPTIONS_NONE = 0,
  D2D1_DEVICE_CONTEXT_OPTIONS_ENABLE_MULTITHREADED_OPTIMIZATIONS = 1,
  D2D1_DEVICE_CONTEXT_OPTIONS_FORCE_DWORD = 0xffffffff
} ;