typedef enum D2D1_INTERPOLATION_MODE {
  D2D1_INTERPOLATION_MODE_NEAREST_NEIGHBOR,
  D2D1_INTERPOLATION_MODE_LINEAR,
  D2D1_INTERPOLATION_MODE_CUBIC,
  D2D1_INTERPOLATION_MODE_MULTI_SAMPLE_LINEAR,
  D2D1_INTERPOLATION_MODE_ANISOTROPIC,
  D2D1_INTERPOLATION_MODE_HIGH_QUALITY_CUBIC,
  D2D1_INTERPOLATION_MODE_FORCE_DWORD = 0xffffffff
} ;