typedef enum __MIDL___MIDL_itf_wiavideo_xp_0000_0000_0001 {
  WIAVIDEO_NO_VIDEO = 1,
  WIAVIDEO_CREATING_VIDEO = 2,
  WIAVIDEO_VIDEO_CREATED = 3,
  WIAVIDEO_VIDEO_PLAYING = 4,
  WIAVIDEO_VIDEO_PAUSED = 5,
  WIAVIDEO_DESTROYING_VIDEO = 6
} WIAVIDEO_STATE;