typedef enum _EAP_AUTHENTICATOR_SEND_TIMEOUT {
  EAP_AUTHENTICATOR_SEND_TIMEOUT_NONE = 0,
  EAP_AUTHENTICATOR_SEND_TIMEOUT_BASIC,
  EAP_AUTHENTICATOR_SEND_TIMEOUT_INTERACTIVE
} EAP_AUTHENTICATOR_SEND_TIMEOUT;