typedef struct tagEMRSETICMPROFILE {
  EMR   emr;
  DWORD dwFlags;
  DWORD cbName;
  DWORD cbData;
  BYTE  Data[1];
} EMRSETICMPROFILE, *PEMRSETICMPROFILE, EMRSETICMPROFILEA, *PEMRSETICMPROFILEA, EMRSETICMPROFILEW, *PEMRSETICMPROFILEW;