typedef enum _tagAUTOCOMPLETELISTOPTIONS {
  ACLO_NONE = 0,
  ACLO_CURRENTDIR = 1,
  ACLO_MYCOMPUTER = 2,
  ACLO_DESKTOP = 4,
  ACLO_FAVORITES = 8,
  ACLO_FILESYSONLY = 16,
  ACLO_FILESYSDIRS = 32,
  ACLO_VIRTUALNAMESPACE = 64
} AUTOCOMPLETELISTOPTIONS;