typedef enum {
  DROPIMAGE_INVALID = -1,
  DROPIMAGE_NONE = 0,
  DROPIMAGE_COPY,
  DROPIMAGE_MOVE,
  DROPIMAGE_LINK,
  DROPIMAGE_LABEL = 6,
  DROPIMAGE_WARNING = 7,
  DROPIMAGE_NOIMAGE = 8
} DROPIMAGETYPE;