typedef struct {
  DATABLOCK_HEADER dbh;
  DATABLOCK_HEADER DUMMYSTRUCTNAME;
  WORD             wFillAttribute;
  WORD             wPopupFillAttribute;
  COORD            dwScreenBufferSize;
  COORD            dwWindowSize;
  COORD            dwWindowOrigin;
  DWORD            nFont;
  DWORD            nInputBufferSize;
  COORD            dwFontSize;
  UINT             uFontFamily;
  UINT             uFontWeight;
  WCHAR            FaceName[LF_FACESIZE];
  UINT             uCursorSize;
  BOOL             bFullScreen;
  BOOL             bQuickEdit;
  BOOL             bInsertMode;
  BOOL             bAutoPosition;
  UINT             uHistoryBufferSize;
  UINT             uNumberOfHistoryBuffers;
  BOOL             bHistoryNoDup;
  COLORREF         ColorTable[16];
} NT_CONSOLE_PROPS, *LPNT_CONSOLE_PROPS;