typedef enum tagPROBLEM_TYPE {
  PT_INVALID = 0,
  PT_LOW_HEALTH = 1,
  PT_LOWER_HEALTH = 2,
  PT_DOWN_STREAM_HEALTH = 4,
  PT_HIGH_UTILIZATION = 8,
  PT_HIGHER_UTILIZATION = 16,
  PT_UP_STREAM_UTILIZATION = 32
} PROBLEM_TYPE;