typedef enum _BLUETOOTH_IO_CAPABILITY {
  BLUETOOTH_IO_CAPABILITY_DISPLAYONLY = 0x00,
  BLUETOOTH_IO_CAPABILITY_DISPLAYYESNO = 0x01,
  BLUETOOTH_IO_CAPABILITY_KEYBOARDONLY = 0x02,
  BLUETOOTH_IO_CAPABILITY_NOINPUTNOOUTPUT = 0x03,
  BLUETOOTH_IO_CAPABILITY_UNDEFINED = 0xff
} BLUETOOTH_IO_CAPABILITY;