typedef struct _PEP_PROCESSOR_IDLE_CONSTRAINTS {
  ULONGLONG               IdleDuration;
  BOOLEAN                 Interruptible;
  PEP_PROCESSOR_IDLE_TYPE Type;
} PEP_PROCESSOR_IDLE_CONSTRAINTS, *PPEP_PROCESSOR_IDLE_CONSTRAINTS;