typedef enum _STORAGE_ZONES_ATTRIBUTES {
  ZonesAttributeTypeAndLengthMayDifferent,
  ZonesAttributeTypeSameLengthSame,
  ZonesAttributeTypeSameLastZoneLengthDifferent,
  ZonesAttributeTypeMayDifferentLengthSame
} STORAGE_ZONES_ATTRIBUTES, *PSTORAGE_ZONES_ATTRIBUTES;