typedef struct _STORAGE_DEVICE_SELF_ENCRYPTION_PROPERTY {
  ULONG   Version;
  ULONG   Size;
  BOOLEAN SupportsSelfEncryption;
} STORAGE_DEVICE_SELF_ENCRYPTION_PROPERTY, *PSTORAGE_DEVICE_SELF_ENCRYPTION_PROPERTY;