typedef struct _DEVICE_DSM_TIERING_QUERY_INPUT {
  ULONG Version;
  ULONG Size;
  ULONG Flags;
  ULONG NumberOfTierIds;
  GUID  TierIds[ANYSIZE_ARRAY];
} DEVICE_DSM_TIERING_QUERY_INPUT, *PDEVICE_DSM_TIERING_QUERY_INPUT, DEVICE_DSM_TIERING_QUERY_PARAMETERS, *PDEVICE_DSM_TIERING_QUERY_PARAMETERS;