typedef struct _DEVICE_DSM_REPORT_ZONES_DATA {
  ULONG                    Size;
  ULONG                    ZoneCount;
  STORAGE_ZONES_ATTRIBUTES Attributes;
  ULONG                    Reserved0;
  STORAGE_ZONE_DESCRIPTOR  ZoneDescriptors[ANYSIZE_ARRAY];
} DEVICE_DSM_REPORT_ZONES_DATA, *PDEVICE_DSM_REPORT_ZONES_DATA, DEVICE_DSM_REPORT_ZONES_OUTPUT, *PDEVICE_DSM_REPORT_ZONES_OUTPUT;