typedef struct _DEVICE_DSM_REPORT_ZONES_PARAMETERS {
  ULONG Size;
  UCHAR ReportOption;
  UCHAR Partial;
  UCHAR Reserved[2];
} DEVICE_DSM_REPORT_ZONES_PARAMETERS, *PDEVICE_DSM_REPORT_ZONES_PARAMETERS;