typedef struct _STORAGE_HW_ENDURANCE_DATA_DESCRIPTOR {
  ULONG                     Version;
  ULONG                     Size;
  STORAGE_HW_ENDURANCE_INFO EnduranceInfo;
} STORAGE_HW_ENDURANCE_DATA_DESCRIPTOR, *PSTORAGE_HW_ENDURANCE_DATA_DESCRIPTOR;