typedef enum _AVCSTRM_FUNCTION {
  AVCSTRM_READ,
  AVCSTRM_WRITE,
  AVCSTRM_ABORT_STREAMING,
  AVCSTRM_OPEN,
  AVCSTRM_CLOSE,
  AVCSTRM_GET_STATE,
  AVCSTRM_SET_STATE,
  AVCSTRM_GET_PROPERTY,
  AVCSTRM_SET_PROPERTY
} AVCSTRM_FUNCTION;