typedef enum _AVCSTRM_FORMAT {
  AVCSTRM_FORMAT_SDDV_NTSC,
  AVCSTRM_FORMAT_SDDV_PAL,
  AVCSTRM_FORMAT_MPEG2TS,
  AVCSTRM_FORMAT_HDDV_NTSC,
  AVCSTRM_FORMAT_HDDV_PAL,
  AVCSTRM_FORMAT_SDLDV_NTSC,
  AVCSTRM_FORMAT_SDLDV_PAL
} AVCSTRM_FORMAT;