DXGKDDI_VIDPNSOURCEMODESET_ACQUIREFIRSTMODEINFO DxgkddiVidpnsourcemodesetAcquirefirstmodeinfo;

NTSTATUS DxgkddiVidpnsourcemodesetAcquirefirstmodeinfo(
  [in]  IN_CONST_D3DKMDT_HVIDPNSOURCEMODESET hVidPnSourceModeSet,
  [out] DEREF_OUT_CONST_PPD3DKMDT_VIDPN_SOURCE_MODE ppFirstVidPnSourceModeInfo
)
{...}