DXGKDDI_CREATEPERIODICFRAMENOTIFICATION DxgkddiCreateperiodicframenotification;

NTSTATUS DxgkddiCreateperiodicframenotification(
  INOUT_PDXGKARG_CREATEPERIODICFRAMENOTIFICATION pCreatePeriodicFrameNotification
)
{...}