DXGKDDI_SETINTERRUPTTARGETPRESENTID DxgkddiSetinterrupttargetpresentid;

NTSTATUS DxgkddiSetinterrupttargetpresentid(
  IN_CONST_HANDLE hAdapter,
  IN_CONST_PDXGKARG_SETINTERRUPTTARGETPRESENTID pSetInterruptTargetPresentId
)
{...}