typedef enum _DXGK_PHYSICAL_MEMORY_TYPE {
  DXGK_PHYSICAL_MEMORY_TYPE_MDL,
  DXGK_PHYSICAL_MEMORY_TYPE_CONTIGUOUS_MEMORY,
  DXGK_PHYSICAL_MEMORY_TYPE_SECTION,
  DXGK_PHYSICAL_MEMORY_TYPE_IO_SPACE
} DXGK_PHYSICAL_MEMORY_TYPE;