typedef enum _DXGK_RECOMMENDVIDPNTOPOLOGY_REASON {
  DXGK_RVT_UNINITIALIZED,
  DXGK_RVT_INITIALIZATION_NOLKG,
  DXGK_RVT_AUGMENTATION_NOLKG,
  DXGK_RVT_AUGMENTATION_LKGOVERRIDE,
  DXGK_RVT_INITIALIZATION_LKGOVERRIDE
} DXGK_RECOMMENDVIDPNTOPOLOGY_REASON;