typedef enum _DXGK_GLITCH_EFFECT {
  DXGK_GLITCH_EFFECT_SYNC_LOSS,
  DXGK_GLITCH_EFFECT_GARBAGE_CONTENT,
  DXGK_GLITCH_EFFECT_STALE_CONTENT,
  DXGK_GLITCH_EFFECT_BLACK_CONTENT,
  DXGK_GLITCH_EFFECT_DEGRADED_CONTENT,
  DXGK_GLITCH_EFFECT_SEAMLESS
} DXGK_GLITCH_EFFECT;