typedef enum _DXGK_POWER_COMPONENT_TYPE {
  DXGK_POWER_COMPONENT_ENGINE,
  DXGK_POWER_COMPONENT_MONITOR,
  DXGK_POWER_COMPONENT_MONITOR_REFRESH,
  DXGK_POWER_COMPONENT_MEMORY,
  DXGK_POWER_COMPONENT_MEMORY_REFRESH,
  DXGK_POWER_COMPONENT_OTHER,
  DXGK_POWER_COMPONENT_D3_TRANSITION,
  DXGK_POWER_COMPONENT_SHARED,
  DXGK_POWER_COMPONENT_MAX
} DXGK_POWER_COMPONENT_TYPE;