typedef enum _DXGK_MONITOR_INTERFACE_VERSION {
  DXGK_MONITOR_INTERFACE_VERSION_UNINITIALIZED = 0,
  DXGK_MONITOR_INTERFACE_VERSION_V1 = 1,
  DXGK_MONITOR_INTERFACE_VERSION_V2 = 2,
  DXGK_MONITOR_INTERFACE_VERSION_V3
} DXGK_MONITOR_INTERFACE_VERSION;