typedef enum _DXGK_GLITCH_DURATION {
  DXGK_GLITCH_DURATION_INDEFINITE,
  DXGK_GLITCH_DURATION_MULTI_FRAME,
  DXGK_GLITCH_DURATION_SINGLE_FRAME,
  DXGK_GLITCH_DURATION_MULTI_LINE,
  DXGK_GLITCH_DURATION_SINGLE_LINE,
  DXGK_GLITCH_DURATION_NONE
} DXGK_GLITCH_DURATION;