typedef enum _DXGK_GLITCH_CAUSE {
  DXGK_GLITCH_CAUSE_DRIVER_ERROR,
  DXGK_GLITCH_CAUSE_TIMING_CHANGE,
  DXGK_GLITCH_CAUSE_PIPELINE_CHANGE,
  DXGK_GLITCH_CAUSE_MEMORY_TIMING,
  DXGK_GLITCH_CAUSE_ENCODER_RECONFIG,
  DXGK_GLITCH_CAUSE_MODIFIED_WIRE_USAGE,
  DXGK_GLITCH_CAUSE_METADATA_CHANGE,
  DXGK_GLITCH_CAUSE_NONE
} DXGK_GLITCH_CAUSE;