typedef enum _DXGK_PAGESIZE {
  DXGK_PAGESIZE_4KB,
  DXGK_PAGESIZE_8KB,
  DXGK_PAGESIZE_16KB,
  DXGK_PAGESIZE_32KB,
  DXGK_PAGESIZE_64KB,
  DXGK_PAGESIZE_128KB,
  DXGK_PAGESIZE_256KB,
  DXGK_PAGESIZE_512KB,
  DXGK_PAGESIZE_1MB,
  DXGK_PAGESIZE_2MB,
  DXGK_PAGESIZE_4MB,
  DXGK_PAGESIZE_8MB,
  DXGK_PAGESIZE_16MB,
  DXGK_PAGESIZE_32MB,
  DXGK_PAGESIZE_64MB,
  DXGK_PAGESIZE_128MB
} DXGK_PAGESIZE;