typedef struct _DXGK_SCHEDULING_LOG_CONTEXT_STATE_CHANGE {
  HANDLE                            hKmdContext;
  DXGK_SCHEDULING_LOG_CONTEXT_STATE newContextState;
} DXGK_SCHEDULING_LOG_CONTEXT_STATE_CHANGE;