typedef struct _DXGK_PRESENTMULTIPLANEOVERLAYINFO {
  [in] D3DDDI_VIDEO_PRESENT_SOURCE_ID    VidPnSourceId;
  [in] UINT                              PlaneListCount;
  [in] DXGK_PRESENTMULTIPLANEOVERLAYLIST *pPlaneList;
} DXGK_PRESENTMULTIPLANEOVERLAYINFO;