typedef struct _DXGK_CONNECTION_USB4_INFO {
  UINT Dpcd_DP_IN_Adapter_Number;
  UINT Dpcd_USB4_Driver_ID;
  BYTE Dpcd_USB4_ROUTER_TOPOLOGY_ID[5];
} DXGK_CONNECTION_USB4_INFO, *PDXGK_CONNECTION_USB4_INFO;