typedef struct _DXGKARG_RECOMMENDMONITORMODES {
  IN D3DDDI_VIDEO_PRESENT_TARGET_ID            VideoPresentTargetId;
  IN D3DKMDT_HMONITORSOURCEMODESET             hMonitorSourceModeSet;
  IN const DXGK_MONITORSOURCEMODESET_INTERFACE *pMonitorSourceModeSetInterface;
} DXGKARG_RECOMMENDMONITORMODES;