typedef struct _DXGKARG_QUERYVIDPNHWCAPABILITY {
  [in]  IN D3DKMDT_HVIDPN                 hFunctionalVidPn;
  [in]  IN D3DDDI_VIDEO_PRESENT_SOURCE_ID SourceId;
  [in]  IN D3DDDI_VIDEO_PRESENT_TARGET_ID TargetId;
  [out] OUT D3DKMDT_VIDPN_HW_CAPABILITY   VidPnHWCaps;
} DXGKARG_QUERYVIDPNHWCAPABILITY;