typedef struct _DXGK_MONITORLINKINFO {
  [in]  DXGK_MONITORLINKINFO_USAGEHINTS    UsageHints;
  [out] DXGK_MONITORLINKINFO_CAPABILITIES  Capabilities;
  [out] D3DKMDT_WIRE_FORMAT_AND_PREFERENCE DitheringSupport;
} DXGK_MONITORLINKINFO;