typedef struct _DXGK_MONITORSOURCEMODESET_INTERFACE {
  DXGKDDI_MONITORSOURCEMODESET_GETNUMMODES              pfnGetNumModes;
  DXGKDDI_MONITORSOURCEMODESET_ACQUIREPREFERREDMODEINFO pfnAcquirePreferredModeInfo;
  DXGKDDI_MONITORSOURCEMODESET_ACQUIREFIRSTMODEINFO     pfnAcquireFirstModeInfo;
  DXGKDDI_MONITORSOURCEMODESET_ACQUIRENEXTMODEINFO      pfnAcquireNextModeInfo;
  DXGKDDI_MONITORSOURCEMODESET_CREATENEWMODEINFO        pfnCreateNewModeInfo;
  DXGKDDI_MONITORSOURCEMODESET_ADDMODE                  pfnAddMode;
  DXGKDDI_MONITORSOURCEMODESET_RELEASEMODEINFO          pfnReleaseModeInfo;
} DXGK_MONITORSOURCEMODESET_INTERFACE;