typedef struct _DXGK_MONITOR_INTERFACE_V2 {
  DXGK_MONITOR_INTERFACE_VERSION                  Version;
  DXGKDDI_MONITOR_ACQUIREMONITORSOURCEMODESET     pfnAcquireMonitorSourceModeSet;
  DXGKDDI_MONITOR_RELEASEMONITORSOURCEMODESET     pfnReleaseMonitorSourceModeSet;
  DXGKDDI_MONITOR_GETMONITORFREQUENCYRANGESET     pfnGetMonitorFrequencyRangeSet;
  DXGKDDI_MONITOR_GETMONITORDESCRIPTORSET         pfnGetMonitorDescriptorSet;
  DXGKDDI_MONITOR_GETADDITIONALMONITORMODESET     pfnGetAdditionalMonitorModeSet;
  DXGKDDI_MONITOR_RELEASEADDITIONALMONITORMODESET pfnReleaseAdditionalMonitorModeSet;
} DXGK_MONITOR_INTERFACE_V2;