typedef struct _DXGKARGCB_ISFEATUREENABLED2 {
  DXGK_FEATURE_ID                   FeatureId;
  DXGKARGCB_ISFEATUREENABLED2_FLAGS Flags;
  DXGK_ISFEATUREENABLED_RESULT      Result;
} DXGKARGCB_ISFEATUREENABLED2;