typedef struct _DXGKARGCB_DISCONNECTDOORBELL {
  HANDLE                             hHwQueue;
  DXGKARGCB_DISCONNECTDOORBELL_FLAGS Flags;
  D3DDDI_DOORBELLSTATUS              DisconnectReason;
} DXGKARGCB_DISCONNECTDOORBELL;