typedef struct _DXGKARG_CONTROLMODEBEHAVIOR {
  IN DXGK_MODE_BEHAVIOR_FLAGS  Request;
  OUT DXGK_MODE_BEHAVIOR_FLAGS Satisfied;
  OUT DXGK_MODE_BEHAVIOR_FLAGS NotSatisfied;
} DXGKARG_CONTROLMODEBEHAVIOR;