typedef struct _DXGKARG_RECOMMENDVIDPNTOPOLOGY {
  IN D3DKMDT_HVIDPN                     hVidPn;
  IN D3DDDI_VIDEO_PRESENT_SOURCE_ID     VidPnSourceId;
  IN DXGK_RECOMMENDVIDPNTOPOLOGY_REASON RequestReason;
  IN D3DKMDT_HVIDPNTOPOLOGY             hFallbackTopology;
} DXGKARG_RECOMMENDVIDPNTOPOLOGY;