typedef struct _DXGKARG_SETUPPRIORITYBANDS {
  UINT64 gracePeriodForBand[DXGK_SCHEDULING_PRIORITY_BAND_COUNT];
  UINT64 processQuantumForBand[DXGK_SCHEDULING_PRIORITY_BAND_COUNT];
  UINT64 processGracePeriodForBand[DXGK_SCHEDULING_PRIORITY_BAND_COUNT];
  UINT   targetNormalBandPercentage;
} DXGKARG_SETUPPRIORITYBANDS;