EVT_IDD_CX_MONITOR_QUERY_TARGET_MODES EvtIddCxMonitorQueryTargetModes;

NTSTATUS EvtIddCxMonitorQueryTargetModes(
  IDDCX_MONITOR MonitorObject,
  const IDARG_IN_QUERYTARGETMODES *pInArgs,
  IDARG_OUT_QUERYTARGETMODES *pOutArgs
)
{...}