EVT_IDD_CX_PARSE_MONITOR_DESCRIPTION2 EvtIddCxParseMonitorDescription2;

NTSTATUS EvtIddCxParseMonitorDescription2(
  const IDARG_IN_PARSEMONITORDESCRIPTION2 *pInArgs,
  IDARG_OUT_PARSEMONITORDESCRIPTION *pOutArgs
)
{...}