typedef enum IDDCX_MONITOR_DESCRIPTION_TYPE {
  IDDCX_MONITOR_DESCRIPTION_TYPE_UNINITIALIZED = 0,
  IDDCX_MONITOR_DESCRIPTION_TYPE_EDID = 1,
  IDDCX_MONITOR_DESCRIPTION_TYPE_DISPLAYID_AND_EDID = 2
} ;