typedef enum IDDCX_DISPLAYCONFIGPATH2_FLAGS {
  IDDCX_DISPLAYCONFIGPATH2_FLAGS_UNINITIALIZED = 0x0,
  IDDCX_DISPLAYCONFIGPATH2_FLAGS_MODE_VALID = 0x1,
  IDDCX_DISPLAYCONFIGPATH2_FLAGS_MONITOR_SCALE_FACTOR_VALID = 0x2,
  IDDCX_DISPLAYCONFIGPATH2_FLAGS_MONITOR_PHYSICAL_SIZE_VALID = 0x4,
  IDDCX_DISPLAYCONFIGPATH2_FLAGS_MONITOR_COLORIMETRY_VALID = 0x8,
  IDDCX_DISPLAYCONFIGPATH2_FLAGS_MONITOR_SDRWHITELEVEL_VALID = 0x10
} ;