typedef enum IDDCX_TRANSMISSION_TYPE {
  IDDCX_TRANSMISSION_TYPE_UNINITIALIZED = 0,
  IDDCX_TRANSMISSION_TYPE_WIRED_USB = 0x1,
  IDDCX_TRANSMISSION_TYPE_WIRED_MIRACAST = 0x2,
  IDDCX_TRANSMISSION_TYPE_WIRED_OTHER = 0x3,
  IDDCX_TRANSMISSION_TYPE_WIRELESS_MAUSB = 0x4,
  IDDCX_TRANSMISSION_TYPE_WIRELESS_USB_OTHER = 0x5,
  IDDCX_TRANSMISSION_TYPE_WIRELESS_WIFI_OTHER = 0x6,
  IDDCX_TRANSMISSION_TYPE_WIRELESS_MIRACAST = 0x7,
  IDDCX_TRANSMISSION_TYPE_WIRELESS_OTHER = 0x8,
  IDDCX_TRANSMISSION_TYPE_NETWORK_OTHER = 0x9,
  IDDCX_TRANSMISSION_TYPE_OTHER = 0xFFFFFFFF
} ;