typedef enum IDDCX_DISPLAYCONFIG_MONITOR_COLORIMETRY_FLAGS {
  IDDCX_DISPLAYCONFIG_MONITOR_COLORIMETRY_FLAGS_UNINITIALIZED = 0x0,
  IDDCX_DISPLAYCONFIG_MONITOR_COLORIMETRY_FLAGS_BT2020YCC = 0x1,
  IDDCX_DISPLAYCONFIG_MONITOR_COLORIMETRY_FLAGS_BT2020RGB = 0x2,
  IDDCX_DISPLAYCONFIG_MONITOR_COLORIMETRY_FLAGS_ST2084 = 0x4
} ;