typedef enum IDDCX_DISPLAYCONFIG_MONITOR_COLORMODE {
  IDDCX_DISPLAYCONFIG_MONITOR_COLORMODE_UNINITIALIZED = 0,
  IDDCX_DISPLAYCONFIG_MONITOR_COLORMODE_SDR = 1,
  IDDCX_DISPLAYCONFIG_MONITOR_COLORMODE_SDRWCG = 2,
  IDDCX_DISPLAYCONFIG_MONITOR_COLORMODE_HDR10 = 3
} ;