typedef enum IDDCX_BITS_PER_COMPONENT {
  IDDCX_BITS_PER_COMPONENT_NONE = 0,
  IDDCX_BITS_PER_COMPONENT_6 = 0x1,
  IDDCX_BITS_PER_COMPONENT_8 = 0x2,
  IDDCX_BITS_PER_COMPONENT_10 = 0x4,
  IDDCX_BITS_PER_COMPONENT_12 = 0x8,
  IDDCX_BITS_PER_COMPONENT_14 = 0x10,
  IDDCX_BITS_PER_COMPONENT_16 = 0x20
} ;