typedef enum IDDCX_DEVICE_FEATURES_1_11 {
  IDDCX_DEVICE_FEATURES_1_11_NONE,
  IDDCX_DEVICE_FEATURES_1_11_D3D12 = 1,
  IDDCX_DEVICE_FEATURES_1_11_DISPLAY_ID_ONLY = 2,
  IDDCX_DEVICE_FEATURES_1_11_UPDATE_REENCODE_COUNT = 4
} ;