typedef enum IDDCX_HDR10_FRAME_METADATA_TYPE {
  IDDCX_HDR10_FRAME_METADATA_TYPE_UNINITIALIZED = 0,
  IDDCX_HDR10_FRAME_METADATA_TYPE_DEFAULT = 1,
  IDDCX_HDR10_FRAME_METADATA_TYPE_UNCHANGED = 2,
  IDDCX_HDR10_FRAME_METADATA_TYPE_NEW = 3
} ;