typedef enum IDDCX_FEATURE_IMPLEMENTATION {
  IDDCX_FEATURE_IMPLEMENTATION_UNINITIALIZED = 0,
  IDDCX_FEATURE_IMPLEMENTATION_NONE = 1,
  IDDCX_FEATURE_IMPLEMENTATION_HARDWARE = 2,
  IDDCX_FEATURE_IMPLEMENTATION_SOFTWARE = 3
} ;