typedef enum FWP_VSWITCH_NETWORK_TYPE_ {
  FWP_VSWITCH_NETWORK_TYPE_UNKNOWN = 0,
  FWP_VSWITCH_NETWORK_TYPE_PRIVATE,
  FWP_VSWITCH_NETWORK_TYPE_INTERNAL,
  FWP_VSWITCH_NETWORK_TYPE_EXTERNAL
} FWP_VSWITCH_NETWORK_TYPE;