typedef enum _DXVAHDDDI_FILTER {
  DXVAHDDDI_FILTER_BRIGHTNESS,
  DXVAHDDDI_FILTER_CONTRAST,
  DXVAHDDDI_FILTER_HUE,
  DXVAHDDDI_FILTER_SATURATION,
  DXVAHDDDI_FILTER_NOISE_REDUCTION,
  DXVAHDDDI_FILTER_EDGE_ENHANCEMENT,
  DXVAHDDDI_FILTER_ANAMORPHIC_SCALING
} DXVAHDDDI_FILTER;