typedef enum _DXVAHDDDI_FEATURE_CAPS {
  DXVAHDDDI_FEATURE_CAPS_ALPHA_FILL,
  DXVAHDDDI_FEATURE_CAPS_CONSTRICTION,
  DXVAHDDDI_FEATURE_CAPS_LUMA_KEY,
  DXVAHDDDI_FEATURE_CAPS_ALPHA_PALETTE,
  DXVAHDDDI_FEATURE_CAPS_ROTATION
} DXVAHDDDI_FEATURE_CAPS;