typedef enum _D3DDDIQUERYTYPE {
  D3DDDIQUERYTYPE_VCACHE,
  D3DDDIQUERYTYPE_RESOURCEMANAGER,
  D3DDDIQUERYTYPE_VERTEXSTATS,
  D3DDDIQUERYTYPE_DDISTATS,
  D3DDDIQUERYTYPE_EVENT,
  D3DDDIQUERYTYPE_OCCLUSION,
  D3DDDIQUERYTYPE_TIMESTAMP,
  D3DDDIQUERYTYPE_TIMESTAMPDISJOINT,
  D3DDDIQUERYTYPE_TIMESTAMPFREQ,
  D3DDDIQUERYTYPE_PIPELINETIMINGS,
  D3DDDIQUERYTYPE_INTERFACETIMINGS,
  D3DDDIQUERYTYPE_VERTEXTIMINGS,
  D3DDDIQUERYTYPE_PIXELTIMINGS,
  D3DDDIQUERYTYPE_BANDWIDTHTIMINGS,
  D3DDDIQUERYTYPE_CACHEUTILIZATION,
  D3DDDIQUERYTYPE_COUNTER_DEVICE_DEPENDENT
} D3DDDIQUERYTYPE;