typedef enum _DXVAHDDDI_ITELECINE_CAPS {
  DXVAHDDDI_ITELECINE_CAPS_32,
  DXVAHDDDI_ITELECINE_CAPS_22,
  DXVAHDDDI_ITELECINE_CAPS_2224,
  DXVAHDDDI_ITELECINE_CAPS_2332,
  DXVAHDDDI_ITELECINE_CAPS_32322,
  DXVAHDDDI_ITELECINE_CAPS_55,
  DXVAHDDDI_ITELECINE_CAPS_64,
  DXVAHDDDI_ITELECINE_CAPS_87,
  DXVAHDDDI_ITELECINE_CAPS_222222222223,
  DXVAHDDDI_ITELECINE_CAPS_OTHER
} DXVAHDDDI_ITELECINE_CAPS;