typedef enum _DXVAHDDDI_FILTER_CAPS {
  DXVAHDDDI_FILTER_CAPS_BRIGHTNESS,
  DXVAHDDDI_FILTER_CAPS_CONTRAST,
  DXVAHDDDI_FILTER_CAPS_HUE,
  DXVAHDDDI_FILTER_CAPS_SATURATION,
  DXVAHDDDI_FILTER_CAPS_NOISE_REDUCTION,
  DXVAHDDDI_FILTER_CAPS_EDGE_ENHANCEMENT,
  DXVAHDDDI_FILTER_CAPS_ANAMORPHIC_SCALING
} DXVAHDDDI_FILTER_CAPS;