typedef enum _D3DDDI_DEVICEEXECUTION_STATE {
  D3DDDI_DEVICEEXECUTION_ACTIVE,
  D3DDDI_DEVICEEXECUTION_RESET,
  D3DDDI_DEVICEEXECUTION_HUNG,
  D3DDDI_DEVICEEXECUTION_STOPPED,
  D3DDDI_DEVICEEXECUTION_ERROR_OUTOFMEMORY,
  D3DDDI_DEVICEEXECUTION_ERROR_DMAFAULT
} D3DDDI_DEVICEEXECUTION_STATE;