typedef enum _DXVAHDDDI_BLT_STATE {
  DXVAHDDDI_BLT_STATE_TARGET_RECT,
  DXVAHDDDI_BLT_STATE_BACKGROUND_COLOR,
  DXVAHDDDI_BLT_STATE_OUTPUT_COLOR_SPACE,
  DXVAHDDDI_BLT_STATE_ALPHA_FILL,
  DXVAHDDDI_BLT_STATE_CONSTRICTION,
  DXVAHDDDI_BLT_STATE_PRIVATE
} DXVAHDDDI_BLT_STATE;