typedef enum _D3DDDITEXTUREFILTERTYPE {
  D3DDDITEXF_NONE,
  D3DDDITEXF_POINT,
  D3DDDITEXF_LINEAR,
  D3DDDITEXF_ANISOTROPIC,
  D3DDDITEXF_PYRAMIDALQUAD,
  D3DDDITEXF_GAUSSIANQUAD,
  D3DDDITEXF_FORCE_UINT
} D3DDDITEXTUREFILTERTYPE;