typedef enum _DXVAHDDDI_DEVICE_CAPS {
  DXVAHDDDI_DEVICE_CAPS_LINEAR_SPACE,
  DXVAHDDDI_DEVICE_CAPS_xvYCC,
  DXVAHDDDI_DEVICE_CAPS_RGB_RANGE_CONVERSION,
  DXVAHDDDI_DEVICE_CAPS_YCbCr_MATRIX_CONVERSION,
  DXVAHDDDI_DEVICE_CAPS_NOMINAL_RANGE
} DXVAHDDDI_DEVICE_CAPS;