typedef struct _D3DDDICB_WAITFORSYNCHRONIZATIONOBJECT {
  [in] HANDLE        hContext;
  [in] UINT          ObjectCount;
       D3DKMT_HANDLE ObjectHandleArray[D3DDDI_MAX_OBJECT_WAITED_ON];
} D3DDDICB_WAITFORSYNCHRONIZATIONOBJECT;