typedef struct _D3DDDICB_WAITFORSYNCHRONIZATIONOBJECT2 {
  [in] HANDLE        hContext;
  [in] UINT          ObjectCount;
       D3DKMT_HANDLE ObjectHandleArray[D3DDDI_MAX_OBJECT_WAITED_ON];
  [in] UINT64        FenceValue;
} D3DDDICB_WAITFORSYNCHRONIZATIONOBJECT2;