typedef struct _D3DDDI_ADAPTERCALLBACKS {
  PFND3DDDI_QUERYADAPTERINFOCB         pfnQueryAdapterInfoCb;
  PFND3DDDI_GETMULTISAMPLEMETHODLISTCB pfnGetMultisampleMethodListCb;
  PFND3DDDI_QUERYADAPTERINFOCB2        pfnQueryAdapterInfoCb2;
} D3DDDI_ADAPTERCALLBACKS;