typedef struct _D3DDDIARG_DXVAHD_GETVIDEOPROCESSBLTSTATEPRIVATE {
  [in]     HANDLE                           hVideoProcessor;
  [in/out] DXVAHDDDI_BLT_STATE_PRIVATE_DATA *pData;
} D3DDDIARG_DXVAHD_GETVIDEOPROCESSBLTSTATEPRIVATE;