typedef struct _D3DDDI_ADAPTERCALLBACKS {
  PFND3DDDI_QUERYADAPTERINFOCB         pfnQueryAdapterInfoCb;
  PFND3DDDI_GETMULTISAMPLEMETHODLISTCB pfnGetMultisampleMethodListCb;
  PFND3DDDI_QUERYADAPTERINFOCB2        pfnQueryAdapterInfoCb2;
  PFND3DDDI_QUERYADAPTERINFOCB3        pfnQueryAdapterInfoCb3;
} D3DDDI_ADAPTERCALLBACKS;