typedef enum __MIDL___MIDL_itf_UIAnimation_0000_0010_0001 {
  UI_ANIMATION_DEPENDENCY_NONE = 0,
  UI_ANIMATION_DEPENDENCY_INTERMEDIATE_VALUES = 0x1,
  UI_ANIMATION_DEPENDENCY_FINAL_VALUE = 0x2,
  UI_ANIMATION_DEPENDENCY_FINAL_VELOCITY = 0x4,
  UI_ANIMATION_DEPENDENCY_DURATION = 0x8
} UI_ANIMATION_DEPENDENCIES;