typedef enum __MIDL___MIDL_itf_UIAnimation_0000_0002_0001 {
  UI_ANIMATION_STORYBOARD_BUILDING = 0,
  UI_ANIMATION_STORYBOARD_SCHEDULED = 1,
  UI_ANIMATION_STORYBOARD_CANCELLED = 2,
  UI_ANIMATION_STORYBOARD_PLAYING = 3,
  UI_ANIMATION_STORYBOARD_TRUNCATED = 4,
  UI_ANIMATION_STORYBOARD_FINISHED = 5,
  UI_ANIMATION_STORYBOARD_READY = 6,
  UI_ANIMATION_STORYBOARD_INSUFFICIENT_PRIORITY = 7
} UI_ANIMATION_STORYBOARD_STATUS;