typedef enum tagOFFLINEFILES_COMPARE {
  OFFLINEFILES_COMPARE_EQ = 0,
  OFFLINEFILES_COMPARE_NEQ,
  OFFLINEFILES_COMPARE_LT,
  OFFLINEFILES_COMPARE_GT,
  OFFLINEFILES_COMPARE_LTE,
  OFFLINEFILES_COMPARE_GTE
} OFFLINEFILES_COMPARE;