typedef enum tagOFFLINEFILES_PATHFILTER_MATCH {
  OFFLINEFILES_PATHFILTER_SELF = 0,
  OFFLINEFILES_PATHFILTER_CHILD,
  OFFLINEFILES_PATHFILTER_DESCENDENT,
  OFFLINEFILES_PATHFILTER_SELFORCHILD,
  OFFLINEFILES_PATHFILTER_SELFORDESCENDENT
} OFFLINEFILES_PATHFILTER_MATCH;