typedef enum tagOFFLINEFILES_CACHING_MODE {
  OFFLINEFILES_CACHING_MODE_NONE = 0,
  OFFLINEFILES_CACHING_MODE_NOCACHING,
  OFFLINEFILES_CACHING_MODE_MANUAL,
  OFFLINEFILES_CACHING_MODE_AUTO_DOC,
  OFFLINEFILES_CACHING_MODE_AUTO_PROGANDDOC
} OFFLINEFILES_CACHING_MODE;