typedef enum tagOFFLINEFILES_ITEM_TYPE {
  OFFLINEFILES_ITEM_TYPE_FILE = 0,
  OFFLINEFILES_ITEM_TYPE_DIRECTORY,
  OFFLINEFILES_ITEM_TYPE_SHARE,
  OFFLINEFILES_ITEM_TYPE_SERVER
} OFFLINEFILES_ITEM_TYPE;