typedef struct tMIXERCONTROLDETAILS_LISTTEXT {
  DWORD dwParam1;
  DWORD dwParam2;
  char  szName[MIXER_LONG_NAME_CHARS];
} MIXERCONTROLDETAILS_LISTTEXT, *PMIXERCONTROLDETAILS_LISTTEXT, *LPMIXERCONTROLDETAILS_LISTTEXT;