typedef struct _SIDEBANDAUDIO_EP_USBAUDIO_TRANSPORT_RESOURCES {
  USHORT bcdAudioSpec;
  UCHAR  bDelay;
  UCHAR  bSlotSize;
} SIDEBANDAUDIO_EP_USBAUDIO_TRANSPORT_RESOURCES, *PSIDEBANDAUDIO_EP_USBAUDIO_TRANSPORT_RESOURCES;