typedef struct _WLX_TERMINAL_SERVICES_DATA {
  WCHAR ProfilePath[WLX_DIRECTORY_LENGTH + 1];
  WCHAR HomeDir[WLX_DIRECTORY_LENGTH + 1];
  WCHAR HomeDirDrive[4];
} WLX_TERMINAL_SERVICES_DATA, *PWLX_TERMINAL_SERVICES_DATA;