typedef enum _WDI_PACKET_FILTER_TYPE {
  WDI_PACKET_FILTER_NONE,
  WDI_PACKET_FILTER_DIRECTED,
  WDI_PACKET_FILTER_MULTICAST,
  WDI_PACKET_FILTER_ALL_MULTICAST,
  WDI_PACKET_FILTER_BROADCAST,
  WDI_PACKET_FILTER_PROMISCUOUS,
  WDI_PACKET_FILTER_802_11_RAW_DATA,
  WDI_PACKET_FILTER_802_11_DIRECTED_MGMT,
  WDI_PACKET_FILTER_802_11_BROADCAST_MGMT,
  WDI_PACKET_FILTER_802_11_MULTICAST_MGMT,
  WDI_PACKET_FILTER_802_11_ALL_MULTICAST_MGMT,
  WDI_PACKET_FILTER_802_11_PROMISCUOUS_MGMT,
  WDI_PACKET_FILTER_802_11_RAW_MGMT,
  WDI_PACKET_FILTER_802_11_DIRECTED_CTRL,
  WDI_PACKET_FILTER_802_11_BROADCAST_CTRL,
  WDI_PACKET_FILTER_802_11_PROMISCUOUS_CTRL,
  WDI_PACKET_FILTER_ALL
} WDI_PACKET_FILTER_TYPE;