typedef enum _WDI_P2P_DISCOVER_TYPE {
  WDI_P2P_DISCOVER_TYPE_SCAN_ONLY,
  WDI_P2P_DISCOVER_TYPE_FIND_ONLY,
  WDI_P2P_DISCOVER_TYPE_AUTO,
  WDI_P2P_DISCOVER_TYPE_SCAN_SOCIAL_CHANNELS,
  WDI_P2P_DISCOVER_TYPE_MAX_VALUE
} WDI_P2P_DISCOVER_TYPE;