typedef enum _WDI_AUTH_ALGORITHM {
  WDI_AUTH_ALGO_UNKNOWN,
  WDI_AUTH_ALGO_80211_OPEN,
  WDI_AUTH_ALGO_80211_SHARED_KEY,
  WDI_AUTH_ALGO_WPA,
  WDI_AUTH_ALGO_WPA_PSK,
  WDI_AUTH_ALGO_WPA_NONE,
  WDI_AUTH_ALGO_RSNA,
  WDI_AUTH_ALGO_RSNA_PSK,
  WDI_AUTH_ALGO_WPA3_ENT_192,
  WDI_AUTH_ALGO_WPA3_SAE,
  WDI_AUTH_ALGO_OWE,
  WDI_AUTH_ALGO_WPA3_ENT,
  WDI_AUTH_ALGO_IHV_START,
  WDI_AUTH_ALGO_IHV_END
} WDI_AUTH_ALGORITHM;