typedef enum _WDI_FTM_RESPONSE_STATUS {
  WDI_FTM_RESPONSE_STATUS_SUCCESS,
  WDI_FTM_RESPONSE_STATUS_UNREACHABLE,
  WDI_FTM_RESPONSE_STATUS_REJECTED,
  WDI_FTM_RESPONSE_STATUS_INCAPABLE,
  WDI_FTM_RESPONSE_STATUS_TIMEOUT,
  WDI_FTM_RESPONSE_STATUS_NOT_ATTEMPTED,
  WDI_FTM_RESPONSE_STATUS_ABORTED,
  WDI_FTM_RESPONSE_STATUS_FAILED
} WDI_FTM_RESPONSE_STATUS;