typedef enum _WDI_SCAN_TRIGGER {
  WDI_SCAN_TRIGGER_MANUAL,
  WDI_SCAN_TRIGGER_BACKGROUND,
  WDI_SCAN_TRIGGER_ROAM,
  WDI_SCAN_TRIGGER_CONNECT,
  WDI_SCAN_TRIGGER_ANQP_QUERY,
  WDI_SCAN_TRIGGER_FAST_ROAM,
  WDI_SCAN_TRIGGER_FTM
} WDI_SCAN_TRIGGER;