typedef enum _WDI_STOP_AP_REASON {
  WDI_STOP_AP_REASON_FREQUENCY_NOT_AVAILABLE,
  WDI_STOP_AP_REASON_CHANNEL_NOT_AVAILABLE,
  WDI_STOP_AP_REASON_AP_ACTIVE,
  WDI_STOP_AP_REASON_IHV_START,
  WDI_STOP_AP_REASON_IHV_END
} WDI_STOP_AP_REASON;