typedef enum _WDI_CIPHER_ALGORITHM {
  WDI_CIPHER_ALGO_NONE,
  WDI_CIPHER_ALGO_WEP40,
  WDI_CIPHER_ALGO_TKIP,
  WDI_CIPHER_ALGO_CCMP,
  WDI_CIPHER_ALGO_WEP104,
  WDI_CIPHER_ALGO_BIP,
  WDI_CIPHER_ALGO_GCMP,
  WDI_CIPHER_ALGO_GCMP_256,
  WDI_CIPHER_ALGO_CCMP_256,
  WDI_CIPHER_ALGO_BIP_GMAC_128,
  WDI_CIPHER_ALGO_BIP_GMAC_256,
  WDI_CIPHER_ALGO_BIP_CMAC_256,
  WDI_CIPHER_ALGO_WPA_USE_GROUP,
  WDI_CIPHER_ALGO_RSN_USE_GROUP,
  WDI_CIPHER_ALGO_WEP,
  WDI_CIPHER_ALGO_IHV_START,
  WDI_CIPHER_ALGO_IHV_END
} WDI_CIPHER_ALGORITHM;