typedef enum _WDI_POWER_SAVE_LEVEL {
  WDI_POWER_SAVE_LEVEL_NO_POWER_SAVE,
  WDI_POWER_SAVE_LEVEL_FAST_PSP,
  WDI_POWER_SAVE_LEVEL_MAX_PSP,
  WDI_POWER_SAVE_LEVEL_MAXIMUM_LEVEL
} WDI_POWER_SAVE_LEVEL;