typedef enum _WDI_P2P_LISTEN_STATE {
  WDI_P2P_LISTEN_STATE_OFF,
  WDI_P2P_LISTEN_STATE_PASSIVE_AVAILABILITY,
  WDI_P2P_LISTEN_STATE_AUTOMATIC_AVAILABILITY,
  WDI_P2P_LISTEN_STATE_HIGH_AVAILABILITY,
  WDI_P2P_LISTEN_STATE_DUMMY_MAX_VALUE
} WDI_P2P_LISTEN_STATE;