typedef enum _WDI_SAE_REQUEST_TYPE {
  WDI_SAE_REQUEST_TYPE_COMMIT_REQUEST = 0,
  WDI_SAE_REQUEST_TYPE_CONFIRM_REQUEST = 1,
  WDI_SAE_REQUEST_TYPE_FAILURE = 2,
  WDI_SAE_REQUEST_TYPE_SUCCESS = 3,
  WDI_SAE_REQUEST_TYPE_COMMIT_REQUEST_H2E = 4
} WDI_SAE_REQUEST_TYPE;