typedef struct tagHH_WINTYPE {
  int         cbStruct;
  BOOL        fUniCodeStrings;
  LPCTSTR     pszType;
  DWORD       fsValidMembers;
  DWORD       fsWinProperties;
  LPCTSTR     pszCaption;
  DWORD       dwStyles;
  DWORD       dwExStyles;
  RECT        rcWindowPos;
  int         nShowState;
  HWND        hwndHelp;
  HWND        hwndCaller;
  HH_INFOTYPE *paInfoTypes;
  HWND        hwndToolBar;
  HWND        hwndNavigation;
  HWND        hwndHTML;
  int         iNavWidth;
  RECT        rcHTML;
  LPCTSTR     pszToc;
  LPCTSTR     pszIndex;
  LPCTSTR     pszFile;
  LPCTSTR     pszHome;
  DWORD       fsToolBarFlags;
  BOOL        fNotExpanded;
  int         curNavType;
  int         tabpos;
  int         idNotify;
  BYTE        tabOrder[HH_MAX_TABS + 1];
  int         cHistory;
  LPCTSTR     pszJump1;
  LPCTSTR     pszJump2;
  LPCTSTR     pszUrlJump1;
  LPCTSTR     pszUrlJump2;
  RECT        rcMinSize;
  int         cbInfoTypes;
  LPCTSTR     pszCustomTabs;
} HH_WINTYPE, *PHH_WINTYPE;