typedef struct _CRYPTUI_WIZ_DIGITAL_SIGN_PVK_FILE_INFO {
  DWORD  dwSize;
  LPWSTR pwszPvkFileName;
  LPWSTR pwszProvName;
  DWORD  dwProvType;
} CRYPTUI_WIZ_DIGITAL_SIGN_PVK_FILE_INFO, *PCRYPTUI_WIZ_DIGITAL_SIGN_PVK_FILE_INFO;