typedef enum _CREDENTIAL_PROVIDER_GET_SERIALIZATION_RESPONSE {
  CPGSR_NO_CREDENTIAL_NOT_FINISHED = 0,
  CPGSR_NO_CREDENTIAL_FINISHED,
  CPGSR_RETURN_CREDENTIAL_FINISHED,
  CPGSR_RETURN_NO_CREDENTIAL_FINISHED
} CREDENTIAL_PROVIDER_GET_SERIALIZATION_RESPONSE;