typedef enum _CREDENTIAL_PROVIDER_FIELD_TYPE {
  CPFT_INVALID = 0,
  CPFT_LARGE_TEXT,
  CPFT_SMALL_TEXT,
  CPFT_COMMAND_LINK,
  CPFT_EDIT_TEXT,
  CPFT_PASSWORD_TEXT,
  CPFT_TILE_IMAGE,
  CPFT_CHECKBOX,
  CPFT_COMBOBOX,
  CPFT_SUBMIT_BUTTON
} CREDENTIAL_PROVIDER_FIELD_TYPE;