typedef enum _D3DKMDT_ENUMCOFUNCMODALITY_PIVOT_TYPE {
  D3DKMDT_EPT_UNINITIALIZED,
  D3DKMDT_EPT_VIDPNSOURCE,
  D3DKMDT_EPT_VIDPNTARGET,
  D3DKMDT_EPT_SCALING,
  D3DKMDT_EPT_ROTATION,
  D3DKMDT_EPT_NOPIVOT
} D3DKMDT_ENUMCOFUNCMODALITY_PIVOT_TYPE;