typedef enum _D3DKMDT_VIDPN_PRESENT_PATH_IMPORTANCE {
  D3DKMDT_VPPI_UNINITIALIZED,
  D3DKMDT_VPPI_PRIMARY,
  D3DKMDT_VPPI_SECONDARY,
  D3DKMDT_VPPI_TERTIARY,
  D3DKMDT_VPPI_QUATERNARY,
  D3DKMDT_VPPI_QUINARY,
  D3DKMDT_VPPI_SENARY,
  D3DKMDT_VPPI_SEPTENARY,
  D3DKMDT_VPPI_OCTONARY,
  D3DKMDT_VPPI_NONARY,
  D3DKMDT_VPPI_DENARY
} D3DKMDT_VIDPN_PRESENT_PATH_IMPORTANCE;