typedef enum _D3DKMDT_VIDPN_PRESENT_PATH_SCALING {
  D3DKMDT_VPPS_UNINITIALIZED,
  D3DKMDT_VPPS_IDENTITY,
  D3DKMDT_VPPS_CENTERED,
  D3DKMDT_VPPS_STRETCHED,
  D3DKMDT_VPPS_ASPECTRATIOCENTEREDMAX,
  D3DKMDT_VPPS_CUSTOM,
  D3DKMDT_VPPS_RESERVED1,
  D3DKMDT_VPPS_UNPINNED,
  D3DKMDT_VPPS_NOTSPECIFIED
} D3DKMDT_VIDPN_PRESENT_PATH_SCALING;