typedef enum _DXGK_DISPLAY_TECHNOLOGY {
  DXGK_DT_INVALID = 0,
  DXGK_DT_OTHER = 1,
  DXGK_DT_LCD = 2,
  DXGK_DT_OLED = 3,
  DXGK_DT_PROJECTOR = 4,
  DXGK_DT_MAX = 5
} DXGK_DISPLAY_TECHNOLOGY, *PDXGK_DISPLAY_TECHNOLOGY;