typedef enum _DXGK_DISPLAYMUX_DRIVER_SUPPORT_LEVEL {
  DXGK_DISPLAYMUX_DRIVER_SUPPORT_LEVEL_UNINITIALIZED = 0,
  DXGK_DISPLAYMUX_DRIVER_SUPPORT_LEVEL_NONE = 1,
  DXGK_DISPLAYMUX_DRIVER_SUPPORT_LEVEL_DEVELOPMENT = 2,
  DXGK_DISPLAYMUX_DRIVER_SUPPORT_LEVEL_EXPERIMENTAL = 3,
  DXGK_DISPLAYMUX_DRIVER_SUPPORT_LEVEL_FULL = 4
} DXGK_DISPLAYMUX_SUPPORT_LEVEL, *PDXGK_DISPLAYMUX_SUPPORT_LEVEL;