typedef enum _DXGK_PAGE_FAULT_FLAGS {
  DXGK_PAGE_FAULT_WRITE,
  DXGK_PAGE_FAULT_FENCE_INVALID,
  DXGK_PAGE_FAULT_ADAPTER_RESET_REQUIRED,
  DXGK_PAGE_FAULT_ENGINE_RESET_REQUIRED,
  DXGK_PAGE_FAULT_FATAL_HARDWARE_ERROR,
  DXGK_PAGE_FAULT_IOMMU,
  DXGK_PAGE_FAULT_HW_CONTEXT_VALID,
  DXGK_PAGE_FAULT_PROCESS_HANDLE_VALID
} DXGK_PAGE_FAULT_FLAGS;