typedef enum _D3DKMDT_GDISURFACETYPE {
  D3DKMDT_GDISURFACE_INVALID,
  D3DKMDT_GDISURFACE_TEXTURE,
  D3DKMDT_GDISURFACE_STAGING_CPUVISIBLE,
  D3DKMDT_GDISURFACE_STAGING,
  D3DKMDT_GDISURFACE_LOOKUPTABLE,
  D3DKMDT_GDISURFACE_EXISTINGSYSMEM,
  D3DKMDT_GDISURFACE_TEXTURE_CPUVISIBLE,
  D3DKMDT_GDISURFACE_TEXTURE_CROSSADAPTER,
  D3DKMDT_GDISURFACE_TEXTURE_CPUVISIBLE_CROSSADAPTER
} D3DKMDT_GDISURFACETYPE;