typedef enum _DXGKMDT_OPM_ACP_PROTECTION_LEVEL {
  DXGKMDT_OPM_ACP_OFF,
  DXGKMDT_OPM_ACP_LEVEL_ONE,
  DXGKMDT_OPM_ACP_LEVEL_TWO,
  DXGKMDT_OPM_ACP_LEVEL_THREE,
  DXGKMDT_OPM_ACP_FORCE_ULONG
} DXGKMDT_OPM_ACP_PROTECTION_LEVEL;