typedef enum _D3DKMDT_MONITOR_TIMING_TYPE {
  D3DKMDT_MTT_UNINITIALIZED,
  D3DKMDT_MTT_ESTABLISHED,
  D3DKMDT_MTT_STANDARD,
  D3DKMDT_MTT_EXTRASTANDARD,
  D3DKMDT_MTT_DETAILED,
  D3DKMDT_MTT_DEFAULTMONITORPROFILE,
  D3DKMDT_MTT_DRIVER
} D3DKMDT_MONITOR_TIMING_TYPE;