typedef enum {
  DXGK_ENGINE_TYPE_OTHER,
  DXGK_ENGINE_TYPE_3D,
  DXGK_ENGINE_TYPE_VIDEO_DECODE,
  DXGK_ENGINE_TYPE_VIDEO_ENCODE,
  DXGK_ENGINE_TYPE_VIDEO_PROCESSING,
  DXGK_ENGINE_TYPE_SCENE_ASSEMBLY,
  DXGK_ENGINE_TYPE_COPY,
  DXGK_ENGINE_TYPE_OVERLAY,
  DXGK_ENGINE_TYPE_CRYPTO,
  DXGK_ENGINE_TYPE_VIDEO_CODEC,
  DXGK_ENGINE_TYPE_MAX
} DXGK_ENGINE_TYPE;