typedef enum _DXGKMDT_OPM_CGMSA {
  DXGKMDT_OPM_CGMSA_OFF,
  DXGKMDT_OPM_CGMSA_COPY_FREELY,
  DXGKMDT_OPM_CGMSA_COPY_NO_MORE,
  DXGKMDT_OPM_CGMSA_COPY_ONE_GENERATION,
  DXGKMDT_OPM_CGMSA_COPY_NEVER,
  DXGKMDT_OPM_REDISTRIBUTION_CONTROL_REQUIRED
} DXGKMDT_OPM_CGMSA;