typedef enum _D3DKMDT_MONITOR_DESCRIPTOR_TYPE {
  D3DKMDT_MDT_UNINITIALIZED,
  D3DKMDT_MDT_VESA_EDID_V1_BASEBLOCK,
  D3DKMDT_MDT_VESA_EDID_V1_BLOCKMAP,
  D3DKMDT_MDT_OTHER
} D3DKMDT_MONITOR_DESCRIPTOR_TYPE;