typedef enum _D3DKMDT_MONITOR_CAPABILITIES_ORIGIN {
  D3DKMDT_MCO_UNINITIALIZED,
  D3DKMDT_MCO_DEFAULTMONITORPROFILE,
  D3DKMDT_MCO_MONITORDESCRIPTOR,
  D3DKMDT_MCO_MONITORDESCRIPTOR_REGISTRYOVERRIDE,
  D3DKMDT_MCO_SPECIFICCAP_REGISTRYOVERRIDE,
  D3DKMDT_MCO_DRIVER
} D3DKMDT_MONITOR_CAPABILITIES_ORIGIN;