typedef enum _DXGKMDT_OPM_STATUS {
  DXGKMDT_OPM_STATUS_NORMAL,
  DXGKMDT_OPM_STATUS_LINK_LOST,
  DXGKMDT_OPM_STATUS_RENEGOTIATION_REQUIRED,
  DXGKMDT_OPM_STATUS_TAMPERING_DETECTED,
  DXGKMDT_OPM_STATUS_REVOKED_HDCP_DEVICE_ATTACHED
} DXGKMDT_OPM_STATUS;