typedef enum _DXGKMDT_CERTIFICATE_TYPE {
  DXGKMDT_OPM_CERTIFICATE,
  DXGKMDT_COPP_CERTIFICATE,
  DXGKMDT_UAB_CERTIFICATE,
  DXGKMDT_INDIRECT_DISPLAY_CERTIFICATE,
  DXGKMDT_FORCE_ULONG
} DXGKMDT_CERTIFICATE_TYPE;