typedef enum _D3DKMDT_VIDPN_SOURCE_MODE_TYPE {
  D3DKMDT_RMT_UNINITIALIZED,
  D3DKMDT_RMT_GRAPHICS,
  D3DKMDT_RMT_TEXT,
  D3DKMDT_RMT_GRAPHICS_STEREO,
  D3DKMDT_RMT_GRAPHICS_STEREO_ADVANCED_SCAN
} D3DKMDT_VIDPN_SOURCE_MODE_TYPE;