typedef struct _D3DKMDT_VIDPN_PRESENT_PATH_TRANSFORMATION {
  D3DKMDT_VIDPN_PRESENT_PATH_SCALING          Scaling;
  D3DKMDT_VIDPN_PRESENT_PATH_SCALING_SUPPORT  ScalingSupport;
  D3DKMDT_VIDPN_PRESENT_PATH_ROTATION         Rotation;
  D3DKMDT_VIDPN_PRESENT_PATH_ROTATION_SUPPORT RotationSupport;
} D3DKMDT_VIDPN_PRESENT_PATH_TRANSFORMATION;