typedef struct _D3DKMDT_MONITOR_SOURCE_MODE {
  D3DKMDT_MONITOR_SOURCE_MODE_ID      Id;
  D3DKMDT_VIDEO_SIGNAL_INFO           VideoSignalInfo;
  D3DKMDT_COLOR_BASIS                 ColorBasis;
  D3DKMDT_COLOR_COEFF_DYNAMIC_RANGES  ColorCoeffDynamicRanges;
  D3DKMDT_MONITOR_CAPABILITIES_ORIGIN Origin;
  D3DKMDT_MODE_PREFERENCE             Preference;
} D3DKMDT_MONITOR_SOURCE_MODE;