typedef struct _DXGK_DISPLAYMUX_SET_INTERNAL_PANEL_INFO {
  BOOLEAN                            Brightness3Supported;
  DXGK_BRIGHTNESS_CAPS               Brightness3Caps;
  DXGK_BRIGHTNESS_GET_NIT_RANGES_OUT Bridgtness3Ranges;
} DXGK_DISPLAYMUX_SET_INTERNAL_PANEL_INFO, *PDXGK_DISPLAYMUX_SET_INTERNAL_PANEL_INFO;