typedef struct _D3DKMDT_VIDPN_SOURCE_MODE {
  D3DKMDT_VIDEO_PRESENT_SOURCE_MODE_ID Id;
  D3DKMDT_VIDPN_SOURCE_MODE_TYPE       Type;
  union {
    D3DKMDT_GRAPHICS_RENDERING_FORMAT Graphics;
    D3DKMDT_TEXT_RENDERING_FORMAT     Text;
  } Format;
} D3DKMDT_VIDPN_SOURCE_MODE;