typedef struct _IMAGE_ENCLAVE_IMPORT {
  DWORD MatchType;
  DWORD MinimumSecurityVersion;
  BYTE  UniqueOrAuthorID[IMAGE_ENCLAVE_LONG_ID_LENGTH];
  BYTE  FamilyID[IMAGE_ENCLAVE_SHORT_ID_LENGTH];
  BYTE  ImageID[IMAGE_ENCLAVE_SHORT_ID_LENGTH];
  DWORD ImportName;
  DWORD Reserved;
} IMAGE_ENCLAVE_IMPORT, *PIMAGE_ENCLAVE_IMPORT;