typedef struct _CLAIM_SECURITY_ATTRIBUTE_RELATIVE_V1 {
  DWORD Name;
  WORD  ValueType;
  WORD  Reserved;
  DWORD Flags;
  DWORD ValueCount;
  union {
    DWORD pInt64[ANYSIZE_ARRAY];
    DWORD pUint64[ANYSIZE_ARRAY];
    DWORD ppString[ANYSIZE_ARRAY];
    DWORD pFqbn[ANYSIZE_ARRAY];
    DWORD pOctetString[ANYSIZE_ARRAY];
  } Values;
} CLAIM_SECURITY_ATTRIBUTE_RELATIVE_V1, *PCLAIM_SECURITY_ATTRIBUTE_RELATIVE_V1;