typedef struct _ACTIVATION_CONTEXT_RUN_LEVEL_INFORMATION {
  DWORD                      ulFlags;
  ACTCTX_REQUESTED_RUN_LEVEL RunLevel;
  DWORD                      UiAccess;
} ACTIVATION_CONTEXT_RUN_LEVEL_INFORMATION, *PACTIVATION_CONTEXT_RUN_LEVEL_INFORMATION;