typedef struct _SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX {
  LOGICAL_PROCESSOR_RELATIONSHIP Relationship;
  DWORD                          Size;
  union {
    PROCESSOR_RELATIONSHIP           Processor;
    NUMA_NODE_RELATIONSHIP           NumaNode;
    CACHE_RELATIONSHIP               Cache;
    GROUP_RELATIONSHIP               Group;
    SHARED_COMPUTE_UNIT_RELATIONSHIP SharedComputeUnit;
  } DUMMYUNIONNAME;
} SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX, *PSYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX;