typedef struct _PROCESS_DYNAMIC_ENFORCED_ADDRESS_RANGE {
  ULONG_PTR BaseAddress;
  SIZE_T    Size;
  DWORD     Flags;
} PROCESS_DYNAMIC_ENFORCED_ADDRESS_RANGE, *PPROCESS_DYNAMIC_ENFORCED_ADDRESS_RANGE;