typedef enum __MIDL___MIDL_itf_xpsdigitalsignature_0000_0000_0002 {
  XPS_SIGN_POLICY_NONE = 0,
  XPS_SIGN_POLICY_CORE_PROPERTIES = 0x1,
  XPS_SIGN_POLICY_SIGNATURE_RELATIONSHIPS = 0x2,
  XPS_SIGN_POLICY_PRINT_TICKET = 0x4,
  XPS_SIGN_POLICY_DISCARD_CONTROL = 0x8,
  XPS_SIGN_POLICY_ALL = 0xf
} XPS_SIGN_POLICY;