typedef enum __MIDL___MIDL_itf_xpsdigitalsignature_0000_0000_0001 {
  XPS_SIGNATURE_STATUS_INCOMPLIANT = 1,
  XPS_SIGNATURE_STATUS_INCOMPLETE = 2,
  XPS_SIGNATURE_STATUS_BROKEN = 3,
  XPS_SIGNATURE_STATUS_QUESTIONABLE = 4,
  XPS_SIGNATURE_STATUS_VALID = 5
} XPS_SIGNATURE_STATUS;