typedef enum UIAutomationType {
  UIAutomationType_Int = 0x1,
  UIAutomationType_Bool = 0x2,
  UIAutomationType_String = 0x3,
  UIAutomationType_Double = 0x4,
  UIAutomationType_Point = 0x5,
  UIAutomationType_Rect = 0x6,
  UIAutomationType_Element = 0x7,
  UIAutomationType_Array = 0x10000,
  UIAutomationType_Out = 0x20000,
  UIAutomationType_IntArray,
  UIAutomationType_BoolArray,
  UIAutomationType_StringArray,
  UIAutomationType_DoubleArray,
  UIAutomationType_PointArray,
  UIAutomationType_RectArray,
  UIAutomationType_ElementArray,
  UIAutomationType_OutInt,
  UIAutomationType_OutBool,
  UIAutomationType_OutString,
  UIAutomationType_OutDouble,
  UIAutomationType_OutPoint,
  UIAutomationType_OutRect,
  UIAutomationType_OutElement,
  UIAutomationType_OutIntArray,
  UIAutomationType_OutBoolArray,
  UIAutomationType_OutStringArray,
  UIAutomationType_OutDoubleArray,
  UIAutomationType_OutPointArray,
  UIAutomationType_OutRectArray,
  UIAutomationType_OutElementArray
} ;