typedef struct _MIDL_STUB_MESSAGE {
  PRPC_MESSAGE                       RpcMsg;
  unsigned char                      *Buffer;
  unsigned char                      *BufferStart;
  unsigned char                      *BufferEnd;
  unsigned char                      *BufferMark;
  unsigned long                      BufferLength;
  unsigned long                      MemorySize;
  unsigned char                      *Memory;
  unsigned char                      IsClient;
  unsigned char                      Pad;
  unsigned short                     uFlags2;
  int                                ReuseBuffer;
  struct NDR_ALLOC_ALL_NODES_CONTEXT *pAllocAllNodesContext;
  struct NDR_POINTER_QUEUE_STATE     *pPointerQueueState;
  int                                IgnoreEmbeddedPointers;
  unsigned char                      *PointerBufferMark;
  unsigned char                      CorrDespIncrement;
  unsigned char                      uFlags;
  unsigned short                     UniquePtrCount;
  ULONG_PTR                          MaxCount;
  unsigned long                      Offset;
  unsigned long                      ActualCount;
  void * )(size_t)                               *(pfnAllocate;
  void()(void *)                              * pfnFree;
  unsigned char                      *StackTop;
  unsigned char                      *pPresentedType;
  unsigned char                      *pTransmitType;
  handle_t                           SavedHandle;
  const _MIDL_STUB_DESC              *StubDesc;
  struct                             _MIDL_STUB_DESC;
  struct _FULL_PTR_XLAT_TABLES       *FullPtrXlatTables;
  unsigned long                      FullPtrRefId;
  unsigned long                      PointerLength;
  unsigned int                       fInDontFree : 1;
  unsigned int                       fDontCallFreeInst : 1;
  unsigned int                       fUnused1 : 1;
  unsigned int                       fHasReturn : 1;
  unsigned int                       fHasExtensions : 1;
  unsigned int                       fHasNewCorrDesc : 1;
  unsigned int                       fIsIn : 1;
  unsigned int                       fIsOut : 1;
  unsigned int                       fIsOicf : 1;
  unsigned int                       fBufferValid : 1;
  unsigned int                       fHasMemoryValidateCallback : 1;
  unsigned int                       fInFree : 1;
  unsigned int                       fNeedMCCP : 1;
  unsigned int                       fUnused2 : 3;
  unsigned int                       fUnused3 : 16;
  unsigned long                      dwDestContext;
  void                               *pvDestContext;
  NDR_SCONTEXT                       *SavedContextHandles;
  long                               ParamNumber;
  struct IRpcChannelBuffer           *pRpcChannelBuffer;
  PARRAY_INFO                        pArrayInfo;
  unsigned long                      *SizePtrCountArray;
  unsigned long                      *SizePtrOffsetArray;
  unsigned long                      *SizePtrLengthArray;
  void                               *pArgQueue;
  unsigned long                      dwStubPhase;
  void                               *LowStackMark;
  PNDR_ASYNC_MESSAGE                 pAsyncMsg;
  PNDR_CORRELATION_INFO              pCorrInfo;
  unsigned char                      *pCorrMemory;
  void                               *pMemoryList;
  INT_PTR                            pCSInfo;
  unsigned char                      *ConformanceMark;
  unsigned char                      *VarianceMark;
  INT_PTR                            Unused;
  struct _NDR_PROC_CONTEXT           *pContext;
  void                               *ContextHandleHash;
  void                               *pUserMarshalList;
  unsigned char                      *pFullPtrFormat;
  INT_PTR                            Reserved51_4;
  INT_PTR                            Reserved51_5;
} MIDL_STUB_MESSAGE, *PMIDL_STUB_MESSAGE;