typedef enum D3D12_VIDEO_EXTENSION_COMMAND_PARAMETER_FLAGS {
  D3D12_VIDEO_EXTENSION_COMMAND_PARAMETER_FLAG_NONE = 0,
  D3D12_VIDEO_EXTENSION_COMMAND_PARAMETER_FLAG_READ = 0x1,
  D3D12_VIDEO_EXTENSION_COMMAND_PARAMETER_FLAG_WRITE = 0x2
} ;