typedef enum D3D12_VIDEO_FRAME_STEREO_FORMAT {
  D3D12_VIDEO_FRAME_STEREO_FORMAT_NONE,
  D3D12_VIDEO_FRAME_STEREO_FORMAT_MONO,
  D3D12_VIDEO_FRAME_STEREO_FORMAT_HORIZONTAL,
  D3D12_VIDEO_FRAME_STEREO_FORMAT_VERTICAL,
  D3D12_VIDEO_FRAME_STEREO_FORMAT_SEPARATE
} ;