typedef enum D3D12_VIDEO_DECODE_STATUS {
  D3D12_VIDEO_DECODE_STATUS_OK,
  D3D12_VIDEO_DECODE_STATUS_CONTINUE,
  D3D12_VIDEO_DECODE_STATUS_CONTINUE_SKIP_DISPLAY,
  D3D12_VIDEO_DECODE_STATUS_RESTART,
  D3D12_VIDEO_DECODE_STATUS_RATE_EXCEEDED
} ;