typedef struct D3D12_VIDEO_PROCESS_INPUT_STREAM_ARGUMENTS {
  D3D12_VIDEO_PROCESS_INPUT_STREAM       InputStream[2];
  D3D12_VIDEO_PROCESS_TRANSFORM          Transform;
  D3D12_VIDEO_PROCESS_INPUT_STREAM_FLAGS Flags;
  D3D12_VIDEO_PROCESS_INPUT_STREAM_RATE  RateInfo;
  INT                                    FilterLevels[32];
  D3D12_VIDEO_PROCESS_ALPHA_BLENDING     AlphaBlending;
} D3D12_VIDEO_PROCESS_INPUT_STREAM_ARGUMENTS;