typedef struct D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_H264 {
  D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_H264_FLAGS                   ConfigurationFlags;
  D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_H264_DIRECT_MODES            DirectModeConfig;
  D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_H264_SLICES_DEBLOCKING_MODES DisableDeblockingFilterConfig;
} D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_H264;