typedef struct D3D12_FEATURE_DATA_VIDEO_ENCODER_OUTPUT_RESOLUTION_RATIOS_COUNT {
  UINT                      NodeIndex;
  D3D12_VIDEO_ENCODER_CODEC Codec;
  UINT                      ResolutionRatiosCount;
} D3D12_FEATURE_DATA_VIDEO_ENCODER_OUTPUT_RESOLUTION_RATIOS_COUNT;