typedef struct D3D12_VIDEO_ENCODER_SEQUENCE_GOP_STRUCTURE {
  UINT  DataSize;
  union {
    D3D12_VIDEO_ENCODER_SEQUENCE_GOP_STRUCTURE_H264 *pH264GroupOfPictures;
    D3D12_VIDEO_ENCODER_SEQUENCE_GOP_STRUCTURE_HEVC *pHEVCGroupOfPictures;
    D3D12_VIDEO_ENCODER_AV1_SEQUENCE_STRUCTURE      *pAV1SequenceStructure;
  };
} D3D12_VIDEO_ENCODER_SEQUENCE_GOP_STRUCTURE;