typedef struct D3D12_VIDEO_ENCODER_LEVEL_SETTING {
  UINT  DataSize;
  union {
    D3D12_VIDEO_ENCODER_LEVELS_H264                 *pH264LevelSetting;
    D3D12_VIDEO_ENCODER_LEVEL_TIER_CONSTRAINTS_HEVC *pHEVCLevelSetting;
    D3D12_VIDEO_ENCODER_AV1_LEVEL_TIER_CONSTRAINTS  *pAV1LevelSetting;
  };
} D3D12_VIDEO_ENCODER_LEVEL_SETTING;