typedef struct D3D12_VIDEO_ENCODER_PROFILE_DESC {
  UINT  DataSize;
  union {
    D3D12_VIDEO_ENCODER_PROFILE_H264 *pH264Profile;
    D3D12_VIDEO_ENCODER_PROFILE_HEVC *pHEVCProfile;
    D3D12_VIDEO_ENCODER_AV1_PROFILE  *pAV1Profile;
  };
} D3D12_VIDEO_ENCODER_PROFILE_DESC;