typedef struct D3D12_VIDEO_ENCODER_ENCODEFRAME_OUTPUT_ARGUMENTS1 {
  D3D12_VIDEO_ENCODER_COMPRESSED_BITSTREAM1            Bitstream;
  D3D12_VIDEO_ENCODER_RECONSTRUCTED_PICTURE            ReconstructedPicture;
  D3D12_VIDEO_ENCODER_ENCODE_OPERATION_METADATA_BUFFER EncoderOutputMetadata;
  D3D12_VIDEO_ENCODER_RECONSTRUCTED_PICTURE            FrameAnalysisReconstructedPicture;
} D3D12_VIDEO_ENCODER_ENCODEFRAME_OUTPUT_ARGUMENTS1;