typedef struct D3D12_VIDEO_ENCODER_INPUT_MAP_DATA {
  D3D12_VIDEO_ENCODER_INPUT_MAP_TYPE MapType;
  union {
    D3D12_VIDEO_ENCODER_INPUT_MAP_DATA_QUANTIZATION_MATRIX Quantization;
    D3D12_VIDEO_ENCODER_INPUT_MAP_DATA_DIRTY_REGIONS       DirtyRegions;
    D3D12_VIDEO_ENCODER_INPUT_MAP_DATA_MOTION_VECTORS      MotionVectors;
  };
} D3D12_VIDEO_ENCODER_INPUT_MAP_DATA;