typedef struct D3D12_VIDEO_ENCODER_ENCODEFRAME_OUTPUT_ARGUMENTS {
  D3D12_VIDEO_ENCODER_COMPRESSED_BITSTREAM             Bitstream;
  D3D12_VIDEO_ENCODER_RECONSTRUCTED_PICTURE            ReconstructedPicture;
  D3D12_VIDEO_ENCODER_ENCODE_OPERATION_METADATA_BUFFER EncoderOutputMetadata;
} D3D12_VIDEO_ENCODER_ENCODEFRAME_OUTPUT_ARGUMENTS;