typedef struct D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_SUPPORT {
  UINT  DataSize;
  union {
    D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_SUPPORT_H264 *pH264Support;
    D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_SUPPORT_HEVC *pHEVCSupport;
    D3D12_VIDEO_ENCODER_AV1_CODEC_CONFIGURATION_SUPPORT  *pAV1Support;
  };
} D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_SUPPORT;