typedef struct D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA {
  UINT  DataSize;
  union {
    D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA_H264  *pH264PicData;
    D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA_HEVC  *pHEVCPicData;
    D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA_HEVC1 *pHEVCPicData1;
    D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_CODEC_DATA   *pAV1PicData;
  };
} D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA;