typedef struct D3D12_FEATURE_DATA_VIDEO_ENCODER_PROFILE_LEVEL {
  UINT                              NodeIndex;
  D3D12_VIDEO_ENCODER_CODEC         Codec;
  D3D12_VIDEO_ENCODER_PROFILE_DESC  Profile;
  BOOL                              IsSupported;
  D3D12_VIDEO_ENCODER_LEVEL_SETTING MinSupportedLevel;
  D3D12_VIDEO_ENCODER_LEVEL_SETTING MaxSupportedLevel;
} D3D12_FEATURE_DATA_VIDEO_ENCODER_PROFILE_LEVEL;