typedef struct D3D12_VIDEO_ENCODER_DIRTY_REGIONS_CONFIGURATION {
  BOOL                                              Enabled;
  D3D12_VIDEO_ENCODER_INPUT_MAP_SOURCE              MapSource;
  D3D12_VIDEO_ENCODER_DIRTY_REGIONS_MAP_VALUES_MODE MapValuesType;
} D3D12_VIDEO_ENCODER_DIRTY_REGIONS_CONFIGURATION;