typedef struct D3D12_VIDEO_ENCODER_PICTURE_CONTROL_SUBREGIONS_LAYOUT_DATA_SLICES {
  union {
    UINT MaxBytesPerSlice;
    UINT NumberOfCodingUnitsPerSlice;
    UINT NumberOfRowsPerSlice;
    UINT NumberOfSlicesPerFrame;
  };
} D3D12_VIDEO_ENCODER_PICTURE_CONTROL_SUBREGIONS_LAYOUT_DATA_SLICES;