typedef struct D3D12_VIDEO_ENCODER_RATE_CONTROL {
  D3D12_VIDEO_ENCODER_RATE_CONTROL_MODE                 Mode;
  D3D12_VIDEO_ENCODER_RATE_CONTROL_FLAGS                Flags;
  D3D12_VIDEO_ENCODER_RATE_CONTROL_CONFIGURATION_PARAMS ConfigParams;
  DXGI_RATIONAL                                         TargetFrameRate;
} D3D12_VIDEO_ENCODER_RATE_CONTROL;