typedef struct D3D12_VIDEO_PROCESS_OUTPUT_STREAM_ARGUMENTS {
  D3D12_VIDEO_PROCESS_OUTPUT_STREAM OutputStream[2];
  D3D12_RECT                        TargetRectangle;
} D3D12_VIDEO_PROCESS_OUTPUT_STREAM_ARGUMENTS;