typedef struct D3D12_VIDEO_EXTENSION_COMMAND_PARAMETER_INFO {
  LPCWSTR                                       Name;
  D3D12_VIDEO_EXTENSION_COMMAND_PARAMETER_TYPE  Type;
  D3D12_VIDEO_EXTENSION_COMMAND_PARAMETER_FLAGS Flags;
} D3D12_VIDEO_EXTENSION_COMMAND_PARAMETER_INFO;