typedef struct D3D12_VIDEO_ENCODER_COMPRESSED_BITSTREAM1 {
  D3D12_VIDEO_ENCODER_COMPRESSED_BITSTREAM_NOTIFICATION_MODE NotificationMode;
  union {
    D3D12_VIDEO_ENCODER_COMPRESSED_BITSTREAM           FrameOutputBuffer;
    D3D12_VIDEO_ENCODER_SUBREGION_COMPRESSED_BITSTREAM SubregionOutputBuffers;
  };
} D3D12_VIDEO_ENCODER_COMPRESSED_BITSTREAM1;