typedef struct D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION {
  UINT  DataSize;
  union {
    D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_H264 *pH264Config;
    D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC *pHEVCConfig;
    D3D12_VIDEO_ENCODER_AV1_CODEC_CONFIGURATION  *pAV1Config;
  };
} D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION;