typedef struct tagJOYCAPSW {
  WORD  wMid;
  WORD  wPid;
  WCHAR szPname[MAXPNAMELEN];
  UINT  wXmin;
  UINT  wXmax;
  UINT  wYmin;
  UINT  wYmax;
  UINT  wZmin;
  UINT  wZmax;
  UINT  wNumButtons;
  UINT  wPeriodMin;
  UINT  wPeriodMax;
  UINT  wRmin;
  UINT  wRmax;
  UINT  wUmin;
  UINT  wUmax;
  UINT  wVmin;
  UINT  wVmax;
  UINT  wCaps;
  UINT  wMaxAxes;
  UINT  wNumAxes;
  UINT  wMaxButtons;
  WCHAR szRegKey[MAXPNAMELEN];
  WCHAR szOEMVxD[MAX_JOYSTICKOEMVXDNAME];
} JOYCAPSW, *PJOYCAPSW, *NPJOYCAPSW, *LPJOYCAPSW;