typedef enum WINML_TENSOR_DATA_TYPE {
  WINML_TENSOR_UNDEFINED = 0,
  WINML_TENSOR_FLOAT,
  WINML_TENSOR_UINT8,
  WINML_TENSOR_INT8,
  WINML_TENSOR_UINT16,
  WINML_TENSOR_INT16,
  WINML_TENSOR_INT32,
  WINML_TENSOR_INT64,
  WINML_TENSOR_STRING,
  WINML_TENSOR_BOOLEAN,
  WINML_TENSOR_FLOAT16,
  WINML_TENSOR_DOUBLE,
  WINML_TENSOR_UINT32,
  WINML_TENSOR_UINT64,
  WINML_TENSOR_COMPLEX64,
  WINML_TENSOR_COMPLEX128
} ;