typedef enum tagDOT11_ADHOC_CIPHER_ALGORITHM {
  DOT11_ADHOC_CIPHER_ALGO_INVALID,
  DOT11_ADHOC_CIPHER_ALGO_NONE,
  DOT11_ADHOC_CIPHER_ALGO_CCMP,
  DOT11_ADHOC_CIPHER_ALGO_WEP
} DOT11_ADHOC_CIPHER_ALGORITHM;