typedef struct _SECURITY_FUNCTION_TABLE_A {
  unsigned long                        dwVersion;
  ENUMERATE_SECURITY_PACKAGES_FN_A     EnumerateSecurityPackagesA;
  QUERY_CREDENTIALS_ATTRIBUTES_FN_A    QueryCredentialsAttributesA;
  ACQUIRE_CREDENTIALS_HANDLE_FN_A      AcquireCredentialsHandleA;
  FREE_CREDENTIALS_HANDLE_FN           FreeCredentialHandle;
  void                                 *Reserved2;
  INITIALIZE_SECURITY_CONTEXT_FN_A     InitializeSecurityContextA;
  ACCEPT_SECURITY_CONTEXT_FN           AcceptSecurityContext;
  COMPLETE_AUTH_TOKEN_FN               CompleteAuthToken;
  DELETE_SECURITY_CONTEXT_FN           DeleteSecurityContext;
  APPLY_CONTROL_TOKEN_FN               ApplyControlToken;
  QUERY_CONTEXT_ATTRIBUTES_FN_A        QueryContextAttributesA;
  IMPERSONATE_SECURITY_CONTEXT_FN      ImpersonateSecurityContext;
  REVERT_SECURITY_CONTEXT_FN           RevertSecurityContext;
  MAKE_SIGNATURE_FN                    MakeSignature;
  VERIFY_SIGNATURE_FN                  VerifySignature;
  FREE_CONTEXT_BUFFER_FN               FreeContextBuffer;
  QUERY_SECURITY_PACKAGE_INFO_FN_A     QuerySecurityPackageInfoA;
  void                                 *Reserved3;
  void                                 *Reserved4;
  EXPORT_SECURITY_CONTEXT_FN           ExportSecurityContext;
  IMPORT_SECURITY_CONTEXT_FN_A         ImportSecurityContextA;
  ADD_CREDENTIALS_FN_A                 AddCredentialsA;
  void                                 *Reserved8;
  QUERY_SECURITY_CONTEXT_TOKEN_FN      QuerySecurityContextToken;
  ENCRYPT_MESSAGE_FN                   EncryptMessage;
  DECRYPT_MESSAGE_FN                   DecryptMessage;
  SET_CONTEXT_ATTRIBUTES_FN_A          SetContextAttributesA;
  SET_CREDENTIALS_ATTRIBUTES_FN_A      SetCredentialsAttributesA;
  CHANGE_PASSWORD_FN_A                 ChangeAccountPasswordA;
  void                                 *Reserved9;
  QUERY_CONTEXT_ATTRIBUTES_EX_FN_A     QueryContextAttributesExA;
  QUERY_CREDENTIALS_ATTRIBUTES_EX_FN_A QueryCredentialsAttributesExA;
} SecurityFunctionTableA, *PSecurityFunctionTableA;