typedef union _SEC_WINNT_AUTH_IDENTITY_INFO {
  SEC_WINNT_AUTH_IDENTITY_EXW AuthIdExw;
  SEC_WINNT_AUTH_IDENTITY_EXA AuthIdExa;
  SEC_WINNT_AUTH_IDENTITY_A   AuthId_a;
  SEC_WINNT_AUTH_IDENTITY_W   AuthId_w;
  SEC_WINNT_AUTH_IDENTITY_EX2 AuthIdEx2;
} SEC_WINNT_AUTH_IDENTITY_INFO, *PSEC_WINNT_AUTH_IDENTITY_INFO;