typedef struct _INTERNET_CACHE_GROUP_INFOW {
  DWORD dwGroupSize;
  DWORD dwGroupFlags;
  DWORD dwGroupType;
  DWORD dwDiskUsage;
  DWORD dwDiskQuota;
  DWORD dwOwnerStorage[GROUP_OWNER_STORAGE_SIZE];
  WCHAR szGroupName[GROUPNAME_MAX_LENGTH];
} INTERNET_CACHE_GROUP_INFOW, *LPINTERNET_CACHE_GROUP_INFOW;