enum RILUICCSLOTSTATE {
  RIL_UICCSLOT_OFF_EMPTY  = 0x01,
  RIL_UICCSLOT_OFF        = 0x02,
  RIL_UICCSLOT_EMPTY      = 0x03,
  RIL_UICCSLOT_NOT_READY  = 0x04,
  RIL_UICCSLOT_ACTIVE     = 0x05,
  RIL_UICCSLOT_ERROR      = 0x06

};