typedef enum RILSERVICEPROVISIONINGSTATUS {
  RIL_SVCPROV_UNKNOWN,
  RIL_SVCPROV_NOTPROVISIONED,
  RIL_SVCPROV_PROVISIONED,
  RIL_SVCPROV_TEMPMODERESTRICTED,
  RIL_SVCPROV_TEMPMODEALLOWED,
  RIL_SVCPROV_MAX
} ;