typedef enum RILMSGMWIDETAILLISTPARAMMASK {
  RIL_PARAM_MWIDETAIL_EXECUTOR,
  RIL_PARAM_MWIDETAIL_REFNUM,
  RIL_PARAM_MWIDETAIL_NUMDETAILITEMS,
  RIL_PARAM_MWIDETAIL_DETAILITEMS,
  RIL_PARAM_MWIDETAIL_ALL
} ;