typedef enum RILIMSSIPREASON {
  RIL_IMSSIPREASON_NONE,
  RIL_IMSSIPREASON_NOT_AUTHORIZED_FOR_SERVICE,
  RIL_IMSSIPREASON_SERVICE_NOT_ALLOWED_IN_THIS_LOCATION,
  RIL_IMSSIPREASON_EMERGENCY_CALLS_OVER_WIFI_NOT_ALLOWED_IN_THIS_LOCATION,
  RIL_IMSSIPREASON_MAX
} ;