typedef enum RILCALLFORWARDINGSETTINGSPARAMMASK {
  RIL_PARAM_CFS_STATUS,
  RIL_PARAM_CFS_INFOCLASSES,
  RIL_PARAM_CFS_ADDRESS,
  RIL_PARAM_CFS_SUBADDRESS,
  RIL_PARAM_CFS_DELAYTIME,
  RIL_PARAM_CFS_ALL
} ;