enum RILUICCFILELOCKSTATUSACCESSCONDITION {
  RIL_UICCFILEACCESSCONDITION_ALW   = 0x00,
  RIL_UICCFILEACCESSCONDITION_PIN1  = 0x01,
  RIL_UICCFILEACCESSCONDITION_PIN2  = 0x02,
  RIL_UICCFILEACCESSCONDITION_RFU3  = 0x03,
  RIL_UICCFILEACCESSCONDITION_RFU4  = 0x04,
  RIL_UICCFILEACCESSCONDITION_ADM5  = 0x05,
  RIL_UICCFILEACCESSCONDITION_ADM6  = 0x06,
  RIL_UICCFILEACCESSCONDITION_NEV   = 0x07

};