typedef enum RILREMOTEPARTYINFOVALUEPARAM {
  RIL_PARAM_RPI_EXECUTOR,
  RIL_PARAM_RPI_ADDRESS,
  RIL_PARAM_RPI_SUBADDRESS,
  RIL_PARAM_RPI_DESCRIPTION,
  RIL_PARAM_RPI_NUM_PRES_IND,
  RIL_PARAM_RPI_NAME_PRES_IND,
  RIL_PARAM_RPI_ID,
  RIL_PARAM_RPI_ALL
}  RILREMOTEPARTYINFOPARAM;