enum RILREGSTAT  {
  RIL_REGSTAT_UNKNOWN = 0,
  RIL_REGSTAT_UNREGISTERED = 0x1,
  RIL_REGSTAT_HOME = 0x2,
  RIL_REGSTAT_ATTEMPTING = 0x3,
  RIL_REGSTAT_DENIED = 0x4,
  RIL_REGSTAT_ROAMING = 0x5,
  RIL_REGSTAT_ROAMING_DOMESTIC = 0x6,
  RIL_REGSTAT_MAX = RIL_REGSTAT_ROAMING_DOMESTIC

};