typedef enum RILIMSSSTATUSPARAMMASK {
  RIL_PARAM_IMSSTATUS_EXECUTOR,
  RIL_PARAM_IMSSTATUS_HUICCAPP,
  RIL_PARAM_IMSSTATUS_AVAILABLESERVICES,
  RIL_PARAM_IMSSTATUS_SMSSUPPORTEDFORMAT,
  RIL_PARAM_IMSSTATUS_SERVINGDOMAIN,
  RIL_PARAM_IMSSTATUS_SYSTEMTYPE,
  RIL_PARAM_IMSSTATUS_BLOCKREASONLTE,
  RIL_PARAM_IMSSTATUS_BLOCKREASONWIFI,
  RIL_PARAM_IMSSTATUS_ALL
} ;