typedef enum RILCALLHANDOVERPHASE {
  RIL_CALLHANDOVERPHASE_STARTED,
  RIL_CALLHANDOVERPHASE_COMPLETED,
  RIL_CALLHANDOVERPHASE_FAILED,
  RIL_CALLHANDOVERPHASE_CANCELLED,
  RIL_CALLHANDOVERPHASE_MAX
} ;