enum RILUICCLOCKSTATELOCKSTATE {
  RIL_UICCLOCKSTATE_NONE = 0,
  RIL_UICCLOCKSTATE_VERIFIED = 0x1,
  RIL_UICCLOCKSTATE_ENABLED = 0x2,
  RIL_UICCLOCKSTATE_BLOCKED = 0x4,
  RIL_UICCLOCKSTATE_ALL = 0x7
};