typedef enum RILTONESIGNALINFOPARAMMASK {
  RIL_PARAM_TONESIGNAL_GPPTONE,
  RIL_PARAM_TONESIGNAL_GPP2TONE,
  RIL_PARAM_TONESIGNAL_GPP2ISDNALERTING,
  RIL_PARAM_TONESIGNAL_EXECUTOR,
  RIL_PARAM_TONESIGNAL_All
} ;