enum RILDEVICEINFORMATION {
  RIL_DEVICEINFO_MANUFACTURER       = 0x01,
  RIL_DEVICEINFO_MODEL              = 0x02,
  RIL_DEVICEINFO_REVISION           = 0x03,
  RIL_DEVICEINFO_SERIALNUMBER_GW    = 0x04,
  RIL_DEVICEINFO_SERIALNUMBER_CDMA  = 0x05,
  RIL_DEVICEINFO_ARG_SMALLEST       = RIL_DEVICEINFO_MANUFACTURER,
  RIL_DEVICEINFO_ARG_LARGEST        = RIL_DEVICEINFO_SERIALNUMBER_CDMA

};