typedef enum RILRADIOSTATEITEMATTRIBUTES {
  RIL_RADIOSTATE_ITEM_ATTRIBUTE_NO_ATTRIBUTE,
  RIL_RADIOSTATE_ITEM_ATTRIBUTE_ISDIRTY,
  RIL_RADIOSTATE_ITEM_ATTRIBUTE_ISWRITABLE,
  RIL_RADIOSTATE_ITEM_ATTRIBUTE_HAVEOPTIONS,
  RIL_RADIOSTATE_ITEM_ATTRIBUTE_ALL
} ;