typedef struct RILPHONEBOOKADDITIONALNUMBER {
  DWORD      cbSize;
  DWORD      dwParams;
  RILADDRESS raAddress;
  DWORD      dwNumId;
} RILPHONEBOOKADDITIONALNUMBER, *LPRILPHONEBOOKADDITIONALNUMBER;