typedef struct RILMSGCDMAINDELIVER {
  RILADDRESS               raOrigAddress;
  RILSUBADDRESS            rsaOrigSubaddr;
  RILSYSTEMTIME            stSCReceiveTime;
  RILSYSTEMTIME            stValidityPeriodAbs;
  RILSYSTEMTIME            stValidityPeriodRel;
  RILSYSTEMTIME            stDeferredDelTimeAbs;
  RILSYSTEMTIME            stDeferredDelTimeRel;
  DWORD                    dwNumMsgs;
  RILADDRESS               raCallBackNumber;
  RILMSGCDMAMSGPRIORITY    dwMsgPriority;
  DWORD                    dwAlertOnMsgDelivery;
  RILMSGCDMAMSGPRIVACY     dwMsgPrivacy;
  BOOL                     bUserAckRequest;
  RILMSGCDMAMSGDISPLAYMODE dwMsgDisplayMode;
  DWORD                    dwTeleservice;
  DWORD                    dwServiceID;
  DWORD                    dwMsgID;
  RILMSGCDMALANGUAGE       dwMsgLang;
  RILMSGCDMAMSGENCODING    dwMsgEncoding;
  DWORD                    cbHdrLength;
  DWORD                    cchMsgLength;
  BYTE                     rgbHdr[140];
  BYTE                     rgbMsg[256];
} RILMSGCDMAINDELIVER, *LPRILMSGCDMAINDELIVER;