typedef struct RILSETSYSTEMSELECTIONPREFSPARAMS_V2 {
  DWORD                   dwFlags;
  RILSYSTEMSELECTIONPREFS rilSystemSelectionPrefs;
} RILSETSYSTEMSELECTIONPREFSPARAMS_V2, *LPRILSETSYSTEMSELECTIONPREFSPARAMS_V2, RILSETSYSTEMSELECTIONPREFSPARAMS, *LPRILSETSYSTEMSELECTIONPREFSPARAMS;