typedef struct RILCALLMEDIAOFFERANSWERSET {
  DWORD                       cbSize;
  RILCALLMEDIAOFFERANSWERTYPE dwType;
  DWORD                       dwNumberOfItems;
  RILCALLMEDIAOFFERANSWER     stOfferAnswer[4];
} RILCALLMEDIAOFFERANSWERSET, *LPRILCALLMEDIAOFFERANSWERSET;