typedef struct RILSETPREFERREDOPERATORLISTPARAMS {
  HUICCAPP         hUiccApp;
  DWORD            dwPreferredListSize;
  RILOPERATORNAMES PreferredList[1];
} RILSETPREFERREDOPERATORLISTPARAMS, *LPRILSETPREFERREDOPERATORLISTPARAMS;