typedef struct RILPHONEBOOKADDITIONALNUMBERINFO {
  DWORD                              cbSize;
  DWORD                              dwRilPBANSSize;
  RILPHONEBOOKADDITIONALNUMBERSTRING RilPBANS[1];
} RILPHONEBOOKADDITIONALNUMBERINFO, *LPRILPHONEBOOKADDITIONALNUMBERINFO;