typedef struct RILADDCALLFORWARDINGPARAMS {
  DWORD                           dwExecutor;
  RILCALLFORWARDINGSETTINGSREASON dwReason;
  RILCALLFORWARDINGSETTINGS       rcfsSettings;
} RILADDCALLFORWARDINGPARAMS, *LPRILADDCALLFORWARDINGPARAMS;