typedef struct RILSETGEOLOCATIONDATAPARAMS {
  DWORD                cbSize;
  DWORD                dwExecutor;
  RILOSGEOLOCATIONINFO locationInfo;
} RILSETGEOLOCATIONDATAPARAMS, *LPRILSETGEOLOCATIONDATAPARAMS;