typedef struct RILSETSYSTEMSELECTIONPREFSPARAMS_V1 {
  DWORD                      dwFlags;
  RILSYSTEMSELECTIONPREFS_V1 rilSystemSelectionPrefs;
} RILSETSYSTEMSELECTIONPREFSPARAMS_V1, *LPRILSETSYSTEMSELECTIONPREFSPARAMS_V1;