typedef struct RILCALLMEDIASTATE {
  RILCALLMEDIADIRECTION  dwDirection;
  RILCALLMEDIATYPE       dwCallMediaType;
  union {
    RILCALLAUDIOMEDIASTATE  stAudioState;
    RILCALLVIDEOMEDIASTATE  stVideoState;
    RILCALLCUSTOMMEDIASTATE dwCustomStateSpecific;
    DWORD                   pad[16];
  } RILCALLMEDIASTATEUNION;
  RILCALLMEDIASTATEUNION mediaStateUnion;
} RILCALLMEDIASTATE, *LPRILCALLMEDIASTATE;