typedef struct RILCALLAUDIOMEDIASTATE {
  DWORD               dwParams;
  RILCALLAUDIOSOURCE  dwAudioSource;
  RILCALLAUDIOQUALITY dwAudioQuality;
  DWORD               dwFlags;
} RILCALLAUDIOMEDIASTATE, *LPRILCALLAUDIOMEDIASTATE;