typedef struct RILADDITIONALNUMBERSTRINGUPDATE {
  DWORD                    cbSize;
  HUICCAPP                 hUiccApp;
  RILPHONEBOOKANSOPERATION dwOpType;
  DWORD                    dwNumId;
  WCHAR                    wszText[256];
} RILADDITIONALNUMBERSTRINGUPDATE, *LPRILADDITIONALNUMBERSTRINGUPDATE;