void NET_ADAPTER_OFFLOAD_TX_CHECKSUM_CAPABILITIES_INIT(
  [_Out_] NET_ADAPTER_OFFLOAD_TX_CHECKSUM_CAPABILITIES *Capabilities,
  [_In_]  NET_ADAPTER_OFFLOAD_LAYER3_FLAGS             Layer3Flags,
  [_In_]  PFN_NET_ADAPTER_OFFLOAD_SET_TX_CHECKSUM      EvtAdapterOffloadSetTxChecksum
);