void NET_ADAPTER_OFFLOAD_IEEE8021Q_TAG_CAPABILITIES_INIT(
  [_Out_] NET_ADAPTER_OFFLOAD_IEEE8021Q_TAG_CAPABILITIES *Ieee8021qCapabilities,
  [_In_]  NET_ADAPTER_OFFLOAD_IEEE8021Q_TAG_FLAGS        Flags
);