void NET_ADAPTER_OFFLOAD_RX_CHECKSUM_CAPABILITIES_INIT(
  [_Out_] NET_ADAPTER_OFFLOAD_RX_CHECKSUM_CAPABILITIES *Capabilities,
  [_In_]  PFN_NET_ADAPTER_OFFLOAD_SET_RX_CHECKSUM      EvtAdapterOffloadSetRxChecksum
);