typedef struct _NET_ADAPTER_OFFLOAD_RX_CHECKSUM_CAPABILITIES {
  ULONG                                   Size;
  PFN_NET_ADAPTER_OFFLOAD_SET_RX_CHECKSUM EvtAdapterOffloadSetRxChecksum;
} NET_ADAPTER_OFFLOAD_RX_CHECKSUM_CAPABILITIES;