typedef struct _NET_ADAPTER_OFFLOAD_IEEE8021Q_TAG_CAPABILITIES {
  ULONG                                   Size;
  NET_ADAPTER_OFFLOAD_IEEE8021Q_TAG_FLAGS Flags;
} NET_ADAPTER_OFFLOAD_IEEE8021Q_TAG_CAPABILITIES;