typedef enum SpbIoctl {
  IOCTL_SPB_LOCK_CONTROLLER,
  IOCTL_SPB_UNLOCK_CONTROLLER,
  IOCTL_SPB_EXECUTE_SEQUENCE,
  IOCTL_SPB_LOCK_CONNECTION,
  IOCTL_SPB_UNLOCK_CONNECTION,
  IOCTL_SPB_FULL_DUPLEX,
  IOCTL_SPB_MULTI_SPI_TRANSFER
}  *PSpbIoctl;