ULONG StorPortEtwEvent8(
  [in]          PVOID                                                        HwDeviceExtension,
  [in/optional] PSTOR_ADDRESS                                                Address,
  [in]          ULONG                                                        EventId,
  [in]          PWSTR                                                        EventDescription,
  [in]          ULONGLONG                                                    EventKeywords,
  [in]          STORPORT_ETW_LEVEL                                           EventLevel,
  [in]          STORPORT_ETW_EVENT_OPCODE                                    EventOpcode,
  [in/optional] PSCSI_REQUEST_BLOCK                                          Srb,
  [in/optional] _In_reads_or_z_opt_(STORPORT_ETW_MAX_PARAM_NAME_LENGTH)PWSTR Parameter1Name,
  [in]          ULONGLONG                                                    Parameter1Value,
  [in/optional] _In_reads_or_z_opt_(STORPORT_ETW_MAX_PARAM_NAME_LENGTH)PWSTR Parameter2Name,
  [in]          ULONGLONG                                                    Parameter2Value,
  [in/optional] _In_reads_or_z_opt_(STORPORT_ETW_MAX_PARAM_NAME_LENGTH)PWSTR Parameter3Name,
  [in]          ULONGLONG                                                    Parameter3Value,
  [in/optional] _In_reads_or_z_opt_(STORPORT_ETW_MAX_PARAM_NAME_LENGTH)PWSTR Parameter4Name,
  [in]          ULONGLONG                                                    Parameter4Value,
  [in/optional] _In_reads_or_z_opt_(STORPORT_ETW_MAX_PARAM_NAME_LENGTH)PWSTR Parameter5Name,
  [in]          ULONGLONG                                                    Parameter5Value,
  [in/optional] _In_reads_or_z_opt_(STORPORT_ETW_MAX_PARAM_NAME_LENGTH)PWSTR Parameter6Name,
  [in]          ULONGLONG                                                    Parameter6Value,
  [in/optional] _In_reads_or_z_opt_(STORPORT_ETW_MAX_PARAM_NAME_LENGTH)PWSTR Parameter7Name,
  [in]          ULONGLONG                                                    Parameter7Value,
  [in/optional] _In_reads_or_z_opt_(STORPORT_ETW_MAX_PARAM_NAME_LENGTH)PWSTR Parameter8Name,
  [in]          ULONGLONG                                                    Parameter8Value
);