typedef struct _STOR_RICH_DEVICE_DESCRIPTION {
       ULONG Version;
       ULONG Size;
       CHAR  VendorId[STOR_VENDOR_ID_LENGTH + 1];
       CHAR  ModelNumber[STOR_MODEL_NUMBER_LENGTH + 1];
       CHAR  FirmwareRevision[STOR_FIRMWARE_REVISION_LENGTH + 1];
} STOR_RICH_DEVICE_DESCRIPTION, *PSTOR_RICH_DEVICE_DESCRIPTION;