typedef struct _STORMQ_PROPERTY_AFFINITY_DESCRIPTOR {
  ULONG Version;
  ULONG NumberOfElements;
  ULONG Affinity[ANYSIZE_ARRAY];
} STORMQ_PROPERTY_AFFINITY_DESCRIPTOR, *PSTORMQ_PROPERTY_AFFINITY_DESCRIPTOR;