typedef struct _STOR_UNIT_CONTROL_POWER {
  PSTOR_ADDRESS           Address;
  STOR_POWER_ACTION       PowerAction;
  STOR_DEVICE_POWER_STATE PowerState;
} STOR_UNIT_CONTROL_POWER, *PSTOR_UNIT_CONTROL_POWER;