typedef struct _VPD_EXTENDED_INQUIRY_DATA_PAGE {
  UCHAR DeviceType : 5;
  UCHAR DeviceTypeQualifier : 3;
  UCHAR PageCode;
  UCHAR PageLength[2];
  UCHAR RefChk : 1;
  UCHAR AppChk : 1;
  UCHAR GrdChk : 1;
  UCHAR Spt : 3;
  UCHAR ActivateMicrocode : 2;
  UCHAR SimpSup : 1;
  UCHAR OrdSup : 1;
  UCHAR HeadSup : 1;
  UCHAR PriorSup : 1;
  UCHAR GroupSup : 1;
  UCHAR UaskSup : 1;
  UCHAR Reserved0 : 2;
  UCHAR VSup : 1;
  UCHAR NvSup : 1;
  UCHAR Obsolete0 : 1;
  UCHAR WuSup : 1;
  UCHAR Reserved1 : 4;
  UCHAR LuiClr : 1;
  UCHAR Reserved2 : 3;
  UCHAR PiiSup : 1;
  UCHAR NoPiChk : 1;
  UCHAR Reserved3 : 2;
  UCHAR Obsolete1 : 1;
  UCHAR HssRelef : 1;
  UCHAR Reserved4 : 1;
  UCHAR RtdSup : 1;
  UCHAR RSup : 1;
  UCHAR LuCollectionType : 3;
  UCHAR Multi_i_t_Nexus_Microcode_Download : 4;
  UCHAR Reserved5 : 4;
  UCHAR ExtendedSelfTestCompletionMinutes[2];
  UCHAR Reserved6 : 5;
  UCHAR VsaSup : 1;
  UCHAR HraSup : 1;
  UCHAR PoaSup : 1;
  UCHAR MaxSupportedSenseDataLength;
  UCHAR Nrd0 : 1;
  UCHAR Nrd1 : 1;
  UCHAR Sac : 1;
  UCHAR Reserved7 : 3;
  UCHAR Ias : 1;
  UCHAR Ibs : 1;
  UCHAR MaxInquiryChangeLogs[2];
  UCHAR MaxModePageChangeLogs[2];
  UCHAR Reserved8[45];
} VPD_EXTENDED_INQUIRY_DATA_PAGE, *PVPD_EXTENDED_INQUIRY_DATA_PAGE;