typedef struct _STORPORT_TELEMETRY_EVENT {
  ULONG     DriverVersion;
  ULONG     EventId;
  UCHAR     EventName[EVENT_NAME_MAX_LENGTH];
  ULONG     EventVersion;
  ULONG     Flags;
  ULONG     EventBufferLength;
  PUCHAR    EventBuffer;
  UCHAR     ParameterName0[EVENT_MAX_PARAM_NAME_LEN];
  ULONGLONG ParameterValue0;
  UCHAR     ParameterName1[EVENT_MAX_PARAM_NAME_LEN];
  ULONGLONG ParameterValue1;
  UCHAR     ParameterName2[EVENT_MAX_PARAM_NAME_LEN];
  ULONGLONG ParameterValue2;
  UCHAR     ParameterName3[EVENT_MAX_PARAM_NAME_LEN];
  ULONGLONG ParameterValue3;
  UCHAR     ParameterName4[EVENT_MAX_PARAM_NAME_LEN];
  ULONGLONG ParameterValue4;
  UCHAR     ParameterName5[EVENT_MAX_PARAM_NAME_LEN];
  ULONGLONG ParameterValue5;
  UCHAR     ParameterName6[EVENT_MAX_PARAM_NAME_LEN];
  ULONGLONG ParameterValue6;
  UCHAR     ParameterName7[EVENT_MAX_PARAM_NAME_LEN];
  ULONGLONG ParameterValue7;
} STORPORT_TELEMETRY_EVENT, *PSTORPORT_TELEMETRY_EVENT;