typedef struct _STOR_POFX_POWER_REQUIRED_CONTEXT {
  STOR_POWER_CONTROL_HEADER Header;
  BOOLEAN                   PowerRequired;
} STOR_POFX_POWER_REQUIRED_CONTEXT, *PSTOR_POFX_POWER_REQUIRED_CONTEXT;