typedef struct _STOR_ADAPTER_CONTROL_POWER {
  STOR_POWER_CONTROL_HEADER Header;
  STOR_POWER_ACTION         PowerAction;
  STOR_DEVICE_POWER_STATE   PowerState;
} STOR_ADAPTER_CONTROL_POWER, *PSTOR_ADAPTER_CONTROL_POWER;