typedef struct _NDIS_WWAN_SAR_TRANSMISSION_STATUS_INFO {
  NDIS_OBJECT_HEADER                Header;
  WWAN_STATUS                       uStatus;
  WWAN_SAR_TRANSMISSION_STATUS_INFO TransmissionStatus;
} NDIS_WWAN_SAR_TRANSMISSION_STATUS_INFO, *PNDIS_WWAN_SAR_TRANSMISSION_STATUS_INFO;