typedef struct _NDIS_WWAN_SET_UICC_TERMINAL_CAPABILITY {
  NDIS_OBJECT_HEADER                Header;
  WWAN_SET_UICC_TERMINAL_CAPABILITY SetUiccTerminalCapability;
} NDIS_WWAN_SET_UICC_TERMINAL_CAPABILITY, *PNDIS_WWAN_SET_UICC_TERMINAL_CAPABILITY;