typedef struct _NDIS_WWAN_REGISTRATION_STATE {
  NDIS_OBJECT_HEADER      Header;
  WWAN_STATUS             uStatus;
  WWAN_REGISTRATION_STATE RegistrationState;
} NDIS_WWAN_REGISTRATION_STATE, *PNDIS_WWAN_REGISTRATION_STATE;