typedef struct _NDIS_WWAN_UICC_RESET_INFO {
  NDIS_OBJECT_HEADER   Header;
  WWAN_STATUS          uStatus;
  WWAN_UICC_RESET_INFO UiccResetInfo;
} NDIS_WWAN_UICC_RESET_INFO, *PNDIS_WWAN_UICC_RESET_INFO;