typedef struct _NDIS_WWAN_NETWORK_BLACKLIST {
  NDIS_OBJECT_HEADER          Header;
  WWAN_STATUS                 uStatus;
  WWAN_NETWORK_BLACKLIST_INFO NetworkBlacklistInfo;
} NDIS_WWAN_NETWORK_BLACKLIST, *PNDIS_WWAN_NETWORK_BLACKLIST;