typedef struct _NDIS_WWAN_UICC_TERMINAL_CAPABILITY_INFO {
  NDIS_OBJECT_HEADER                 Header;
  WWAN_STATUS                        uStatus;
  WWAN_UICC_TERMINAL_CAPABILITY_INFO UiccCapabilityInfo;
} NDIS_WWAN_UICC_TERMINAL_CAPABILITY_INFO, *PNDIS_WWAN_UICC_TERMINAL_CAPABILITY_INFO;