typedef struct _NDIS_WWAN_REGISTER_PARAMS_INFO {
  NDIS_OBJECT_HEADER            Header;
  WWAN_STATUS                   uStatus;
  WWAN_REGISTRATION_PARAMS_INFO RegisterParamsInfo;
} NDIS_WWAN_REGISTER_PARAMS_INFO, *PNDIS_WWAN_REGISTER_PARAMS_INFO;