typedef struct _NDIS_WWAN_SET_SAR_TRANSMISSION_STATUS {
  NDIS_OBJECT_HEADER               Header;
  WWAN_SET_SAR_TRANSMISSION_STATUS SetTransmissionStatus;
} NDIS_WWAN_SET_SAR_TRANSMISSION_STATUS, *PNDIS_WWAN_SET_SAR_TRANSMISSION_STATUS;