typedef struct _NDIS_WWAN_DEVICE_SERVICE_SESSION_WRITE {
  NDIS_OBJECT_HEADER                Header;
  WWAN_DEVICE_SERVICE_SESSION_WRITE WriteData;
} NDIS_WWAN_DEVICE_SERVICE_SESSION_WRITE, *PNDIS_WWAN_DEVICE_SERVICE_SESSION_WRITE;