typedef struct _NDIS_WWAN_DEVICE_SLOT_MAPPING_INFO {
  NDIS_OBJECT_HEADER            Header;
  WWAN_STATUS                   uStatus;
  WWAN_DEVICE_SLOT_MAPPING_INFO DeviceSlotMappingInfo;
} NDIS_WWAN_DEVICE_SLOT_MAPPING_INFO, *PNDIS_WWAN_DEVICE_SLOT_MAPPING_INFO;