typedef struct _NDIS_WWAN_BASE_STATIONS_INFO_REQ {
  NDIS_OBJECT_HEADER          Header;
  WWAN_BASE_STATIONS_INFO_REQ BaseStationsInfoRequest;
} NDIS_WWAN_BASE_STATIONS_INFO_REQ, *PNDIS_WWAN_BASE_STATIONS_INFO_REQ;