typedef struct _NDIS_WWAN_MODEM_CONFIG_INFO {
  NDIS_OBJECT_HEADER     Header;
  WWAN_STATUS            uStatus;
  WWAN_MODEM_CONFIG_INFO ModemConfigInfo;
} NDIS_WWAN_MODEM_CONFIG_INFO, *PNDIS_WWAN_MODEM_CONFIG_INFO;