typedef struct _NDIS_WWAN_GET_VISIBLE_PROVIDERS {
  NDIS_OBJECT_HEADER         Header;
  WWAN_GET_VISIBLE_PROVIDERS VisibleProviders;
} NDIS_WWAN_GET_VISIBLE_PROVIDERS, *PNDIS_WWAN_GET_VISIBLE_PROVIDERS;