typedef struct _NDIS_WWAN_LTE_ATTACH_CONTEXTS {
  NDIS_OBJECT_HEADER     Header;
  WWAN_STATUS            uStatus;
  WWAN_LTE_ATTACH_CONFIG LteAttachContext;
} NDIS_WWAN_LTE_ATTACH_CONTEXTS, *PNDIS_WWAN_LTE_ATTACH_CONTEXTS;