typedef struct _NDIS_WWAN_UICC_FILE_STATUS {
  NDIS_OBJECT_HEADER    Header;
  WWAN_STATUS           uStatus;
  WWAN_UICC_FILE_STATUS UiccFileStatus;
} NDIS_WWAN_UICC_FILE_STATUS, *PNDIS_WWAN_UICC_FILE_STATUS;