typedef struct _NDIS_WWAN_SET_REGISTER_PARAMS {
  NDIS_OBJECT_HEADER            Header;
  WWAN_REGISTRATION_PARAMS_INFO SetRegisterParams;
} NDIS_WWAN_SET_REGISTER_PARAMS, *PNDIS_WWAN_SET_REGISTER_PARAMS;