typedef struct _NDIS_WWAN_DEVICE_SERVICE_RESPONSE {
  NDIS_OBJECT_HEADER           Header;
  WWAN_STATUS                  uStatus;
  WWAN_DEVICE_SERVICE_RESPONSE Response;
} NDIS_WWAN_DEVICE_SERVICE_RESPONSE, *PNDIS_WWAN_DEVICE_SERVICE_RESPONSE;