typedef struct _NDIS_WWAN_SET_SMS_CONFIGURATION {
  NDIS_OBJECT_HEADER         Header;
  WWAN_SET_SMS_CONFIGURATION SetSmsConfiguration;
} NDIS_WWAN_SET_SMS_CONFIGURATION, *PNDIS_WWAN_SET_SMS_CONFIGURATION;