typedef struct _NDIS_WWAN_SET_NETWORK_BLACKLIST {
  NDIS_OBJECT_HEADER          Header;
  WWAN_NETWORK_BLACKLIST_INFO SetNetworkBlacklist;
} NDIS_WWAN_SET_NETWORK_BLACKLIST, *PNDIS_WWAN_SET_NETWORK_BLACKLIST;