typedef struct _NDIS_WWAN_NETWORK_PARAMS_INFO {
  NDIS_OBJECT_HEADER       Header;
  WWAN_STATUS              uStatus;
  WWAN_NETWORK_PARAMS_INFO NetworkParamsInfo;
} NDIS_WWAN_NETWORK_PARAMS_INFO, *PNDIS_WWAN_NETWORK_PARAMS_INFO;