typedef struct _NDIS_WWAN_QUERY_UICC_TERMINAL_CAPABILITY {
  NDIS_OBJECT_HEADER                  Header;
  WWAN_QUERY_UICC_TERMINAL_CAPABILITY QueryUiccTerminalCapability;
} NDIS_WWAN_QUERY_UICC_TERMINAL_CAPABILITY, *PNDIS_WWAN_QUERY_UICC_TERMINAL_CAPABILITY;