typedef struct _NDIS_WWAN_SET_MODEM_LOGGING_CONFIG {
  NDIS_OBJECT_HEADER        Header;
  WWAN_MODEM_LOGGING_CONFIG ModemLoggingConfig;
} NDIS_WWAN_SET_MODEM_LOGGING_CONFIG, *PNDIS_WWAN_SET_MODEM_LOGGING_CONFIG;