typedef struct _NDIS_WWAN_LTE_ATTACH_STATUS {
  NDIS_OBJECT_HEADER     Header;
  WWAN_STATUS            uStatus;
  WWAN_LTE_ATTACH_STATUS LteAttachStatus;
} NDIS_WWAN_LTE_ATTACH_STATUS, *PNDIS_WWAN_LTE_ATTACH_STATUS;