typedef struct _NDIS_WWAN_SET_PROVISIONED_CONTEXT_V2 {
  NDIS_OBJECT_HEADER              Header;
  WWAN_SET_PROVISIONED_CONTEXT_V2 ProvisionedContext;
} NDIS_WWAN_SET_PROVISIONED_CONTEXT_V2, *PNDIS_WWAN_SET_PROVISIONED_CONTEXT_V2;