typedef struct _NDIS_WWAN_MODEM_LOGGING_CONFIG {
  NDIS_OBJECT_HEADER        Header;
  WWAN_STATUS               uStatus;
  WWAN_MODEM_LOGGING_CONFIG ModemLoggingConfig;
} NDIS_WWAN_MODEM_LOGGING_CONFIG, *PNDIS_WWAN_MODEM_LOGGING_CONFIG;