typedef struct _NDIS_WWAN_SET_SIGNAL_INDICATION {
  NDIS_OBJECT_HEADER         Header;
  WWAN_SET_SIGNAL_INDICATION SignalIndication;
} NDIS_WWAN_SET_SIGNAL_INDICATION, *PNDIS_WWAN_SET_SIGNAL_INDICATION;