typedef struct _NDIS_WWAN_DEVICE_SET_SERVICE_SESSION {
  NDIS_OBJECT_HEADER          Header;
  WWAN_DEVICE_SERVICE_SESSION Session;
} NDIS_WWAN_SET_DEVICE_SERVICE_SESSION, *PNDIS_WWAN_SET_DEVICE_SERVICE_SESSION;