typedef struct _NDIS_WWAN_SET_DEVICE_SLOT_MAPPING_INFO {
  NDIS_OBJECT_HEADER            Header;
  WWAN_DEVICE_SLOT_MAPPING_INFO SetDeviceSlotMappingInfo;
} NDIS_WWAN_SET_DEVICE_SLOT_MAPPING_INFO, *PNDIS_WWAN_SET_DEVICE_SLOT_MAPPING_INFO;