typedef struct _WER_REPORT_SIGNATURE {
       WCHAR                EventName[WER_MAX_EVENT_NAME_LENGTH + 1];
       WER_REPORT_PARAMETER Parameters[WER_MAX_PARAM_COUNT];
} WER_REPORT_SIGNATURE, *PWER_REPORT_SIGNATURE;