typedef enum _D3DKMT_DEVICEEXECUTION_STATE {
  D3DKMT_DEVICEEXECUTION_ACTIVE,
  D3DKMT_DEVICEEXECUTION_RESET,
  D3DKMT_DEVICEEXECUTION_HUNG,
  D3DKMT_DEVICEEXECUTION_STOPPED,
  D3DKMT_DEVICEEXECUTION_ERROR_OUTOFMEMORY,
  D3DKMT_DEVICEEXECUTION_ERROR_DMAFAULT,
  D3DKMT_DEVICEEXECUTION_ERROR_DMAPAGEFAULT
} D3DKMT_DEVICEEXECUTION_STATE;