typedef enum _D3DKMT_VAD_ESCAPE_COMMAND {
  D3DKMT_VAD_ESCAPE_GETNUMVADS,
  D3DKMT_VAD_ESCAPE_GETVAD,
  D3DKMT_VAD_ESCAPE_GETVADRANGE,
  D3DKMT_VAD_ESCAPE_GET_PTE,
  D3DKMT_VAD_ESCAPE_GET_GPUMMU_CAPS,
  D3DKMT_VAD_ESCAPE_GET_SEGMENT_CAPS,
  D3DKMT_VAD_ESCAPE_GET_PTE_DATA
} D3DKMT_VAD_ESCAPE_COMMAND;