typedef enum _D3DKMT_VIDPNSOURCEOWNER_TYPE {
  D3DKMT_VIDPNSOURCEOWNER_UNOWNED,
  D3DKMT_VIDPNSOURCEOWNER_SHARED,
  D3DKMT_VIDPNSOURCEOWNER_EXCLUSIVE,
  D3DKMT_VIDPNSOURCEOWNER_EXCLUSIVEGDI,
  D3DKMT_VIDPNSOURCEOWNER_EMULATED
} D3DKMT_VIDPNSOURCEOWNER_TYPE;