typedef enum _D3DKMT_TDRDBGCTRLTYPE {
  D3DKMT_TDRDBGCTRLTYPE_FORCETDR,
  D3DKMT_TDRDBGCTRLTYPE_DISABLEBREAK,
  D3DKMT_TDRDBGCTRLTYPE_ENABLEBREAK,
  D3DKMT_TDRDBGCTRLTYPE_UNCONDITIONAL,
  D3DKMT_TDRDBGCTRLTYPE_VSYNCTDR,
  D3DKMT_TDRDBGCTRLTYPE_GPUTDR,
  D3DKMT_TDRDBGCTRLTYPE_FORCEDODTDR,
  D3DKMT_TDRDBGCTRLTYPE_FORCEDODVSYNCTDR,
  D3DKMT_TDRDBGCTRLTYPE_ENGINETDR
} D3DKMT_TDRDBGCTRLTYPE;