typedef enum _KMTUMDVERSION {
  KMTUMDVERSION_DX9,
  KMTUMDVERSION_DX10,
  KMTUMDVERSION_DX11,
  KMTUMDVERSION_DX12,
  KMTUMDVERSION_DX12_WSA32,
  KMTUMDVERSION_DX12_WSA64,
  NUM_KMTUMDVERSIONS
} KMTUMDVERSION;