typedef enum _D3DKMT_DEVICESTATE_TYPE {
  D3DKMT_DEVICESTATE_EXECUTION,
  D3DKMT_DEVICESTATE_PRESENT,
  D3DKMT_DEVICESTATE_RESET,
  D3DKMT_DEVICESTATE_PRESENT_DWM,
  D3DKMT_DEVICESTATE_PAGE_FAULT,
  D3DKMT_DEVICESTATE_PRESENT_QUEUE
} D3DKMT_DEVICESTATE_TYPE;