typedef struct _D3DKMT_GDIMODEL_SYSMEM_PRESENTHISTORYTOKEN {
  [in] D3DKMT_ALIGN64 ULONG64 hlsurf;
  [in] DWORD                  dwDirtyFlags;
  [in] D3DKMT_ALIGN64 UINT64  uiCookie;
} D3DKMT_GDIMODEL_SYSMEM_PRESENTHISTORYTOKEN;