typedef struct _D3DKMT_SEGMENTGROUPSIZEINFO {
  UINT32                   PhysicalAdapterIndex;
  D3DKMT_SEGMENTSIZEINFO   LegacyInfo;
  D3DKMT_ALIGN64 ULONGLONG LocalMemory;
  D3DKMT_ALIGN64 ULONGLONG NonLocalMemory;
  D3DKMT_ALIGN64 ULONGLONG NonBudgetMemory;
} D3DKMT_SEGMENTGROUPSIZEINFO;