typedef struct _D3DKMT_QUERYSTATSTICS_PAGING_TRANSFER {
  D3DKMT_ALIGN64 ULONGLONG BytesFilled;
  D3DKMT_ALIGN64 ULONGLONG BytesDiscarded;
  D3DKMT_ALIGN64 ULONGLONG BytesMappedIntoAperture;
  D3DKMT_ALIGN64 ULONGLONG BytesUnmappedFromAperture;
  D3DKMT_ALIGN64 ULONGLONG BytesTransferredFromMdlToMemory;
  D3DKMT_ALIGN64 ULONGLONG BytesTransferredFromMemoryToMdl;
  D3DKMT_ALIGN64 ULONGLONG BytesTransferredFromApertureToMemory;
  D3DKMT_ALIGN64 ULONGLONG BytesTransferredFromMemoryToAperture;
} D3DKMT_QUERYSTATSTICS_PAGING_TRANSFER;