typedef struct _D3DKMT_QUERYSTATSTICS_ALLOCATIONS {
  D3DKMT_QUERYSTATISTICS_COUNTER Created;
  D3DKMT_QUERYSTATISTICS_COUNTER Destroyed;
  D3DKMT_QUERYSTATISTICS_COUNTER Opened;
  D3DKMT_QUERYSTATISTICS_COUNTER Closed;
  D3DKMT_QUERYSTATISTICS_COUNTER MigratedSuccess;
  D3DKMT_QUERYSTATISTICS_COUNTER MigratedFail;
  D3DKMT_QUERYSTATISTICS_COUNTER MigratedAbandoned;
} D3DKMT_QUERYSTATSTICS_ALLOCATIONS;