typedef struct _D3DKMT_SHAREDPRIMARYUNLOCKNOTIFICATION {
  [in] LUID                           AdapterLuid;
  [in] D3DDDI_VIDEO_PRESENT_SOURCE_ID VidPnSourceId;
} D3DKMT_SHAREDPRIMARYUNLOCKNOTIFICATION;