typedef struct _D3DKMT_WAITFORSYNCHRONIZATIONOBJECT {
  [in] D3DKMT_HANDLE hContext;
  [in] UINT          ObjectCount;
       D3DKMT_HANDLE ObjectHandleArray[D3DDDI_MAX_OBJECT_WAITED_ON];
} D3DKMT_WAITFORSYNCHRONIZATIONOBJECT;