typedef struct _D3DKMT_GPUVERSION {
  UINT32 PhysicalAdapterIndex;
  WCHAR  BiosVersion[DXGK_MAX_GPUVERSION_NAME_LENGTH];
  WCHAR  GpuArchitecture[DXGK_MAX_GPUVERSION_NAME_LENGTH];
} D3DKMT_GPUVERSION;