typedef struct _D3DKMT_BLTMODEL_PRESENTHISTORYTOKEN {
  [in] D3DKMT_ALIGN64 ULONG64 hLogicalSurface;
  [in] D3DKMT_ALIGN64 ULONG64 hPhysicalSurface;
  [in] D3DKMT_ALIGN64 ULONG64 EventId;
  [in] D3DKMT_DIRTYREGIONS    DirtyRegions;
} D3DKMT_BLTMODEL_PRESENTHISTORYTOKEN;