typedef struct _D3DKMT_QUERYSTATISTICS_VIDEO_MEMORY {
  ULONG                          AllocsCommitted;
  D3DKMT_QUERYSTATISTICS_COUNTER AllocsResidentInP[D3DKMT_QUERYSTATISTICS_SEGMENT_PREFERENCE_MAX];
  D3DKMT_QUERYSTATISTICS_COUNTER AllocsResidentInNonPreferred;
  D3DKMT_ALIGN64 ULONGLONG       TotalBytesEvictedDueToPreparation;
} D3DKMT_QUERYSTATISTICS_VIDEO_MEMORY;