typedef struct _D3DKMT_SUBMITPRESENTBLTTOHWQUEUE {
  D3DKMT_HANDLE         hHwQueue;
  D3DKMT_ALIGN64 UINT64 HwQueueProgressFenceId;
  D3DKMT_PRESENT        PrivatePresentData;
} D3DKMT_SUBMITPRESENTBLTTOHWQUEUE;