typedef union _D3DKMT_ADAPTER_VERIFIER_OPTION_DATA {
  D3DKMT_ADAPTER_VERIFIER_VIDMM_FLAGS         VidMmFlags;
  D3DKMT_ADAPTER_VERIFIER_VIDMM_TRIM_INTERVAL VidMmTrimInterval;
} D3DKMT_ADAPTER_VERIFIER_OPTION_DATA;