typedef struct _D3DKMT_QUERYREMOTEVIDPNSOURCEFROMGDIDISPLAYNAME {
        WCHAR                          DeviceName[32];
  [out] D3DDDI_VIDEO_PRESENT_SOURCE_ID VidPnSourceId;
} D3DKMT_QUERYREMOTEVIDPNSOURCEFROMGDIDISPLAYNAME;