typedef struct _D3DKMT_ADAPTER_VERIFIER_OPTION {
  D3DKMT_ADAPTER_VERIFIER_OPTION_TYPE Type;
  D3DKMT_VERIFIER_OPTION_MODE         Mode;
  D3DKMT_ADAPTER_VERIFIER_OPTION_DATA Data;
} D3DKMT_ADAPTER_VERIFIER_OPTION;