typedef struct _D3DKMT_MIRACAST_DISPLAY_DEVICE_CAPS {
  BOOLEAN HdcpSupported;
  ULONG   DefaultControlPort;
  BOOLEAN UsesIhvSolution;
} D3DKMT_MIRACAST_DISPLAY_DEVICE_CAPS, *PD3DKMT_MIRACAST_DISPLAY_DEVICE_CAPS;