typedef struct _D3DKMT_QUERYSTATISTICS_PROCESS_SEGMENT_GROUP_INFORMATION {
  D3DKMT_ALIGN64 UINT64 Budget;
  D3DKMT_ALIGN64 UINT64 Requested;
  D3DKMT_ALIGN64 UINT64 Usage;
  D3DKMT_ALIGN64 UINT64 Demoted[D3DKMT_QUERYSTATISTICS_ALLOCATION_PRIORITY_CLASS_MAX];
} D3DKMT_QUERYSTATISTICS_PROCESS_SEGMENT_GROUP_INFORMATION;