typedef struct _D3DKMT_REQUEST_MACHINE_CRASH_ESCAPE {
  D3DKMT_ALIGN64 D3DKMT_ULONG_PTR Param1;
  D3DKMT_ALIGN64 D3DKMT_ULONG_PTR Param2;
  D3DKMT_ALIGN64 D3DKMT_ULONG_PTR Param3;
} D3DKMT_REQUEST_MACHINE_CRASH_ESCAPE;