typedef struct _D3DKMT_ACQUIREKEYEDMUTEX {
  D3DKMT_HANDLE         hKeyedMutex;
  D3DKMT_ALIGN64 UINT64 Key;
  PLARGE_INTEGER        pTimeout;
  D3DKMT_ALIGN64 UINT64 FenceValue;
} D3DKMT_ACQUIREKEYEDMUTEX;