typedef struct _D3DKMT_QUERYSTATISTICS_VIDPNSOURCE_INFORMATION {
  D3DKMT_QUERYSTATISTICS_PROCESS_VIDPNSOURCE_INFORMATION GlobalInformation;
  D3DKMT_QUERYSTATISTICS_PROCESS_VIDPNSOURCE_INFORMATION SystemInformation;
  D3DKMT_ALIGN64 UINT64                                  Reserved[8];
} D3DKMT_QUERYSTATISTICS_VIDPNSOURCE_INFORMATION;