typedef union _D3DKMT_PROCESS_VERIFIER_OPTION_DATA {
  D3DKMT_PROCESS_VERIFIER_VIDMM_FLAGS           VidMmFlags;
  D3DKMT_PROCESS_VERIFIER_VIDMM_RESTRICT_BUDGET VidMmRestrictBudget;
} D3DKMT_PROCESS_VERIFIER_OPTION_DATA;