typedef struct _D3DKMT_SHAREOBJECTWITHHOST {
  D3DKMT_HANDLE         hDevice;
  D3DKMT_HANDLE         hObject;
  D3DKMT_ALIGN64 UINT64 Reserved;
  D3DKMT_ALIGN64 UINT64 hVailProcessNtHandle;
} D3DKMT_SHAREOBJECTWITHHOST;