typedef struct _D3DKMT_QUERYSTATISTICS_PHYSICAL_ADAPTER_INFORMATION {
  D3DKMT_ADAPTER_PERFDATA     AdapterPerfData;
  D3DKMT_ADAPTER_PERFDATACAPS AdapterPerfDataCaps;
  D3DKMT_GPUVERSION           GpuVersion;
} D3DKMT_QUERYSTATISTICS_PHYSICAL_ADAPTER_INFORMATION;