typedef struct _D3DKMT_PROCESS_VERIFIER_OPTION {
  HANDLE                              hProcess;
  D3DKMT_PROCESS_VERIFIER_OPTION_TYPE Type;
  D3DKMT_VERIFIER_OPTION_MODE         Mode;
  D3DKMT_PROCESS_VERIFIER_OPTION_DATA Data;
} D3DKMT_PROCESS_VERIFIER_OPTION;