typedef struct _D3DKMT_FREEGPUVIRTUALADDRESS {
  D3DKMT_HANDLE                         hAdapter;
  D3DKMT_ALIGN64 D3DGPU_VIRTUAL_ADDRESS BaseAddress;
  D3DKMT_ALIGN64 D3DGPU_SIZE_T          Size;
} D3DKMT_FREEGPUVIRTUALADDRESS;