typedef struct _D3DKMT_QUERYSTATISTICS_DMA_PACKET_TYPE_INFORMATION {
  ULONG PacketSubmited;
  ULONG PacketCompleted;
  ULONG PacketPreempted;
  ULONG PacketFaulted;
} D3DKMT_QUERYSTATISTICS_DMA_PACKET_TYPE_INFORMATION;