typedef enum __MIDL___MIDL_itf_xpsobjectmodel_0000_0000_0004 {
  XPS_STYLE_SIMULATION_NONE = 1,
  XPS_STYLE_SIMULATION_ITALIC,
  XPS_STYLE_SIMULATION_BOLD,
  XPS_STYLE_SIMULATION_BOLDITALIC
} XPS_STYLE_SIMULATION;