typedef enum __MIDL___MIDL_itf_xpsobjectmodel_0000_0000_0015 {
  XPS_THUMBNAIL_SIZE_VERYSMALL = 1,
  XPS_THUMBNAIL_SIZE_SMALL,
  XPS_THUMBNAIL_SIZE_MEDIUM,
  XPS_THUMBNAIL_SIZE_LARGE
} XPS_THUMBNAIL_SIZE;