typedef enum __MIDL___MIDL_itf_xpsobjectmodel_0000_0000_0011 {
  XPS_SEGMENT_TYPE_ARC_LARGE_CLOCKWISE = 1,
  XPS_SEGMENT_TYPE_ARC_LARGE_COUNTERCLOCKWISE,
  XPS_SEGMENT_TYPE_ARC_SMALL_CLOCKWISE,
  XPS_SEGMENT_TYPE_ARC_SMALL_COUNTERCLOCKWISE,
  XPS_SEGMENT_TYPE_BEZIER,
  XPS_SEGMENT_TYPE_LINE,
  XPS_SEGMENT_TYPE_QUADRATIC_BEZIER
} XPS_SEGMENT_TYPE;