typedef enum __MIDL___MIDL_itf_xpsobjectmodel_0000_0000_0014 {
  XPS_OBJECT_TYPE_CANVAS = 1,
  XPS_OBJECT_TYPE_GLYPHS,
  XPS_OBJECT_TYPE_PATH,
  XPS_OBJECT_TYPE_MATRIX_TRANSFORM,
  XPS_OBJECT_TYPE_GEOMETRY,
  XPS_OBJECT_TYPE_SOLID_COLOR_BRUSH,
  XPS_OBJECT_TYPE_IMAGE_BRUSH,
  XPS_OBJECT_TYPE_LINEAR_GRADIENT_BRUSH,
  XPS_OBJECT_TYPE_RADIAL_GRADIENT_BRUSH,
  XPS_OBJECT_TYPE_VISUAL_BRUSH
} XPS_OBJECT_TYPE;