typedef enum __MIDL___MIDL_itf_xpsobjectmodel_0000_0000_0012 {
  XPS_SEGMENT_STROKE_PATTERN_ALL = 1,
  XPS_SEGMENT_STROKE_PATTERN_NONE,
  XPS_SEGMENT_STROKE_PATTERN_MIXED
} XPS_SEGMENT_STROKE_PATTERN;