typedef enum __MIDL___MIDL_itf_xpsobjectmodel_0000_0000_0013 {
  XPS_FONT_EMBEDDING_NORMAL = 1,
  XPS_FONT_EMBEDDING_OBFUSCATED,
  XPS_FONT_EMBEDDING_RESTRICTED,
  XPS_FONT_EMBEDDING_RESTRICTED_UNOBFUSCATED
} XPS_FONT_EMBEDDING;