typedef enum __MIDL___MIDL_itf_micaut_0000_0000_0001 {
  MICUIELEMENT_BUTTON_WRITE,
  MICUIELEMENT_BUTTON_ERASE,
  MICUIELEMENT_BUTTON_CORRECT,
  MICUIELEMENT_BUTTON_CLEAR,
  MICUIELEMENT_BUTTON_UNDO,
  MICUIELEMENT_BUTTON_REDO,
  MICUIELEMENT_BUTTON_INSERT,
  MICUIELEMENT_BUTTON_CANCEL,
  MICUIELEMENT_INKPANEL_BACKGROUND,
  MICUIELEMENT_RESULTPANEL_BACKGROUND
} MICUIELEMENT;