typedef struct _PEP_PPM_PLATFORM_STATE_RESIDENCIES {
  [in] ULONG                             Count;
  [in] PPEP_PPM_PLATFORM_STATE_RESIDENCY States;
} PEP_PPM_PLATFORM_STATE_RESIDENCIES, *PPEP_PPM_PLATFORM_STATE_RESIDENCIES;