typedef struct _PEP_PPM_QUERY_COORDINATED_STATES {
  [in]  ULONG                      Count;
        PEP_COORDINATED_IDLE_STATE States[ANYSIZE_ARRAY];
} PEP_PPM_QUERY_COORDINATED_STATES, *PPEP_PPM_QUERY_COORDINATED_STATES;