typedef struct _PEP_COORDINATED_DEPENDENCY_OPTION {
  UCHAR   ExpectedStateIndex;
  BOOLEAN LooseDependency;
  BOOLEAN InitiatingState;
  BOOLEAN DependentState;
} PEP_COORDINATED_DEPENDENCY_OPTION, *PPEP_COORDINATED_DEPENDENCY_OPTION;