typedef struct _PEP_QUERY_COMPONENT_PERF_CAPABILITIES {
  [in]  PEPHANDLE DeviceHandle;
  [in]  ULONG     Component;
  [out] ULONG     SetCount;
} PEP_QUERY_COMPONENT_PERF_CAPABILITIES, *PPEP_QUERY_COMPONENT_PERF_CAPABILITIES;