typedef struct _PEP_DEBUGGER_TRANSITION_REQUIREMENTS {
  [in] PEPHANDLE DeviceHandle;
  [in] ULONG     PlatformStateCount;
  [in] PBOOLEAN  PowerTransitionRequired;
} PEP_DEBUGGER_TRANSITION_REQUIREMENTS, *PPEP_DEBUGGER_TRANSITION_REQUIREMENTS;