typedef struct _PEP_PPM_QUERY_FEEDBACK_COUNTERS {
  [in]  ULONG                          Count;
        PEP_PROCESSOR_FEEDBACK_COUNTER Counters[ANYSIZE_ARRAY];
} PEP_PPM_QUERY_FEEDBACK_COUNTERS, *PPEP_PPM_QUERY_FEEDBACK_COUNTERS;