typedef struct _STORAGE_ENDURANCE_DATA_DESCRIPTOR {
  ULONG                  Version;
  ULONG                  Size;
  STORAGE_ENDURANCE_INFO EnduranceInfo;
} STORAGE_ENDURANCE_DATA_DESCRIPTOR, *PSTORAGE_ENDURANCE_DATA_DESCRIPTOR;