typedef enum __MIDL___MIDL_itf_rendezvoussession_0000_0000_0001 {
  RSS_UNKNOWN = 0,
  RSS_READY,
  RSS_INVITATION,
  RSS_ACCEPTED,
  RSS_CONNECTED,
  RSS_CANCELLED,
  RSS_DECLINED,
  RSS_TERMINATED
} RENDEZVOUS_SESSION_STATE;