VOID SERCX2_CUSTOM_TRANSMIT_TRANSACTION_CONFIG_INIT(
  [out] SERCX2_CUSTOM_TRANSMIT_TRANSACTION_CONFIG    *Config,
  [in]  PFN_SERCX2_CUSTOM_TRANSMIT_TRANSACTION_START EvtSerCx2CustomTransmitTransactionStart
);