typedef struct _SERCX2_CUSTOM_TRANSMIT_TRANSACTION_CONFIG {
  ULONG                                             Size;
  PFN_SERCX2_CUSTOM_TRANSMIT_TRANSACTION_INITIALIZE EvtSerCx2CustomTransmitTransactionInitialize;
  PFN_SERCX2_CUSTOM_TRANSMIT_TRANSACTION_START      EvtSerCx2CustomTransmitTransactionStart;
  PFN_SERCX2_CUSTOM_TRANSMIT_TRANSACTION_CLEANUP    EvtSerCx2CustomTransmitTransactionCleanup;
} SERCX2_CUSTOM_TRANSMIT_TRANSACTION_CONFIG, *PSERCX2_CUSTOM_TRANSMIT_TRANSACTION_CONFIG;