typedef enum tag_WBEM_GET_TEXT_FLAGS {
  WBEMPATH_COMPRESSED = 0x1,
  WBEMPATH_GET_RELATIVE_ONLY = 0x2,
  WBEMPATH_GET_SERVER_TOO = 0x4,
  WBEMPATH_GET_SERVER_AND_NAMESPACE_ONLY = 0x8,
  WBEMPATH_GET_NAMESPACE_ONLY = 0x10,
  WBEMPATH_GET_ORIGINAL = 0x20
} ;