typedef enum __MIDL___MIDL_itf_wmiutils_0000_0001_0003 {
  WMIQ_ASSOCQ_ASSOCIATORS = 0x1,
  WMIQ_ASSOCQ_REFERENCES = 0x2,
  WMIQ_ASSOCQ_RESULTCLASS = 0x4,
  WMIQ_ASSOCQ_ASSOCCLASS = 0x8,
  WMIQ_ASSOCQ_ROLE = 0x10,
  WMIQ_ASSOCQ_RESULTROLE = 0x20,
  WMIQ_ASSOCQ_REQUIREDQUALIFIER = 0x40,
  WMIQ_ASSOCQ_REQUIREDASSOCQUALIFIER = 0x80,
  WMIQ_ASSOCQ_CLASSDEFSONLY = 0x100,
  WMIQ_ASSOCQ_KEYSONLY = 0x200,
  WMIQ_ASSOCQ_SCHEMAONLY = 0x400,
  WMIQ_ASSOCQ_CLASSREFSONLY = 0x800
} WMIQ_ASSOCQ_FLAGS;