typedef enum tag_WBEM_PATH_CREATE_FLAG {
  WBEMPATH_CREATE_ACCEPT_RELATIVE = 0x1,
  WBEMPATH_CREATE_ACCEPT_ABSOLUTE = 0x2,
  WBEMPATH_CREATE_ACCEPT_ALL = 0x4,
  WBEMPATH_TREAT_SINGLE_IDENT_AS_NS = 0x8
} ;