typedef struct CLRES_FUNCTION_TABLE {
  DWORD TableSize;
  DWORD Version;
  union {
    CLRES_V1_FUNCTIONS V1Functions;
    CLRES_V2_FUNCTIONS V2Functions;
    CLRES_V3_FUNCTIONS V3Functions;
    CLRES_V4_FUNCTIONS V4Functions;
  } DUMMYUNIONNAME;
} CLRES_FUNCTION_TABLE, *PCLRES_FUNCTION_TABLE;