typedef enum _DXVAHD_DEVICE_CAPS {
  DXVAHD_DEVICE_CAPS_LINEAR_SPACE = 0x1,
  DXVAHD_DEVICE_CAPS_xvYCC = 0x2,
  DXVAHD_DEVICE_CAPS_RGB_RANGE_CONVERSION = 0x4,
  DXVAHD_DEVICE_CAPS_YCbCr_MATRIX_CONVERSION = 0x8
} DXVAHD_DEVICE_CAPS;