typedef enum _DXVAHD_INPUT_FORMAT_CAPS {
  DXVAHD_INPUT_FORMAT_CAPS_RGB_INTERLACED = 0x1,
  DXVAHD_INPUT_FORMAT_CAPS_RGB_PROCAMP = 0x2,
  DXVAHD_INPUT_FORMAT_CAPS_RGB_LUMA_KEY = 0x4,
  DXVAHD_INPUT_FORMAT_CAPS_PALETTE_INTERLACED = 0x8
} DXVAHD_INPUT_FORMAT_CAPS;