typedef enum _DXVAHD_FEATURE_CAPS {
  DXVAHD_FEATURE_CAPS_ALPHA_FILL = 0x1,
  DXVAHD_FEATURE_CAPS_CONSTRICTION = 0x2,
  DXVAHD_FEATURE_CAPS_LUMA_KEY = 0x4,
  DXVAHD_FEATURE_CAPS_ALPHA_PALETTE = 0x8
} DXVAHD_FEATURE_CAPS;