typedef struct _SECPKG_DLL_FUNCTIONS {
  PLSA_ALLOCATE_LSA_HEAP AllocateHeap;
  PLSA_FREE_LSA_HEAP     FreeHeap;
  PLSA_REGISTER_CALLBACK RegisterCallback;
  PLSA_LOCATE_PKG_BY_ID  LocatePackageById;
} SECPKG_DLL_FUNCTIONS, *PSECPKG_DLL_FUNCTIONS;