typedef enum MF_TIMED_TEXT_DECORATION {
  MF_TIMED_TEXT_DECORATION_NONE = 0,
  MF_TIMED_TEXT_DECORATION_UNDERLINE = 1,
  MF_TIMED_TEXT_DECORATION_LINE_THROUGH = 2,
  MF_TIMED_TEXT_DECORATION_OVERLINE = 4
} ;