typedef enum MF_MEDIA_ENGINE_CREATEFLAGS {
  MF_MEDIA_ENGINE_AUDIOONLY = 0x1,
  MF_MEDIA_ENGINE_WAITFORSTABLE_STATE = 0x2,
  MF_MEDIA_ENGINE_FORCEMUTE = 0x4,
  MF_MEDIA_ENGINE_REAL_TIME_MODE = 0x8,
  MF_MEDIA_ENGINE_DISABLE_LOCAL_PLUGINS = 0x10,
  MF_MEDIA_ENGINE_CREATEFLAGS_MASK = 0x1f
} ;