typedef struct _ACX_TARGET_FACTORY_CIRCUIT_CONFIG {
  ULONG       Size;
  ULONG       Flags;
  WDFIOTARGET IoTarget;
  WDFSTRING   SymbolicLinkName;
} ACX_TARGET_FACTORY_CIRCUIT_CONFIG, *PACX_TARGET_FACTORY_CIRCUIT_CONFIG;