typedef enum {
  MIRACAST_STATUS_CRITICAL_ERROR,
  MIRACAST_STATUS_MISSING_KEEPALIVE,
  MIRACAST_STATUS_SINK_DISOCNNECT_REQUEST,
  MIRACAST_STATUS_INSUFFICIENT_BANDWIDTH,
  MIRACAST_STATUS_SINK_FAILED_STANDARD_MODE_CHANGE,
  MIRACAST_STATUS_COMPANION_DRIVER_DISCONNECT,
  MIRACAST_STATUS_FORCE_UINT32
} MIRACAST_STATUS;