typedef enum {
  MIRACAST_STATISTIC_TYPE_CHUNK_PROCESSING_COMPLETE,
  MIRACAST_STATISTIC_TYPE_CHUNK_SENT,
  MIRACAST_STATISTIC_TYPE_EVENT,
  MIRACAST_STATISTIC_TYPE_FORCE_UINT32
} MIRACAST_STATISTIC_TYPE;