typedef enum {
  MIRACAST_CHUNK_TYPE_UNKNOWN,
  MIRACAST_CHUNK_TYPE_COLOR_CONVERT_COMPLETE,
  MIRACAST_CHUNK_TYPE_ENCODE_COMPLETE,
  MIRACAST_CHUNK_TYPE_FRAME_START,
  MIRACAST_CHUNK_TYPE_FRAME_DROPPED,
  MIRACAST_CHUNK_TYPE_ENCODE_DRIVER_DEFINED_1,
  MIRACAST_CHUNK_TYPE_ENCODE_DRIVER_DEFINED_2,
  MIRACAST_CHUNK_TYPE_ENCODE_FORCE_UINT32
} MIRACAST_CHUNK_TYPE;