typedef enum _tagSYNCMGRSTATUS {
  SYNCMGRSTATUS_STOPPED = 0,
  SYNCMGRSTATUS_SKIPPED = 0x1,
  SYNCMGRSTATUS_PENDING = 0x2,
  SYNCMGRSTATUS_UPDATING = 0x3,
  SYNCMGRSTATUS_SUCCEEDED = 0x4,
  SYNCMGRSTATUS_FAILED = 0x5,
  SYNCMGRSTATUS_PAUSED = 0x6,
  SYNCMGRSTATUS_RESUMING = 0x7,
  SYNCMGRSTATUS_UPDATING_INDETERMINATE = 0x8,
  SYNCMGRSTATUS_DELETED = 0x100
} SYNCMGRSTATUS;