typedef enum _tagSYNCMGRITEMFLAGS {
  SYNCMGRITEM_HASPROPERTIES = 0x1,
  SYNCMGRITEM_TEMPORARY = 0x2,
  SYNCMGRITEM_ROAMINGUSER = 0x4,
  SYNCMGRITEM_LASTUPDATETIME = 0x8,
  SYNCMGRITEM_MAYDELETEITEM = 0x10,
  SYNCMGRITEM_HIDDEN = 0x20
} SYNCMGRITEMFLAGS;