typedef enum _tagSYNCMGRHANDLERFLAGS {
  SYNCMGRHANDLER_HASPROPERTIES = 0x1,
  SYNCMGRHANDLER_MAYESTABLISHCONNECTION = 0x2,
  SYNCMGRHANDLER_ALWAYSLISTHANDLER = 0x4,
  SYNCMGRHANDLER_HIDDEN = 0x8
} SYNCMGRHANDLERFLAGS;