typedef enum _tagSYNCMGRFLAG {
  SYNCMGRFLAG_CONNECT = 0x1,
  SYNCMGRFLAG_PENDINGDISCONNECT = 0x2,
  SYNCMGRFLAG_MANUAL = 0x3,
  SYNCMGRFLAG_IDLE = 0x4,
  SYNCMGRFLAG_INVOKE = 0x5,
  SYNCMGRFLAG_SCHEDULED = 0x6,
  SYNCMGRFLAG_EVENTMASK = 0xff,
  SYNCMGRFLAG_SETTINGS = 0x100,
  SYNCMGRFLAG_MAYBOTHERUSER = 0x200
} SYNCMGRFLAG;