typedef enum DIRECTMANIPULATION_HITTEST_TYPE {
  DIRECTMANIPULATION_HITTEST_TYPE_ASYNCHRONOUS = 0,
  DIRECTMANIPULATION_HITTEST_TYPE_SYNCHRONOUS = 0x1,
  DIRECTMANIPULATION_HITTEST_TYPE_AUTO_SYNCHRONOUS = 0x2
} ;