typedef enum DIRECTMANIPULATION_CONFIGURATION {
  DIRECTMANIPULATION_CONFIGURATION_NONE = 0,
  DIRECTMANIPULATION_CONFIGURATION_INTERACTION = 0x1,
  DIRECTMANIPULATION_CONFIGURATION_TRANSLATION_X = 0x2,
  DIRECTMANIPULATION_CONFIGURATION_TRANSLATION_Y = 0x4,
  DIRECTMANIPULATION_CONFIGURATION_SCALING = 0x10,
  DIRECTMANIPULATION_CONFIGURATION_TRANSLATION_INERTIA = 0x20,
  DIRECTMANIPULATION_CONFIGURATION_SCALING_INERTIA = 0x80,
  DIRECTMANIPULATION_CONFIGURATION_RAILS_X = 0x100,
  DIRECTMANIPULATION_CONFIGURATION_RAILS_Y = 0x200
} ;