typedef enum DIRECTMANIPULATION_AUTOSCROLL_CONFIGURATION {
  DIRECTMANIPULATION_AUTOSCROLL_CONFIGURATION_STOP = 0,
  DIRECTMANIPULATION_AUTOSCROLL_CONFIGURATION_FORWARD = 1,
  DIRECTMANIPULATION_AUTOSCROLL_CONFIGURATION_REVERSE = 2
} ;