typedef enum DIRECTMANIPULATION_DRAG_DROP_STATUS {
  DIRECTMANIPULATION_DRAG_DROP_READY = 0,
  DIRECTMANIPULATION_DRAG_DROP_PRESELECT = 1,
  DIRECTMANIPULATION_DRAG_DROP_SELECTING = 2,
  DIRECTMANIPULATION_DRAG_DROP_DRAGGING = 3,
  DIRECTMANIPULATION_DRAG_DROP_CANCELLED = 4,
  DIRECTMANIPULATION_DRAG_DROP_COMMITTED = 5
} ;