typedef enum DIRECTMANIPULATION_DRAG_DROP_CONFIGURATION {
  DIRECTMANIPULATION_DRAG_DROP_CONFIGURATION_VERTICAL = 0x1,
  DIRECTMANIPULATION_DRAG_DROP_CONFIGURATION_HORIZONTAL = 0x2,
  DIRECTMANIPULATION_DRAG_DROP_CONFIGURATION_SELECT_ONLY = 0x10,
  DIRECTMANIPULATION_DRAG_DROP_CONFIGURATION_SELECT_DRAG = 0x20,
  DIRECTMANIPULATION_DRAG_DROP_CONFIGURATION_HOLD_DRAG = 0x40
} ;