typedef enum DIRECTMANIPULATION_VIEWPORT_OPTIONS {
  DIRECTMANIPULATION_VIEWPORT_OPTIONS_DEFAULT = 0,
  DIRECTMANIPULATION_VIEWPORT_OPTIONS_AUTODISABLE = 0x1,
  DIRECTMANIPULATION_VIEWPORT_OPTIONS_MANUALUPDATE = 0x2,
  DIRECTMANIPULATION_VIEWPORT_OPTIONS_INPUT = 0x4,
  DIRECTMANIPULATION_VIEWPORT_OPTIONS_EXPLICITHITTEST = 0x8,
  DIRECTMANIPULATION_VIEWPORT_OPTIONS_DISABLEPIXELSNAPPING = 0x10
} ;