typedef enum DIRECTMANIPULATION_HORIZONTALALIGNMENT {
  DIRECTMANIPULATION_HORIZONTALALIGNMENT_NONE = 0,
  DIRECTMANIPULATION_HORIZONTALALIGNMENT_LEFT = 0x1,
  DIRECTMANIPULATION_HORIZONTALALIGNMENT_CENTER = 0x2,
  DIRECTMANIPULATION_HORIZONTALALIGNMENT_RIGHT = 0x4,
  DIRECTMANIPULATION_HORIZONTALALIGNMENT_UNLOCKCENTER = 0x8
} ;