typedef enum DIRECTMANIPULATION_SNAPPOINT_TYPE {
  DIRECTMANIPULATION_SNAPPOINT_MANDATORY = 0,
  DIRECTMANIPULATION_SNAPPOINT_OPTIONAL = 1,
  DIRECTMANIPULATION_SNAPPOINT_MANDATORY_SINGLE = 2,
  DIRECTMANIPULATION_SNAPPOINT_OPTIONAL_SINGLE = 3
} ;