typedef enum DIRECTMANIPULATION_MOTION_TYPES {
  DIRECTMANIPULATION_MOTION_NONE = 0,
  DIRECTMANIPULATION_MOTION_TRANSLATEX = 0x1,
  DIRECTMANIPULATION_MOTION_TRANSLATEY = 0x2,
  DIRECTMANIPULATION_MOTION_ZOOM = 0x4,
  DIRECTMANIPULATION_MOTION_CENTERX = 0x10,
  DIRECTMANIPULATION_MOTION_CENTERY = 0x20,
  DIRECTMANIPULATION_MOTION_ALL
} ;