typedef enum DIRECTMANIPULATION_GESTURE_CONFIGURATION {
  DIRECTMANIPULATION_GESTURE_NONE = 0,
  DIRECTMANIPULATION_GESTURE_DEFAULT = 0,
  DIRECTMANIPULATION_GESTURE_CROSS_SLIDE_VERTICAL = 0x8,
  DIRECTMANIPULATION_GESTURE_CROSS_SLIDE_HORIZONTAL = 0x10,
  DIRECTMANIPULATION_GESTURE_PINCH_ZOOM = 0x20
} ;