typedef enum DIRECTMANIPULATION_VERTICALALIGNMENT {
  DIRECTMANIPULATION_VERTICALALIGNMENT_NONE = 0,
  DIRECTMANIPULATION_VERTICALALIGNMENT_TOP = 0x1,
  DIRECTMANIPULATION_VERTICALALIGNMENT_CENTER = 0x2,
  DIRECTMANIPULATION_VERTICALALIGNMENT_BOTTOM = 0x4,
  DIRECTMANIPULATION_VERTICALALIGNMENT_UNLOCKCENTER = 0x8
} ;