typedef struct _ENHANCED_STORAGE_PASSWORD_SILO_INFORMATION {
  BYTE  CurrentAdminFailures;
  BYTE  CurrentUserFailures;
  DWORD TotalUserAuthenticationCount;
  DWORD TotalAdminAuthenticationCount;
  BOOL  FipsCompliant;
  BOOL  SecurityIDAvailable;
  BOOL  InitializeInProgress;
  BOOL  ITMSArmed;
  BOOL  ITMSArmable;
  BOOL  UserCreated;
  BOOL  ResetOnPORDefault;
  BOOL  ResetOnPORCurrent;
  BYTE  MaxAdminFailures;
  BYTE  MaxUserFailures;
  DWORD TimeToCompleteInitialization;
  DWORD TimeRemainingToCompleteInitialization;
  DWORD MinTimeToAuthenticate;
  BYTE  MaxAdminPasswordSize;
  BYTE  MinAdminPasswordSize;
  BYTE  MaxAdminHintSize;
  BYTE  MaxUserPasswordSize;
  BYTE  MinUserPasswordSize;
  BYTE  MaxUserHintSize;
  BYTE  MaxUserNameSize;
  BYTE  MaxSiloNameSize;
  WORD  MaxChallengeSize;
} ENHANCED_STORAGE_PASSWORD_SILO_INFORMATION, *PENHANCED_STORAGE_PASSWORD_SILO_INFORMATION;