typedef enum _UFX_CLASS_FUNCTIONS {
  UfxFdoInitIndex = ,
  UfxDeviceCreateIndex = ,
  UfxDeviceEventCompleteIndex = ,
  UfxDeviceNotifyHardwareReadyIndex = ,
  UfxDeviceNotifyAttachIndex = ,
  UfxDeviceNotifyDetachIndex = ,
  UfxDeviceNotifySuspendIndex = ,
  UfxDeviceNotifyResumeIndex = ,
  UfxDeviceNotifyResetIndex = ,
  UfxDevicePortDetectCompleteIndex = ,
  UfxDeviceProprietaryChargerDetectCompleteIndex = ,
  UfxDeviceNotifyHardwareFailureIndex = ,
  UfxDeviceIoControlIndex = ,
  UfxDeviceIoInternalControlIndex = ,
  UfxEndpointCreateIndex = ,
  UfxEndpointInitSetEventCallbacksIndex = ,
  UfxEndpointNotifySetupIndex = ,
  UfxEndpointGetTransferQueueIndex = ,
  UfxEndpointGetCommandQueueIndex = ,
  UfxDevicePortDetectCompleteExIndex = ,
  UfxDeviceNotifyFinalExitIndex = ,
  UfxFunctionsMax = 
} UFX_CLASS_FUNCTIONS;