typedef struct _PKTMON_PROVIDER_DISPATCH {
  USHORT                                       Size;
  PKTMON_PROVIDER_REGISTER_COMPONENT_HANDLER   ComponentRegister;
  PKTMON_PROVIDER_UNREGISTER_COMPONENT_HANDLER ComponentUnregister;
  PKTMON_PROVIDER_SET_COMP_PROPERTY_HANDLER    SetCompProperty;
  PKTMON_PROVIDER_ADD_EDGE_HANDLER             EdgeAdd;
  PKTMON_PROVIDER_PACKET_LOG_HANDLER           PacketLog;
  PKTMON_PROVIDER_PACKET_DROP_HANDLER          PacketDrop;
} PKTMON_PROVIDER_DISPATCH;