typedef struct _PKTMON_CLIENT_DISPATCH {
  USHORT                            Size;
  PKTMON_CLIENT_ENABLE_HANDLER      ClientEnable;
  PKTMON_CLIENT_COMP_ENABLE_HANDLER CompEnable;
  PKTMON_CLIENT_COMP_CLOSE_HANDLER  CompClose;
} PKTMON_CLIENT_DISPATCH;