typedef enum _NFC_CX_NFCIP_MODE_CONFIG {
  NFC_CX_NFCIP_NFC_A,
  NFC_CX_NFCIP_NFC_F_212,
  NFC_CX_NFCIP_NFC_F_424,
  NFC_CX_NFCIP_NFC_ACTIVE,
  NFC_CX_NFCIP_NFC_ACTIVE_A,
  NFC_CX_NFCIP_NFC_ACTIVE_F_212,
  NFC_CX_NFCIP_NFC_ACTIVE_F_424,
  NFC_CX_NFCIP_DEFAULT
} NFC_CX_NFCIP_MODE_CONFIG, *PNFC_CX_NFCIP_MODE_CONFIG;