typedef enum _NFC_CX_POLL_MODE_CONFIG {
  NFC_CX_POLL_NFC_A,
  NFC_CX_POLL_NFC_B,
  NFC_CX_POLL_NFC_F_212,
  NFC_CX_POLL_NFC_F_424,
  NFC_CX_POLL_NFC_15693,
  NFC_CX_POLL_NFC_ACTIVE,
  NFC_CX_POLL_NFC_A_KOVIO,
  NFC_CX_POLL_DEFAULT
} NFC_CX_POLL_MODE_CONFIG, *PNFC_CX_POLL_MODE_CONFIG;