typedef enum _NFC_CX_NFCIP_TGT_MODE_CONFIG {
  NFC_CX_NFCIP_TGT_NFC_A,
  NFC_CX_NFCIP_TGT_NFC_F,
  NFC_CX_NFCIP_TGT_NFC_ACTIVE_A,
  NFC_CX_NFCIP_TGT_NFC_ACTIVE_F,
  NFC_CX_NFCIP_TGT_DEFAULT
} NFC_CX_NFCIP_TGT_MODE_CONFIG, *PNFC_CX_NFCIP_TGT_MODE_CONFIG;