typedef enum FWPM_SYSTEM_PORT_TYPE_ {
  FWPM_SYSTEM_PORT_RPC_EPMAP = 0,
  FWPM_SYSTEM_PORT_TEREDO,
  FWPM_SYSTEM_PORT_IPHTTPS_IN,
  FWPM_SYSTEM_PORT_IPHTTPS_OUT,
  FWPM_SYSTEM_PORT_TYPE_MAX
} FWPM_SYSTEM_PORT_TYPE;