typedef enum FWPM_PROVIDER_CONTEXT_TYPE_ {
  FWPM_IPSEC_KEYING_CONTEXT = 0,
  FWPM_IPSEC_IKE_QM_TRANSPORT_CONTEXT,
  FWPM_IPSEC_IKE_QM_TUNNEL_CONTEXT,
  FWPM_IPSEC_AUTHIP_QM_TRANSPORT_CONTEXT,
  FWPM_IPSEC_AUTHIP_QM_TUNNEL_CONTEXT,
  FWPM_IPSEC_IKE_MM_CONTEXT,
  FWPM_IPSEC_AUTHIP_MM_CONTEXT,
  FWPM_CLASSIFY_OPTIONS_CONTEXT,
  FWPM_GENERAL_CONTEXT,
  FWPM_IPSEC_IKEV2_QM_TUNNEL_CONTEXT,
  FWPM_IPSEC_IKEV2_MM_CONTEXT,
  FWPM_IPSEC_DOSP_CONTEXT,
  FWPM_IPSEC_IKEV2_QM_TRANSPORT_CONTEXT,
  FWPM_NETWORK_CONNECTION_POLICY_CONTEXT,
  FWPM_PROVIDER_CONTEXT_TYPE_MAX
} FWPM_PROVIDER_CONTEXT_TYPE;