typedef enum FWPM_ENGINE_OPTION_ {
  FWPM_ENGINE_COLLECT_NET_EVENTS = 0,
  FWPM_ENGINE_NET_EVENT_MATCH_ANY_KEYWORDS,
  FWPM_ENGINE_NAME_CACHE,
  FWPM_ENGINE_MONITOR_IPSEC_CONNECTIONS,
  FWPM_ENGINE_PACKET_QUEUING,
  FWPM_ENGINE_TXN_WATCHDOG_TIMEOUT_IN_MSEC,
  FWPM_ENGINE_OPTION_MAX
} FWPM_ENGINE_OPTION;