typedef struct FWPM_NETWORK_CONNECTION_POLICY_SETTINGS0_ {
  UINT32                                  numSettings;
  FWPM_NETWORK_CONNECTION_POLICY_SETTING0 *settings;
} FWPM_NETWORK_CONNECTION_POLICY_SETTINGS0;