typedef struct FWPM_NET_EVENT1_ {
  FWPM_NET_EVENT_HEADER1 header;
  FWPM_NET_EVENT_TYPE    type;
  union {
    FWPM_NET_EVENT_IKEEXT_MM_FAILURE1 *ikeMmFailure;
    FWPM_NET_EVENT_IKEEXT_QM_FAILURE0 *ikeQmFailure;
    FWPM_NET_EVENT_IKEEXT_EM_FAILURE1 *ikeEmFailure;
    FWPM_NET_EVENT_CLASSIFY_DROP1     *classifyDrop;
    FWPM_NET_EVENT_IPSEC_KERNEL_DROP0 *ipsecDrop;
    FWPM_NET_EVENT_IPSEC_DOSP_DROP0   *idpDrop;
  };
} FWPM_NET_EVENT1;