typedef struct FWPM_NETWORK_CONNECTION_POLICY_SETTING0_ {
  FWP_NETWORK_CONNECTION_POLICY_SETTING_TYPE type;
  FWP_VALUE0                                 value;
} FWPM_NETWORK_CONNECTION_POLICY_SETTING0;