typedef struct FWPM_NET_EVENT2_ {
  FWPM_NET_EVENT_HEADER2 header;
  FWPM_NET_EVENT_TYPE    type;
  union {
    FWPM_NET_EVENT_IKEEXT_MM_FAILURE1 *ikeMmFailure;
    FWPM_NET_EVENT_IKEEXT_QM_FAILURE0 *ikeQmFailure;
    FWPM_NET_EVENT_IKEEXT_EM_FAILURE1 *ikeEmFailure;
    FWPM_NET_EVENT_CLASSIFY_DROP2     *classifyDrop;
    FWPM_NET_EVENT_IPSEC_KERNEL_DROP0 *ipsecDrop;
    FWPM_NET_EVENT_IPSEC_DOSP_DROP0   *idpDrop;
    FWPM_NET_EVENT_CLASSIFY_ALLOW0    *classifyAllow;
    FWPM_NET_EVENT_CAPABILITY_DROP0   *capabilityDrop;
    FWPM_NET_EVENT_CAPABILITY_ALLOW0  *capabilityAllow;
    FWPM_NET_EVENT_CLASSIFY_DROP_MAC0 *classifyDropMac;
  };
} FWPM_NET_EVENT2;