typedef enum _DRM_STATUS_MSG {
  DRM_MSG_ACTIVATE_MACHINE,
  DRM_MSG_ACTIVATE_GROUPIDENTITY,
  DRM_MSG_ACQUIRE_LICENSE,
  DRM_MSG_ACQUIRE_ADVISORY,
  DRM_MSG_SIGN_ISSUANCE_LICENSE,
  DRM_MSG_ACQUIRE_CLIENTLICENSOR,
  DRM_MSG_ACQUIRE_ISSUANCE_LICENSE_TEMPLATE
} DRM_STATUS_MSG;