typedef enum _FSM_STATE {
  NO_STATE = 0,
  INIT,
  STARTUP,
  NORMAL,
  COMMUNICATION_INT,
  PARTNER_DOWN,
  POTENTIAL_CONFLICT,
  CONFLICT_DONE,
  RESOLUTION_INT,
  RECOVER,
  RECOVER_WAIT,
  RECOVER_DONE,
  PAUSED,
  SHUTDOWN
} FSM_STATE;