typedef struct _DHCP_SUBNET_ELEMENT_INFO_ARRAY_V5 {
  DWORD                         NumElements;
  LPDHCP_SUBNET_ELEMENT_DATA_V5 Elements;
} DHCP_SUBNET_ELEMENT_INFO_ARRAY_V5, *LPDHCP_SUBNET_ELEMENT_INFO_ARRAY_V5;