typedef struct _DHCPV4_FAILOVER_CLIENT_INFO {
  DHCP_IP_ADDRESS  ClientIpAddress;
  DHCP_IP_MASK     SubnetMask;
  DHCP_CLIENT_UID  ClientHardwareAddress;
  LPWSTR           ClientName;
  LPWSTR           ClientComment;
  DATE_TIME        ClientLeaseExpires;
  DHCP_HOST_INFO   OwnerHost;
  BYTE             bClientType;
  BYTE             AddressState;
  QuarantineStatus Status;
  DATE_TIME        ProbationEnds;
  BOOL             QuarantineCapable;
  DWORD            SentPotExpTime;
  DWORD            AckPotExpTime;
  DWORD            RecvPotExpTime;
  DWORD            StartTime;
  DWORD            CltLastTransTime;
  DWORD            LastBndUpdTime;
  DWORD            BndMsgStatus;
  LPWSTR           PolicyName;
  BYTE             Flags;
} DHCPV4_FAILOVER_CLIENT_INFO, *LPDHCPV4_FAILOVER_CLIENT_INFO;