typedef struct _DHCPV4_FAILOVER_CLIENT_INFO_ARRAY {
  DWORD                         NumElements;
  LPDHCPV4_FAILOVER_CLIENT_INFO *Clients;
} DHCPV4_FAILOVER_CLIENT_INFO_ARRAY, *LPDHCPV4_FAILOVER_CLIENT_INFO_ARRAY;