typedef struct _DHCP_CLIENT_FILTER_STATUS_INFO_ARRAY {
  DWORD                            NumElements;
  LPDHCP_CLIENT_FILTER_STATUS_INFO *Clients;
} DHCP_CLIENT_FILTER_STATUS_INFO_ARRAY, *LPDHCP_CLIENT_FILTER_STATUS_INFO_ARRAY;