typedef struct _DHCP_FAILOVER_RELATIONSHIP_ARRAY {
  DWORD                        NumElements;
  LPDHCP_FAILOVER_RELATIONSHIP pRelationships;
} DHCP_FAILOVER_RELATIONSHIP_ARRAY, *LPDHCP_FAILOVER_RELATIONSHIP_ARRAY;