typedef struct _DHCP_SUBNET_ELEMENT_INFO_ARRAY_V6 {
  DWORD                         NumElements;
  LPDHCP_SUBNET_ELEMENT_DATA_V6 Elements;
} DHCP_SUBNET_ELEMENT_INFO_ARRAY_V6, *LPDHCP_SUBNET_ELEMENT_INFO_ARRAY_V6;