typedef struct _DHCP_SUBNET_ELEMENT_INFO_ARRAY_V4 {
  DWORD                         NumElements;
  LPDHCP_SUBNET_ELEMENT_DATA_V4 Elements;
} DHCP_SUBNET_ELEMENT_INFO_ARRAY_V4, *LPDHCP_SUBNET_ELEMENT_INFO_ARRAY_V4;