typedef struct _MAPPING_SERVICE_INFO {
  size_t   Size;
  LPWSTR   pszCopyright;
  WORD     wMajorVersion;
  WORD     wMinorVersion;
  WORD     wBuildVersion;
  WORD     wStepVersion;
  DWORD    dwInputContentTypesCount;
  LPWSTR   *prgInputContentTypes;
  DWORD    dwOutputContentTypesCount;
  LPWSTR   *prgOutputContentTypes;
  DWORD    dwInputLanguagesCount;
  LPWSTR   *prgInputLanguages;
  DWORD    dwOutputLanguagesCount;
  LPWSTR   *prgOutputLanguages;
  DWORD    dwInputScriptsCount;
  LPWSTR   *prgInputScripts;
  DWORD    dwOutputScriptsCount;
  LPWSTR   *prgOutputScripts;
  GUID     guid;
  LPWSTR   pszCategory;
  LPWSTR   pszDescription;
  DWORD    dwPrivateDataSize;
  LPVOID   pPrivateData;
  LPVOID   pContext;
  unsigned IsOneToOneLanguageMapping : 1;
  unsigned HasSubservices : 1;
  unsigned OnlineOnly : 1;
  unsigned ServiceType : 2;
} MAPPING_SERVICE_INFO, *PMAPPING_SERVICE_INFO;