typedef enum SECURELOCKCODE {
  SECURELOCK_NOCHANGE = -1,
  SECURELOCK_SET_UNSECURE = 0,
  SECURELOCK_SET_MIXED,
  SECURELOCK_SET_SECUREUNKNOWNBIT,
  SECURELOCK_SET_SECURE40BIT,
  SECURELOCK_SET_SECURE56BIT,
  SECURELOCK_SET_FORTEZZA,
  SECURELOCK_SET_SECURE128BIT,
  SECURELOCK_FIRSTSUGGEST,
  SECURELOCK_SUGGEST_UNSECURE,
  SECURELOCK_SUGGEST_MIXED,
  SECURELOCK_SUGGEST_SECUREUNKNOWNBIT,
  SECURELOCK_SUGGEST_SECURE40BIT,
  SECURELOCK_SUGGEST_SECURE56BIT,
  SECURELOCK_SUGGEST_FORTEZZA,
  SECURELOCK_SUGGEST_SECURE128BIT
} ;