typedef enum _EVT_CHANNEL_CONFIG_PROPERTY_ID {
  EvtChannelConfigEnabled = 0,
  EvtChannelConfigIsolation,
  EvtChannelConfigType,
  EvtChannelConfigOwningPublisher,
  EvtChannelConfigClassicEventlog,
  EvtChannelConfigAccess,
  EvtChannelLoggingConfigRetention,
  EvtChannelLoggingConfigAutoBackup,
  EvtChannelLoggingConfigMaxSize,
  EvtChannelLoggingConfigLogFilePath,
  EvtChannelPublishingConfigLevel,
  EvtChannelPublishingConfigKeywords,
  EvtChannelPublishingConfigControlGuid,
  EvtChannelPublishingConfigBufferSize,
  EvtChannelPublishingConfigMinBuffers,
  EvtChannelPublishingConfigMaxBuffers,
  EvtChannelPublishingConfigLatency,
  EvtChannelPublishingConfigClockType,
  EvtChannelPublishingConfigSidType,
  EvtChannelPublisherList,
  EvtChannelPublishingConfigFileMax,
  EvtChannelConfigPropertyIdEND
} EVT_CHANNEL_CONFIG_PROPERTY_ID;