typedef enum PLACEHOLDER_STATES {
  PS_NONE = 0,
  PS_MARKED_FOR_OFFLINE_AVAILABILITY = 0x1,
  PS_FULL_PRIMARY_STREAM_AVAILABLE = 0x2,
  PS_CREATE_FILE_ACCESSIBLE = 0x4,
  PS_CLOUDFILE_PLACEHOLDER = 0x8,
  PS_DEFAULT,
  PS_ALL
} ;