typedef enum _SIGDN {
  SIGDN_NORMALDISPLAY = 0,
  SIGDN_PARENTRELATIVEPARSING,
  SIGDN_DESKTOPABSOLUTEPARSING,
  SIGDN_PARENTRELATIVEEDITING,
  SIGDN_DESKTOPABSOLUTEEDITING,
  SIGDN_FILESYSPATH,
  SIGDN_URL,
  SIGDN_PARENTRELATIVEFORADDRESSBAR,
  SIGDN_PARENTRELATIVE,
  SIGDN_PARENTRELATIVEFORUI
} SIGDN;