typedef enum IORING_OP_CODE {
  IORING_OP_NOP,
  IORING_OP_READ,
  IORING_OP_REGISTER_FILES,
  IORING_OP_REGISTER_BUFFERS,
  IORING_OP_CANCEL,
  IORING_OP_WRITE,
  IORING_OP_FLUSH,
  IORING_OP_READ_SCATTER,
  IORING_OP_WRITE_GATHER
} ;