typedef enum _UCX_USBDEVICE_RECOVERY_ACTION {
  UcxUsbDeviceRecoverActionNone,
  UcxUsbDeviceRecoverActionFunctionLevelDeviceReset,
  UcxUsbDeviceRecoverActionPlatformLevelDeviceReset
} UCX_USBDEVICE_RECOVERY_ACTION;