typedef enum tag_SCRIPT_JUSTIFY {
  SCRIPT_JUSTIFY_NONE = 0,
  SCRIPT_JUSTIFY_ARABIC_BLANK = 1,
  SCRIPT_JUSTIFY_CHARACTER = 2,
  SCRIPT_JUSTIFY_RESERVED1 = 3,
  SCRIPT_JUSTIFY_BLANK = 4,
  SCRIPT_JUSTIFY_RESERVED2 = 5,
  SCRIPT_JUSTIFY_RESERVED3 = 6,
  SCRIPT_JUSTIFY_ARABIC_NORMAL = 7,
  SCRIPT_JUSTIFY_ARABIC_KASHIDA = 8,
  SCRIPT_JUSTIFY_ARABIC_ALEF = 9,
  SCRIPT_JUSTIFY_ARABIC_HA = 10,
  SCRIPT_JUSTIFY_ARABIC_RA = 11,
  SCRIPT_JUSTIFY_ARABIC_BA = 12,
  SCRIPT_JUSTIFY_ARABIC_BARA = 13,
  SCRIPT_JUSTIFY_ARABIC_SEEN = 14,
  SCRIPT_JUSTIFY_ARABIC_SEEN_M = 15
} SCRIPT_JUSTIFY;