typedef struct _ACX_AUDIOMODULE_DESCRIPTOR {
  GUID  ClassId;
  ULONG InstanceId;
  ULONG VersionMajor;
  ULONG VersionMinor;
  WCHAR Name[ACX_AUDIOMODULE_MAX_NAME_CCH_SIZE];
} ACX_AUDIOMODULE_DESCRIPTOR, *PACX_AUDIOMODULE_DESCRIPTOR;