name: Generate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * SUN'

concurrency:
  group: generate
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          path: main
      - name: Checkout MicrosoftDocs/windows-driver-docs-ddi
        uses: actions/checkout@v5
        with:
          repository: MicrosoftDocs/windows-driver-docs-ddi
          path: windows-driver-docs-ddi
      - name: Checkout MicrosoftDocs/sdk-api
        uses: actions/checkout@v5
        with:
          repository: MicrosoftDocs/sdk-api
          path: sdk-api
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r main/requirements.txt
      - name: Generate docs - Windows Driver Kit DDI
        run: |
          cd main
          python -u scraper.py \
            --input ../windows-driver-docs-ddi \
            --output ./output/windows-driver-docs-ddi \
            --content-path wdk-ddi-src/content \
            --base-url https://learn.microsoft.com/windows-hardware/drivers/ddi/
      - name: Generate docs - Win32 API
        run: |
          cd main
          python -u scraper.py \
            --input ../sdk-api \
            --output ./output/sdk-api \
            --content-path sdk-api-src/content \
            --base-url https://learn.microsoft.com/windows/win32/api/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./main/output
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
