typedef enum _HAL_SET_INFORMATION_CLASS {
  HalProfileSourceInterval,
  HalProfileSourceInterruptHandler,
  HalMcaRegisterDriver,
  HalKernelErrorHandler,
  HalCmcRegisterDriver,
  HalCpeRegisterDriver,
  HalMcaLog,
  HalCmcLog,
  HalCpeLog,
  HalGenerateCmcInterrupt,
  HalProfileSourceTimerHandler,
  HalEnlightenment,
  HalProfileDpgoSourceInterruptHandler,
  HalRegisterSecondaryInterruptInterface,
  HalSetChannelPowerInformation,
  HalI386ExceptionChainTerminatorInformation,
  HalSetResetParkDisposition,
  HalSetPsciSuspendMode,
  HalSetHvciEnabled,
  HalSetProcessorTraceInterruptHandler,
  HalProfileSourceAdd,
  HalProfileSourceRemove,
  HalSetSwInterruptHandler,
  HalSetClockTimerMinimumInterval,
  HalRegisterPmuNotification,
  HalUnregisterPmuNotification
} HAL_SET_INFORMATION_CLASS, *PHAL_SET_INFORMATION_CLASS;