typedef enum _SOC_SUBSYSTEM_TYPE {
  SOC_SUBSYS_WIRELESS_MODEM,
  SOC_SUBSYS_AUDIO_DSP,
  SOC_SUBSYS_WIRELSS_CONNECTIVITY,
  SOC_SUBSYS_SENSORS,
  SOC_SUBSYS_COMPUTE_DSP = ,
  SOC_SUBSYS_SECURE_PROC,
  SOC_SUBSYS_VENDOR_DEFINED
} SOC_SUBSYSTEM_TYPE, *PSOC_SUBSYSTEM_TYPE;