typedef struct _PCI_EXPRESS_DPC_CAPABILITY {
  PCI_EXPRESS_ENHANCED_CAPABILITY_HEADER       Header;
  PCI_EXPRESS_DPC_CAPS_REGISTER                DpcCapabilities;
  PCI_EXPRESS_DPC_CONTROL_REGISTER             DpcControl;
  PCI_EXPRESS_DPC_STATUS_REGISTER              DpcStatus;
  PCI_EXPRESS_DPC_ERROR_SOURCE_ID              DpcErrSrcId;
  PCI_EXPRESS_DPC_RP_PIO_STATUS_REGISTER       RpPioStatus;
  PCI_EXPRESS_DPC_RP_PIO_MASK_REGISTER         RpPioMask;
  PCI_EXPRESS_DPC_RP_PIO_SEVERITY_REGISTER     RpPioSeverity;
  PCI_EXPRESS_DPC_RP_PIO_SYSERR_REGISTER       RpPioSysError;
  PCI_EXPRESS_DPC_RP_PIO_EXCEPTION_REGISTER    RpPioException;
  PCI_EXPRESS_DPC_RP_PIO_HEADERLOG_REGISTER    RpPioHeaderLog;
  PCI_EXPRESS_DPC_RP_PIO_IMPSPECLOG_REGISTER   RpPioImpSpecLog;
  PCI_EXPRESS_DPC_RP_PIO_TLPPREFIXLOG_REGISTER RpPioPrefixLog;
} PCI_EXPRESS_DPC_CAPABILITY, *PPCI_EXPRESS_DPC_CAPABILITY;