typedef struct _PCI_FPB_CAPABILITY {
  PCI_FPB_CAPABILITY_HEADER                 Header;
  PCI_FPB_CAPABILITIES_REGISTER             CapabilitiesRegister;
  PCI_FPB_RID_VECTOR_CONTROL1_REGISTER      RidVectorControl1Register;
  PCI_FPB_RID_VECTOR_CONTROL2_REGISTER      RidVectorControl2Register;
  PCI_FPB_MEM_LOW_VECTOR_CONTROL_REGISTER   MemLowVectorControlRegister;
  PCI_FPB_MEM_HIGH_VECTOR_CONTROL1_REGISTER MemHighVectorControl1Register;
  PCI_FPB_MEM_HIGH_VECTOR_CONTROL2_REGISTER MemHighVectorControl2Register;
  PCI_FPB_VECTOR_ACCESS_CONTROL_REGISTER    VectorAccessControlRegister;
  PCI_FPB_VECTOR_ACCESS_DATA_REGISTER       VectorAccessDataRegister;
} PCI_FPB_CAPABILITY, *PPCI_FPB_CAPABILITY;