typedef struct _WHEA_MEMORY_THROTTLE_SUMMARY_FAILED_EVENT {
  WHEA_EVENT_LOG_ENTRY WheaEventLogEntry;
  NTSTATUS             Status;
} WHEA_MEMORY_THROTTLE_SUMMARY_FAILED_EVENT, *PWHEA_MEMORY_THROTTLE_SUMMARY_FAILED_EVENT;