typedef struct _WHEA_THROTTLE_REG_DATA_IGNORED_EVENT {
  WHEA_EVENT_LOG_ENTRY WheaEventLogEntry;
  WHEA_THROTTLE_TYPE   ThrottleType;
} WHEA_THROTTLE_REG_DATA_IGNORED_EVENT, *PWHEA_THROTTLE_REG_DATA_IGNORED_EVENT;