typedef struct _PCI_EXPRESS_SECONDARY_CAPABILITY {
  PCI_EXPRESS_ENHANCED_CAPABILITY_HEADER Header;
  PCI_EXPRESS_LINK_CONTROL3              LinkControl3;
  PCI_EXPRESS_LANE_ERROR_STATUS          LaneErrorStatus;
} PCI_EXPRESS_SECONDARY_CAPABILITY, *PPCI_EXPRESS_SECONDARY_CAPABILITY;