typedef union _WHEA_REPORT_HW_ERROR_DEVICE_DRIVER_FLAGS {
  struct {
    ULONG Reserved : 32;
  } DUMMYSTRUCTNAME;
  ULONG  AsULONG;
} WHEA_REPORT_HW_ERROR_DEVICE_DRIVER_FLAGS, *PWHEA_REPORT_HW_ERROR_DEVICE_DRIVER_FLAGS;