typedef union _PCI_EXPRESS_LINK_CAPABILITIES_2_REGISTER {
  struct {
    ULONG Rsvd0 : 1;
    ULONG SupportedLinkSpeedsVector : 7;
    ULONG Rsvd8_31 : 24;
  } DUMMYSTRUCTNAME;
  ULONG  AsULONG;
} PCI_EXPRESS_LINK_CAPABILITIES_2_REGISTER, *PPCI_EXPRESS_LINK_CAPABILITIES_2_REGISTER;