typedef struct _WHEA_PSHED_PLUGIN_PLATFORM_SUPPORT_EVENT {
  WHEA_EVENT_LOG_ENTRY WheaEventLogEntry;
  WCHAR                PluginName[WHEA_ERROR_TEXT_LEN];
  BOOLEAN              Supported;
} WHEA_PSHED_PLUGIN_PLATFORM_SUPPORT_EVENT, *PWHEA_PSHED_PLUGIN_PLATFORM_SUPPORT_EVENT;