typedef union _PCI_FPB_RID_VECTOR_CONTROL2_REGISTER {
  struct {
    ULONG Rsvd0 : 3;
    ULONG RidSecondaryStart : 13;
    ULONG Rsvd1 : 16;
  } DUMMYSTRUCTNAME;
  ULONG  AsULONG;
} PCI_FPB_RID_VECTOR_CONTROL2_REGISTER, *PPCI_FPB_RID_VECTOR_CONTROL2_REGISTER;