typedef union _WHEA_MEMORY_CORRECTABLE_ERROR_SECTION_VALIDBITS {
  struct {
    ULONGLONG SocketId : 1;
    ULONGLONG ChannelId : 1;
    ULONGLONG DimmSlot : 1;
    ULONGLONG CorrectableErrorCount : 1;
    ULONGLONG Reserved : 60;
  } DUMMYSTRUCTNAME;
  ULONGLONG ValidBits;
} WHEA_MEMORY_CORRECTABLE_ERROR_SECTION_VALIDBITS, *PWHEA_MEMORY_CORRECTABLE_ERROR_SECTION_VALIDBITS;