typedef struct _WHEA_SEL_BUGCHECK_RECOVERY_STATUS_START_EVENT {
  WHEA_EVENT_LOG_ENTRY WheaEventLogEntry;
  KIRQL                StartingIrql;
} WHEA_SEL_BUGCHECK_RECOVERY_STATUS_START_EVENT, *PWHEA_SEL_BUGCHECK_RECOVERY_STATUS_START_EVENT;