typedef union _WHEA_PCIXDEVICE_ERROR_SECTION_VALIDBITS {
  struct {
    ULONGLONG ErrorStatus : 1;
    ULONGLONG IdInfo : 1;
    ULONGLONG MemoryNumber : 1;
    ULONGLONG IoNumber : 1;
    ULONGLONG RegisterDataPairs : 1;
    ULONGLONG Reserved : 59;
  } DUMMYSTRUCTNAME;
  ULONGLONG ValidBits;
} WHEA_PCIXDEVICE_ERROR_SECTION_VALIDBITS, *PWHEA_PCIXDEVICE_ERROR_SECTION_VALIDBITS;