typedef struct {
  ULONG                          Version;
  pHalQuerySystemInformation     HalQuerySystemInformation;
  pHalSetSystemInformation       HalSetSystemInformation;
  pHalQueryBusSlots              HalQueryBusSlots;
  ULONG                          Spare1;
  pHalExamineMBR                 HalExamineMBR;
  pHalIoReadPartitionTable       HalIoReadPartitionTable;
  pHalIoSetPartitionInformation  HalIoSetPartitionInformation;
  pHalIoWritePartitionTable      HalIoWritePartitionTable;
  pHalHandlerForBus              HalReferenceHandlerForBus;
  pHalReferenceBusHandler        HalReferenceBusHandler;
  pHalReferenceBusHandler        HalDereferenceBusHandler;
  pHalInitPnpDriver              HalInitPnpDriver;
  pHalInitPowerManagement        HalInitPowerManagement;
  pHalGetDmaAdapter              HalGetDmaAdapter;
  pHalGetInterruptTranslator     HalGetInterruptTranslator;
  pHalStartMirroring             HalStartMirroring;
  pHalEndMirroring               HalEndMirroring;
  pHalMirrorPhysicalMemory       HalMirrorPhysicalMemory;
  pHalEndOfBoot                  HalEndOfBoot;
  pHalMirrorVerify               HalMirrorVerify;
  pHalGetAcpiTable               HalGetCachedAcpiTable;
  pHalSetPciErrorHandlerCallback HalSetPciErrorHandlerCallback;
  pHalGetPrmCache                HalGetPrmCache;
  pHalInvokePrmFwHandler         HalInvokePrmFwHandler;
} HAL_DISPATCH, *PHAL_DISPATCH;