typedef struct _WHEA_THROTTLE_REGISTRY_CORRUPT_EVENT {
  WHEA_EVENT_LOG_ENTRY WheaEventLogEntry;
  WHEA_THROTTLE_TYPE   ThrottleType;
} WHEA_THROTTLE_REGISTRY_CORRUPT_EVENT, *PWHEA_THROTTLE_REGISTRY_CORRUPT_EVENT;