typedef struct _WHEA_ERROR_SOURCE_CONFIGURATION {
  ULONG                           Flags;
  WHEA_ERROR_SOURCE_CORRECT       Correct;
  WHEA_ERROR_SOURCE_INITIALIZE    Initialize;
  WHEA_ERROR_SOURCE_CREATE_RECORD CreateRecord;
  WHEA_ERROR_SOURCE_RECOVER       Recover;
  WHEA_ERROR_SOURCE_UNINITIALIZE  Uninitialize;
  PVOID                           Reserved;
} WHEA_ERROR_SOURCE_CONFIGURATION, *PWHEA_ERROR_SOURCE_CONFIGURATION;