typedef struct _PROCESS_MITIGATION_USER_POINTER_AUTH_POLICY {
  union {
    ULONG Flags;
    struct {
      ULONG EnablePointerAuthUserIp : 1;
      ULONG ReservedFlags : 31;
    } DUMMYSTRUCTNAME;
  } DUMMYUNIONNAME;
} PROCESS_MITIGATION_USER_POINTER_AUTH_POLICY, *PPROCESS_MITIGATION_USER_POINTER_AUTH_POLICY;