typedef struct _WHEA_AMD_EXTENDED_REGISTERS {
  ULONGLONG IPID;
  ULONGLONG SYND;
  ULONGLONG CONFIG;
  ULONGLONG DESTAT;
  ULONGLONG DEADDR;
  ULONGLONG MISC1;
  ULONGLONG MISC2;
  ULONGLONG MISC3;
  ULONGLONG MISC4;
  ULONGLONG RasCap;
  ULONGLONG Reserved[WHEA_XPF_MCA_EXTREG_MAX_COUNT - WHEA_AMD_EXT_REG_NUM];
} WHEA_AMD_EXTENDED_REGISTERS, *PWHEA_AMD_EXTENDED_REGISTERS;