typedef union _WHEA_PMEM_ERROR_SECTION_VALIDBITS {
  struct {
    ULONGLONG ErrorStatus : 1;
    ULONGLONG NFITHandle : 1;
    ULONGLONG LocationInfo : 1;
    ULONGLONG Reserved : 61;
  } DUMMYSTRUCTNAME;
  ULONGLONG ValidBits;
} WHEA_PMEM_ERROR_SECTION_VALIDBITS, *PWHEA_PMEM_ERROR_SECTION_VALIDBITS;