typedef struct _WHEAP_ERR_SRC_INVALID_EVENT {
  WHEA_EVENT_LOG_ENTRY         WheaEventLogEntry;
  WHEA_ERROR_SOURCE_DESCRIPTOR ErrDescriptor;
  CHAR                         Error[WHEA_ERROR_TEXT_LEN];
} WHEAP_ERR_SRC_INVALID_EVENT, *PWHEAP_ERR_SRC_INVALID_EVENT;