typedef struct _WHEA_THROTTLE_PCIE_REMOVE_EVENT {
  WHEA_EVENT_LOG_ENTRY WheaEventLogEntry;
  WHEA_PCIE_ADDRESS    Address;
  UINT32               Mask;
} WHEA_THROTTLE_PCIE_REMOVE_EVENT, *PWHEA_THROTTLE_PCIE_REMOVE_EVENT;