typedef struct _WHEAP_DROPPED_CORRECTED_ERROR_EVENT {
  WHEA_EVENT_LOG_ENTRY   WheaEventLogEntry;
  WHEA_ERROR_SOURCE_TYPE ErrorSourceType;
  ULONG                  ErrorSourceId;
} WHEAP_DROPPED_CORRECTED_ERROR_EVENT, *PWHEAP_DROPPED_CORRECTED_ERROR_EVENT;