typedef struct _WHEA_ERROR_SOURCE_CONFIGURATION_DD {
  WHEA_ERROR_SOURCE_INITIALIZE_DEVICE_DRIVER   Initialize;
  WHEA_ERROR_SOURCE_UNINITIALIZE_DEVICE_DRIVER Uninitialize;
  WHEA_ERROR_SOURCE_CORRECT_DEVICE_DRIVER      Correct;
} WHEA_ERROR_SOURCE_CONFIGURATION_DD, *PWHEA_ERROR_SOURCE_CONFIGURATION_DD;