typedef struct _WHEA_PSHED_PLUGIN_INIT_FAILED_EVENT {
  WHEA_EVENT_LOG_ENTRY WheaEventLogEntry;
  NTSTATUS             Status;
} WHEA_PSHED_PLUGIN_INIT_FAILED_EVENT, *PWHEA_PSHED_PLUGIN_INIT_FAILED_EVENT;