typedef struct _WHEA_SEL_BUGCHECK_RECOVERY_STATUS_PHASE2_EVENT {
  WHEA_EVENT_LOG_ENTRY WheaEventLogEntry;
  ULONG                BootId;
  BOOLEAN              Success;
} WHEA_SEL_BUGCHECK_RECOVERY_STATUS_PHASE2_EVENT, *PWHEA_SEL_BUGCHECK_RECOVERY_STATUS_PHASE2_EVENT;