typedef struct _PCI_EXPRESS_NPEM_CAPABILITY {
  PCI_EXPRESS_ENHANCED_CAPABILITY_HEADER Header;
  PCI_EXPRESS_NPEM_CAPABILITY_REGISTER   Capability;
  PCI_EXPRESS_NPEM_CONTROL_REGISTER      Control;
  PCI_EXPRESS_NPEM_STATUS_REGISTER       Status;
} PCI_EXPRESS_NPEM_CAPABILITY, *PPCI_EXPRESS_NPEM_CAPABILITY;