typedef struct _WHEA_MEMORY_CORRECTABLE_ERROR_SECTION {
  WHEA_MEMORY_CORRECTABLE_ERROR_HEADER Header;
  WHEA_MEMORY_CORRECTABLE_ERROR_DATA   Data[ANYSIZE_ARRAY];
} WHEA_MEMORY_CORRECTABLE_ERROR_SECTION, *PWHEA_MEMORY_CORRECTABLE_ERROR_SECTION;