typedef union _PCI_FPB_VECTOR_ACCESS_CONTROL_REGISTER {
  struct {
    ULONG VectorAccessOffset : 8;
    ULONG Rsvd0 : 6;
    ULONG VectorSelect : 2;
    ULONG Rsvd1 : 16;
  } DUMMYSTRUCTNAME;
  ULONG  AsULONG;
} PCI_FPB_VECTOR_ACCESS_CONTROL_REGISTER, *PPCI_FPB_VECTOR_ACCESS_CONTROL_REGISTER;