typedef struct _WHEA_PSHED_PLUGIN_UNLOAD_EVENT {
  WHEA_EVENT_LOG_ENTRY WheaEventLogEntry;
  WCHAR                PluginName[WHEA_ERROR_TEXT_LEN];
} WHEA_PSHED_PLUGIN_UNLOAD_EVENT, *PWHEA_PSHED_PLUGIN_UNLOAD_EVENT;