typedef union _PCI_EXPRESS_DPC_ERROR_SOURCE_ID {
  struct {
    USHORT Function : 3;
    USHORT Device : 5;
    USHORT Bus : 8;
  } DUMMYSTRUCTNAME;
  USHORT AsUSHORT;
} PCI_EXPRESS_DPC_ERROR_SOURCE_ID, *PPCI_EXPRESS_DPC_ERROR_SOURCE_ID;