typedef union _WHEA_PCIE_CORRECTABLE_ERROR_DEVICES_VALIDBITS {
  struct {
    ULONGLONG Segment : 1;
    ULONGLONG Bus : 1;
    ULONGLONG Device : 1;
    ULONGLONG Function : 1;
    ULONGLONG Mask : 1;
    ULONGLONG CorrectableErrorCount : 1;
    ULONGLONG Reserved : 58;
  } DUMMYSTRUCTNAME;
  ULONGLONG ValidBits;
} WHEA_PCIE_CORRECTABLE_ERROR_DEVICES_VALIDBITS, *PWHEA_PCIE_CORRECTABLE_ERROR_DEVICES_VALIDBITS;