typedef struct _WHEA_FIRMWARE_ERROR_RECORD_REFERENCE {
  UCHAR     Type;
  UCHAR     Reserved[7];
  ULONGLONG FirmwareRecordId;
} WHEA_FIRMWARE_ERROR_RECORD_REFERENCE, *PWHEA_FIRMWARE_ERROR_RECORD_REFERENCE;