typedef union _WHEA_XPF_PROCESSOR_ERROR_SECTION_VALIDBITS {
  struct {
    ULONGLONG LocalAPICId : 1;
    ULONGLONG CpuId : 1;
    ULONGLONG ProcInfoCount : 6;
    ULONGLONG ContextInfoCount : 6;
    ULONGLONG Reserved : 50;
  } DUMMYSTRUCTNAME;
  ULONGLONG ValidBits;
} WHEA_XPF_PROCESSOR_ERROR_SECTION_VALIDBITS, *PWHEA_XPF_PROCESSOR_ERROR_SECTION_VALIDBITS;