typedef enum DWM_TAB_WINDOW_REQUIREMENTS {
  DWMTWR_NONE,
  DWMTWR_IMPLEMENTED_BY_SYSTEM,
  DWMTWR_WINDOW_RELATIONSHIP,
  DWMTWR_WINDOW_STYLES,
  DWMTWR_WINDOW_REGION,
  DWMTWR_WINDOW_DWM_ATTRIBUTES,
  DWMTWR_WINDOW_MARGINS,
  DWMTWR_TABBING_ENABLED,
  DWMTWR_USER_POLICY,
  DWMTWR_GROUP_POLICY,
  DWMTWR_APP_COMPAT
} ;