typedef enum __MIDL___MIDL_itf_tsgpolicyengine_0000_0000_0001 {
  AA_AUTH_MIN = 0,
  AA_AUTH_BASIC,
  AA_AUTH_NTLM,
  AA_AUTH_SC,
  AA_AUTH_LOGGEDONCREDENTIALS,
  AA_AUTH_NEGOTIATE,
  AA_AUTH_ANY,
  AA_AUTH_COOKIE,
  AA_AUTH_DIGEST,
  AA_AUTH_ORGID,
  AA_AUTH_CONID,
  AA_AUTH_SSPI_NTLM,
  AA_AUTH_MAX
} AAAuthSchemes;